### ISSUE TITLE
Missing libReactNativePermissions.a

### ISSUE THREAD

**Issue by jonlong** [zoontek/react-native-permissions#1]
Hey, thanks for this library — it fits my use case perfectly.

I didn't see `libReactNativePermissions.a` anywhere in the repo (per the installation instructions in the README) or in the npm package. Was it omitted by accident, or is there something I'm missing on my end?

Thanks!

**Comment by yonahforst** [comment]
Sorry for the late reply. It should be in the .xcodeproj folder that you dragged into xcode (`ReactNativePermissions.xcodeproj` > `Products`)
