### ISSUE TITLE
problem occurred configuring project ':react-native-permissions'.

### ISSUE THREAD

**Issue by lavarajallu** [zoontek/react-native-permissions#104]
Hi,

I have a Getting this issue,
         When i was use it's working fine, But unfortunately this is going to this issue.

F```
AILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':react-native-permissions'.
      > You have not accepted the license agreements of the following SDK components:
        [Android Support Repository].
        Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
        Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

Total time: 41.291 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

**Comment by yonahforst** [comment]
I'm not sure, but this doesn't seem like an issue related to this library. Try this: https://stackoverflow.com/questions/39760172/you-have-not-accepted-the-license-agreements-of-the-following-sdk-components
