### ISSUE TITLE
Cannot obtain location permissions status

### ISSUE THREAD

**Issue by tarang9211** [zoontek/react-native-permissions#106]
I am attempting to use this module to obtain the permissions status the user has supplied. When I try calling the function below:

```javascript
Permissions.getPermissionStatus('location')
      .then(response => {
        this.setState({ locationPermission: response })
      })
```

After executing this code, I receive the following error: 
```
Cannot read property 'getPermissionStatus' of undefined
```
Versions I am using on iOS
```javascript
"react": "16.0.0-alpha.6",
"react-native": "0.44.0",
```

Could someone guide me? This is a little urgent.

**Comment by tarang9211** [comment]
@yonahforst Could you help me out here?

**Comment by roshangm1** [comment]
Please check if every thing is linked properly. Some times, react-native link doesn't work as expected.
Try to do manual linking.

**Comment by yonahforst** [comment]
@tarang9211 - were you able to solve this with manual linking?

**Comment by tarang9211** [comment]
I have been using manual linking only. Let me try this with another sample project and see what happens. Stay tuned.

**Comment by rexlow** [comment]
+1

**Comment by sators** [comment]
+1

**Comment by mattmcdev** [comment]
It looks like `getPermissionStatus` has changed to `check`.

Calling the `check` method still runs `RNPermissions.getPermissionStatus`.

**Comment by RobinClowers** [comment]
I saw this error as well, I fixed it by doing clean and rebuild in xcode.
