### ISSUE TITLE
Sms permission

### ISSUE THREAD

**Issue by nazarTrynko** [zoontek/react-native-permissions#107]
Hi! Is there a way to ask for SMS_RECEIVE permission?

**Comment by yonahforst** [comment]
Should be really easy to do in version 1.0.0. (PR's welcome ;)

**Comment by vspedr** [comment]
I might give it a try soon :) Meanwhile, you could use this directly:
http://facebook.github.io/react-native/releases/0.42/docs/permissionsandroid.html
