### ISSUE TITLE
using Permissions.openSettings().then() as shown in example fails

### ISSUE THREAD

**Issue by simitii** [zoontek/react-native-permissions#109]
Permissions.openSettings()
      .then(() => alert('back to app!!'))
FAILS
It is related to .then part of expression. Anyway I can deal with it without .then but I just want to inform you.

react-native version 44
console output:
undefined is not an object (evaluating '_reactNativePermissions2.default.openSettings().then')

Native Android Error:
06-20 02:58:48.526: E/AndroidRuntime(21653): FATAL EXCEPTION: mqt_native_modules
06-20 02:58:48.526: E/AndroidRuntime(21653): Process: com.dolmussofur, PID: 21653
06-20 02:58:48.526: E/AndroidRuntime(21653): com.facebook.react.common.JavascriptException: undefined is not an object (evaluating '_reactNativePermissions2.default.openSettings().then'), stack:
06-20 02:58:48.526: E/AndroidRuntime(21653): openGPSSettings@61931:57
06-20 02:58:48.526: E/AndroidRuntime(21653): <unknown>@15766:61
06-20 02:58:48.526: E/AndroidRuntime(21653): __invokeCallback@4755:21
06-20 02:58:48.526: E/AndroidRuntime(21653): <unknown>@4601:32
06-20 02:58:48.526: E/AndroidRuntime(21653): __guard@4690:11
06-20 02:58:48.526: E/AndroidRuntime(21653): invokeCallbackAndReturnFlushedQueue@4600:19
06-20 02:58:48.526: E/AndroidRuntime(21653): 	at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:99)
06-20 02:58:48.526: E/AndroidRuntime(21653): 	at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:83)
06-20 02:58:48.526: E/AndroidRuntime(21653): 	at java.lang.reflect.Method.invoke(Native Method)
06-20 02:58:48.526: E/AndroidRuntime(21653): 	at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:368)
06-20 02:58:48.526: E/AndroidRuntime(21653): 	at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:138)
06-20 02:58:48.526: E/AndroidRuntime(21653): 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
06-20 02:58:48.526: E/AndroidRuntime(21653): 	at android.os.Handler.handleCallback(Handler.java:739)
06-20 02:58:48.526: E/AndroidRuntime(21653): 	at android.os.Handler.dispatchMessage(Handler.java:95)
06-20 02:58:48.526: E/AndroidRuntime(21653): 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
06-20 02:58:48.526: E/AndroidRuntime(21653): 	at android.os.Looper.loop(Looper.java:168)
06-20 02:58:48.526: E/AndroidRuntime(21653): 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:208)
06-20 02:58:48.526: E/AndroidRuntime(21653): 	at java.lang.Thread.run(Thread.java:818)

**Comment by yonahforst** [comment]
Hi @simitii - thanks for letting me know. 

Actually, in the latest version (1.0.0 - atm) I removed `openSettings()` from the Android API. This is because we're using RN's own `PermissionAndroid` JS api (to avoid additional linking). 

there are are several NPM modules for opening settings on android (https://github.com/Aleksandern/react-native-android-settings-library)
