### ISSUE TITLE
Request Location Permission Mode

### ISSUE THREAD

**Issue by jadidian** [zoontek/react-native-permissions#11]
Thank you for the awesome job, I have a question and hope someone can help, the issue is actually related to `react-native` itself rather than `react-native-permissions`; I'm working on an app which has few different types of users, for some users I should beg for "Allow access to location while using the app" while other types of users would willingly "Allow access always", I have both `NSLocationAlwaysUsageDescription` and `NSLocationWhenInUseUsageDescription` set in `Info.plist`, your library does an awesome job checking and requesting a specific type of location tracking permission, but as soon as I call `navigator.geolocation.getCurrentPosition()` it will pop the "allow always" dialog only because its been set in `Info.plist`, even when the user has already permitted "while using", this is very annoying from UX point of view and I'm thinking about writing a native module for tracking the location for those users and use it instead of react-native's navigator, but before that I thought maybe someone has already found a workaround for this.

**Comment by yonahforst** [comment]
@jadidian - hrmmm, I don't know if I can help you there. There's a few location modules out there already which might solve this. I'm using https://github.com/transistorsoft/react-native-background-geolocation to get the location in the background, but that might be overkill for your case. (also, you need to pay for the android lib)

**Comment by jadidian** [comment]
@yonahforst thanks for the advise, I ended up writing a simple Objective-C module, its working fine and I put it here in case someone wants to solve a similar problem, BTW, `Permissions.requestPermission().then()` didn't work as expected, the `.then()` block doesn't run after permitting location tracking so I used the same native module for that (see the last JavaScript function)... I'm using react-native 0.28.0, iOS 9.3, react-native-permissions 0.1.0

``` objective-c
// LocationManager.h
@interface LocationManager: NSObject <RCTBridgeModule, CLLocationManagerDelegate>
@property (nonatomic) CLLocationManager *locationManager;
@end
```

``` objective-c
// LocationManager.m
#import <Foundation/Foundation.h>
#import <CoreLocation/CoreLocation.h>
#import "RCTBridgeModule.h"

#import "LocationManager.h"
#import "RCTBridge.h"
#import "RCTEventDispatcher.h"

@implementation LocationManager

@synthesize locationManager;
@synthesize bridge;

RCT_EXPORT_MODULE();

- (instancetype)init
{
  self = [super init];
  if (self) {
    locationManager = [[CLLocationManager alloc] init];
    locationManager.delegate = self;
  }
  return self;
}

RCT_EXPORT_METHOD(requestWhenInUseAuthorization)
{
  [locationManager requestWhenInUseAuthorization];
}

RCT_EXPORT_METHOD(requestAlwaysAuthorization)
{
  [locationManager requestAlwaysAuthorization];
}

RCT_EXPORT_METHOD(startUpdatingLocation)
{
  [locationManager startUpdatingLocation];
}

RCT_EXPORT_METHOD(stopUpdatingLocation)
{
  [locationManager stopUpdatingLocation];
}

- (void)locationManager:(CLLocationManager *)manager didUpdateLocations:(NSArray<CLLocation *> *)locations
{
  CLLocation *location = locations[ 0 ];
  if (location) {
    NSNumber *latitude = [[NSNumber alloc] initWithDouble:location.coordinate.latitude];
    NSNumber *longitude = [[NSNumber alloc] initWithDouble:location.coordinate.longitude];
    [self.bridge.eventDispatcher sendAppEventWithName:@"LocationUpdated"
                                                 body:@{@"latitude": latitude, @"longitude": longitude}];
  }
}

- (void)locationManager:(CLLocationManager *)manager didFailWithError:(NSError *)error
{
  [self.bridge.eventDispatcher sendAppEventWithName:@"LocationFailed"
                                               body:@{@"error": error.localizedDescription}];
}

@end

```

Then in JavaScript

``` js
...
  componentDidMount() {
    this._locationUpdatedBinding = NativeAppEventEmitter.addListener('LocationUpdated', this._onLocationUpdated);
    this._locationFailedBinding = NativeAppEventEmitter.addListener('LocationFailed', this._onLocationFailed);
  }

  componentWillUnmount() {
    NativeModules.LocationManager.stopUpdatingLocation();
    this._locationUpdatedBinding.remove();
    this._locationFailedBinding.remove();
  }

  _onLocationUpdated(location) {
    NativeModules.LocationManager.stopUpdatingLocation();
    // do something with location
  }

  _onLocationFailed(error) {
    NativeModules.LocationManager.stopUpdatingLocation();
    // show an alert or something
  }

  _onLocateButtonPressed() {
    // NOTE: Permissions.requestPermission().then() didn't work!
    // Permissions.requestPermission('location', 'whenInUse')
    //   .then(response => {
    //      if (response === 'authorized') { NativeModules.LocationManager.startUpdatingLocation(); }
    //    });
    _.delay(NativeModules.LocationManager.requestWhenInUseAuthorization, 100);
    _.delay(NativeModules.LocationManager.startUpdatingLocation, 1000);
  }
```

**Comment by yonahforst** [comment]
which commit are you using? I pushed a fix this morning that might have solved then `then()` issue

**Comment by jadidian** [comment]
Just pulled the latest commit b8dd7d8bf1554e4cfc4d4f81fe55b6ca0565e2f8 and now it closes the dialog before clicking "Allow" or "Deny"
![untitled](https://cloud.githubusercontent.com/assets/650099/16841791/c7c0a0de-49a8-11e6-927f-5209399d962b.gif)

**Comment by jadidian** [comment]
It actually calls the `.then(response => {})` with `undetermined` value, but it closes the dialog before user taps on "Allow" or "Don't Allow"

**Comment by yonahforst** [comment]
ok, try it now. I found some more changes that I forgot to commit and push.

Great looking app by the way!!

**Comment by jadidian** [comment]
Awesome, it works now... thank you. It would be great if you bumped a minor version number so I set it in `package.json`, something like `"react-native-permissions": "0.1.1"` instead of `"react-native-permissions": "git@github.com:yonahforst/react-native-permissions.git#c6e762d9cfa26d48ffa13469b2fd93a8311ab239"`

**Comment by yonahforst** [comment]
will do. give me a day or two for all the issues to settle then i'll bump and push to NPM
