### ISSUE TITLE
_reactNativePermissions2.default.check is not a function

### ISSUE THREAD

**Issue by sandropoluan** [zoontek/react-native-permissions#112]
**Error**
> Possible Unhandled Promise Rejection (id: 0):
> TypeError: _reactNativePermissions2.default.check is not a function
> TypeError: _reactNativePermissions2.default.check is not a function

**My code**
```
  cekpermission=async ()=>{
    Permissions.check('location')
      .then(response => {
        //response is one of: 'authorized', 'denied', 'restricted', or 'undetermined'
        console.log(response);
        //this.setState({ photoPermission: response })
      });
  }

  componentDidMount(){
    this.cekpermission()
}
```

**npm i react-native-permissions --save**  done!
**react-native link react-native-permissions** done!
**gradlew clean** done!

RN 0.44.0
React 16.0.0-alpha.6
targetSdkVersion 25
minSdkVersion 16
compileSdkVersion 25
buildToolsVersion "25.0.3"

**Comment by iskWang** [comment]
m... I try the `checkMultiplePermissions` will work, maybe the current README.md not sync with old version.

Ref. https://github.com/yonahforst/react-native-permissions/tree/dc61a0484505f74f9a212d9282ba71bb493c0de7

**Comment by yonahforst** [comment]
@iskWang - the documentation has been updated for the latest version (1.0.0)

I'll be publishing it to NPM shorty. Meanwhile you can install from github/master
