### ISSUE TITLE
Return Device Token for Push Notifications Request

### ISSUE THREAD

**Issue by johnstew** [zoontek/react-native-permissions#116]
Currently when I am running the Push Notifications Request on my app I am able to see the dialog and receive a status of `authorized` as the response but I was wondering if its possible to receive the Device Token in this case for Remote Push Notifications?

Thanks!

**Comment by yonahforst** [comment]
@johnstew - not possible through this library. You would need to add a method in your main AppDelegate.m

Have a look at this library: https://github.com/zo0r/react-native-push-notification

**Comment by fershibli** [comment]
I think this should be supported by `react-native-permissions`, because we need this in order to integrate any notification service.
Even a simple documentation of how to implement it for iOS, Android and Windows, should do it.

**Comment by mikehardy** [comment]
device tokens have nothing to do with permissions
