### ISSUE TITLE
ReactNativePermissions: photoPermissionStatus is depricated. Use getPermissionStatus('photo') instead.

### ISSUE THREAD

**Issue by siemya** [zoontek/react-native-permissions#12]
**react-native: 0.27**

When i tried to use getPermissionStatus('photo') i got an 'is not a function' error.

So i started to use Permissions.default.photoPermissionStatus() which looks like depricated. Also there isn't an openSettings function in this object.

This is the Permissions object when i require 'react-native-permissions'

```
{ default: 
   { StatusUndetermined: 'undetermined',
     StatusDenied: 'denied',
     StatusAuthorized: 'authorized',
     StatusRestricted: 'restricted',
     locationPermissionStatus: [Function],
     cameraPermissionStatus: [Function],
     microphonePermissionStatus: [Function],
     photoPermissionStatus: [Function],
     contactsPermissionStatus: [Function],
     eventPermissionStatus: [Function],
     reminderPermissionStatus: [Function],
     bluetoothPermissionStatus: [Function],
     notificationPermissionStatus: [Function],
     backgroundRefreshPermissionStatus: [Function] } }
```

**Comment by yonahforst** [comment]
ok, looks like a problem with how I'm exporting the modules. Try using `import Permissions from 'react-native-permissions'` instead of `require`

**Comment by samuelkraft** [comment]
That fixed it for me 👍

**Comment by yonahforst** [comment]
~~just pushed a fix in https://github.com/yonahforst/react-native-permissions/commit/e63b23ce20b85eb1c0f8746a8795406bfc9a6c17~~

**Comment by yonahforst** [comment]
Sorry, that was the wrong commit. the fix is here: https://github.com/yonahforst/react-native-permissions/commit/0f671f3327485836580bd3ddba5dfe2a89d87b3b

**Comment by peterpme** [comment]
Hey @yonahforst do you mind pushing this fi up to npm? 

Thanks! :)

**Comment by yonahforst** [comment]
@peterpme done. Bumped to 0.1.1
