### ISSUE TITLE
Unable to resolve module `react-native`

### ISSUE THREAD

**Issue by iegik** [zoontek/react-native-permissions#124]
```
    "react": "16.0.0-alpha.12",
    "react-native": "0.46.4",
    "react-native-permissions": "1.0.0",
```

or

```
    "react-native-permissions": "0.2.7",
```

error: bundling failed: "Unable to resolve module `react-native` from `.../node_modules/react-native-permissions/index.ios.js`: Module does not exist in the module map

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start -- --reset-cache`."

https://github.com/yonahforst/react-native-permissions/blob/master/index.ios.js#L3

No lack

**Comment by cgallay** [comment]
Hi, I do experience the same issue did you find how to fix it?

**Comment by iegik** [comment]
Sorry, I did not work anymore on mobile app since that. Seems to be same error as https://github.com/facebook/react-native/issues/14209#issuecomment-322748700

**Comment by iegik** [comment]
```
react-native-git-upgrade 0.48.1
```
