### ISSUE TITLE
android check always authorized.

### ISSUE THREAD

**Issue by wuyunqiang** [zoontek/react-native-permissions#125]
I register permission to manifest.xml and check it in js.
but it always authorized.and not dialog show me to allow it.
if I not register permission to manifest.xml it crash.

version:
"react": "16.0.0-alpha.12",
"react-native": "0.46.4",
"react-native-permissions": "^1.0.0",
android:7.1

**Comment by wuyunqiang** [comment]
sorry my fault.

**Comment by andrey-shostik** [comment]
What is your fault ? Im have the same issue

**Comment by wuyunqiang** [comment]
config like this.
<img width="388" alt="permission" src="https://user-images.githubusercontent.com/13480948/28854092-8fac77fc-7767-11e7-932c-892f8cf82da2.png">

**Comment by sfratini** [comment]
For people reaching this, targetSdkVersion 23 was not enough for me. Setting it to 25 actually solved it.
