### ISSUE TITLE
Create consts to statuses

### ISSUE THREAD

**Issue by ArmandoAssuncao** [zoontek/react-native-permissions#129]
It would be interesting to have constants to reference the permissions states, something like:
Permissions.GRANTED
Permissions.DENIED
Permissions.AUTHORIZED
Permissions.UNDETERMINED

what do you think?

**Comment by yonahforst** [comment]
@ArmandoAssuncao - sounds good to me, if you want to submit a PR!

**Comment by zoontek** [comment]
I close this, but take notes for the v2.0 🙂
