### ISSUE TITLE
Request location permission not showing up if the permission is denied from Settings

### ISSUE THREAD

**Issue by zakster12** [zoontek/react-native-permissions#132]
I am pretty grateful for the great library. I have just one issue:
When my app loads it asks the user for location permission like this:

```
Permissions.request('location', 'always')
      .then(response => {
        console.log('Response: ' + response);
        if (response === 'allow') {
          console.log('allow');
        } else if (response === 'denied') {
          console.log('denied');
        }
      });
```
And if the user presses `allow` but later he disabled this permission from Settings -> App -> Location -> Never, then when I check for permission and catch that it's `denied` and I request it again it doesn't show up but the response is `denied`. Somewhere I read that in iOS you can ask only one time for permission but I am not sure that this is true. How I can handle this scenario?

Maybe I should point him to Settings to enabled it again but firstly I would like to hear whether that's the default behaviour or it's a bug in the library?

Thank you in advance.

**Comment by kelset** [comment]
I'm facing the same issue; basically, the only case where I manage to show the "Alert" that enables location permissions is when they decide to allow it, the first time.

From my understanding, this is not a bug: in both cases (Android & iOS) the only solution is, on situations "after the first time", is to show a generic alert saying something like "Go to your OS settings to enable/disable it again". But I agree that maybe there is a better solution.

**Comment by zakster12** [comment]
@kelset Thank you for your fast response. I appreciate the help. I decided to go this way as you described: First time I ask for permission otherwise pointing user to the Settings.

**Comment by yonahforst** [comment]
@zakster12 - what @kelset said is correct. On iOS you only get one chance to request permissions. If the user denies them, you need to direct them to the settings menu.

**Comment by MbF-Sathya** [comment]
Hi all., for me it's working fine in iOS, I am getting the location permission while open the app first time. But the same way not working in android. i added the these are all permissions in manifest file.
` <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />` 
then i have a question, is this will work in android simulator, can i get this location switching on permission in simulator?
