### ISSUE TITLE
JSON value '0' of type NSNumber cannot be converted to NSString

### ISSUE THREAD

**Issue by arminsal1** [zoontek/react-native-permissions#133]
After upgrading to 1.0.0, I get this error when checking multiple permissions:

`[error][tid:main][RCTConvert.m:58] JSON value '0' of type NSNumber cannot be converted to NSString`

<img width="375" alt="screen shot 2017-08-31 at 11 17 20 am" src="https://user-images.githubusercontent.com/8769537/29931015-048512ae-8e3e-11e7-93ee-23f328c99db8.png">
<img width="375" alt="screen shot 2017-08-31 at 11 17 31 am" src="https://user-images.githubusercontent.com/8769537/29931016-04891188-8e3e-11e7-940d-a3b6f7d9788a.png">

My Code:

```
Permissions.checkMultiple(["location","contacts","camera","event"]).then(response => {
            //response is one of: 'authorized', 'denied', 'restricted', or 'undetermined'
            if (response.location != "undetermined" && response.location != "denied" && response.location != "restricted") {
              this._getLocation(response.location)
            }else{
              this.setState({ locationPermission: response.location })
            }
            if (response.contacts != "undetermined" && response.contacts != "denied" && response.contacts != "restricted") {
              this._getContacts(response.contacts)
            }else{
              this.setState({ contactsPermission: response.contacts })
            }
            if (response.event == "authorized") {
              this._getEvents()
            }
            this.setState({cameraPermission:response.camera,eventPermission:response.event})
        }).catch((error) =>{
          console.log("Permissions Error");
          Alert.alert("Error",error.message);
        });
```

React Native Version: 0.47.2

**Comment by arminsal1** [comment]
Fixed it: Excluded location from the checkMultiple and checked it separately.

**Comment by erezrokah** [comment]
@arminsal1 This is more of a workaround than a fix.
There is a bug in the `checkMultiple` function in this line:
`permissions.map(this.check.bind(this))` will pass the the permission as the first argument to the `check` function, but will pass the permission index in the array as the second argument. The second argument is the permission type (which is used only `location` and `notification` permissions)
