### ISSUE TITLE
There aren’t any releases here

### ISSUE THREAD

**Issue by iegik** [zoontek/react-native-permissions#134]
https://github.com/yonahforst/react-native-permissions/releases

**Comment by MoOx** [comment]
That would be nice at least to have git tags :)

**Comment by aaronbuchanan** [comment]
agree ^

**Comment by yonahforst** [comment]
I don't really understand how they work. I'll have to read up on them

**Comment by MoOx** [comment]
It's pretty simple. A "github release" is just a git tag with release notes.
So first thing is to just doing a git tag when you publish a version, and push your tag on github. Then you will see small git tags on the release page. Then you can edit those tags and transform them into releases.
Some cool tools exist to make this transparent for you like [np](https://github.com/sindresorhus/np) or my try on this [npmpub](https://github.com/MoOx/npmpub) that can do npm publish + github release from a CHANGELOG.md in one command :)

**Comment by allenhsu** [comment]
Similar question, why there's no corresponding tag specified in the podspec? We're using Podfile to manage third party libs including react native ones, instead of linking from node_modules. Is it possible to have at least tags for stable versions?

**Comment by allenhsu** [comment]
We forked the repo to have our own tags and pushing the podspec to our private spec repo, but it's still nice to have official tags.

**Comment by sahir** [comment]
@yonahforst can you please provide git tag or change logs of version 1.0.1. currently, I am using version 1.0.0. Which one is stable to use?

**Comment by zoontek** [comment]
I will create release for every new releases. Blame me if I forgot! 😄

**Comment by zoontek** [comment]
First one: https://github.com/yonahforst/react-native-permissions/releases/tag/1.0.2 !
