### ISSUE TITLE
Duplicate RCTMethodInfo

### ISSUE THREAD

**Issue by iegik** [zoontek/react-native-permissions#137]
Was:

```
#if __has_include("RCTBridgeModule.h")
  #import "RCTBridgeModule.h"
#else
  #import <React/RCTBridgeModule.h>
#endif
```

Should:

```
#if __has_include(<React/RCTBridgeModule.h>)
  #import <React/RCTBridgeModule.h>
#else
  #import "RCTBridgeModule.h"
#endif
```

**Comment by amitbravo** [comment]
If I do this , I got #import "RCTDevMenu.h" not found error :(

**Comment by iegik** [comment]
Add following into **Header Search Paths**
```
$(inherited) (non-recursive)
${PODS_DEV_ROOT}/React (recursive)
$(BUILT_PRODUCTS_DIR)/usr/local/include (recursive)
```

**Comment by iegik** [comment]
https://github.com/yonahforst/react-native-permissions/pull/138#issuecomment-328079681

**Comment by MoOx** [comment]
https://github.com/yonahforst/react-native-permissions/pull/138#issuecomment-329737303

**Comment by isAlmogK** [comment]
Has this been fixed

**Comment by benvium** [comment]
@AlmogRnD It's not working for me - I've tried targeting the commit with the merged fix above (package.json `"react-native-permissions": "git+ssh://git@github.com/yonahforst/react-native-permissions.git#e7454a9c62e773a8d5ba5c6dc20843beb56c3c81",`) and I'm still getting the same error on RN 48.3 :-(

**Comment by yonahforst** [comment]
fixed in #146

**Comment by MoOx** [comment]
Any plan to cut a release?

**Comment by yonahforst** [comment]
@MoOx  just published 1.0.1 🎉

**Comment by MoOx** [comment]
Thank you!

**Comment by Pianist038801** [comment]
@legik Thanks for sharing!

**Comment by snarang2** [comment]
@iegik - where do we change the import priority?
 I mean which file?

**Comment by iegik** [comment]
@snarang2 in *.h file, checkout this PR https://github.com/vinnyjth/react-native-permissions/pull/1/files

**Comment by AliaMYH** [comment]
Changing the priority works for me but then i get a linker error:

```
ld: library not found for -lPods-GroceriesApp
clang: error: linker command failed with exit code 1 (use -v to see invocation)

```

How do I handle that ?

Actually it's quite weird, when I open .xcworkspace as opposed to .xcodeproj, I get 27 linker errors, clearly I've installed something incorrectly.

**Comment by chandanyadav7** [comment]
i also have the same issue , In which file we need to change this

**Comment by suijunqiang** [comment]
The issue reproduced on the react-native 0.56.0

**Comment by TheSixer** [comment]
@suijunqiang Same issue here on the react-native 0.56.0.   Has the problem been solved?

**Comment by suijunqiang** [comment]
@TheSixth correct, it can be fixed as @iegik said.

**Comment by leechance** [comment]
@suijunqiang how did you solved this issue?
