### ISSUE TITLE
Android READ_PHONE_STATE permission

### ISSUE THREAD

**Issue by dev6james** [zoontek/react-native-permissions#141]
Hi. Could support be added for requesting the Android 'READ_PHONE_STATE' permission?

**Comment by vspedr** [comment]
Hi @dev6james, I will try sending a PR for this, but if you're in a hurry and your React Native version supports it, you can use [this API](http://facebook.github.io/react-native/releases/0.42/docs/permissionsandroid.html) to request any permission (that's what this library does under the hood, anyway)

**Comment by yonahforst** [comment]
fixed in #155

**Comment by francescortiz** [comment]
I don't see the 'READ_PHONE_STATE' permission applied in the pull request.
