### ISSUE TITLE
 react-native-permissions not linking for 0.48.1

### ISSUE THREAD

**Issue by ghost** [zoontek/react-native-permissions#147]
rnpm-install info Linking react-native-permissions ios dependency 
    rnpm-install info iOS module react-native-permissions has been successfully linked
Can anyone please suggest me  solution for these issue ?

**Comment by IvRRimum** [comment]
+1

**Comment by IvRRimum** [comment]
Try with this: https://github.com/yonahforst/react-native-permissions/pull/139

**Comment by yonahforst** [comment]
resolved with #146
