### ISSUE TITLE
How to use the permissions once granted?

### ISSUE THREAD

**Issue by stanleycyang** [zoontek/react-native-permissions#152]
For me, it seems like the requesting is pretty straightforward in the [docs](http://facebook.github.io/react-native/releases/next/docs/permissionsandroid.html). My problem is with the actually usage of the permissions once granted. 

For example, let's say I get `android.permission.READ_OWNER_DATA`. How would I actually read the owner's data?

**Comment by yonahforst** [comment]
@stanleycyang - this is a bit out of scope. This library is just to make it easy to request permissions using a single API.
