### ISSUE TITLE
Getting the following error on iOS Redefintion of RCTMethodInfo 

### ISSUE THREAD

**Issue by isAlmogK** [zoontek/react-native-permissions#154]
Only happing on iOS anyone have any ideas?

**Comment by JoostVermeulen11** [comment]
+1

**Comment by IvRRimum** [comment]
+1

**Comment by IvRRimum** [comment]
Try with this pull request: https://github.com/yonahforst/react-native-permissions/pull/139

**Comment by isAlmogK** [comment]
That pull request did fix the issue on compile for iOS but now I have a different issue. Will open a new ticket also why was this not yet merged? Feels like this package is not supported anymore or dying out?

**Comment by yonahforst** [comment]
fixed with #146
