### ISSUE TITLE
Regression: Android Notification Support Removed

### ISSUE THREAD

**Issue by ngandhy** [zoontek/react-native-permissions#156]
First, thanks for the great library!

It seems in the commit @ https://github.com/yonahforst/react-native-permissions/commit/306e6928c1dba18ff46c9ff2daf09f2c4e015bad , android lost its Notification support added with ( #25 , #96)

**Comment by yonahforst** [comment]
@ngandhy - we started using [RN's own implementation for android permissions](https://facebook.github.io/react-native/docs/permissionsandroid.html). Notifications on android cannot be requested, you can only check if it's enabled. And it seems RN doesn't support this. I'll update the readme so it's clear

**Comment by yonahforst** [comment]
actually, the readme is already clear on this. Closing this out.

**Comment by ngandhy** [comment]
@yonahforst - ya, I don't think the readme was ever updated when those were merged in.

**Comment by kyangy** [comment]
@yonahforst How do you check if notifications are enabled using the PermissionsAndroid module? The list from `PermissionsAndroid.PERMISSIONS` does not have notifications:
```
{ 
READ_CALENDAR: 'android.permission.READ_CALENDAR',
WRITE_CALENDAR: 'android.permission.WRITE_CALENDAR',
CAMERA: 'android.permission.CAMERA',
READ_CONTACTS: 'android.permission.READ_CONTACTS',
WRITE_CONTACTS: 'android.permission.WRITE_CONTACTS',
GET_ACCOUNTS: 'android.permission.GET_ACCOUNTS',
ACCESS_FINE_LOCATION: 'android.permission.ACCESS_FINE_LOCATION',
ACCESS_COARSE_LOCATION: 'android.permission.ACCESS_COARSE_LOCATION',
RECORD_AUDIO: 'android.permission.RECORD_AUDIO',
READ_PHONE_STATE: 'android.permission.READ_PHONE_STATE',
CALL_PHONE: 'android.permission.CALL_PHONE',
READ_CALL_LOG: 'android.permission.READ_CALL_LOG',
WRITE_CALL_LOG: 'android.permission.WRITE_CALL_LOG',
ADD_VOICEMAIL: 'com.android.voicemail.permission.ADD_VOICEMAIL',
USE_SIP: 'android.permission.USE_SIP',
PROCESS_OUTGOING_CALLS: 'android.permission.PROCESS_OUTGOING_CALLS',
BODY_SENSORS: 'android.permission.BODY_SENSORS',
SEND_SMS: 'android.permission.SEND_SMS',
RECEIVE_SMS: 'android.permission.RECEIVE_SMS',
READ_SMS: 'android.permission.READ_SMS',
RECEIVE_WAP_PUSH: 'android.permission.RECEIVE_WAP_PUSH',
RECEIVE_MMS: 'android.permission.RECEIVE_MMS',
READ_EXTERNAL_STORAGE: 'android.permission.READ_EXTERNAL_STORAGE',
WRITE_EXTERNAL_STORAGE: 'android.permission.WRITE_EXTERNAL_STORAGE'
}
```

**Comment by roysG** [comment]
+1
Any update?

**Comment by ngandhy** [comment]
@roysG - This was removed from the library. Given the exchange above, don't expect it to get added back in. If you need it, look elsewhere or use an old version (this is what I did). Good luck!
