### ISSUE TITLE
Android SDK 17 (Nougat): Request for location permission crash the app

### ISSUE THREAD

**Issue by yihou** [zoontek/react-native-permissions#159]
Below is my code:

```javascript
initRequestLocation = () => {
    if (Platform.OS === 'ios') {
      navigator.geolocation.requestAuthorization();
    } else {
      Permissions.check('location', 'always').then(async (res) => {
          if (!res === 'authorized') {
              // crash even the second parameter is 'whenInUse'
              this.locationPermission = await Permissions.request('location', 'always');
              console.log('permission: ', this.locationPermission);
          }
      });
    }
  };
```
My code dependencies:
"react": "16.0.0-alpha.12",
"react-native": "0.46.4",
"react-native-permissions": "^1.0.0",

Android gradle settings:
compileSdkVersion: "23"
buildToolsVersion: "25.0.3"

**Comment by yonahforst** [comment]
What is the error? This library calls [RN's PermissionsAndroid](https://facebook.github.io/react-native/docs/permissionsandroid.html) under the hood. I would suggest checking there.

**Comment by yihou** [comment]
Sorry for late reply, was busy with other tasks, will get back to you soonest.

**Comment by yihou** [comment]
Sorry, I have rectified the crashing issue, not related to this plugin, I m so sorry.
