### ISSUE TITLE
Compatibility iOS 11

### ISSUE THREAD

**Issue by altras** [zoontek/react-native-permissions#161]
Hello!

We're trying to pick a module with which we can implement the new permission flows: 
https://mackuba.eu/2017/07/13/changes-to-location-tracking-in-ios-11/.

We have updated our Info.plist but we're not able to get the correct permission dialog using `react-native-permissions`. When we try to ask for 'always' permission it's denied immediately without showing the new pop up coming with iOS 11 where the user has the option to choose between - While using the app, Always and Never.

What changes do we need to make in order to get it running ? Maybe we can figure this out together and crate a PR 🤔

**Comment by yonahforst** [comment]
@altras - thanks for bringing this up. I'm not actively developing with RN right now (lolz) and I'm not running iOS 11 on any device. I'm going to have to rely on the community for this one.

**Comment by nicedexter** [comment]
It works if you use the Permissions.request('location', 'always') at first. You just have to add the NSLocationAlwaysAndWhenInUseUsageDescription in your plist for iOS11.

**Comment by andidev** [comment]
https://stackoverflow.com/questions/44424092/location-services-not-working-in-ios-11#answer-44424419

**Comment by MoOx** [comment]
If I am correct, I don't think there is a problem with this package.

**Comment by zoontek** [comment]
@MoOx Correct! See @nicedexter answer to fix your permission flow

**Comment by digitaldavenyc** [comment]
@nicedexter and @andidev thanks for that! I've been trying to figure out why the permission screen wasn't showing for an hr. The change really seems redundant.
