### ISSUE TITLE
react-native link error when linking

### ISSUE THREAD

**Issue by jerameel** [zoontek/react-native-permissions#165]
```
rnpm-install info Linking react-native-permissions ios dependency 
rnpm-install ERR! Something went wrong while linking. Error: buildSettings.LIBRARY_SEARCH_PATHS.push is not a function 
Please file an issue here: https://github.com/facebook/react-native/issues
```

buildSettings.LIBRARY_SEARCH_PATHS.push is not a function

When using react-native link.

But manually adding works well.

**Comment by yonahforst** [comment]
seems to be an rnpm error. check here: https://github.com/airbnb/react-native-maps/issues/1000#issuecomment-329754653

**Comment by henrikra** [comment]
Do linkin manually. It is easy to do: https://github.com/yonahforst/react-native-permissions#ios :)

**Comment by jerameel** [comment]
Yes it works fine just i stated. The issue is just when using react-native link.

**Comment by henrikra** [comment]
@Jerameel Can you close this then? :D

**Comment by yonahforst** [comment]
closing :) thanks @henrikra
