### ISSUE TITLE
`always` gives `authorized` on `whenInUse` instead of `denied`

### ISSUE THREAD

**Issue by dterhorst-zz** [zoontek/react-native-permissions#168]
## Environment

XCode Version 9.0 (9A235)
iPhone X Simulator
`"react-native-permissions": "^0.2.7"`

## Steps to Reproduce

```
Permissions.requestPermission('location', 'always').then((response) => { ... });
```

<img width="276" alt="screen shot 2017-10-04 at 5 06 24 pm" src="https://user-images.githubusercontent.com/410570/31199781-7f598bec-a926-11e7-905c-372f7aba0053.png">

Press `Only While Using the App`

## Expected

The `response` in `.then((response) => { ... })` is `denied`.

## Actual

The `response` in `.then((response) => { ... })` is `authorized`

## Note

This line of code seems to show the expected intent:

https://github.com/yonahforst/react-native-permissions/blob/0ecbb90bf5bc39ee6d5a557f1429849404cc1405/permissions/RNPLocation.m#L26-L27

I suspect this bit of code is the culprit:

https://github.com/yonahforst/react-native-permissions/blob/0ecbb90bf5bc39ee6d5a557f1429849404cc1405/permissions/RNPLocation.m#L71-L74

Due to how it always passes in `getStatusForType:nil` even when the intended `type` is `'always'.

`getPermissionStatus('location', 'always')` returns `denied` as expected.

**Comment by lfkwtz** [comment]
Same issue here. Running version 1.1.1 and RN 0.51

Our workaround for now was just to call `Permissions.check` after the initial `Permissions.request` request resolves

**Comment by ghost** [comment]
This is also a problem here, on RN 0.39 using version 0.2.5 (therefore calling "getPermissionStatus" instead of "check").

There was a [suggested fix](https://github.com/yonahforst/react-native-permissions/issues/51) for this by calling the get/check and then request of "always" specifically, but both come back authorized for me even though the application has been set to "while in use" so it should come back denied.

```
Permissions.getPermissionStatus('location').then(status => {
      console.log(status) // prints authorized whether location is always or whenInUse
      if (status === 'authorized') {
        Permissions.requestPermission('location', 'always').then(reqstatus => 
          console.log(reqstatus) // prints authorized whether location is always or whenInUse
        )
        // extra processing here ....
      }
      else if (status === 'undetermined'){
        Permissions.requestPermission('location', 'always')
      }
    })
```

My app does need to accommodate both always and whenInUse location permissions from users.

**Comment by zoontek** [comment]
I am closing this since this issue does not exists anymore with the [2.0.0 release](https://github.com/react-native-community/react-native-permissions/releases/tag/2.0.0).
