### ISSUE TITLE
Info.plist keys missing

### ISSUE THREAD

**Issue by mkraina** [zoontek/react-native-permissions#169]
Hi, since I've started to use this package, app store rejects my iOS application because of several Info.plist keys missing (NSCalendarsUsageDescription, NSPhotoLibraryUsageDescription, NSBluetoothPeripheralUsageDescription, NSSpeechRecognitionUsageDescription).
I'm not using any of these, I'm just asking for Location Always permission.
Is it possible this package is causing this rejection?
EDIT: OK, I haven't read readme properly, sorry 
https://github.com/yonahforst/react-native-permissions#appstore-submission-disclaimer

**Comment by sonalpaghadal** [comment]
Facing same issue

**Comment by bramus** [comment]
Had the same issue, with warning regarding missing entries for `NSCalendarsUsageDescription`, `NSBluetoothPeripheralUsageDescription`, and `NSSpeechRecognitionUsageDescription`.

After adding those entries (with empty strings – e.g. `<string></string>`–  as their values) the same error occurred. Strange though, as an empty string for `NSLocationWhenInUseUsageDescription` is allowed `¯\_(ツ)_/¯`

--> If you add them, add them with actual strings (and not empty ones)

**Comment by motogod** [comment]
@nasmuris Hi, Did you upload your project succeed after your declare those info.plist key even if you don't use them ? Because i upload my project just like your situation recently. I'm curious with it.
