### ISSUE TITLE
Warnning: RN 0.49.3

### ISSUE THREAD

**Issue by songhanlin** [zoontek/react-native-permissions#171]
Module ReactNativePermissions requires main queue setup since it overrides `init` but doesn't implement `requiresMainQueueSetup. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.

**Comment by vdlindenmark** [comment]
@yonahforst 
**Reference PR for fix**

https://github.com/wix/react-native-navigation/pull/1983/files#diff-b8c48202d12fa78c4c377e5a3225c298

**Comment by zoontek** [comment]
Fixed with https://github.com/yonahforst/react-native-permissions/pull/184
A release will come soon

**Comment by joegaudet** [comment]
Seeing this issue on RN 0.56.0

**Comment by MikhailSemichev** [comment]
Seeing this issue on RN 0.56.0

**Comment by SergeiKalachev** [comment]
@yonahforst @zoontek 
Please reopen the issue, because as of 0.56.0 the problem appears again.

**Comment by byronicone** [comment]
We are also seeing this on RN 0.57.4.  Can we reopen?

**Comment by willdady** [comment]
Same on RN 0.57.8. @zoontek can you please reopen?

**Comment by zoontek** [comment]
@willdady I'd just tried with a fresh 0.57.8 install, no complains. It has been implemented: https://github.com/yonahforst/react-native-permissions/blob/master/ios/ReactNativePermissions.m#L62

Do you have any additional packages installed?

**Comment by willdady** [comment]
@zoontek Yes, lots:
```json
  "dependencies": {
    "@ptomasroos/react-native-multi-slider": "^0.0.14",
    "@svgr/cli": "^4.1.0",
    "assert": "1.4.1",
    "aws-amplify": "^1.1.10",
    "crypto-js": "3.1.9-1",
    "hoist-non-react-statics": "^3.0.1",
    "jwt-decode": "^2.2.0",
    "lodash": "4.17.4",
    "moment": "^2.22.0",
    "path-parser": "2.0.2",
    "prop-types": "15.6.0",
    "query-string": "^6.1.0",
    "react": "16.6.3",
    "react-native": "0.57.8",
    "react-native-actionsheet": "2.2.2",
    "react-native-animatable": "1.2.4",
    "react-native-auth0": "^1.3.0",
    "react-native-auto-height-image": "^1.0.1",
    "react-native-communications": "2.2.1",
    "react-native-config": "^0.11.5",
    "react-native-device-info": "^0.21.5",
    "react-native-fast-image": "^5.1.0",
    "react-native-fbsdk": "^0.8.0",
    "react-native-firebase": "^4.2.0",
    "react-native-gifted-chat": "^0.4.3",
    "react-native-image-crop-picker": "^0.20.3",
    "react-native-intercom": "12.2.0",
    "react-native-keyboard-aware-scroll-view": "0.4.1",
    "react-native-keychain": "2.0.0-rc",
    "react-native-permissions": "1.1.1",
    "react-native-screens": "^1.0.0-alpha.16",
    "react-native-sentry": "0.38.3",
    "react-native-share": "1.1.3",
    "react-native-svg": "^8.0.0",
    "react-navigation": "^2.12.1",
    "react-navigation-backhandler": "^1.1.1",
    "react-navigation-tabs": "^0.8.4",
    "react-redux": "5.0.6",
    "redux": "3.7.2",
    "redux-logger": "3.0.6",
    "redux-persist": "5.2.2",
    "redux-thunk": "2.2.0",
    "url": "0.11.0",
    "uuid": "^3.3.2",
    "validate.js": "^0.12.0"
  }
```
Only this library is showing the queue warning.

**Comment by zoontek** [comment]
I am closing this since this issue does not exists anymore with the [2.0.0 release](https://github.com/react-native-community/react-native-permissions/releases/tag/2.0.0).
