### ISSUE TITLE
After request is Allow response is not returning any value to response

### ISSUE THREAD

**Issue by Ramaraju1992** [zoontek/react-native-permissions#172]
```
Permissions.request('photo')
      .then(response => {
        //returns once the user has chosen to 'allow' or to 'not allow' access
        //response is one of: 'authorized', 'denied', 'restricted', or 'undetermined'
       console.log("Hello==>");
       console.log("Hello==>"+response);
      });
```

by using the above function it is asking for permission thats fine... but problem is After user Selects either Allow or  Deny it won't return any acknowledgement to **response**.............  None of two logs were printed after user selected his option........  How to get Selected Option n response any help...? thank you...........

**Comment by zoontek** [comment]
I am closing this since this issue does not exists anymore with the [2.0.0 release](https://github.com/react-native-community/react-native-permissions/releases/tag/2.0.0).
