### ISSUE TITLE
Permission.request() doesn't prompt the user if the Location Service is turned off

### ISSUE THREAD

**Issue by decodez** [zoontek/react-native-permissions#175]
If the user turned off the location services, Permission.request() doesn't prompt the user to turn it on. How do we handle this situation

**Comment by ncuillery** [comment]
👍  I have this problem too

**Comment by doniyor2109** [comment]
+1

**Comment by doniyor2109** [comment]
I have same situation in simulator. 
```js
Perrmission.request() //  returns false and does not open any dialog
```
However openSetting is working correctly
I have tested on IPhone6s simulator

**Comment by jaseemabbas** [comment]
+1

**Comment by rizwanahmed19** [comment]
+1

**Comment by digitaldavenyc** [comment]
+1

**Comment by danielemontecchi** [comment]
me too, same problem.

**Comment by lfkwtz** [comment]
Not sure why this is an open issue still, this is the expected behavior.

You should check if the status is either `undetermined` or `denied`. If it's `denied`, you should show the user steps on how to manually re-enable and offer a link to the settings section.

**Comment by iranmanesh** [comment]
@lfkwtz unfortunately when GPS is off it returns authorized

**Comment by cstd** [comment]
+1

**Comment by zoontek** [comment]
I am closing this since this issue does not exists anymore with the [2.0.0 release](https://github.com/react-native-community/react-native-permissions/releases/tag/2.0.0).
