### ISSUE TITLE
NSMotionUsageDescription

### ISSUE THREAD

**Issue by benjaminkoetting** [zoontek/react-native-permissions#176]
how can I get the permission value for NSMotionUsageDescription which is the fitness and motion module?

Thanks,
Ben

**Comment by peterlau** [comment]
I'm not involved with the project but looks like somebody did a PR for precisely this:
https://github.com/yonahforst/react-native-permissions/pull/177

Any word maintainers?

**Comment by zoontek** [comment]
It has been merged :D
