### ISSUE TITLE
Request location always on iOS 11 shows request whenInUse dialog

### ISSUE THREAD

**Issue by mkraina** [zoontek/react-native-permissions#178]
Hi, on iOS 11 I'm having a problem showing proper permission request dialog using `
Permissions.requestPermission('location', 'always')`. On simulator it works just fine 
simulator:
<img width="276" alt="snimek obrazovky 2017-11-04 v 16 16 56" src="https://user-images.githubusercontent.com/22944924/32406693-5833da08-c17d-11e7-90eb-015e99ee7d49.png">
physical iPhone SE:
<img width="362" alt="snimek obrazovky 2017-11-04 v 16 27 41" src="https://user-images.githubusercontent.com/22944924/32406696-620f0566-c17d-11e7-87a3-962a1c82288c.png">

**Comment by MoOx** [comment]
It's an iOS 11 change from what I know.

Not an issue of this package.

**Comment by zoontek** [comment]
Like @MoOx said, it's a change with iOS 11. Read about it here: https://developer.apple.com/documentation/corelocation/choosing_the_authorization_level_for_location_services/requesting_always_authorization

**Comment by mkraina** [comment]
Yeah I see, just to make it clear, this was problem not with the new dialog, but that different permissions were asked on simulator and real device, but the problem was with some other package asking for when in usage permission (only on real device) before I Requested always

**Comment by zoontek** [comment]
Thanks for the clarification :)
