### ISSUE TITLE
RN 0.50.3 compileReleaseJavaWithJavac

### ISSUE THREAD

**Issue by OrangeFlavoredColdCoffee** [zoontek/react-native-permissions#180]
i tried  0.2.4、 0.2.7   、1.0.1     same error

**Comment by MoOx** [comment]
Duplicate of #181 (or the opposite haha)

**Comment by zoontek** [comment]
@OrangeFlavoredColdCoffee Do you use Android Studio? Which version?

**Comment by OrangeFlavoredColdCoffee** [comment]
@zoontek  yes ,2.3.0 and now i update to 3.0.1
