### ISSUE TITLE
RN 0.50.x Support

### ISSUE THREAD

**Issue by kcfgl** [zoontek/react-native-permissions#181]
I just upgraded RN to 0.50.1 to take advantage of iPhone X support.  But it looks like react-native-permissions is not ready for anything above .48.  

Any chance you'll be supporting it soon? 

Thanks!

**Comment by MoOx** [comment]
@yonahforst it seems (and that's totally understandable) that you are a busy man and don't really have time to handle all the work this package might require, would you mind to share it with https://github.com/react-community so more people can help to maintain it?

**Comment by zoontek** [comment]
I agreed with @moox on this.

**Comment by yonahforst** [comment]
@MoOx thats a great idea! It seems I would need to transfer ownership of the repo to that organization, right? 

I'll write to them and see if they are willing to accept it.

In the meantime, I would welcome any contributors who have some free time to review issues and PRs

**Comment by zoontek** [comment]
@yonahforst I'm part of the react-community organisation. I can ask them directly if you want :)

**Comment by yonahforst** [comment]
@zoontek - that would be great - thank you!

**Comment by zoontek** [comment]
@yonahforst If it's OK for you, I can make the transfer to https://github.com/react-native-community

**Comment by MoOx** [comment]
So for the support of 0.49/0.50, here is a clue #171

**Comment by zoontek** [comment]
@yonahforst Any news?

**Comment by yonahforst** [comment]
yes! sorry @zoontek, i've just added you as a collaborator.

**Comment by zoontek** [comment]
@yonahforst Thanks a lot! If you don't mind and don't want to be bothered often, can you give me the right to publishes on npm too? (same pseudo)

**Comment by yonahforst** [comment]
NP @zoontek, thank YOU! about npm, if it's ok I'd prefer to see how it goes first. In the meantime, just ping me if you need a push; I'll keep an eye out for it!

So how does react-native-community work? do you transfer the repo to that organization?

**Comment by zoontek** [comment]
@yonahforst As you wish. As a collaborator, I can make the transfer (only owner can), but as a member of react-native-community, I can maintain it.

But for a start, it will be easier to just keep it here.

**Comment by zoontek** [comment]
@yonahforst Sorry, I make a huge cleanup before doing everything else!

**Comment by unicornRainbows** [comment]
Epic how quickly this stuff gets done and everyone gets involved. :)

**Comment by edward-s** [comment]
wow, thank you so much @zoontek and @yonahforst 
can you please remove the React Pod dependency in the new version.
It was deprecated and It's giving my project lots of issues

**Comment by zoontek** [comment]
@edward-s Can you make a PR?

**Comment by zoontek** [comment]
https://github.com/yonahforst/react-native-permissions/releases/tag/1.0.2 It should be published on npm after @yonahforst tested it
