### ISSUE TITLE
Bundled request permissions in android

### ISSUE THREAD

**Issue by pavanmehta91** [zoontek/react-native-permissions#186]
It's there in PermissionsAndroid  module as requestMultiple. This is not implemented in this library and can . be done.

**Comment by zoontek** [comment]
You can directly use `PermissionsAndroid` for that. Even with `getTypes()` if you want.

```js
import { PermissionsAndroid } from 'react-native'
import RNPermissions from 'react-native-permissions'

PermissionsAndroid.requestMultiple([
  RNPermissions.getTypes().location,
  RNPermissions.getTypes().bluetooth,
])
```

I have no plan to add this to this package since it will add reduce even more the Android / iOS interop (there are no way to implement this properly - one dialog - on iOS)
