### ISSUE TITLE
How do I ask for storage, calendar, phone permissions on Android when the app starts?

### ISSUE THREAD

**Issue by EdmundMai** [zoontek/react-native-permissions#188]
I'm trying to submit my app to the Huawei app store. However they are rejecting me with this:

`Dear developer, your app accesses to users sensitive information （Storage，Calendar,Phone）without the users permission, please show the permission notice when the app starts. Error Code d9:“A mark of internal rejected reason, please ignore them.”
`
I added this line when my app starts in response to that:

`Permissions.checkMultiple(["event", "storage"]).then(console.log);`

But they still gave me the same rejection. How would I fix this?

**Comment by zoontek** [comment]
How is your `AndroidManifest.xml`?

**Comment by EdmundMai** [comment]
```
<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW" />
<uses-permission android:name="android.permission.WAKE_LOCK" />
<uses-permission android:name="android.permission.READ_CALENDAR" />
<uses-permission android:name="android.permission.WRITE_CALENDAR" />
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
<permission android:name="${applicationId}.permission.C2D_MESSAGE"
android:protectionLevel="signature" />
<uses-permission android:name="${applicationId}.permission.C2D_MESSAGE" />
<uses-permission android:name="android.permission.VIBRATE" />
<uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
```

I added READ_PHONE_STATE and submitted but they still rejected it with the same rejection

**Comment by zoontek** [comment]
Have you tried with:

```
<uses-permission android:name="android.permission.READ_PHONE_STATE" />
<uses-permission android:name="android.permission.CALL_PHONE" />
```

**Comment by zoontek** [comment]
Also, you need to use the "request" method, not the check one. Like in the examples.

**Comment by EdmundMai** [comment]
Ok I'll try and resubmit my app and let you know

**Comment by EdmundMai** [comment]
Weird thing is that my phone doesn't call anyone, so I don't get what they're referring to when they say "Phone"... I'll try it out anyway
