### ISSUE TITLE
RCTConvert.h not found

### ISSUE THREAD

**Issue by goncalo-msrt** [zoontek/react-native-permissions#191]
Hi,
I tried to use cocoapods and manual link and both of them fail while compiling.

I get
```
RCTConvert+RNPStatus.h:14:11: 'RCTConvert.h' file not found
```

I tried with @1.0.1/2/3 and all failed. React native 0.50

**Comment by r4ggj** [comment]
同问

**Comment by r4ggj** [comment]
same question

**Comment by goncalo-msrt** [comment]
I tried with the new version 1.0.4 and same issue, no idea what to do.
Also tried to downgrade to 0.49, but nothing

**Comment by goncalo-msrt** [comment]
@zoontek sorry to bother you, do you know anything about this? it looks we are already 4 to have this issue. Thanks man for your work :)

**Comment by zoontek** [comment]
@goncalo-msrt Do you have any step to reproduce?
Do you have set any Header search path?

**Comment by goncalo-msrt** [comment]
@zoontek using react-native 0.49 or 0.50 and adding it with cocoapods (but i also tried the manual way) and then compile it ( `react-native run-ios` ). that's it.

**Comment by RobertBiehl** [comment]
Have this problem with cocoapods. Adding this line 
`s.dependency 'React'`
to https://github.com/yonahforst/react-native-permissions/blob/master/ReactNativePermissions.podspec fixes the issue

```
require 'json'

package = JSON.parse(File.read(File.join(__dir__, 'package.json')))

Pod::Spec.new do |s|
  s.name                   = 'ReactNativePermissions'
  s.version                = package['version']
  s.summary                = package['description']
  s.description            = package['description']
  s.homepage               = package['homepage']
  s.license                = package['license']
  s.author                 = package['author']
  s.source                 = { :git => 'https://github.com/yonahforst/react-native-permissions.git', :tag => s.version }

  s.platform               = :ios, '9.0'
  s.ios.deployment_target  = '8.0'

  s.preserve_paths         = 'LICENSE', 'package.json'
  s.source_files           = '**/*.{h,m}'
  s.exclude_files          = 'example/**/*'
  s.dependency           'React'
end
```

**Comment by Maydar** [comment]
Also have this issue RN 0.51

**Comment by zoontek** [comment]
Should be fixed: https://github.com/yonahforst/react-native-permissions/releases/tag/1.0.6
