### ISSUE TITLE
NSPhotoLibraryAddUsageDescription

### ISSUE THREAD

**Issue by vvusts** [zoontek/react-native-permissions#197]
Is it possible to check/request 'NSPhotoLibraryAddUsageDescription' permission?

**Comment by MoOx** [comment]
`Permissions.check('photo')`?

**Comment by vvusts** [comment]
No, that check for gallery, this is on ios 11 for saving photo to gallery

**Comment by MoOx** [comment]
Oh right. Didn't know about the diff. Now I know :)

NSPhotoLibraryUsageDescription covers NSPhotoLibraryAddUsageDescription right?

Anyway I guess this lib does not cover this yet.

**Comment by vvusts** [comment]
> NSPhotoLibraryUsageDescription covers NSPhotoLibraryAddUsageDescription right?

Yes, thanks for pointing this :)
