### ISSUE TITLE
Notification Response 'denied'

### ISSUE THREAD

**Issue by FrenchBully** [zoontek/react-native-permissions#198]
### Describe your environment

* React-Native version: 0.49.3
* Platform: iOS, Android, both? iOS only
* Device (which one?), simulator? iphone 6
* OS version: os 11
* react-native-permissions version: ^1.0.1
* Devtools: Xcode? Android Studio version?: Xcode 9.2
* (Android only: buildToolsVersion)

### How to repeat issue and example
```js
Permissions.request('notification')
      .then(response => {
        console.log('Notifications Response', response);
        if(response === 'authorized') {
          this.player.seek(13);
          clearTimeout(this.state.pauseTimeout);
          this.setState({
            notificationPermission: response,
            notificationSpeechDisplayed: false,
            microphoneSpeechDisplayed: true,
            playerPaused: false
          });
        } else if (this.state.notificationPermission === 'denied') {
            Alert.alert(
              "Push notifications are required.",
              'Please enable push notifications in your phone settings',
              [
                {text: 'Cancel', style: 'cancel'},
                {text: 'Settings', onPress: () => Linking.openURL('app-settings:')},
              ],
              { cancelable: true }
            )
          } else {
            this.setState({
              notificationPermission: response
            });
          }
        });
```
ISSUE:
For some reason the response is coming back `denied` even though I've approved the notification. Can't seem to get any other response for notifications.  Location and microphone both work as expected.

**Comment by ptelad** [comment]
I am having this issue as well.
React-Native version: 0.55.4
react-native-permissions version: 1.1.1

It happens more on slower devices like the iPad mini 4.

**Comment by jdegger** [comment]
How did you solve this?
