### ISSUE TITLE
 the second parameter  of Permissions.check()  should  be string 

### ISSUE THREAD

**Issue by yongqianvip** [zoontek/react-native-permissions#200]
// example
    Permissions.check('location', { type: 'always' }).then(response => {
      this.setState({ locationPermission: response })
    })
ERROR:
    ExceptionsManager.js:73 JSON value '{
        type = always;
    }' of type NSMutableDictionary cannot be converted to NSString

---
Should it be like this:

    Permissions.check('location', 'always').then(response => {
      this.setState({ locationPermission: response })
    })

**Comment by zoontek** [comment]
@yongqianvip Please follow the issue template: https://github.com/yonahforst/react-native-permissions/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by jerameel** [comment]
+1 I can reproduce the issue using iOS simulator, but in the android version it works fine

**Comment by zoontek** [comment]
I just made a release: https://github.com/yonahforst/react-native-permissions/releases/tag/1.0.5

**Comment by hazemhagrass** [comment]
@zoontek 
Still not working at all :(
<img width="542" alt="screen shot 2017-12-15 at 7 12 16 pm" src="https://user-images.githubusercontent.com/3625423/34052667-fab67a2e-e1cb-11e7-8243-70a9dde3aeb3.png">
<img width="404" alt="screen shot 2017-12-15 at 7 12 24 pm" src="https://user-images.githubusercontent.com/3625423/34052668-fae3ba2a-e1cb-11e7-832c-e87e933b671a.png">
