### ISSUE TITLE
Feature Add: Silent and local notification permissions

### ISSUE THREAD

**Issue by FrenchBully** [zoontek/react-native-permissions#202]
Possible to get support for silent and local notification permissions?

**Comment by zoontek** [comment]
@FrenchBully On which system? iOS or Android?

**Comment by FrenchBully** [comment]
yes on iOS

**Comment by FrenchBully** [comment]
also is this deprecated? https://github.com/yonahforst/react-native-permissions/blob/master/permissions/RNPNotification.m#L45

**Comment by zoontek** [comment]
@FrenchBully Your link gives a 404
