### ISSUE TITLE
Android has been returning to authorized

### ISSUE THREAD

**Issue by tianweicc** [zoontek/react-native-permissions#205]
Android has been returning to authorized！！！！ 
targetSdkVersion 23
compileSdkVersion 25

**Comment by zoontek** [comment]
@tianweicc Why did you ignore the issue template? https://github.com/yonahforst/react-native-permissions/blob/master/.github/ISSUE_TEMPLATE.md

EDIT: Sorry, without the issue template I can help much 😕
