### ISSUE TITLE
check('location', 'always' ) vs. check('location', { type: 'always' })

### ISSUE THREAD

**Issue by GedoonS** [zoontek/react-native-permissions#209]
In the guide it says:

```
// example
Permissions.check('location', { type: 'always' }).then(response => {
  this.setState({ locationPermission: response })
})

Permissions.request('location', { type: 'always' }).then(response => {
  this.setState({ locationPermission: response })
})
```

However this triggers an error like "JSON value of type NSMutableDictionary cannot be converted...". If I use `Permissions.request('location', 'always' )` then it seems to work. 

Also the default values are:
```
const DEFAULTS = {
	'location' : 'whenInUse',
	'notification': ['alert', 'badge', 'sound'],
}
```
and not 
```
const DEFAULTS = {
	'location' : {type:'whenInUse'},
	'notification': {type:['alert', 'badge', 'sound']},
}
```
So I really believe the parameters shouldn't be wrapped in objects, but given as is.

**Comment by zoontek** [comment]
@GedoonS The issue template, please.

**Comment by sators** [comment]
I encountered this error as well @GedoonS.  Upgrading to the [1.0.6](https://github.com/yonahforst/react-native-permissions/releases/tag/1.0.6) release resolved it. (See the note on the release about unlinking / upgrade / relink!)
