### ISSUE TITLE
Android app crashed on request location permission

### ISSUE THREAD

**Issue by MugeshM** [zoontek/react-native-permissions#213]
* React-Native version: 0.51.0
* Platform: Android
* Device: MI A1
* OS version: Oreo 8 and Nougat also
* react-native-permissions: 1.0.6
* Devtools:  3.0.1
* (Android only: 23.0.1)

App is getting crashed in android when it requesting for location permission.
This is code the im running
`Permissions.request('location', 'whenInUse').then(async (res) => {
      console.log("res",res);
      if(res == "denied"){
        this.setState({
          locationGranted: false
        })
      }
    });`

And it throws the error 
 **java.lang.SecurityException: Looks like the app doesn't have the permission to access location. Add the following line to your app's AndroidManifest.xml: <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
   LocationModule.java:236 - com.facebook.react.modules.location.LocationModule.throwLocationPermissionMissing**

But i added the location permission in manifest file

**Comment by zoontek** [comment]
Can you publish the content of your AndroidManifest.xml?

**Comment by MugeshM** [comment]
This is my Manifest file
```xml
<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" /> 
<uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
<uses-permission android:name="android.permission.CAMERA" />
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
<uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
<uses-permission android:name="android.permission.VIBRATE" />
```

**Comment by zoontek** [comment]
@MugeshM Try adding

```xml
<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
```

**Comment by abhideepmallick** [comment]
Did you solve this @MugeshM ?

**Comment by ekimlinger** [comment]
This happens even if both permissions are in the manifest file (`ACCESS_COARSE_LOCATION` and `ACCESS_FINE_LOCATION`).

**Comment by abhaynpai** [comment]
Any solution on this issue ?

**Comment by jslz** [comment]
I think we have seen this happen to us, reported via Sentry monitoring. 

```
SecurityExceptioncom.facebook.react.modules.location.LocationModule in throwLocationPermissionMissing
fatalLooks like the app doesn't have the permission to access location. Add the following line to your app's AndroidManifest.xml: <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
```

But we really do have it in AndroidManifest.xml, and we do not have ACCESS_COARSE_LOCATION.

```
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
    <uses-permission android:name="android.permission.READ_PROFILE" />
    <uses-permission android:name="android.permission.READ_CONTACTS" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
```

our code is like 

```
const response = await RNPermissions.request('location');
```

**Comment by GuillotJessica** [comment]
first this module only look for this permission for location, location: PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION, not the COARSE,
in my code at check everytime if permission doesn't return "authorized" then I'm send it to request.
It works, but I'm using the react native api

**Comment by jslz** [comment]
fwiw, this sounds possibly related/relevant: https://github.com/facebook/react-native/pull/10291

**Comment by joshuadiezmo** [comment]
I encounter same problem, 
just change 

compileSdkVersion
buildToolsVersion

to

compileSdkVersion 25
    buildToolsVersion "25.0.1"

and 
implementation "com.android.support:appcompat-v7:25.0.1"

**Comment by jslz** [comment]
@joshuadiezmo unfortunately that is not a good solution for us (and i suspect for many other devs here) because that pushes the permissions UX back to the old "everything at install time" behaviour, i think?

**Comment by joshuadiezmo** [comment]
yeah, its not a good solution, but its working on me.

**Comment by RWOverdijk** [comment]
~Any other ideas? This is still an issue and downgrading is not an option in our case.~

In my case the cause was my own stupidity. I for some reason expected the result to be a boolean, but it's a string. Leaving this here as a monument to my own stupidity and hopefully help for others.

**Comment by soleimanipwy** [comment]
any solution ?!

**Comment by pavithra2110** [comment]
Any Solution?? I am facing the same problem

**Comment by ducpt2** [comment]
I'm trying to replace with PermissionAndroid but it still crash on production.
RN: 0.55.4
Any help pls?

**Comment by 777uday** [comment]
Any lead to this issue? I am facing the same issue. Tried all the solutions provided above but still couldn't solve it.

**Comment by zoontek** [comment]
I am closing this since this issue does not exists anymore with the [2.0.0 release](https://github.com/react-native-community/react-native-permissions/releases/tag/2.0.0).
