### ISSUE TITLE
openSetting   Error   android

### ISSUE THREAD

**Issue by renjinlong** [zoontek/react-native-permissions#214]
possible unhandled promise rejection(id:0):error:'openSettings' is deprecated on android

**Comment by zoontek** [comment]
@renjinlong It's not an error, the feature is only available on iOS: `(iOS only - 8.0 and later)`

**Comment by rashmimhatre100** [comment]
Has opensettings added for android?

**Comment by rashmimhatre100** [comment]
Any update for same?

**Comment by pavermakov** [comment]
@zoontek "canOpenSettings()" returns some goofy object on android. Why can't it just return "false"?

**Comment by mikehardy** [comment]
@pavermakov if you're not testing vs the [2.0 pre-release](https://github.com/react-native-community/react-native-permissions/pull/291#issuecomment-523621347) questions about APIs and return values are likely obsolete.

**Comment by marlti7** [comment]
Any update for same?
