### ISSUE TITLE
Missing comma :(

### ISSUE THREAD

**Issue by gran33** [zoontek/react-native-permissions#216]
### Describe your environment

https://github.com/yonahforst/react-native-permissions/blob/master/ios/RCTConvert%2BRNPStatus.m#L24

missing comma there

### How to repeat issue and example

not compiled :(

### Solution

Add comma :)

**Comment by lelikg** [comment]
+1

**Comment by draperunner** [comment]
And here! https://github.com/yonahforst/react-native-permissions/blob/master/ios/RCTConvert%2BRNPStatus.h#L36
