### ISSUE TITLE
'motion' permission always return 'restricted'

### ISSUE THREAD

**Issue by Vetalyo** [zoontek/react-native-permissions#220]
### Describe your environment

* React-Native version: 0.52.1
* Platform: iOS
* Device : iPhone SE
* OS version: 10.3.3
* react-native-permissions version: 1.1.1
* Devtools: Xcode: 9.2

### How to repeat issue and example

Check 'motion' permission always return 'restricted', even in case permission is granted. On iOS 11.2.1 all works fine.

**Comment by im-aditya** [comment]
Any update on this ? Happening with me as well.

**Comment by pcoh** [comment]
Same here. Does anyone have a solution/workaround?

**Comment by Jose4gg** [comment]
Any updates here?

**Comment by iamjon** [comment]
Hi,
I just wanted to add that this seems to be only happening on the emulator. (Iphone 6) on the iphone 7 physical device it's working as expected.

**Comment by onedazy** [comment]
+1 same here

any updates on this?

**Comment by banduk** [comment]
Same problem here, any update here?
Also when `Permissions.request('motion');` it returns restricted, no matter what's the current state of the permission.

**UPDATE**
My bad, it works perfectly when debugging using the device. It does not work with simulator.

**Comment by ohjeyong** [comment]
same here, and I found the problems.
as @banduk said, if using simulator, motion permission returns restricted.
Also, if real device's iOS version is below 11(10.X, 9.X ...), then motion permission also returns restricted.

**Comment by zoontek** [comment]
I am closing this since this issue does not exists anymore with the [2.0.0 release](https://github.com/react-native-community/react-native-permissions/releases/tag/2.0.0).
