### ISSUE TITLE
Not right check value for Android

### ISSUE THREAD

**Issue by mihailShumilov** [zoontek/react-native-permissions#224]
Component returned true, even if location permission is disabled 

### Describe your environment

* React-Native version - 0.51.0
* Platform: Android
* Simulator: Genymotion Samsung Galaxy S6 API 23
* OS version: 6.0.0
* react-native-permissions version: 1.1.1
* (Android only: buildToolsVersion) Gradle 2.14.1

**Comment by 1uokun** [comment]
it is only support in Android 6.0+

**Comment by zoontek** [comment]
What's your `buildToolsVersion`? `Gradle 2.14.1` is your gradle version

**Comment by zhuchaoming** [comment]
Android 7.0 is also,  buildToolsVersion is 23.0.1, Gradle version is 4.1.

**Comment by yleflour** [comment]
Same here, Android 8.1.0 and build tools at 23.0.1

Steps to reproduce:

- Install app through `react-native run-android`
- Go to app specific settings
- In permissions disable notifications
- `Permissions.check('location')`returns "authorized"

**Comment by yleflour** [comment]
Most likely same as #167 
The solution mentionned on the thread fixed it for me.
I would advise closing this issue as it seems to be a duplicate.

**Comment by woowalker** [comment]
android 8.0, seems always return 'authorized', when request permission  of 'contacts', even i manually turn off this permission in system setting. hope any reply.

**Comment by skbhardwaj** [comment]
I'm also facing same issue in Android v5.1 (Nexus 7), getting "authorized" for `Permissions.check('location')`.

**Comment by zoontek** [comment]
I am closing this since this issue does not exists anymore with the [2.0.0 release](https://github.com/react-native-community/react-native-permissions/releases/tag/2.0.0).
