### ISSUE TITLE
What is the use of this library on Android ? (please read below to understand the question)

### ISSUE THREAD

**Issue by dancomanlive** [zoontek/react-native-permissions#225]
### Describe your environment

* React-Native version "react-native": "0.52.2",
* Platform: iOS, Android, both? Android
* Device (which one?), simulator? Device
* OS version MacOS 10 13 3
* react-native-permissions version "^1.1.1"
* Devtools: Xcode? Android Studio version? Android Studio 3.0.1
* (Android only: buildToolsVersion)  buildToolsVersion "26.0.2"

### How to repeat issue and example

Explain what you did:
- installed the library in a virgin react-native init project
- compared the example provided in this library with my code
- changed the buildToolsVersion from 23 to 26

What you expected to happen:
- I expected to have a pop up when requesting a particular permission and than the chosen permission to be enabled automatically. 

What actually happens:
- When using this configuration in Android.Manifest.xml:

```
<uses-permission android:name="android.permission.INTERNET" />
    <!--<uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>-->
    <!--<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>-->
    <!--<uses-permission android:name="android.permission.CAMERA"/>-->
    <!--<uses-permission android:name="android.permission.RECORD_AUDIO"/>-->
    <!--<uses-permission android:name="android.permission.CALL_PHONE"/>-->
    <!--<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>-->
    <!--<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>-->
    <!--<uses-permission android:name="android.permission.READ_CONTACTS"/>-->
    <!--<uses-permission android:name="android.permission.READ_CALENDAR"/>-->
    <!--<uses-permission android:name="android.permission.READ_SMS"/>-->
    <!--<uses-permission android:name="android.permission.RECEIVE_SMS"/>-->
```

only Storage and Photo permissions are authorized(green) - wonder why that is. All the other are undetermined(gray). 

- When selecting an unauthorized permission there is pop up saying "Woops! There was a problem getting your permission. Please enable it from settings". When selecting OPEN SETTINGS a warning message is displayed saying "Underhanded Promise Rejection Error: 'openSettings' is deprecated on android". This warning is apparently not an error, the feature is only available on iOS(https://github.com/yonahforst/react-native-permissions/issues/214). Same warning happens when selecting Open Settings from the in-app button. 

- When the Mannifest.xml permissions above are enabled(uncommented) than the app shows all permission as authorized. 

### Additional info

On Android 5.0 it is not possible to disable the permissions from the device settings. 

When AndroidManifest.xml has all permission disables except for INTERENT and when looking at the app's permission in Application Manager - App info the following permissions are visible:
- read phone status and identity (as far as I know this is a dangerous permission)
- read, modify or delete the contents of you SD card
- full network access
- draw over other apps.

On Android 8.1.0 (Pixel XL 2) it is possible to disable the permissions from the devices settings.

When AndroidManifest.xml has all permission disabled except for INTERENT and when looking at the app's permission in Application Manager (App info) the following permissions are visible:
- Phone*
- Storage

When disabling a permission there is a pop up saying " This app was designed for an older version of Android. Denying permission may cause it to no longer function as intended". When disabling both permission and reloading the application Storage and Photo are still authorized and green highlighted.

*.    inside the application Photo permission is authorized but inside the device settings Phone permission is enabled and there is no Photo permission.

**Comment by dancomanlive** [comment]
My latest research shows that Phone and Storage permissions are enabled by default in android. The way to disable them is to add tools:node="remove":

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="com.awesomeproject"
    android:versionCode="1"
    android:versionName="1.0">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
    <uses-permission android:name="android.permission.READ_PHONE_STATE" tools:node="remove" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" tools:node="remove" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" tools:node="remove" />
```

**Comment by dancomanlive** [comment]
Update

When cloning react-native-permissions and running the example on Android 6 and above it works. Initially I copied the example code in a brand new react native project and than npm installed react native permissions, as one would do in a regular project. So now I am comparing the differences between these two projects to find out why the brand new project is now working...

**Comment by afilp** [comment]
What did you find?

**Comment by dancomanlive** [comment]
For Android >6 give permissions upfront and they will be enabled when the app is installed. For Android <6 use this library as it seems to be working just fine and permissions are only enabled at run time(OS is responsible for this) . Don't forget to check the table on the readme page for Android compatibility.  And last but not least disable phone permission from Manifest otherwise it will be included by default.

**Comment by sfratini** [comment]
I had this same issue. In case someone is having this problem this could happen due to 2 things. 

1. The new permissions are enabled by default in any SDK lower than 25 (Android M I believe). It is only on new versions that the permissons are not enabled, so first check that. 
2. And this is usually the problem, is the target on the compilation. If you target an older release than 25, then the permissions are also enabled when you install it. Just make your in your app gradle you have compileSdkVersion and targetSdkVersion as 26. 

That should do it.
