### ISSUE TITLE
Bitrise CI builds broken unexpectedly

### ISSUE THREAD

**Issue by jsdario** [zoontek/react-native-permissions#226]
* React-Native version 0.51
* Platform: iOS
* Device: Archive build for any device
* OS version: on macOS 10.12 (Sierra)
* react-native-permissions 1.1.1
* Devtools:  Xcode 8.3.x

### How to repeat issue and example
When I build locally either for Release and Debug it works. Lately, PRs seem to be broken with compilation errors that read the following:

First error:
```
/Users/vagrant/git/node_modules/react-native-permissions/ios/Permissions/RNPMotion.m:17:20: unrecognized platform name iOS
if (@available(iOS 11.0, *)) {
```

Second error:
```
  /Users/vagrant/git/node_modules/react-native-permissions/ios/Permissions/RNPMotion.m:18:9: use of undeclared identifier 'CMAuthorizationStatus'
CMAuthorizationStatus status = [CMMotionActivityManager authorizationStatus];
                   ^
```

Third:
```
/Users/vagrant/git/node_modules/react-native-permissions/ios/Permissions/RNPMotion.m:20:17: use of undeclared identifier 'status'
switch (status) {
```

I'd like to know if it has happened to others and would like to know if you can propose some fix

**Comment by markowork** [comment]
This happens for me too, but I can't build the app anymore from xcode..

<img width="351" alt="screen shot 2018-02-09 at 16 09 41" src="https://user-images.githubusercontent.com/9213223/36035771-2ddcf53c-0db8-11e8-9e09-475ffeb08e76.png">

**Comment by jsdario** [comment]
Hi @markowork I can build locally, but my Xcode is v9.2 and my OS is High Sierra. What is your environment? I am trying to change my CI environment to see if that's the cause.

**Comment by markowork** [comment]
@jsdario 

xcode - 8.3.2
OS - 10.12.5
RN 0.53

**Comment by jsdario** [comment]
Upgrading to High Sierra with Xcode 9.2 was the solution for my CI case. I'm closing the issue.
