### ISSUE TITLE
RNPMediaLibrary.h file not found

### ISSUE THREAD

**Issue by GrishmaM** [zoontek/react-native-permissions#239]
Hello!

IOS build failure showing 'RNPMediaLibrary.h' file not found

* React-Native 0.44.1
* Platform: iOS
* Device: simulator
* react-native-permissions 1.1.1
* Devtools: Xcode 9.2 (9C40b)

**Comment by reimertz** [comment]
I get the same issues now when re-installing my npm dependencies using `yarn`.  

I resolved it by using `npm` instead.

**Comment by siriustom** [comment]
I got the same issue after I upgraded Xcode to 9.3, after I did `npm install`, it still report the same error

**Comment by zoontek** [comment]
I am closing this since this issue does not exists anymore with the [2.0.0 release](https://github.com/react-native-community/react-native-permissions/releases/tag/2.0.0).
