### ISSUE TITLE
photo / photos on iOS vs Android

### ISSUE THREAD

**Issue by vonovak** [zoontek/react-native-permissions#24]
They should be the same, I suppose

```
const RNPTypes = {
    ios: [
        ....
        'photo',
        .... 
    ],
    android: [
        ...
        'photos',
    ]
}
```

**Comment by yonahforst** [comment]
whoa! thanks for spotting this! just pushed a commit to fix it.

**Comment by vonovak** [comment]
no problem :) @yonahforst [this](https://github.com/yonahforst/react-native-permissions/blob/f432ba6d7c62a7f0c7837a463cd9c907f1923380/android/src/main/java/com/joshblour/reactnativepermissions/ReactNativePermissionsModule.java#L121) needs fixing too I think
