### ISSUE TITLE
Getting restricted access when trying to access location

### ISSUE THREAD

**Issue by vikrantnegi** [zoontek/react-native-permissions#241]
### Describe your environment

* React-Native version
* Platform: Android, not checked on iOS
* Device: Redmi 4
* OS version: 
* react-native-permissions version: "^1.1.1"
* Devtools: Android Studio version: 3.1
* (Android only: buildToolsVersion): "23.0.1"

### How to repeat issue and example

Explain what you did, what you expected to happen, and what actually happens.
Provide some code if needed.
Trying to ask permission for the location access on android devices and I'm getting a response of `restricted` even When I've explicitly given it the access to the location. I've tried giving all the permission possible from the device setting but still getting the restricted response.

```
import React, { Component } from 'react';
import { Platform, StyleSheet, Text, View } from 'react-native';
import Permissions from 'react-native-permissions';

const instructions = Platform.select({
  ios: 'Press Cmd+R to reload,\n' + 'Cmd+D or shake for dev menu',
  android: 'Double tap R on your keyboard to reload,\n' + 'Shake or press menu button for dev menu',
});

type Props = {};
export default class App extends Component<Props> {
  componentDidMount() {
    if (Platform.OS === 'android') {
      Permissions.request('location', 'always', {
        rationale: {
          title: 'Cool Photo App Location Permission',
          message:
            'Cool Photo App needs access to your Location ' + 'so you can take walk.',
        },
      }).then(response => {
        // Response is one of: 'authorized', 'denied', 'restricted', or 'undetermined'
        console.log('permission response', response);
      });
    }
  }

  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>Welcome to React Native!</Text>
        <Text style={styles.instructions}>To get started, edit App.js</Text>
        <Text style={styles.instructions}>{instructions}</Text>
      </View>
    );
  }
}
```

### Solution
No.

**Comment by vynogradskyi** [comment]
Hey, did you solve that?

**Comment by Komalov** [comment]
Seems this should be easy but not obvious

@vikrantnegi could you explain what causes the problem?
