### ISSUE TITLE
Permission Popup don't show on Androud 7.1

### ISSUE THREAD

**Issue by burhanahmed92** [zoontek/react-native-permissions#243]
I developed below method and i ran it in componentDidMount() , it works on Android 5 & 6 but not working on version > 7. Kindly tell how to fix this
```

_requestPermission = (reqFor) => {
        Permissions.request(reqFor).then(response => {
        })
    }

_AskForPermissions = () => {
        Permissions.checkMultiple(['camera', 'photo', 'storage', 'location']).then(response => {
            //console.log(response.camera);
            if (response.camera != 'authorized') {
                this._requestPermission('camera')
            }

            if (response.photo != 'authorized') {
                this._requestPermission('photo')
            }

            if (response.storage != 'authorized') {
                this._requestPermission('storage')
            }

            if (response.location != 'authorized') {
                this._requestPermission('location')
            }
        })
    }
```
### Describe your environment

* React-Native 0.55.3
* Platform: iOS, Android
* Device: simulator + Samsung device 
* OS 10
* react-native-permissions 1.1.1
* Devtools: Android Studio version 3
* (Android only: 23/26.0.2)

**Comment by b-asaf** [comment]
I am using Android 7,
So I am guessing it has something to do with RN version.

**Comment by zoontek** [comment]
I am closing this since this issue does not exists anymore with the [2.0.0 release](https://github.com/react-native-community/react-native-permissions/releases/tag/2.0.0).
