### ISSUE TITLE
application/component does not refresh after permission change

### ISSUE THREAD

**Issue by b-asaf** [zoontek/react-native-permissions#244]
### Describe your environment

* React-Native : 0.52.0
* Platform: Android
* Device ? Galaxy S6
* OS version : 7.0
* react-native-permissions : 1.1.1
* Devtools: Atom
* (Android only: buildToolsVersion): 26.0.2

### How to repeat issue and example

I want to check if my application has permission to the camera, and my code is:
```
    checkPermissions = () => {
        Permissions.check('camera')
            .then((response) => {
                if (response !== 'authorized') {
                    Permissions.request('camera').then((userResponse) => {
                        if (userResponse !== 'authorized') {
                            this.props.onBack();
                        } else {
                            this.setState({}); // This does not work as well :(
                        }
                    });
                }
            });
    }
```

`checkPermissions` is called from `componentDidMount` method.
If the user click `Allow` the camera component inside my module remain `blocked` and the application does not refresh.
I thought that the application refresh automatically when one of its settings change.
When I change the camera settings manually, the application changes.

Any thoughts?

**Comment by emreedgu** [comment]
Same problem I have

**Comment by shilu-stha** [comment]
I have same issue, has there been any update?

**Comment by zoontek** [comment]
I am closing this since this issue does not exists anymore with the [2.0.0 release](https://github.com/react-native-community/react-native-permissions/releases/tag/2.0.0).

**Comment by pugson** [comment]
Dropping a note here that you can use [AppState](https://reactnative.dev/docs/appstate) to listen for app changes to `foreground` / `inactive` / `background` focus to update component state.
