### ISSUE TITLE
Android: WRITE access not granted

### ISSUE THREAD

**Issue by hhravn** [zoontek/react-native-permissions#246]
Against assumption, "dangerous" WRITE access is not automatically granted just by defining in the manifest file and requesting read access.

https://developer.android.com/guide/topics/permissions/overview#normal-dangerous

> Note: Your app still needs to explicitly request every permission it needs, even if the user has already granted another permission in the same group. In addition, the grouping of permissions into groups may change in future Android releases. Your code shouldn't have logic that depends on a set of particular permissions being in the same group.

This means that write access cannot be obtained to e.g. `WRITE_CONTACTS` or `WRITE_CALENDAR` using react-native-permissions.

**Comment by hhravn** [comment]
adressed here: https://github.com/yonahforst/react-native-permissions/pull/232

**Comment by zoontek** [comment]
I am closing this since this issue does not exists anymore with the [2.0.0 release](https://github.com/react-native-community/react-native-permissions/releases/tag/2.0.0).
