### ISSUE TITLE
audio recording permission on ios simulator

### ISSUE THREAD

**Issue by hyochan** [zoontek/react-native-permissions#248]
In the readme, it said `microphone` permission is not working in ios simulator but it was possible in `expo`. 

If I just wrote below code in `expo` and run it, the`microphone` permission poped up in simulator.
```
const result: any = await checkPermission('RECORDING');
if (!result) {
  const permissionResult = await Expo.Permissions.askAsync(Expo.Permissions.AUDIO_RECORDING);
  console.log(permissionResult);
}
```

How can I able to make audio recording working in my simulator?

**Comment by msman** [comment]
I do not think this works on expo. You have to read about expo ejecting.

**Comment by zoontek** [comment]
I am closing this since this issue does not exists anymore with the [2.0.0 release](https://github.com/react-native-community/react-native-permissions/releases/tag/2.0.0).
