### ISSUE TITLE
Check then request permission?

### ISSUE THREAD

**Issue by jodm** [zoontek/react-native-permissions#249]
### Describe your environment

* react-native: 0.55.4
* Platform: iOS
* Device 
* 11.3.1
* react-native-permissions version latest
* Devtools: xCode

### How to repeat issue and example

In componentWillMount I have the following:

      Permissions.check('location', { type: 'whenInUse' }).then(response => {
         this.setState({ location_permissions: response })
       })
    
    Permissions.check('camera').then(response => {
      this.setState({ camera_permissions: response })
    })

All I want is the status of these permissions. What's happening is in iOS I am getting the OS prompt to grant permission. I do not want to show the dialog yet. I want to show my permissions screen then request the permission. 

Please advise what I am doing wrong.

**Comment by jannainm** [comment]
Is this happening every time? When I experienced this behavior it was because I did not realize I had some code running that actually used the permission I was trying to check. This caused the OS to automatically prompt.

**Comment by zoontek** [comment]
I am closing this since this issue does not exists anymore with the [2.0.0 release](https://github.com/react-native-community/react-native-permissions/releases/tag/2.0.0).
