### ISSUE TITLE
Invalid RNPType after upgrading react-native

### ISSUE THREAD

**Issue by jamesone** [zoontek/react-native-permissions#251]
### Describe your environment

* React-Native version: 0.55.4
* Platform: iOS, Android, both? Both (this issue is arising on IOS though - haven't tested Android yet)
* Device (which one?), simulator? Simulator
* OS version: 10.12.6
* react-native-permissions version: 1.1.1
* Devtools: Xcode? Android Studio version?
* (Android only: buildToolsVersion)

### Issue:

```
Invalid RNPType 'mediaLibrary'. should be one of: (
    backgroundRefresh,
    bluetooth,
    camera,
    contacts,
    event,
    location,
    microphone,
    notification,
    photo,
    reminder,
    speechRecognition
)


reactConsoleErrorHandler | @ | ExceptionsManager.js:71
-- | -- | --
  | console.error | @ | YellowBox.js:69
  | logToConsole | @ | RCTLog.js:46
  | logIfNoNativeHook | @ | RCTLog.js:29
  | __callFunction | @ | MessageQueue.js:351
  | (anonymous) | @ | MessageQueue.js:116
  | __guardSafe | @ | MessageQueue.js:314
  | callFunctionReturnFlushedQueue | @ | MessageQueue.js:115
  | t | @ | RNDebuggerWorker.js:1

-----

Invalid RNPType 'motion'. should be one of: (
    backgroundRefresh,
    bluetooth,
    camera,
    contacts,
    event,
    location,
    microphone,
    notification,
    photo,
    reminder,
    speechRecognition
)

```

**Screenshot of simulator:** https://www.dropbox.com/s/ejy7ux2hc0fsjjm/Screenshot%202018-06-05%2015.56.15.png?dl=0

### How to repeat issue and example

I'm in the process of upgrading RN. After upgrading a bunch of other packages, I am now getting the following error from react-native-permissions. 

1. install latest `react-native-permissions`
2. `react-native link react-native-perimssions`

### Solution

No solution yet. 

----

**After investigating this further**: I found that commenting out the following in `lib/permissions.ios.js` fixes the red screen error:

```
// 'mediaLibrary',
// 'motion'
```

Can anyone explain why these ^ values don't work with the latest react-native (0.55)?

### Other

Has this happened to anyone?

**Comment by zoontek** [comment]
I am closing this since this issue does not exists anymore with the [2.0.0 release](https://github.com/react-native-community/react-native-permissions/releases/tag/2.0.0).
