### ISSUE TITLE
The request dialog box is showing twice.

### ISSUE THREAD

**Issue by rodrigofbm** [zoontek/react-native-permissions#254]
### Describe your environment
  OS: Linux 4.13
  Node: 8.11.2
  Yarn: 1.7.0
  npm: 5.6.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.

react-native-permissions latest

### How to repeat issue and example
The dialog box for permission is showing twice. One of the react-native-permissions
and other from React native, I guess. How to show only the dialog request from the react-native-permissions?

**Comment by MarkRunWu** [comment]
The sample code would show dialogs twice.
To just show system dialog on iOS, you may call `Permissions.request` directly:
```
if (this.state.photoPermission == 'undetermined') {
   Permissions.request(...)
}
```

**Comment by zoontek** [comment]
I am closing this since this issue does not exists anymore with the [2.0.0 release](https://github.com/react-native-community/react-native-permissions/releases/tag/2.0.0).

**Comment by creditcoder** [comment]
Same issue.

> "react-native": "0.61.5",
"react-native-permissions": "^2.0.9",
