### ISSUE TITLE
Cannot request location always after successfully requesting location whenInUse

### ISSUE THREAD

**Issue by lukasgjetting** [zoontek/react-native-permissions#255]
### Description

When requesting location-permissions, it is often wise to separate whenInUse and always ([from apple](https://developer.apple.com/documentation/corelocation/choosing_the_authorization_level_for_location_services/requesting_always_authorization)).

After getting permission to use location _whenInUse_, you are not able to request permission for _always_.

This is caused by the following code (from ios/Permissions/RNPLocation.m):

```
NSString *status = [RNPLocation getStatusForType:nil];  
    if (status == RNPStatusUndetermined) {  
        ....  
    } else {  
        if (
            [CLLocationManager authorizationStatus] == kCLAuthorizationStatusAuthorizedWhenInUse &&
            [type isEqualToString:@"always"]
        ) {  
            completionHandler(RNPStatusDenied);  
        }  
    }
```

### Describe your environment

* React-Native version: 0.55.4
* Platform: iOS
* Device: Simulator (iPhone 6, iOS 11.4)
* OS version: macOS 10.13.5
* RNP version: 1.1.1
* Devtools: Xcode (running through CLI)

### How to repeat issue and example

1. Ask for location permission 'whenInUse'.
2. Ask for location permission 'always' after previous request is granted.
3. Watch as it instantly fails

Example:  
```
const whenInUse = yield Permissions.request('location');  
const always = yield Permissions.request('location', 'always');  
console.log('WIU', whenInUse, 'Always', always); 
```

This example is using generator functions, but it can also be done using the standard promise .then.

### Solution

Move the `[CLLocationManager authorizationStatus] == kCLAuthorizationStatusAuthorizedWhenInUse && [type isEqualToString:@"always"]` check to the first if-statement. As if this condition is true, we should still request permission.

However! This creates an issue with the `didChangeAuthorizationStatus` callback, as it checks the status and sets locationManager to nil if it's not not-determined. I suggest a private property `locationManagerJustInit` is added. This is set to true when initializing locationManager, then tested at the beginning and set to false at the end of `didChangeAuthorizationStatus`. We can do this because the callback is always called twice: once when the locationManager is initialized and once when the auth status is changed ([source](https://stackoverflow.com/questions/30106341/swift-locationmanager-didchangeauthorizationstatus-always-called)).

Again, another issue arises: If the user denies the permission-escalation, `didChangeAuthorizationStatus` is never called. This could be fixed by setting a timeout which would automatically return `denied` after a period of time has passed.

I'd be willing to submit a pull request, but I'm not quite sure about the procedure. If this is confirmed a problem, I'll get started on a pull request.

**Comment by noambonnie** [comment]
Hi there @lukasgjetting and thank you for working to fix this, I see that the PR is still in the works. Is there any quick-and-dirty workaround for this (besides requesting "always" to begin with...)

**Comment by lukasgjetting** [comment]
Hi @noambonnie 

The way we do it currently, is simply to reference our own fork ([here](https://github.com/lukasgjetting/react-native-permissions/)) in package.json like so:

````
"dependencies: {
    "react-native-permissions": "git+https://github.com/lukasgjetting/react-native-permissions.git",
    ....
}
````

**I would suggest forking either this project, mine or andwaal's (from #228).**

The issue is fixed in my fork, but, as andwaal notes, it might crash if you request the permission multiple times in quick succession.

**Comment by noambonnie** [comment]
Thanks @lukasgjetting. I will give it a spin. Are you guys still working on this or has it been put to rest? I'm trying to figure out if it's worth waiting for a PR to be merged.

It looks like this library is not being maintained... :-/

**Comment by lukasgjetting** [comment]
@noambonnie 

Yeah, I don't think anyone maintains it anymore. You probably shouldn't count on new releases.

The fix implemented in my fork works for my use case, so I will probably just keep using that - sorry.

**Comment by noambonnie** [comment]
@lukasgjetting Finally had a chance to integrate your code. For the most part it works. There's one piece that I don't understand though (and behaves oddly). Admittedly, I'm completely ignorant in Swift.

When I try to escalate to "always" and select "Always allow" it works great. But if I select "Only when in use" (i.e. deny the escalation), there's a 30 second wait before I get the response.

I see in your code the following:
```
dispatch_after(dispatch_time(DISPATCH_TIME_NOW, 30 * NSEC_PER_SEC), dispatch_get_main_queue(), ^{
    NSUserDefaults *defaults = [NSUserDefaults standardUserDefaults];
    [defaults setObject:@"YES" forKey:EscalatedServiceRequested];
    [defaults synchronize];
    self.escelatedRightsRequested = [NSNumber numberWithBool:YES];
    
    if(self.completionHandler){
        self.completionHandler(RNPStatusDenied);
        self.completionHandler = nil;
    }
});
```
Which seems to be some sort of intentional delay of the response. Can you shed some light? Am I using it wrong? All I do in my javascript code is call `request('location', "always")` after I called with "whenInUse".

Any help would be appreciated.

**Comment by noambonnie** [comment]
...aaaaand I apologize @lukasgjetting - I just noticed that there's a whole discussion about it in the PR. So how do you guys go about this? Simply don't wait for the response from the request? That would actually work for me I think. I don't really need the escalation response immediately. Is that how you go about it?

**Comment by lukasgjetting** [comment]
@noambonnie Yeah, it only works of you don't need a "DENIED" response immediately. Make sure the user can proceed without waiting the 20 seconds and handle the denial in the background when it timeouts.

**Comment by cwhenderson20** [comment]
A temporary, hacky workaround for this is to first request `whenInUse` permissions with react-native-permissions and then at some point upgrade the permissions by requesting via the built-in `navigator` method:


```js
const permission = Permissions.request('location', { type: 'whenInUse' }); // granted

// ...at some later point when you want 'always' permissions
navigator.geolocation.requestAuthorization();
```

Other than the obvious downside of having to use two libraries to do the job, the `navigator` method doesn't appear to return the user's choice in any way (it neither returns a promise nor accepts a callback). However, in a pinch, it'll get the job done.

I'd love to see react-native-permissions adopt this functionality natively. Unfortunately, not knowing native iOS, I can't be of much help.

**Comment by zoontek** [comment]
@cwhenderson20 Check the `2.0.0`. It supports location permission escalation: https://github.com/react-native-community/react-native-permissions/blob/2.0.0/README.md

Feedbacks are welcomed 🙂

**Comment by cwhenderson20** [comment]
@zoontek great to hear! Looking forward to the stable release. Thanks for your work on this.

**Comment by rogerzklotz** [comment]
> @cwhenderson20 Check the `2.0.0`. It supports location permission escalation: https://github.com/react-native-community/react-native-permissions/blob/2.0.0/README.md
> 
> Feedbacks are welcomed 🙂

Can you describe how to use this? I can't find escalation or anything related in docs or code.

**Comment by zoontek** [comment]
> > @cwhenderson20 Check the `2.0.0`. It supports location permission escalation: https://github.com/react-native-community/react-native-permissions/blob/2.0.0/README.md
> > Feedbacks are welcomed 🙂
> 
> Can you describe how to use this? I can't find escalation or anything related in docs or code.

Documentation still need to be improved. As `when in use` and `always` logic are totally dependant, you can request `always` then check for `when in use`.

If the user already accept a `when in use` permission request before (`always` is still requestable, will be `denied`), the escalation is possible and the user will be prompted.

If the user already denied an `always` permission request before (`always` is not requestable, will be `blocked`), the escalation is impossible and you need to alert the user and use `openSettings`

```js
import { check, request, PERMISSIONS, RESULTS, openSettings } from "react-native-permissions";

let requestLocation = async () => {
  let always = await request(PERMISSIONS.IOS.LOCATION_ALWAYS);

  if (always === RESULTS.UNAVAILABLE) {
    return "unavailable"; // location services are unavailable, prompt the user to enable them
  }

  if (always === RESULTS.GRANTED) {
    return "always"; // user chose "always"
  }

  let whenInUse = await check(PERMISSIONS.IOS.LOCATION_WHEN_IN_USE);

  if (whenInUse === RESULTS.GRANTED) {
    return "whenInUse"; // user chose "when in use"
  }

  // neither "always" or "whenInUse" as been accepted, time to alert the user and use "openSettings"
};
```

**Comment by zoontek** [comment]
I am closing this since this issue does not exists anymore with the [2.0.0 release](https://github.com/react-native-community/react-native-permissions/releases/tag/2.0.0).
