### ISSUE TITLE
iOS: check('mediaLibrary') always return undetermined

### ISSUE THREAD

**Issue by mastersam92** [zoontek/react-native-permissions#261]
### Describe your environment

* React-Native: 0.54.4
* Platform: iOS
* Device iPhone 6S+
* OS: 11.3.1
* react-native-permissions: 1.1.1
* Devtools: Xcode 9.3.1

### How to repeat issue and example
1. Check permission. It always returns *undetermined*
2. Try request permission. It return *authorized* if user allow or *deny*, if user deny request OR blocked permission in settings.

```

  Permissions.check('mediaLibrary')
    .then((accessCheckResult) => {
      console.log('[permissionHelper] check:', accessCheckResult);
      Permissions.request('mediaLibrary')
        .then((requestPermissionResult) =>
          console.log('[permissionHelper] request:', requestPermissionResult))
    });
```

So, how to determine is user deny request or blocked permission in settings earlier ?

### Solution
No

**Comment by maulikdhameliya** [comment]
Hello, I am also facing this issue. Does anyone have solution?

**Comment by zoontek** [comment]
I am closing this since this issue does not exists anymore with the [2.0.0 release](https://github.com/react-native-community/react-native-permissions/releases/tag/2.0.0).
