### ISSUE TITLE
[Android] Location check promise never resolves

### ISSUE THREAD

**Issue by luskin** [zoontek/react-native-permissions#262]
### Describe your environment

* React-Native version: 0.55
* Platform: iOS, Android, both? Both
* Device (which one?), simulator? Samsung S7
* OS version Android 7
* react-native-permissions version: 1.1.1
* Devtools: Xcode? Android Studio version? Android Studio
* (Android only: buildToolsVersion): 27.0.3

### How to repeat issue and example

The Permission check promise for location never resolves. The other checks work fine but this one just hangs.

```
const location = await Permissions.check('location', { type: 'always' })
```
or
```
const location = await Permissions.check('location', 'always')
```
or
```
const location = Permissions.check('location', 'always').then(location => console.log('Got Location').catch(error => console.error('Error: ', error)
```

**Comment by vladimir-ivanov-epam** [comment]
Any updates?

**Comment by LupascuAndrei** [comment]
Any1 found any fixes for this? Happens randomly on my device

**Comment by zoontek** [comment]
I am closing this since this issue does not exists anymore with the [2.0.0 release](https://github.com/react-native-community/react-native-permissions/releases/tag/2.0.0).

**Comment by thespacemanatee** [comment]
I am getting this behaviour on Android 11 and library version 3.0.5. Anyone else?
