### ISSUE TITLE
iOS: Requesting bluetooth permissions causes API misuse error

### ISSUE THREAD

**Issue by garrottkai** [zoontek/react-native-permissions#264]
### Describe your environment

* React-Native version: 0.55.4
* Platform: iOS
* Device: iPad (2018)
* OS version: 11.4
* react-native-permissions version: 1.1.1
* Devtools: Xcode 9.4.1

### How to repeat issue and example

I'm calling `Permissions.request('bluetooth').... ` and it immediately returns `undetermined` without showing the dialog. In Xcode, I get the following error:
`[CoreBluetooth] API MISUSE: <CBPeripheralManager: 0x1c02cf3b0> can only accept this command while in the powered on state`
indicating that a connection attempt is made before `peripheralManagerDidUpdateState` has signaled that CBPeripheralManager is ready.

**Comment by wuzhijiangithub** [comment]
me too

**Comment by philipaarseth** [comment]
Me too, anyone found a solution to this??

**Comment by zoontek** [comment]
I am closing this since this issue does not exists anymore with the [2.0.0 release](https://github.com/react-native-community/react-native-permissions/releases/tag/2.0.0).
