### ISSUE TITLE
App crash in Android on request permissions if permissions denied or approved

### ISSUE THREAD

**Issue by halaharr** [zoontek/react-native-permissions#265]
### Describe your environment

* React-Native version
    0.54.0
* Platform: iOS, Android, both?
   Android: 7.0
* Device (which one?), simulator?
     Samsung Galaxy 7 edge
* OS version
   
* react-native-permissions version
   1.1.1
* Devtools: Xcode? Android Studio version?
* (Android only: buildToolsVersion)

### How to repeat issue and example
The app crashes if the permissions is granted or denied.
const granted = await Permissions.request('camera');
        alert(granted);
        if (granted === PermissionsAndroid.RESULTS.GRANTED) {
          console.log('You can use the camera');
        } else {
          console.log('Camera permission denied');
        }

Explain what you did, what you expected to happen, and what actually happens.
Provide some code if needed.
Expect to grant or deny the permissions but the app crashes.

### Solution

Do you know what needs to be done to address this issue? Ideally, provide a pull
request with a fix.

**Comment by halaharr** [comment]
I am not sure if the React-native-navigation is causing the problem. I created brand new project without react-native-navigation and it works fine.

**Comment by oujieying** [comment]
if my activity launches twice,i can't get the permission dialog and dismiss it before finish,so the app will be crashed

**Comment by askaaqib** [comment]
Any Solution yet? I'm having the same issue as it crashes app when allow permissions for the first time.. after that it's running smooth.

**Comment by zoontek** [comment]
I am closing this since this issue does not exists anymore with the [2.0.0 release](https://github.com/react-native-community/react-native-permissions/releases/tag/2.0.0).
