### ISSUE TITLE
Permissions.check(): Always returns 'authorized'

### ISSUE THREAD

**Issue by octobocto** [zoontek/react-native-permissions#267]
### Describe your environment

* React-Native version: 0.55.4
* Platform: iOS
* Device (all iPhones - simulator)
* OS version: 11.4
* react-native-permissions version: 1.1.1
* Devtools: Xcode
* (Android only: buildToolsVersion)

### How to repeat issue and example

1. Used yarn add react-native-permissions to add the project.
2. Manually linked in XCode by following the guide (see my file further down for info about how it looks)
3. Tried checking for permission
4. iPhone always returns 'authorized', when I expect 'undetermined'. I have checked that it isn't actually authorized.

And it works on android!

<img width="844" alt="screen shot 2018-08-03 at 10 54 12" src="https://user-images.githubusercontent.com/26007343/43634128-9da80d48-970b-11e8-808e-321d24ed6b81.png">
<img width="836" alt="screen shot 2018-08-03 at 10 53 51" src="https://user-images.githubusercontent.com/26007343/43634129-9dd6946a-970b-11e8-9f90-ad5f34dd6585.png">
<img width="853" alt="screen shot 2018-08-03 at 10 53 36" src="https://user-images.githubusercontent.com/26007343/43634131-9e086f4e-970b-11e8-8634-162e6c230624.png">
<img width="424" alt="screen shot 2018-08-03 at 10 49 40" src="https://user-images.githubusercontent.com/26007343/43634132-9e3b4aae-970b-11e8-9d90-0ef56d3b6487.png">
<img width="785" alt="screen shot 2018-08-03 at 10 49 18" src="https://user-images.githubusercontent.com/26007343/43634133-9e71ab1c-970b-11e8-931a-8ff0b4a91b48.png">

**Comment by zhaiyjgithub** [comment]
same issue on Android. When i set it to denied before, it returns **authorized** when I request permission again.

**Comment by jackphuongvu** [comment]
same issue on android

## Environment
React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.3
      CPU: x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
      Memory: 27.68 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.2 - /usr/local/bin/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 6.1.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.0, macOS 10.13, tvOS 11.0, watchOS 4.0
      Android SDK:
        Build Tools: 21.1.2, 23.0.1, 23.0.3, 25.0.0, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.3, 28.0.0
        API Levels: 22, 23, 25, 26, 27
    IDEs:
      Android Studio: 3.0 AI-171.4443003
      Xcode: 9.0/9A235 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.1 => 16.4.1 
      react-native: 0.56.0 => 0.56.0 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1

## Description
When i set it to denied before, it returns authorized when I request permission again.

**Comment by ryuoryuo** [comment]
same issue

**Comment by elizond0** [comment]
same issue on Android

**Comment by xutm** [comment]
@elizond0  I think this problem is from react-native. 

Because call `PermissionsAndroid ` on Android

**Comment by octobocto** [comment]
> @elizond0 I think this problem is from react-native.
> 
> Because call `PermissionsAndroid` on Android

Seems somewhat buggy to me.

The only thing I have found out is to make sure the permission you are checking is supported in the "Supported permission types" table. Also, as @xutm suggests, use React Natives own PermissionAndroid on Android devices.

**Comment by zoontek** [comment]
I am closing this since this issue does not exists anymore with the [2.0.0 release](https://github.com/react-native-community/react-native-permissions/releases/tag/2.0.0).
