### ISSUE TITLE
Archiving iOS app through Xcode Issue - clang: error: no such file or directory: '.../Release-iphoneos/libReactNativePermissions.a'

### ISSUE THREAD

**Issue by quachsimon** [zoontek/react-native-permissions#268]
* React-Native version
0.55.3
* Platform: iOS, Android, both?
. iOS
* Device (which one?), simulator?
Generic iOS Device
* OS version
High Sierra 10.13.5
* react-native-permissions version
1.1.1
* Devtools: Xcode? Android Studio version?
Xcode
* (Android only: buildToolsVersion)

### How to repeat issue and example

Explain what you did, what you expected to happen, and what actually happens.
I tried to archive and build the app through Xcode for a release onto the app store.
The build fails with the following error: 

`clang: error: no such file or directory: '/Users/myname/Library/Developer/Xcode/DerivedData/AppName-gozkfjyzwqgplggeljaadogheqxv/Build/Intermediates.noindex/ArchiveIntermediates/Sphere/BuildProductsPath/Release-iphoneos/libReactNativePermissions.a'
`

I took a look at the path and noticed that the file `libReactNativePermissions.a` file is inside a directory called `ReactNativePermissions`. Is there a way to move it out? 

This issue does not happen when building on the simulators.

**Comment by leiz-me** [comment]
I am facing the same issue.

Any idea?
@yonahforst

**Comment by leiz-me** [comment]
I found a way to solved this issue.
Just make sure that you don't have libReactNativePermissions.a in the section "Link Binary With Libraries" of Xcode.

**Comment by quachsimon** [comment]
My issue was that the previous had linked the library using `react-native link` AND included it inside cocoapods. I removed the cocoapod installation and it worked for me.
