### ISSUE TITLE
App asking for Calendar usage when not requesting. Removing description crashes app

### ISSUE THREAD

**Issue by quachsimon** [zoontek/react-native-permissions#270]
* React-Native version: 0.55.3
* Platform: iOS
* Device (which one?), simulator?
* OS version: High Sierra 10.13.5
* react-native-permissions version: 1.1.1
* Devtools: Xcode

I've followed the setup in the README and added the usage descriptions in the Info.plist

When I run the app for the first time, it automatically requests for my calendar usage even though I have not requested it...

Is there a way to not request this or any permissions for that matter? I tried to remove the description from the Info.plist file and that resulted in my app not building.

The only permission I need are the camera and microphone.

**Comment by mihir0x69** [comment]
Ran into same problem! I'd like to know how to do this.

**Comment by zoontek** [comment]
I am closing this since this issue does not exists anymore with the [2.0.0 release](https://github.com/react-native-community/react-native-permissions/releases/tag/2.0.0).
