### ISSUE TITLE
Is it support with React Native Version 0.57.0?

### ISSUE THREAD

**Issue by lyseiha** [zoontek/react-native-permissions#271]

**Comment by wynch** [comment]
Hello, We're using react-native-permissions along with RN 0.57.0, so far, no problems (except known issues)

**Comment by octobocto** [comment]
@wynch What are the known issues?

**Comment by KevinColemanInc** [comment]
I think this library is having issues described here:

https://github.com/facebook/react-native/issues/17985#issuecomment-429541452

**Comment by zoontek** [comment]
I just tried with a fresh install on RN 0.57, no particular problem noticed. I close this.
