### ISSUE TITLE
How to redirect to app's info dynamically after denied the run-time permission in android?

### ISSUE THREAD

**Issue by Harsh2402** [zoontek/react-native-permissions#272]
### Describe your environment

* React-Native version: 0.57.0
* Platform: Android

If I have always denied the runtime permissions and need to redirect to current app's info for the enable the permission, then how can I redirect to the app info?

**Comment by zoontek** [comment]
I am closing this since this issue does not exists anymore with the [2.0.0 release](https://github.com/react-native-community/react-native-permissions/releases/tag/2.0.0).
