### ISSUE TITLE
Only request Always for location

### ISSUE THREAD

**Issue by jeremyfrancis** [zoontek/react-native-permissions#273]
My issue is simple. In iOS for location, you can only request with the options, "Always" and "When in Use" at the same time. You cannot only prompt the user to select "Always" or only "When in Use", which you are suppose to be able to do.

The solution is to remove the AlwaysAndWhenInUsuageDescription from Info.plist, but in doing so, react-native-permissions cannot work at all.

**Comment by zoontek** [comment]
@jeremyfrancis It's impossible since iOS 10.

If you ask for `Always`, user will have to choose between `Always`, `When in use` or `Never`
If you ask for `When in use`, user will have to choose between `When in use` or `Never`
