### ISSUE TITLE
feature request - FaceID permissions check

### ISSUE THREAD

**Issue by tonmanayo** [zoontek/react-native-permissions#274]
### Feature request - motivation

In the last year quite a few phone models have implemented FaceID to be able to login, we are able to use this feature to authenticate our apps. It would be really cool of this library provided us with the api to check weather faceID has been granted by the user or not on android and IOS or just IOS for now.

If someone knows how to do a PR for this I'd really appreciate it

**Comment by zoontek** [comment]
@tonmanayo It's planned for the version 2.0.0: https://github.com/yonahforst/react-native-permissions/pull/291
