### ISSUE TITLE
SEND_SMS permission

### ISSUE THREAD

**Issue by avishayhajbi** [zoontek/react-native-permissions#275]
Hello,

can you please provide a key for SEND_SMS permission in Android ? 

p.s
i asked for permission and allow but still i got that error
_java.lang.SecurityException: Set ValidityPeriod: uid 10331 does not have android.permission.SEND_SMS_

thanks

**Comment by avishayhajbi** [comment]
SOLVED by updating plugin to sdk 22 
_android studio update it automatically to 23_

**Comment by gamesover** [comment]
react native supports send_sms permission. But this lib does not support send_sms permission?

https://facebook.github.io/react-native/docs/permissionsandroid.html#request

Am I wrong? How could I send sms out automatically without send_sms permission granted?
