### ISSUE TITLE
react-native link react-native-permissions no auto link Android

### ISSUE THREAD

**Issue by giantss** [zoontek/react-native-permissions#280]
`react-native link react-native-permissions` no auto link Android.

## environment

* "react-native": "0.57.5"
* "react-native-permissions": "^1.1.1"

<img width="695" alt="image" src="https://user-images.githubusercontent.com/13778798/48706389-1ab18c80-ec37-11e8-8153-79b6c7e588f5.png">

Why android does not have automatic link ?

**Comment by git-Asir** [comment]
android doesn't have native code
android use permissionAndroid

**Comment by giantss** [comment]
@git-Asir The description of this plugin is like this. `Check and request user permissions in ReactNative (iOS and Android)`

**Comment by darekg11** [comment]
But it does not need to link anything against Android as React-Native provides `AndroidPermissions` module by default:
https://facebook.github.io/react-native/docs/permissionsandroid
