### ISSUE TITLE
Multiple scheme permissions issue

### ISSUE THREAD

**Issue by llaine** [zoontek/react-native-permissions#281]
* React-Native version : 0.57.
* Platform: iOS
* Device: Simulator & Device
* OS version : 12.1
* react-native-permissions version 1.1.1
* Devtools: Xcode

Hello,
I'm having issues requesting permissions on the production scheme of my app.
When I'm using the `Debug` scheme everything works fine and I get the Debug App in the Settings screen, only when I'm in production nothing appears and when requesting the permissions. Nothing is happening.
I'm wondering if this has to do with the fact that I have multiple scheme using multiple bundle id for the same app? 

Any ideas?

**Comment by DimaMklk** [comment]
I have the same problem. Everything is working in the development environment but crashes in production. With some data from the crash reports, I found that the problem is in `getPermissionStatus` function, which I found in the js bundle.

**Comment by DimaMklk** [comment]
I figured out that in my case the problem was that I was linking the library `libReactNativePermissions.a` only in debug scheme and forgot to link it in other schemas

**Comment by llaine** [comment]
My issue is that I wasn't properly asking for the permissions when the state was `undetermined`.
