### ISSUE TITLE
Support for a custom rationale on iOS

### ISSUE THREAD

**Issue by joncursi** [zoontek/react-native-permissions#284]
My app is being rejected by Apple because my camera permission prompts are ambiguous. See below:

```
Guideline 5.1.1 - Legal - Privacy - Data Collection and Storage


We noticed that your app requests the user’s consent to access their camera but does not clarify the use of this feature in the permission modal alert.

Next Steps

To resolve this issue, please revise the permission modal alert to specify why the app is requesting access to the user's camera.

The permission request alert should specify how your app will use this feature to help users understand why your app is requesting access to their personal data.
```

![attachment-7529742165440226486screenshot-1210-095052](https://user-images.githubusercontent.com/4974609/49753797-6d082b00-fc82-11e8-97b9-98e598b679ca.png)

The reason my prompts are generic is because I am using the camera in multiple places in my app for different things, but right now we can only provide one string in `Info.plist`. So I had to generalize the message to fit all use-cases.

I am currently blocked from updating my app in the app store because Apple won't let me push any more updates until these prompts are less general and more specific. 😢 

The iOS portion of this library doesn't seem to currently support the `rationale` field. Can we add this so that we can customize the permission message on a per-prompt basis?

**Comment by zoontek** [comment]
iOS does not supports any rationale others that the one in you app’s plist.

Maybe try to be a little more exhaustive in your description, or consider adding a custom modal before asking them https://github.com/pascalbros/PAPermissions
