### ISSUE TITLE
What is difference between permissions types photo and media Library

### ISSUE THREAD

**Issue by thuytony** [zoontek/react-native-permissions#285]
Hi. I have one question. I don't know what iis difference between permissions types photo and media Library.
Can you help me understand it?
Thank you!

**Comment by zoontek** [comment]
Hi.

Photo = files handled by the photo app (with PhotoKit, more infos: https://developer.apple.com/documentation/photokit?language=objc)

Media Library = audio, podcasts, video (more infos: https://developer.apple.com/documentation/mediaplayer?language=objc)
