### ISSUE TITLE
[Question] for single/multiple permissions request

### ISSUE THREAD

**Issue by ozankonur** [zoontek/react-native-permissions#286]
Android 7.0
Emulator

I am trying to implement multi-permisions. First I tried **single** permission like :

` componentWillMount() {
        Permissions.check('photo').then(response => {
            // Response is one of: 'authorized', 'denied', 'restricted', or 'undetermined'
            this.setState({ photoPermission: response });
            Alert.alert(""+response);
        })
    }`

But I didn't get permission message, so I looked to the response with Alert and it says 'undetermined'
Why there is no any dialog that ask to user permission ?

If I figure single request out, then I will try multiple permission.
Any idea ?

**Comment by Diego-Franco** [comment]
instead of use `check` you need to use `request` or you can do something like 
```
if(response === 'undeterminate) {
Permissions.request('photo').then(result => //here will be your response)
}
```
