### ISSUE TITLE
Requesting 'bluetooth' always 'undetermined'

### ISSUE THREAD

**Issue by philipaarseth** [zoontek/react-native-permissions#292]
Hello!

I'm having some problems, **requesting 'bluetooth' always returns 'undetermined'.**

### environment

* React-Native version: "react-native": "0.57.8",
* Platform: iOS
* Device: iPhone XS Max
* OS version: 12.1.3
* react-native-permissions version: "^1.1.1"
* Devtools: Xcode

### How to repeat issue and example

Followed suggested setup steps + manual Xcode linking

Here's the code

`import Permissions from 'react-native-permissions'`

``` javascript
constructor(props){
    super(props);
    this.state = {
      bluetoothPermission: ''
    };
  }
```

``` javascript
componentDidMount() {
    this.checkBTPermissions();
}

checkBTPermissions() {
    Permissions.check('bluetooth').then(response => {
      // Response is one of: 'authorized', 'denied', 'restricted', or 'undetermined'
      console.log("permissions for bluetooth: " + response);
      this.setState({ bluetoothPermission: response });
      if (response !== 'authorized') {
        this._alertForBTPermission();
      }
    });
  }

_alertForBTPermission = () => {
    Alert.alert(
      'Can we access your bluetooth?',
      'We need access so so we can connect you to the FoodSense unit.',
      [
        {
          text: 'No thanks',
          onPress: () => console.log('Permission denied'),
          style: 'cancel',
        },
        this.state.bluetoothPermission === 'undetermined'
          ? { text: 'Allow', onPress: this._requestPermission }
          : { text: 'Open Settings', onPress: Permissions.openSettings },
      ],
    )
  }


   _requestPermission = () => {
    Permissions.request('bluetooth').then(response => {
      // Returns once the user has chosen to 'allow' or to 'not allow' access
      console.log("permissions for bluetooth is now: " + response)
      // Response is one of: 'authorized', 'denied', 'restricted', or 'undetermined'
      this.setState({ bluetoothPermission: response })
    })
  }
```

I'm getting this error in Xcode when requesting
`[CoreBluetooth] API MISUSE: <CBPeripheralManager: 0x282611b20> can only accept this command while in the powered on state`

So I tried only asking for permission after BLE is powered On like this

``` javascript
import { BleManager } from 'react-native-ble-plx';


componentDidMount() {
    this.bleManager = new BleManager();
    // start scanning for BLE when ready

    const subscription = this.bleManager.onStateChange((state) => {
      if (state === 'PoweredOn') {

          console.log("bluetooth state is now: " + state);
          // check for bluetooth permissions
          if(this.state.checkingForPermissions){
            this.checkBTPermissions();
          }

          if (this.state.bluetoothPermission === 'authorized') {
            this.scanAndConnect();
            subscription.remove();
          }
      }
    }, true);
  }
```
but it didn't work

### Solution

None yet.

**Comment by songxiaoliang** [comment]
same

**Comment by GreyGao** [comment]
same issue

**Comment by Saketh-Reddy** [comment]
@philipaarseth Hey philipaarseth, I just gone through the doc and implemented changes accordingly. I can see a modal popup with allow and deny. when I click on allow .. At this point **__requestPermission_** in this method the state is not updating 
console.log("permissions for bluetooth is now: " + response)

### response : undetermined 

I think this is same case for you .Have you solved this ? if yes can you please let me know. Awaiting for your reply!!

Thanks

**Comment by philipaarseth** [comment]
Unfortunately, I have not found a solution for this yet.

**Comment by zoontek** [comment]
I am closing this since this issue does not exists anymore with the [2.0.0 release](https://github.com/react-native-community/react-native-permissions/releases/tag/2.0.0).
