### ISSUE TITLE
Permissions.request("location") never resolves

### ISSUE THREAD

**Issue by viniciuszim** [zoontek/react-native-permissions#294]
### Describe your environment

* React-Native version: 0.58.4
* Platform: iOS, Android, both?: Only tested on iOS
* Device (which one?), simulator?: Simulator and iPhone X
* OS version: iOS 12.1
* react-native-permissions version: 1.1.1
* Devtools: Xcode? Android Studio version?: VS Code

### How to repeat issue and example

I'm simply running this code on the componentDidMount method:

```js
  checkPermissions = async () => {
   Permissions.check('location', { type: 'whenInUse' }).then((response) => {
      console.tron.log(`locationPermission: ${response}`);
    },
    (error) => {
      console.tron.error(`There has been a problem with your fetch operation: ${error.message}`);
    }).catch(error => console.tron.error(error)); // error handling for promise
  }
```

Nothing appears... just get this error on reactotron:

```
line: 153447
column: 28
sourceURL: http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false
```

### Additional Info
I'm using all UsageDescriptions in my info.plist and it does not work:

```
<key>NSBluetoothPeripheralUsageDescription</key>
  <string>Some description</string>
  <key>NSCalendarsUsageDescription</key>
  <string>Some description</string>
  <key>NSCameraUsageDescription</key>
  <string>Some description</string>
  <key>NSLocationUsageDescription</key>
	<string>GPS data is required to verify your commutes and generate rewards.</string>
	<key>NSLocationWhenInUseUsageDescription</key>
	<string>Permitir acesso a sua localização para encontrarmos os prestadores mais próximos.</string>
	<key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
	<string>Permitir acesso a sua localização para encontrarmos os prestadores mais próximos.</string>
  <key>NSPhotoLibraryAddUsageDescription</key>
  <string>Some description</string>
  <key>NSPhotoLibraryUsageDescription</key>
  <string>Some description</string>
  <key>NSSpeechRecognitionUsageDescription</key>
  <string>Some description</string>
  <key>NSAppleMusicUsageDescription</key>
  <string>Some description</string>
  <key>NSMotionUsageDescription</key>
  <string>Some description</string>
```

**Comment by angielle** [comment]
encountering the same error using Android

**Comment by leofontes** [comment]
Any fix for this?

**Comment by AilsonFreire** [comment]
It's getting undefined

**Comment by ghost** [comment]
Please check this. I will work.

Permissions.request('location').then(response => {
    // Returns once the user has chosen to 'allow' or to 'not allow' access
    // Response is one of: 'authorized', 'denied', 'restricted', or 'undetermined'
    this.setState({cameraPermission: response});
  });

**Comment by zoontek** [comment]
I am closing this since this issue does not exists anymore with the [2.0.0 release](https://github.com/react-native-community/react-native-permissions/releases/tag/2.0.0).
