### ISSUE TITLE
Running `npm install react-native-permissions` installs 2.0.0-alpha.1 instead of 1.1.1 stable. Is this intentional?

### ISSUE THREAD

**Issue by tallpants** [zoontek/react-native-permissions#296]
This is entirely @yonahforst's call but I feel like running `npm install react-native-permissions` shouldn't give you the latest alpha, instead it should give you the last stable release 1.1.1 by default.

You should need to explicity install something `react-native-permissions@next` or `react-native-permissions@2.0.0-alpha.1` to get the alpha since the alpha isn't ready for stable usage yet.

Just want to make sure this is intentional. @yonahforst if you meant to do this then please feel free to close the issue, it's your library all. 😄

**Comment by zoontek** [comment]
@tallpants Not intentional at all, I forgot to add the correct dist-tags 😅
It's fixed, thanks
