### ISSUE TITLE
Great utility! Is Android in the roadmap?

### ISSUE THREAD

**Issue by willks** [zoontek/react-native-permissions#3]
Hi,
  Thanks for this utility! Just wondering if there was an Android app equivalent? I'm just checking as I do want to support Android at one stage. Same behaviour, no reprompt - we'll guide the user into providing the required access if required.

Thanks

**Comment by yonahforst** [comment]
@willks  glad you find it useful. Yeah, android is on the roadmap, in the next month or two.

**Comment by KGALLET** [comment]
So what about Android?

**Comment by yonahforst** [comment]
It's there. Grab the latest version :)

**Comment by KGALLET** [comment]
Upsssss, i didn't see... thx @yonahforst
