### ISSUE TITLE
Async Storage has been extracted from react-native core

### ISSUE THREAD

**Issue by ghost** [zoontek/react-native-permissions#300]
### Describe your environment

* React-Native: 0.59.1
* Platform: Android
* Device: Physical (OnePlus 5)
* OS: 9 (Pie)
* react-native-permissions: 1.1.1
* Devtools: VSCode

### How to repeat issue and example

Getting this warning when used `react-native-permissions` to check for permissions:

```
Warning: Async Storage has been extracted from react-native core and will be removed in 
a future release. It can now be installed and imported from 
'@react-native-community/async-storage' instead of 'react-native'. See
https://github.com/react-native-community/react-native-async-storage
```

### Solution

Importing AsyncStorage from new `@react-native-community/async-storage`

**Comment by JanithaR** [comment]
Import where exactly?

**Comment by ghost** [comment]
@JanithaR, where AsyncStorage is used, all the places. Right now it will be something like this:

```js
import { AsyncStorage } from "react-native";
```

we need to change it to this:

```js
import AsyncStorage from "@react-native-community/async-storage":
```

**Comment by JanithaR** [comment]
That's weird. I'm not even using AsyncStorage, yet I still had to install 

> @react-native-community/async-storage

to get rid of the warning.

**Comment by ghost** [comment]
You might not be using AsyncStorage but some of your dependency might be using. Like for example `react-native-permissions` uses AsyncStorage.

**Comment by anchetaWern** [comment]
I'm also getting the same issue. I tried installing the legacy AsyncStorage from here: https://github.com/react-native-community/async-storage/tree/LEGACY
but the warning is still showing up.

**Comment by jahicDario** [comment]
Any update on this issue? Did someone create a pull request?

**Comment by ghost** [comment]
Already created... https://github.com/yonahforst/react-native-permissions/issues/301

**Comment by zoontek** [comment]
It's now available in the 1.2.0! Please check the changelog https://github.com/react-native-community/react-native-permissions/releases/tag/1.2.0

**Comment by Aequitas737** [comment]
Running 1.2.0
RN 0.59.9

Get error:
```
error: bundling failed: Error: Unable to resolve module `@react-native-community/async-storage` from `...\node_modules\react-native-permissions\index.js`: Module `@react-native-community/async-storage` does not exist in the Haste module map
```

Looks like the dependency isn't set up correctly and the package has to be installed separately

**Comment by zoontek** [comment]
@Aequitas737 Yes, it's a peer dependency.

**Comment by HarisSpahija** [comment]
This is issue is still persistant, is there any way we can fix the package without installing a seperate dependency?

**Comment by zoontek** [comment]
@HarisSpahija No. It will break autolinking for RN 0.60+ users.
