### ISSUE TITLE
Allow XXX to access this device's location, How can I Personalise this alert?  

### ISSUE THREAD

**Issue by rmartinezoliva** [zoontek/react-native-permissions#302]
![foto1](https://user-images.githubusercontent.com/34873868/56448786-f89c6300-62d7-11e9-8cfc-5b37da833c45.png)

### Describe your environment

* React-Native version
* Platform: iOS, Android, both?
* Device (which one?), simulator?
* OS version
* react-native-permissions version
* Devtools: Xcode? Android Studio version?
* (Android only: buildToolsVersion)

**Comment by zoontek** [comment]
You can't. The only text you can personalise is the rationale https://developer.android.com/training/permissions/requesting
