### ISSUE TITLE
A Problem with launching on real iOS device after system update

### ISSUE THREAD

**Issue by AmadeuszZaradny** [zoontek/react-native-permissions#304]
React-Native: 0.58.4
Platform: iOS 12.2 real device
react-native-permissions: ^2.0.0-alpha.1
Devtools: xCode 10.2.1

Hello,
I have a problem with launching my RN app on real iOS device. App is working on both of the simulators (iOS and Android) but if i want to launch it on real device it works fine only on Android. 
I got this error in xCode:

<img width="1141" alt="Screen Shot 2019-04-26 at 5 18 56 PM" src="https://user-images.githubusercontent.com/45848839/56819128-63561d00-6849-11e9-83b0-f63be8ed74cc.png">

**Comment by llanginger** [comment]
Same issue, rn version 0.59.5

**Comment by zoontek** [comment]
@AmadeuszZaradny This already has been fixed here: https://github.com/zoontek/react-native-permissions and will be in the beta :)
