### ISSUE TITLE
Android - App crashes when I change permission from settings

### ISSUE THREAD

**Issue by HugoLiconV** [zoontek/react-native-permissions#307]
### Describe your environment

* React-Native version 0.5
* Platform: iOS, Android, both? Android 
* Device (which one?), simulator? Samsung S8
* OS version 9 
* react-native-permissions version 1.1.1
* Devtools: Xcode? Android Studio version? Visual Studio Code
* (Android only: buildToolsVersion) 26.0.2

### How to repeat issue and an example

I request for permissions for the location and I authorized it. But, then with the app open, I go to setting and I denied the permission and the app crash. I read in the Troubleshooting that that's normal in IOs, but I wanna know if that's something normal in Android

### Solution

Do you know what needs to be done to address this issue? Ideally, provide a pull
request with a fix.

**Comment by mikehardy** [comment]
This is standard android behavior. If you revoke permissions from an app, the system *kills* the app. Immediately. There is no workaround, it is system behavior.

To quickly address the opposite scenario - you will not receive any notification at all if the user uses the system settings to grant permission while your app is running.

**Comment by HugoLiconV** [comment]
@mikehardy Thanks, I just wanted to be sure that that was the expected behavior

**Comment by Pat-Gekoski** [comment]
You can check to see if a specific permission has been granted using the AppState API. For example, using Expo Location you can write something like this:

```
import {AppState} from "react-native";

const [appState, setAppState] = useState(AppState.currentState);

const checkWhenAppStateChanges = (nextAppState) => {
        if (appState.match(/inactive|background/) && nextAppState === "active") {
            checkForPermission();
        }
        setAppState(nextAppState)
    }

const checkForPermission = async () => {
     const permission = await getPermissionAsync();
     return permission.status === 'granted';
}
```

**Comment by mikehardy** [comment]
This is true but it should be noted that many (most?) times when permission changes from the system preferences in Android, the system kills and restarts your app

**Comment by Pat-Gekoski** [comment]
I came to this page with the same issue. While my app was running, if I revoked the permission for location, the app would re-start. If I did it a second time, the app would terminate without restarting. I thought it was a bug in my code or in React. Thanks for the info 👍🏻

**Comment by deepaksinghcb** [comment]
> This is standard android behavior. If you revoke permissions from an app, the system _kills_ the app. Immediately. There is no workaround, it is system behavior.
> 
> To quickly address the opposite scenario - you will not receive any notification at all if the user uses the system settings to grant permission while your app is running.

@mikehardy Apps like Uber is able to manage this scenario. I have checked some other apps as well which are able to to check dynamic changes from settings.

**Comment by mikehardy** [comment]
@deepaksinghcb great report! If you can figure out how they do it (perhaps storing dehydrated local state / nav position, restoring it on restart?) then everyone here would know how to do it as well.

My statements above are facts though as far as I know. You can poll permissions perhaps - at important parts of your app - to get grants but there is no "I was granted a permission" listener you can set. And revokes will kill your app. That is actually a system behavior, not app-specific

**Comment by KiranSayone** [comment]
Is there any method to overcome this issue, .ie., keeping the app open even when the permission is denied from settings. As @deepaksinghcb mentioned apps like uber is handling it somehow. So does anyone know how to handle this scenario. The problem is that when this happens first time the app just restarts and when this happens next time onwards the andorid system starts to show a warning dialogue box telling that this app is crashing many time.

**Comment by vishaljnimblechapps** [comment]
Does anyone have a solution for this problem?

**Comment by Ali-Raza24** [comment]
Is their any solution ?
