### ISSUE TITLE
React Native "react-native-permissions" , Location Settings Enable Error

### ISSUE THREAD

**Issue by ElangoPrince** [zoontek/react-native-permissions#308]
**hi, location access permission error. Permissions request response returns "authorized", but settings can't be enabled.**
 

> here my code:
> `

``
requestPermission = () => {
    Permissions.request('location', 'always')
    .then(response => {
        console.log(response);
    })
    .catch((error) => {
      this.getJobs();
    });
  }
```

**Comment by zoontek** [comment]
I am closing this since this issue does not exists anymore with the [2.0.0 release](https://github.com/react-native-community/react-native-permissions/releases/tag/2.0.0).
