### ISSUE TITLE
[iOS] Request notification permission right after app is initialized and get `denied` response immediately

### ISSUE THREAD

**Issue by MarkRunWu** [zoontek/react-native-permissions#309]
### Describe your environment

* React-Native version: 0.59.5
* Platform: iOS, Android, both? iOS
* Device (which one?), simulator? iphone XR
* OS version: 12.1
* react-native-permissions version: 1.1.1
* Devtools: Xcode? Version 10.1 (10B61)

### How to repeat issue and example

- call Permissions.request('notification') in componentDidMount method of app.js
- show notification permission system dialog for user confirmation and receive `denied` immediately before use click any button.

### Solution

For now, i use `PushNotificationIOS` to check and request notification permission.

**Comment by zoontek** [comment]
I am closing this since this issue does not exists anymore with the [2.0.0 release](https://github.com/react-native-community/react-native-permissions/releases/tag/2.0.0).

**Comment by katesawyerdev** [comment]
This is still happening in v2.0.9 of the app with `"react-native": "0.61.5"` and `"react-native-permissions": "^2.0.9"` using the following request to obtain permissions: 

```
    requestNotifications([
      'alert',
      'badge',
      'sound',
      'criticalAlert',
      'carPlay',
      'provisional',
    ]).then(({ status, settings }) => {
      Alert.alert('requested', JSON.stringify({ status, settings }));
    });
```

**Comment by davrosull** [comment]
@katesowles  I was seeing the same thing until I took out `provisional` and `carPlay`.

**Comment by katesawyerdev** [comment]
Ah yes! I found the same yesterday after a bit of tinkering but failed to follow up. Good catch, @davrosull! 👍
