### ISSUE TITLE
Can't Permissions.check for badge, sound or alert notifications individually.

### ISSUE THREAD

**Issue by noway** [zoontek/react-native-permissions#310]
### Describe your environment

* React-Native version 0.56.0
* Platform: iOS
* Device: iPhone 7 Plus
* OS version: 12.3.1
* react-native-permissions: 1.1.1
* Devtools: Xcode

### How to repeat issue and example
```javascript
    const notificationAlertPermission = await Permissions.check('notification', { type: 'alert' })
    const notificationBadgePermission = await Permissions.check('notification', { type: 'badge' })
    const notificationSoundPermission = await Permissions.check('notification', { type: 'sound' })
```
notificationAlertPermission, notificationBadgePermission and notificationSoundPermission are never the actual alert, badge or sound settings in the iOS settings. I checked the source code of react-native-permissions, and it doesn't look like there's alert, badge and sound specific code for Permissions.check? Only for Permissions.request.

### Solution

I think this feature is just missed? Would really appreciate if this would be implemented.

Thanks.

**Comment by zoontek** [comment]
@noway Indeed, this feature is missing. I add this to the v2 roadmap

**Comment by zoontek** [comment]
It is now possible: https://github.com/react-native-community/react-native-permissions/tree/2.0.0
