### ISSUE TITLE
[Question] Capture permission change event

### ISSUE THREAD

**Issue by vovkind** [zoontek/react-native-permissions#311]
### Describe your environment

* React-Native version: 0.59.8
* Platform: both
* Device: iOS, Android models
* OS version: iOS, Android
* react-native-permissions version: 2.0.0-alpha.1
* Devtools: Xcode, Android Studio
* (Android only: buildToolsVersion): 28

### How to repeat issue and example

I'd like to capture permission change performed by the user: for example, the user has switched off location permission for the app in Settings.

Can we have some callback with using this plugin?

### Solution

Using setInterval to ping status of permission?

**Comment by itsMapleLeaf** [comment]
I'd love something like this, and I don't really see any (efficient) way to do it with the current API. Ideally, I'd like to make a hook like this:
```ts
function useGeoLocation() {
  const [permissionStatus, setPermissionStatus] = useState('undetermined')
  const [location, setLocation] = useState()

  useEffect(() => {
    const unwatch = Permissions.watch('location', setPermissionStatus)
    return () => unwatch()
  }, [])

  useEffect(() => {
    if (permissionStatus !== 'authorized') return

    const watchId = navigator.geolocation.watchPosition(
      setLocation,
      (error) => {},
      { enableHighAccuracy: true },
    )
    return () => navigator.geolocation.clearWatch(watchId)
  }, [permissionStatus])

  return location
}
```
But the only current way to make this work would be to do some sort of interval loop. I don't know if there would be any unwarranted side effects from checking permissions so often, but I imagine it's still not the best idea.

**Comment by zoontek** [comment]
@vovkind You cannot really do it. The best way to handle it might be to check permissions statuses when the app `AppState` get back to `active`.

**Comment by cinder92** [comment]
@zoontek this not works when android users pull statusbar down, only when app is minimized
