### ISSUE TITLE
[Android] Add support for Android Q new ACCESS_BACKGROUND_LOCATION permission

### ISSUE THREAD

**Issue by mhdtouban** [zoontek/react-native-permissions#312]
# Feature Request

Android Q is in Beta 5 right now and is about to be released in **August** following the normal trend. Android Q introduced different changes in the APIs, especially targeting user privacy. It extends the transparency and control that users have over data and app capabilities. 
Privacy checklist summarizes that: https://developer.android.com/preview/privacy/checklist.

One of the key changes is giving the user more control on when to share location in the app.
If the app requires the location while it's in the background, then it won't be able to have access to it unless the user has accepted to provide that. This is the normal behavior starting Android Q, which means it won't affect apps running on prior to android Q. 

## Why it is needed

Currently, PermissionsAndroid doesn't support the new `ACCESS_BACKGROUND_LOCATION`
which breaks the normal behavior an app have if it requires location while it's in background. 

If Android Q device installed the app he would only have access to the location while the app is in the foreground.
https://developer.android.com/preview/privacy/device-location#device-upgrade

## Possible implementation

Follow the changes required in Android documentation
https://developer.android.com/preview/privacy/device-location
migrating to Android Q: https://developer.android.com/preview/migration

**Comment by zoontek** [comment]
I am closing this since this issue does not exists anymore with the [2.0.0 release](https://github.com/react-native-community/react-native-permissions/releases/tag/2.0.0).
