### ISSUE TITLE
[Android] check & request has different value for `receiveSms`

### ISSUE THREAD

**Issue by JulioOrellana** [zoontek/react-native-permissions#315]
# Bug

Wrong response from `.check` using `receiveSms`

## Environment info

React native info output:

```bash
 React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
      Memory: 31.37 MB / 8.00 GB
      Shell: 3.2.57 - /bin/sh
    Binaries:
      Node: 12.4.0 - ~/.nvm/versions/node/v12.4.0/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v12.4.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 25.0.2, 26.0.1, 27.0.3, 28.0.0, 28.0.3
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.1 => 16.6.1
      react-native: 0.57.7 => 0.57.7
```

Library version: `^1.1.1`

## Steps To Reproduce

I am using `receiveSms` check and return value is `undetermined`, so I do `Permissions.request('receiveSms')` and reject it.
After reloading the app, `Permissions.check('receiveSms')` still returns `undetermined` but `Permissions.request('receiveSms')` returns `authorized`.

Even if a deactivate SMS permissions from phone settings, `.check` is still `undetermined`

--

Any way to make `check` detect the right permission?

**Comment by zoontek** [comment]
I am closing this since this issue does not exists anymore with the [2.0.0 release](https://github.com/react-native-community/react-native-permissions/releases/tag/2.0.0).
