### ISSUE TITLE
install react native permission ???  

### ISSUE THREAD

**Issue by hoangngocthangbmw** [zoontek/react-native-permissions#316]
# Question

**Comment by hoangngocthangbmw** [comment]
npm install --save react-native-permissions @react-native-community/async-storage 
yarn add react-native-permissions @react-native-community/async-storage

wth? @react-native-community/async-storage  Install this library for what?
I'm in need of camera and gallery access, 
The command to install is "yarn add-native-permissions"?

**Comment by mikehardy** [comment]
I personally find a question with no real question and a "what the hell" in it a bit insulting.

**Comment by zoontek** [comment]
I don't understand your "question", sorry.
