### ISSUE TITLE
RN 0.60+ support and Android X

### ISSUE THREAD

**Issue by quachsimon** [zoontek/react-native-permissions#318]
We are looking to update our project to the latest version of RN (v0.60.5) and going through the docs I could not find anything on updating this.

All I know is there are breaking changes with 0.60 in regards to Android X and I was wondering if this is in the pipeline somewhere that may be addressed?

Has anyone run into any issues with v0.60+?

Thanks

**Comment by pontusab** [comment]
Can confirm it works with 0.60.5 version `2.0.0-rc.0`

**Comment by mikehardy** [comment]
likewise I'm using it with 0.60.5 and permissions 1.2.0 (and I have jetifier integrated in my postinstall)

**Comment by zoontek** [comment]
@quachsimon Like @pontusab said, version `2.0.0-rc0` have support for RN `0.60`. Check the version documentation to install it: https://github.com/react-native-community/react-native-permissions/tree/2.0.0?files=1 🙂

If you are not ready to make the change, `jetifier` is an option too.
