### ISSUE TITLE
Unable to resolve module @react-native-community/async-storage

### ISSUE THREAD

**Issue by ghost** [zoontek/react-native-permissions#319]
# Bug

I get the following error :

![Screenshot_1567157112](https://user-images.githubusercontent.com/50737997/64009829-e4cffb80-cb18-11e9-8499-21ed324301d6.png)

See latest version changelog :

> ⚠️ BREAKING CHANGE. Since AsyncStorage has been removed from the core, react-native-permissions now relies on @react-native-community/async-storage

## Environment info

React native info output:

```bash
React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (8) x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
      Memory: 537.23 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.15.1 - /usr/local/opt/node@8/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/opt/node@8/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
      Android SDK:
        API Levels: 23, 24, 25, 26, 27, 28
        Build Tools: 27.0.3, 28.0.2, 28.0.3
        System Images: android-23 | Google APIs Intel x86 Atom, android-24 | Google Play Intel x86 Atom, android-25 | Google Play Intel x86 Atom, android-26 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.4 => 16.8.4 
      react-native: 0.59.10 => 0.59.10 
    npmGlobalPackages:
      create-react-native-app: 2.0.2
      react-native-bcrypt: 2.4.0
      react-native-cli: 2.0.1
```

Library version: ^1.1.1

## Steps To Reproduce

1. react-native run-android
...

Describe what you expected to happen:

1. On my emulator, I get this error

I think it's caused by my react-native version which is not compatible with latest react-native-permissions release. I think I have to upgrade my **react-native** version or downgrade **react-native-permissions** to 1.1.1 ?

**EDIT:**

I confirm that downgrade **react-native-permissions** to 1.1.1 works for me

**Comment by zoontek** [comment]
Did you install and link @react-native-community/async-storage? It does not came as a dependency with 1.2.0, it's only a peer dependency.

**Comment by ghost** [comment]
@zoontek Yes I do ! But same result... When I downgrade react-native-permissions to 1.1.1 version, it's works ! I think I should upgrade my react-native version if I want react-native-permissions 1.2.0 version

**Comment by zoontek** [comment]
Because the version 1.1.1 use `AsyncStorage` from react-native (which is now deprecated).
Please check that you follow every steps from their 0.59 install: https://github.com/react-native-community/async-storage/blob/LEGACY/README.md

**Comment by zoontek** [comment]
I am closing this since this issue does not exists anymore with the [2.0.0 release](https://github.com/react-native-community/react-native-permissions/releases/tag/2.0.0).
