### ISSUE TITLE
Add auto start permission request for Android

### ISSUE THREAD

**Issue by bogdancochioras-clarisoft** [zoontek/react-native-permissions#321]
# Feature Request

  Add auto start permission request for Android.

## Why it is needed

    Some devices need to have a request for auto start of application on Android so that push notifications are received after application is killed, can such permission handling be added, see the following issues as reference: [](https://github.com/firebase/quickstart-android/issues/41)

**Comment by zoontek** [comment]
@bogdancochioras-clarisoft This is not related to user permissions
