### ISSUE TITLE
Release 1.21 is missing Android and lacking documentation.

### ISSUE THREAD

**Issue by AndreasAnderssonBluedeer** [zoontek/react-native-permissions#327]
![Screenshot 2019-09-30 at 16 54 47](https://user-images.githubusercontent.com/11209801/65890353-08e65d00-e3a3-11e9-8de1-2e418164b0b5.png)
Hi, 
first time I'm using your lib - and unfortunately stumbled into trouble right away. I'm building a react native app on version 59.10 (currently). Downloaded the 1.21 version and manage to integrate the IOS version after some Podfile issues. (The documentation isn't updated with the correct pod file names, podspecs etc). 

However - your 1.21 release doesn't include any android project. 
would be great if you want to release an update.

**Comment by mikehardy** [comment]
You should use v2.0.0 in combination with jetifier -r (if you need to stay on support libraries), I'm not sure it is even worthwhile to troubleshoot a v1 issue here. For v1 I used the react-native built in permissions for Android, personally

**Comment by zoontek** [comment]
@bambismurfen Version 1.x never shipped with `/android`native implementation, but relied on `PermissionsAndroid` React Native bundled API.

As @mikehardy said, I really suggest you to use `2.0.0` with `jetifier`. Version 1.x does not supports Android 10 / iOS 13 and will never be.

> The documentation isn't updated with the correct pod file names, podspecs etc

What do you mean by this? The list is [here](https://github.com/react-native-community/react-native-permissions#ios) and the `podspec` files [here](https://github.com/react-native-community/react-native-permissions/tree/2.0.0/ios)

**Comment by AndreasAnderssonBluedeer** [comment]
Oh okay - my bad! Guess I'll have ago on that tomorrow then.

Thanks for the quick response!

Den mån 30 sep. 2019 18:53Mathieu Acthernoene <notifications@github.com>
skrev:

**Comment by zoontek** [comment]
@bambismurfen No problem! Don't hesitate if you have any struggle. Documentation for the v2 is still basic and need improvements, we need your feedbacks for this 🙂
