### ISSUE TITLE
Android openSettings

### ISSUE THREAD

**Issue by vinayr** [zoontek/react-native-permissions#33]
`openSettings` for Android opens application settings which just shows list of permissions for that app. We cannot change permissions like in iOS. It would be better if `openSettings` for Android opens device settings (`ACTION_SETTINGS`) instead of app settings (`ACTION_APPLICATION_DETAILS_SETTINGS`).

**Comment by yonahforst** [comment]
@vinayr I think the behavior depends on the android version, if it's pre or post M.

From what I remember, post M `ACTION_APPLICATION_DETAILS_SETTINGS` opens a screen that lets you change the permission settings.

**Comment by vinayr** [comment]
You are right. Marshmallow's app permission is similar to iOS.
