### ISSUE TITLE
No visible @interface for CBManager while building on xcode 10.3

### ISSUE THREAD

**Issue by jimji1005** [zoontek/react-native-permissions#333]
# Bug

When attempting to build on Xcode with bluetooth peripherial pod, xcode throws error 
`No visible @interface for 'CBManager' declares the selector 'authorization'`

Have not tested this on xcode 11. 

## Environment info

React native info output:

```bash
info 
  React Native Environment Info:
    System:
      OS: macOS 10.14.6
      CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
      Memory: 655.88 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
      Yarn: 1.19.0 - /usr/local/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.10 => 0.59.10 
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

<img width="213" alt="Screen Shot 2019-10-03 at 11 13 29 AM" src="https://user-images.githubusercontent.com/5834998/66152703-e46ec880-e5ce-11e9-9a24-aed94018689d.png">

Library version: 2.0.0

## Steps To Reproduce

1. Install lib
2. Add `pod 'Permission-BluetoothPeripheral', :path => "#{permissions_path}/BluetoothPeripheral.podspec"`
3. build
Describe what you expected to happen:

should build without error

**Comment by jimji1005** [comment]
Xcode 10.3 does not have this problem with `2.0.0-rc1`

i think the 2.0.0 bluetooth podspec is the cause

The only downside of using 2.0.0-rc1 is that bluetoothPermission always says unavailable

**Comment by zoontek** [comment]
@jimji1005 For now, this lib require Xcode 11 / iOS 13 SDK (even if support does down to iOS 9).
On iOS 12-, Bluetooth permission will always returns `unavailable` on simulator, you need to check it on a real device. It will also returns `unavailable` if you don't check `Acts as a BluetoothLE accessory`.

**Comment by jimji1005** [comment]
@zoontek thanks for the confirmation. 

I guess there is some confusion on my part to what `Acts as a BluetoothLE accessory` is for. 

With ios 13 various apps started to request permission on Bluetooth protocols, the `Permission-BluetoothPeripheral` listed here, is that the permission that we are requesting here? 

If so, what downside would `Acts as a BluetoothLE accessory` bring to the app? (exposed to scanning?)

With the new ios 13 its bringing quite a lot of headaches on BLE stuff at the moment specially with the new permissions

**Comment by jimji1005** [comment]
@zoontek just re-read the apple docs on this.
`bluetooth-peripheral` basically allows app to advertise while in background. its not something that we need. We would only need `bluetooth-central` which is basically interacting with ble while in background..

is `Permission-BluetoothPeripheral` for `bluetooth-peripheral` only?

**Comment by zoontek** [comment]
> is `Permission-BluetoothPeripheral` for `bluetooth-peripheral` only?

Yes. An elegant solution could be to write a `Permission-BluetoothCentral` handler which will require `bluetooth-central` `UIBackgroundMode`. It will make no difference on iOS 13 (which uses `CBManager.authorization` anyway).

I will also add development warnings about `UIBackgroundMode` to enable.

**Comment by jimji1005** [comment]
@zoontek is there any plans to add a permissions request for the _basic_ `bluetooth sharing` option for ios 13? Screenshot below.

![IMG_EE996D770B40-1](https://user-images.githubusercontent.com/5834998/66231817-41848000-e69c-11e9-8f68-be56ac1154a1.jpeg)

**Comment by zoontek** [comment]
@jimji1005 Not for now, but pull requests are welcomed.

**Comment by jimji1005** [comment]
Confirmed that build does work with Xcode 11

**Comment by ajaykumar97** [comment]
I am facing this issue saying ``"No visible @interface for CBManager while building on xcode 10.3"``while creating the "Archive". When I run in debug mode, everything is working fine. Can anyone tell me the workaround for this?

**Comment by zoontek** [comment]
@ajaykumar97 With Xcode 11?

**Comment by ajaykumar97** [comment]
@zoontek No! My version configuration is:

```
Xcode: 10.1
react-native: 0.61.1
react-native-permissions: 2.0.2
```

**Comment by zoontek** [comment]
@ajaykumar97 That's normal then. This lib targets iOS 9 to iOS13.

You can update it via the App store, it's free

**Comment by ajaykumar97** [comment]
@zoontek So you are saying that upgrading Xcode to ``Xcode 11`` would resolve the issue. Right?

**Comment by zoontek** [comment]
@ajaykumar97 Yes

**Comment by ajaykumar97** [comment]
@zoontek Okay. Thanks for your help.
