### ISSUE TITLE
Invalid RNPermission 'ios.permission.LOCATION_WHEN_IN_USE' should be one of

### ISSUE THREAD

**Issue by mertbuldur** [zoontek/react-native-permissions#339]
Hi I have some error help me please 
My Code is :
`check(PERMISSIONS.IOS.LOCATION_WHEN_IN_USE)
            .then(result => {
                switch (result) {
                    case RESULTS.UNAVAILABLE:
                        console.log(
                            'This feature is not available (on this device / in this context)',
                        );
                        break;
                    case RESULTS.DENIED:
                        console.log(
                            'The permission has not been requested / is denied but requestable',
                        );
                        break;
                    case RESULTS.GRANTED:
                        console.log('The permission is granted');
                        break;
                    case RESULTS.BLOCKED:
                        console.log('The permission is denied and not requestable anymore');
                        break;
                }
            })
            .catch(error => {
                // …
            });`

**Comment by zoontek** [comment]
@mertbuldur Did you check https://github.com/react-native-community/react-native-permissions/issues/326 ?

**Comment by mertbuldur** [comment]
@zoontek  Thanks for help , open .xworkspace after rebuild its worked :D
