### ISSUE TITLE
Requesting PERMISSIONS.IOS.MICROPHONE not working on iOS 11.4 simulator

### ISSUE THREAD

**Issue by defrian** [zoontek/react-native-permissions#349]
# Bug

iOS system dialogue for the user to allow microphone access does not come up on iOS 11.4.
It works on iOS 12.2 and 13.1

## Environment info

React native info output:

```bash
System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 3.60 GB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.16.2 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.1, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
  IDEs:
    Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.2 => 0.61.2 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7
```

Library version: 2.0.2

## Steps To Reproduce

1. Init new RN project
2. run npm install --save react-native-permissions
2. Add pods for this Library
3. Add NSMicrophoneUsageDescription to Info.plist
4. Add code to request microphone
5. Run in simulator with iOS 11.4
6. ...

Describe what you expected to happen:

1. System dialogue comes up for the user to allow microphone usage

## Reproducible sample code

Git repo: https://github.com/defrian/PermissionTest

```
import React from 'react';
import {View, Text} from 'react-native';
import {request, check, PERMISSIONS} from 'react-native-permissions';

const checkPermission = () => {
  console.log();
  check(PERMISSIONS.IOS.MICROPHONE).then(response => {
    console.log(response);
  });

  request(PERMISSIONS.IOS.MICROPHONE).then(response => {
    console.log(response);
  });
};

const App = () => {
  checkPermission();
  return (
    <View>
      <Text>Text</Text>
    </View>
  );
};

export default App;
```

**Comment by zoontek** [comment]
Indeed, this seems like a bug on iOS since they're no particular workaround by iOS version in microphone permission handler (https://github.com/react-native-community/react-native-permissions/blob/master/ios/Microphone/RNPermissionHandlerMicrophone.m)

I found similar issues on the web:
https://stackoverflow.com/questions/34696761/avcapturedevice-requestaccessformediatype-never-pops-up-window-and-always-return

I will try on a real device if I can find one blocked on iOS 11.

Edit: another infos, it might only happen in simulator: https://stackoverflow.com/questions/18957643/requestrecordpermission-does-nothing

Even on this repository: https://github.com/react-native-community/react-native-permissions/issues/58

**Comment by zoontek** [comment]
Just made a test with a real device using iOS 10.3 (that's all I've got): OK and 10.3 simulator: KO (same issue)

@defrian Can you confirm the issue only exists in the simulator?

**Comment by defrian** [comment]
I will try to get a physical device running iOS 11 to test it.
What I can confirm is that it worked with XCode 10 and react-native-permissions version 1.2.1

**Comment by aftab410005** [comment]
"WORKING PERFECT NOW"
Its working in my case:
My steps for Microphone permission====>>>
1.install package
"react-native-permissions"
2.pod install
3.I add in podfile below path:
pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone.podspec"

4.pod install 

5.Then in coding::::

 request(PERMISSIONS.IOS.MICROPHONE).then((result) => {
                console.log("permission is--------", result)
              //here getting response as expected
    
            })

Now its working perfect.....!!!!!

So what I was missing before is below path, that is most important step.
pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone.podspec"

After that do not forgot === pod install
*comment if anyone still face issue*
Good luck!!
