### ISSUE TITLE
"photo" or "photos" ?

### ISSUE THREAD

**Issue by norman-kapschefsky** [zoontek/react-native-permissions#35]
Hi @yonahforst, I'm developing for android and iOS and the permission identifier for photos is different on these platforms. I have to use "photos" on Android and "photo" on iOS. Can you roger that? Seems like a bug?!?

Using `"react-native-permissions": "^0.2.4"`

Thank you in advance.

**Comment by yonahforst** [comment]
it's 'photo' (related to #24 ) 
Looks like I need to release a new NPM version. 

In the meantime, try using `"react-native-permissions": "yonahforst/react-native-permissions"`

**Comment by norman-kapschefsky** [comment]
Thank you for your reply. Sorry for duplicate issue. Didn't checked it out. Looking forward to new npm version.
