### ISSUE TITLE
v2.0.2 androidx.core.app does not exist 

### ISSUE THREAD

**Issue by ivankdev** [zoontek/react-native-permissions#351]
"react": "16.8.6",
"react-native": "0.59.9",
"react-native-permissions": "2.0.2", // 2.0.0 the same

Steps:
1) npm install react-native-permissions
2) react-native link react-native-permissions
3) react-native run-android

Result
```
> Task :react-native-permissions:compileDebugJavaWithJavac FAILED
/[.........]/app/node_modules/react-native-permissions/android/src/main/java/com/reactnativecommunity/rnpermissions/RNPermissionsModule.java:10: error: package androidx.core.app does not exist
import androidx.core.app.NotificationManagerCompat;
                        ^
/[.......]/app/node_modules/react-native-permissions/android/src/main/java/com/reactnativecommunity/rnpermissions/RNPermissionsModule.java:91: error: cannot find symbol
    final boolean enabled = NotificationManagerCompat.from(reactContext).areNotificationsEnabled();
                            ^
  symbol:   variable NotificationManagerCompat
  location: class RNPermissionsModule
```

Any ideas?

**Comment by antitoine** [comment]
@a-million-starflakes Why did you close this issue? Have you found any fix ? I run into the same issue.

**Comment by a-million-starflakes** [comment]
@antitoine Found on general page `2.0.0+ & jetify -r | 0.59.0 - 0.59.10`, but actually used 1.1.1 version. I didn't exactly get what specifically do with jetify, if it doesn't solve the issue, I can reopen it.

**Comment by ivankdev** [comment]
@antitoine no actually, but found this `2.0.0+ & jetify -r | 0.59.0 - 0.59.10`. probably it needs some stuff with jetify. can you check it?

**Comment by zoontek** [comment]
@antitoine Because it's the first line of the documentation https://github.com/react-native-community/react-native-permissions/blob/master/README.md#support

**Comment by antitoine** [comment]
Right, I miss the `jetify -r`. Thanks.

**Comment by christopher-18** [comment]
how to use jetify -r @antitoine @zoontek

**Comment by antitoine** [comment]
@18bhavna Read: https://www.npmjs.com/package/jetifier#to-jetify--convert-node_modules-dependencies-to-androidx
You need to run `jetify -r` in the `postinstall` script of your npm package.

**Comment by christopher-18** [comment]
@antitoine I followed the instructions mentioned in the link you mentioned. 
Now my package.json looks like this,

```
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest",
    "prepare": "patch-package",
    "postinstall": "npx jetify -r"
  },
```
Steps that I did,
1. Removed my package.lock and node_modules. 
2. npm i 
by doing so, my other libraries started giving me error. 
Then I added 
```
android.useAndroidX=true
android.enableJetifier=true
```
in my **gradle.properties**, but then I am getting the following the error in one of the library **netInfo**->
 package android.support.v4.net does not exist
import android.support.v4.net.ConnectivityManagerCompat;

Are the steps mentioned are correct?

**Comment by mikehardy** [comment]
>     "postinstall": "npx jetify -r"

So you want to reverse jetify, that is you state: "I do not want to use AndroidX, I want to use the old Android Support Libraries"

Fair enough

> android.useAndroidX=true
> android.enableJetifier=true

Wait, now you say: "I want to use AndroidX"

Those two things do not go together

**Comment by christopher-18** [comment]
@mikehardy my bad! adding postinstall script did work. Just had to fix the dependencies for which the patch file was giving the error.

**Comment by e1016** [comment]
For me was solved by running in terminal `npx jeitfy -r` on the root, thanks.

**Comment by igorgabriel12** [comment]
it worked for me

**Comment by igorgabriel12** [comment]
it worked for me @bhavna-18
