### ISSUE TITLE
Is this package safe for apple review process?

### ISSUE THREAD

**Issue by thanhgiangleo** [zoontek/react-native-permissions#352]
# Question
I want to ask if this package is safe when developers commit to the app store? I mean, before there is also a `react-native-permissions` package (not belongs to community) that requires us to declare almost permissions (many of them didn't suitable for out purposes, and we didn't need to declare those in `Info.plist`, and therefore apple guys rejected our binary).
I've read the docs that we just need to put permissions we need in `Podfile`. I just want to make sure that it's ok when we upload the binary for the review process.
Thanks in advance.

**Comment by mikehardy** [comment]
@thanhgiangleo this is actually the same package as the previous one you mention (hanging off https://github.com/zoontek) it was just moved as a full repo to react-native-community, so it's the same people and the same codebase

That said, the version 2 that was just released after tremendous effort by zoontek addresses the specific problem you mention so you should be okay without all the permission description entries in your plist and possibly difficult review process - 1st bullet point in the release https://github.com/react-native-community/react-native-permissions/releases/tag/2.0.0
