### ISSUE TITLE
Request multiple android permissions in same dialog

### ISSUE THREAD

**Issue by Strate** [zoontek/react-native-permissions#354]
# Feature Request

Allow to request multiple android permissions in one dialog.

## Why it is needed

Common pattern in android is request multiple permissions in one dialog. For example, if you need to take a photo, you need to access CAMERA and EXTERNAL_STORAGE. This is already implemented in PermissionsAndroid RN module: https://facebook.github.io/react-native/docs/permissionsandroid#requestmultiple

## Possible implementation

We can dig into RN module to get code from that.

**Comment by zoontek** [comment]
@Strate A recipe already exists for this: https://github.com/react-native-community/react-native-permissions#request-multiples-permissions

The only difference is that it will not display the total numbers of permissions (2 of 2 on this screenshot)

![Ev2uO](https://user-images.githubusercontent.com/1902323/67005578-33dee980-f0e3-11e9-8ee1-7bba161772b3.png)

But it works on iOS.

**Comment by Strate** [comment]
@zoontek yes, sequentially requesting permissions is solution for now.

But this FR addressed to display total number of permissions in android.

**Comment by mikehardy** [comment]
I understand this is not always a good UI pattern, I just wanted to mention that I have had a project where I was *specifically* asked to pop a request for all the permissions at once. You never know what a business user wants :-). So I think it's a valid feature request if that's worth anything. Cheers

**Comment by zoontek** [comment]
Shipped in [the last version](https://github.com/react-native-community/react-native-permissions/releases/tag/2.1.0) 🎉
