### ISSUE TITLE
ld: library not found for -lReactNativePermissions

### ISSUE THREAD

**Issue by alex-miller-0** [zoontek/react-native-permissions#356]
# Question

I'm trying to use the latest version (`2.0.2`) with react native `0.60.6` and am having trouble building the project. My project does **not** use cocoapods and I am trying to build in XCode. I have added `RNPermissions.xcodeproj` to my project's libraries and `libRNPermissions.a` is in the build phase. This has been sufficient for every other RN lib I've used.

I was previously running into [this issue](https://github.com/react-native-community/react-native-permissions/issues/344#issuecomment-539756320) (from #344, but not the original error) but doing a deep clean of my project resolved that and led to this error instead:

```
ld: library not found for -lReactNativePermissions
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Any help would be appreciated!

**Comment by alex-miller-0** [comment]
This was my mistake - I still had an old version of `RNPermissions.xcodeproj` included in the build that was messing something up. Sorry!

**Comment by abdullateef97** [comment]
@alex-miller-0 can ypu please help explain how you fixed this issue. thanks

**Comment by mmarquezv** [comment]
Hello, I'm having the same issue with RN 0.59.8 and RNPermissions 2.0.10. ¿Has anyone solved the build problem?

**Comment by abdullateef97** [comment]
@mmarquezv [this stackoverflow link](https://stackoverflow.com/a/60808953/9604547) solved it for me

**Comment by bilsak18** [comment]
When you open your project in Xcode, inside the **Libraries** folder, you'll see that you have **RNPermissions.xcodeproj**, delete it (move to Trash). 

That's what worked for me. Hope it helps someone.

**Comment by mtalhagaoglu** [comment]
i have same problem... is there any solution for it?
