### ISSUE TITLE
Always returns unavailable on IOS simulator

### ISSUE THREAD

**Issue by JensonMiralles** [zoontek/react-native-permissions#357]
When I request `location` permission on simulator, `react-native-permissions` always returns `unavailable`. Is this expected behaviour for simulators? So the only way to test permissions is through real devices only? 🤔

**Comment by devdotmohit** [comment]
@JensonMiralles Set **NSLocationWhenInUseUsageDescription** or **NSLocationAlwaysUsageDescription** string in Info.plist.

**Comment by zoontek** [comment]
Is location simulation activated in the simulator settings?

<img width="887" alt="Screenshot 2019-10-18 at 15 31 07" src="https://user-images.githubusercontent.com/1902323/67140816-b5a75200-f25e-11e9-84ad-133cdda61101.png">

**Comment by JensonMiralles** [comment]
Thank you for the info guys! I've updated the `react-native-permissions` to 2.0.2 and it gave me warning about missing `UIBackgroundModes`, so I've added it into my plist, and it fixed my problem.
Once again, thank you, the library really is a big help! 💯

I'm closing the issue now.
