### ISSUE TITLE
How to Test Components?

### ISSUE THREAD

**Issue by joncursi** [zoontek/react-native-permissions#36]
I have a component that uses this module to check for and acquire the user's location.

``` js
    Permissions.getPermissionStatus('location')
      .then((response) => { ... });
```

When I run my unit test suite (Enzyme) on this component, I get the following error:

```
TypeError: Cannot read property 'getPermissionStatus' of undefined
      at ReactNativePermissions.getPermissionStatus (node_modules/react-native-permissions/ReactNativePermissions.js:62:11)
```

How does one test their components that use this module? Is there a way to mock this out?

**Comment by yonahforst** [comment]
I use a solution based on this thread: https://github.com/lelandrichardson/react-native-mock/issues/23

I have a `testHelper.js` that looks like this:

``` js
global.__DEV__ = true

require('react-native-mock/mock');

import mockery from 'mockery'
mockery.enable({
    warnOnReplace: false,
    warnOnUnregistered: false
})

const cblMock = {
    manager: () => {}
}

mockery.registerMock('react-native-push-notification', {})
mockery.registerMock('react-native-facebook-login', {})
mockery.registerMock('react-native-couchbase-lite', cblMock)
mockery.registerMock('NavigationStateUtils', {})
mockery.registerMock('react-native-permissions', {})
```

and in my `package.json`

```
....
  "scripts": {
    "start": "react-native start",
    "test": "mocha --require testHelper.js --compilers js:babel-core/register --recursive src/**/__test__/*.js"
  },
....
```

**Comment by joncursi** [comment]
@yonahforst thanks. It looks like the following tweak is what my code is looking for:

``` js
// setup.js

global.Permissions = {
  location: 'undetermined',
};

mockery.registerMock('react-native-permissions', {
  getPermissionStatus: (type) => Promise.resolve(
    global.Permissions[type]
  ),
});
```

``` js
// test.js

global.Permissions.location = 'authorized'; // set the status needed for the test
expect(something).toEqual(something);
global.Permissions.location = 'undetermined'; // reset to default when test completes
```

**Comment by joncursi** [comment]
@yonahforst would you mind showing me how you would test the following snippet? I'm having a hard time figuring out how to test this due to the use of promises in this package. My toolset is mocha + enzyme + sinon + expect.

Okay, here is a component with an `_askForLocation` method that is called if we detect the user has not yet enabled location services. The calling of this method is invoked once the promise resolves and the status is matched in the switch statement.

``` js
// Component

  componentWillMount() {
    Permissions.getPermissionStatus('location')
      .then((response) => {
        switch (response) {
          case 'undetermined': {
            this._askForLocation();
            break;
          }
          ...
        }
      });
  }

  _askForLocation() { ... };

  ...

```

``` js
  // test file

  it(`calls _askForLocation() when location is undetermined`, function () {
    const callback = sinon.spy(Component.prototype, '_askForLocation');
    shallow(
      <Location {...minProps} />
    );

    expect(
      callback.calledOnce
    ).toEqual(true);
    Location.prototype._askForLocation.restore();
  });
```

This fails because the assertion is run before the Permissions promise is resolved. Can you show me how to tell mocha to "wait"? My initial guess was to wrap the assertion in a `setTimeout` block, but that returned false positives. From my research online, it seems like mocha should "return a promise" or "use a done callback" here, but couldn't quite piece it together to make this work. Any help would be appreciated, thanks!
