### ISSUE TITLE
check(PERMISSIONS.IOS.LOCATION_ALWAYS) returns unavailable

### ISSUE THREAD

**Issue by efecantekin** [zoontek/react-native-permissions#361]
# Question

Hello,

After

`npm install --save react-native-permissions`

I added

```
 permissions_path = '../node_modules/react-native-permissions/ios'
 pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways.podspec"
 pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse.podspec"
```

to my Podfile.

Then updated info.plist with adding

```
  <key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
  <string>YOUR TEXT</string>
  <key>NSLocationAlwaysUsageDescription</key>
  <string>YOUR TEXT</string>
  <key>NSLocationWhenInUseUsageDescription</key>
  <string>YOUR TEXT</string>

```

I want to check location permission for ios with

```
check(PERMISSIONS.IOS.LOCATION_ALWAYS)
        .then((permissionResult) => {
```

But it always returns **unavailable** on iOS 12.4 simulator.

I use now 2.0.2 as a version.
RN: 0.60.5

**Comment by zoontek** [comment]
@efecantekin Did you check https://github.com/react-native-community/react-native-permissions/issues/357 ?

**Comment by efecantekin** [comment]
> @efecantekin Did you check #357 ?

Yes, also I see my location on simulator but check returns unavailable.

If the meaning of adding UIBackgroundModes is like
`<key>UIBackgroundModes</key>`
to plist, I did it.

**Comment by zoontek** [comment]
Are location services enabled on the simulator (Settings > Privacy)?

<img width="584" alt="Screenshot 2019-10-20 at 23 53 51" src="https://user-images.githubusercontent.com/1902323/67166969-ec7f8400-f394-11e9-856e-0fd4278bf23d.png">

Does location update background mode is enable in Xcode?

<img width="634" alt="Screenshot 2019-10-20 at 23 56 29" src="https://user-images.githubusercontent.com/1902323/67167026-6f084380-f395-11e9-9773-bb3ce96b028f.png">

**Comment by efecantekin** [comment]
> Are location services enabled on the simulator (Settings > Privacy)?
> 
> <img alt="Screenshot 2019-10-20 at 23 53 51" width="584" src="https://user-images.githubusercontent.com/1902323/67166969-ec7f8400-f394-11e9-856e-0fd4278bf23d.png">
> 
> Does location update background mode is enable in Xcode?
> 
> <img alt="Screenshot 2019-10-20 at 23 56 29" width="634" src="https://user-images.githubusercontent.com/1902323/67167026-6f084380-f395-11e9-9773-bb3ce96b028f.png">

<img width="366" alt="Screen Shot 2019-10-21 at 00 53 09" src="https://user-images.githubusercontent.com/3815883/67167042-01144a00-f39e-11e9-9da1-3366231a98a1.png">

Yes, I see custom location on map.

**Comment by zoontek** [comment]
@efecantekin Seeing your location on the map does not mean that you have the right to use the location when the app is in background.

You need to add `location` in your `UIBackgroundModes`: https://github.com/react-native-community/react-native-permissions/blob/master/example/ios/RNPermissionsExample/Info.plist#L74

**Comment by efecantekin** [comment]
> You need to add `location` in your `UIBackgroundModes`: https://github.com/react-native-community/react-native-permissions/blob/master/example/ios/RNPermissionsExample/Info.plist#L74

The point was this.

Thank you,

**Comment by apoorva-techie** [comment]
What if I only want to use significant location tracking feature of iOS in background and do not want to enable this UIBackgroundModes location to track locations in background? I still need the permission from user to "Always allow" but location background mode not enabled?
This used to work fine in the earlier versions of react-native-permissions.
Any Thoughts?

**Comment by zoontek** [comment]
@apoorva-techie Indeed, I will remove the check.

**Comment by zoontek** [comment]
@apoorva-techie Done https://github.com/react-native-community/react-native-permissions/releases/tag/2.0.3

**Comment by apoorva-techie** [comment]
> @apoorva-techie Done https://github.com/react-native-community/react-native-permissions/releases/tag/2.0.3

Thank you! Life saver this was!
