### ISSUE TITLE
ios.permission.LOCATION_WHEN_IN_USE'. should be one of

### ISSUE THREAD

**Issue by MuhammadNayabButt** [zoontek/react-native-permissions#362]
I have added the library manually. Followed these steps
https://facebook.github.io/react-native/docs/linking-libraries-ios#manual-linking

I have linked all libraries manually and they work fine. Pods have been used but only for NativeLibraries i.e Firebase, GoogleMaps etc. For React-Native libraries I am not using Pods because at the start I encountered issues of duplicate React folder.

App Crashes when I try to read permissions
Invalid RNPermission 'ios.permission.LOCATION_WHEN_IN_USE'. should be one of: (

## Environment info

System:
    OS: macOS Mojave 10.14.6

  SDKs:
    iOS SDK:
      Platforms: iOS 13.0, 
  
IDEs:
    Xcode: 11.0
  react-native: 0.59.9

**Comment by zoontek** [comment]
@MuhammadNayabButt Please submit your `Podfile`.

EDIT: Even if you don't use Cocoapods, you need to link permissions handlers. If you don't want to rely on a `Podfile` for this, follow https://github.com/react-native-community/react-native-permissions/issues/348#issuecomment-541423154

**Comment by MuhammadNayabButt** [comment]
@zoontek 
I am using CocoaPods but only for native libraries not for ReactNative Libraries
here is the Podfile


target 'MyApp' do 
  pod 'Stripe', '~> 14.0.0'
  pod 'AppAuth', '0.95.0'
  pod 'Intercom'
  pod 'GoogleMaps' 
  pod 'Google-Maps-iOS-Utils'
 
 pod 'FBSDKCoreKit', '~> 5.5'

 pod 'FBSDKLoginKit', '~> 5.5'

 pod 'FBSDKShareKit', '~> 5.5'

 pod 'GoogleSignIn', '~> 4.4.0'
 pod 'Firebase/Auth'
 pod 'Firebase/Analytics'
 pod 'Firebase/Messaging'
 
end

**Comment by zoontek** [comment]
Add handler like mentionned here https://github.com/react-native-community/react-native-permissions#ios

```ruby
target 'MyApp' do
pod 'Stripe', '~> 14.0.0'
pod 'AppAuth', '0.95.0'
pod 'Intercom'
pod 'GoogleMaps'
pod 'Google-Maps-iOS-Utils'

pod 'FBSDKCoreKit', '~> 5.5'

pod 'FBSDKLoginKit', '~> 5.5'

pod 'FBSDKShareKit', '~> 5.5'

pod 'GoogleSignIn', '~> 4.4.0'
pod 'Firebase/Auth'
pod 'Firebase/Analytics'
pod 'Firebase/Messaging'

permissions_path = '../node_modules/react-native-permissions/ios'
pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways.podspec"

end
```

**Comment by MuhammadNayabButt** [comment]
I did this and it resulted in Duplication of React framework
it exist in Under Libraries as well as Under Pods

I did another thing I removed `.depenency : React` from .podspec file but it resulted in obvious error of `React/RCTBridgeModule.h` not found

I am working on the link you mentioned and if does not work I will let you know

**Comment by zoontek** [comment]
@MuhammadNayabButt I understand, but this is not really related to this library. Workarounds exists, like

```ruby
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'react-native-permissions'
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
      end
    end
    if target.name == "React"
      target.remove_from_project
    end
  end
end
```
