### ISSUE TITLE
iOS Folder Does Not Get Installed

### ISSUE THREAD

**Issue by tylerolechnowicz** [zoontek/react-native-permissions#363]
# Bug

Hello, I am trying to use this package and ran `npm install react-native-permissions --save`.

Upon installation of the package, the "ios" folder did not get created. 

![image](https://user-images.githubusercontent.com/32344917/67637071-414b5f00-f8ad-11e9-8992-d6d18f4a6b1d.png)

As you can see I am trying to add the following permissions: 
pod 'Permission-LocationAlways',
pod 'Permission-Notifications',
pod 'Permission-PhotoLibrary'

When I run the command `pod install` I receive the following error:

"No podspec found for `Permission-LocationAlways` in `../node_modules/react-native-permissions/ios/LocationAlways.podspec`"

Please help!

## Environment info

React native info output:

```bash
System:                                                                                                                 OS: Windows 10                                                                                                      CPU: (8) x64 Intel(R) Core(TM) i7-6820HK CPU @ 2.70GHz                                                              Memory: 16.19 GB / 31.87 GB                                                                                       Binaries:                                                                                                             Node: 10.15.1 - C:\Program Files\nodejs\node.EXE                                                                    Yarn: 1.15.2 - ~\AppData\Roaming\npm\yarn.CMD                                                                       npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD                                                                      IDEs:                                                                                                                 Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5900203
--
```

Library version: 2.0.3

**Comment by zoontek** [comment]
@tylerolechnowicz Hello. How did you iOS development on Windows? I thought Cocoapods was not available.

This is a weird issue since it's included the same way as the android folder: https://github.com/react-native-community/react-native-permissions/blob/master/package.json#L23

Could you tru nuke (delete the lock file + the node_modules), clear the npm cache, update npm and install it again?

**Comment by mikehardy** [comment]
Doesn't work on windows apparently but I swear by `npx react-native-clean-project` nothing leaves a project as sparkly fresh as that ;-)

**Comment by tylerolechnowicz** [comment]
@zoontek Cocoapods is available on Windows in beta mode. You can still do 'pod install' which is all I was trying to do. Sent it over to my partner who has a Mac and he did 'npm update' and it brought it everything. Now he is experiencing another issue...Lol. But at least we are passed this one I believe.

@mikehardy good to know! I will definitely put that in my toolbox. Thank you.
