### ISSUE TITLE
check(PERMISSIONS.ANDROID.ACCESS_FINE_LOCATION) should check the android system location setting

### ISSUE THREAD

**Issue by evilrescuer** [zoontek/react-native-permissions#365]
# Bug

`check(PERMISSIONS.ANDROID.ACCESS_FINE_LOCATION)` 
**CAN ONLY** check if location permission of an APP had been turned on/off，but
**CAN NOT** check if the user sets the location permission of the android system as FINE_LOCATION (High accuracy) or not.

## Environment info

React native info output:

```bash
 System:
    OS: macOS 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 884.84 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.1, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29
      Build Tools: 23.0.1, 23.0.2, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.3, 29.0.2
      System Images: android-24 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.5 => 0.60.5
```

Library version: 2.0.3
Android version: 7.0 and 8.1.0

## Steps To Reproduce

1. Copy the following sample code into an android project
2. Run the app on an android device
3. Turn on the location permission of the android system
4. Turn on the location permission of the APP
5. Turn off the location permission of the android system (**OR** set to a mode except 'High accuracy')
6. now the check result would be 'granted' (It shouldn't)

Describe what you expected to happen:

1. Would get 'denied' or 'blocked', but not 'granted'
(otherwise, the status would be meaningless)

## Reproducible sample code

```
import {check, PERMISSIONS} from 'react-native-permissions';

check(PERMISSIONS.ANDROID.ACCESS_FINE_LOCATION)
      .then(result => {
        console.log(result);  // would be "granted"
      })
      .catch(error => {
        console.log('error')
      });
```

**Comment by zoontek** [comment]
@evilrescuer The android part of this lib is a slightly upgraded version of [PermissionAndroid](https://facebook.github.io/react-native/docs/permissionsandroid), thus it does not offers more than permission checking / requesting.

By `check if the user sets the location permission of the android system as FINE_LOCATION (High accuracy), do you mean checking if the Location services are enabled?

![Screenshot_20191104-114506](https://user-images.githubusercontent.com/1902323/68115469-c01d4900-fef8-11e9-95bb-05a352f8e158.png)

**Comment by evilrescuer** [comment]
Yes, as we know, there are `system location permission` and `app location permission` in android.
* The `system location permission` has three kinds of mode (`high accuracy` + `battery saving` + `device only`):
![image](https://user-images.githubusercontent.com/29336701/68312737-772ee580-00ee-11ea-865e-ea8e39e100b8.png)

* The `app location permission` only has a switch:
![image](https://user-images.githubusercontent.com/29336701/68312465-0f789a80-00ee-11ea-954c-ebf732f4f54e.png)

It seems that we would know if the app has the permission of `high accuracy` using `check(PERMISSIONS.ANDROID.ACCESS_FINE_LOCATION)`

But, unfortunately, it doesn't work well. Actually, this API shows if we open the switch (in `app location permission`, it doesn't matter to `high accuracy` in the `system location permission`).

I think the result in `PermissionAndroid` is also wrong and confusing. And this library can be better.
Cause now, I need to write my own native method for RN code to call while checking the permission, like this:
```
// android code
import android.location.LocationManager;

LocationManager locationManager
        = (LocationManager) reactContext.getSystemService(reactContext.LOCATION_SERVICE);
boolean gps = locationManager.isProviderEnabled(LocationManager.GPS_PROVIDER);
boolean network = locationManager.isProviderEnabled(LocationManager.NETWORK_PROVIDER);
// if both gps and network is true, then `high accuracy` in `system location permission` is opened.
```
```
// RN code
// 1. call the native method to get the status of `system location permission`
// 2. call `check(PERMISSIONS.ANDROID.ACCESS_FINE_LOCATION)` to get the status of `app location permission`
// if both of them are true, then the app is ok to get `high accuracy`
```

**Comment by mikehardy** [comment]
https://github.com/react-native-device-info/react-native-device-info#getAvailableLocationProviders

**Comment by tr3v3r** [comment]
@zoontek  can we add this method (getAvailableLocationProviders) into this library at least for Android? It would be nice to have the possibility to detect if location service enabled without installing extra dependencies.

If you OK, I'll make a pr

**Comment by zoontek** [comment]
@tr3v3r No, I'd rather not. This library focuses on permissions and if each of the handler come with its own set of helpers, it could become huge.

**Comment by mikehardy** [comment]
as current device-info maintainer, that's what my lib is for, and likewise I won't add any permissions stuff over there ;-)
