### ISSUE TITLE
App Store permission warnings question

### ISSUE THREAD

**Issue by Return-1** [zoontek/react-native-permissions#367]
Hey everyone,

This might be a miss question however i'd like to ask it anyway. Apple seems to keep asking me to add a permission for **NSLocationAlwaysUsageDescription**. If i understand it correctly it is because of this package. Is this right?

The reason this is a problem is because i'm also using the very common `react-native-geolocation-service` which is the only way to used fused location on android if you want to have access to the geolocation service properly. For that lib an issue has been opened here https://github.com/Agontuk/react-native-geolocation-service/issues/143. 

The question is, if indeed **NSLocationAlwaysUsageDescription** is requested by this here package, is there a way to use `react-native-permissions` but not require **NSLocationAlwaysUsageDescription**? I'm guessing i'd need to fork the project and remove the native code for that.

Anyone else faced this? Thanks a bunch

**Comment by zoontek** [comment]
@Return-1 Which version of the library are you using? (next time respect the issue template, even for asking a question, please 🙏)

**Comment by mikehardy** [comment]
Just to say react-native-background-geolocation also works really well and is (in my actual experience) very very battery friendly. And it will use the always location yes - which I request from this library but is used by that one, and I definitely need the permission. However, if I were using 1.x of this library I'd need the permission string with this library alone because permissions weren't split out like they are here in 2.x - cheers

**Comment by Return-1** [comment]
> @Return-1 Which version of the library are you using? (next time respect the issue template, even for asking a question, please 🙏)

Apologies, the placeholder text for the questions doesnt hint in using the issue template which is why i skipped it but of course doing this makes sense.

## Environment info

Library version: 1.2.0

React native info output:

```bash
System:
    OS: macOS 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
    Memory: 38.21 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.14.0 - ~/.nvm/versions/node/v10.14.0/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.14.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.1, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 23, 24, 25, 26, 27, 28
      Build Tools: 23.0.1, 25.0.2, 26.0.3, 27.0.2, 27.0.3, 28.0.0, 28.0.3
      System Images: android-19 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.3 => 0.60.3 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

**Comment by Return-1** [comment]
I somehow didn't realise 2.0.0 was out and it addresses exactly this issue. This will essentially solve the problem i am facing, thank you so much.
