### ISSUE TITLE
How to get the manifest object

### ISSUE THREAD

**Issue by austinthetaco** [zoontek/react-native-permissions#369]
# Question

So I'm ejecting an expo app that was using expo permissions and expo constants. The issue I'm currently running into is finding a replacement for expo's `Constants.manifest` (and similar constants info). Is there anyway to get the entire manifest object via react-native-permissions library?

**Comment by zoontek** [comment]
@austinthetaco Expo does not uses `react-native-permissions`. They uses their own lib https://www.npmjs.com/package/expo-permissions

**Comment by austinthetaco** [comment]
@zoontek you misread my question. I've ejected from Expo and am trying to find a replacement Constants.manifest. I was asking if i can get something close to that from react-native-permissions.

**Comment by zoontek** [comment]
@austinthetaco I checked the content of the manifest: https://docs.expo.io/versions/latest/workflow/how-expo-works/#expo-manifest. This has nothing to do with permissions, so I closed the issue.

You are looking for https://github.com/react-native-community/react-native-device-info
