### ISSUE TITLE
pod install event with RN > 0.60 ?

### ISSUE THREAD

**Issue by arnaudambro** [zoontek/react-native-permissions#370]
Hi there,

I see in the [ios README](https://github.com/react-native-community/react-native-permissions#ios) that we need to add some lines to the Podfile and still run `pod install` afterwards, is it really the case for RN > 0.60 ?

Thanks

**Comment by mikehardy** [comment]
It is *more* the case with RN>60 now that it is based on Cocoapods. Basically any time you do anything with react-native >=60 (even updating react-native dependencies) you will need to pod install afterwards

**Comment by arnaudambro** [comment]
alright, thanks !
