### ISSUE TITLE
Support for iOS 'BluetoothAlways'

### ISSUE THREAD

**Issue by HansBouwmeester** [zoontek/react-native-permissions#371]
As the docs show, iOS has a `NSBluetoothAlwaysUsageDescription` `<key>` than can be put in `Info.plist` for Apps that want to connect to Bluetooth devices (as "Central" rather than as "Peripheral"):

```
 <key>NSBluetoothAlwaysUsageDescription</key>
 <string>YOUR TEXT</string>
```

However, I don't see a corresponding `PERMISSIONS.IOS.BLUETOOTH_ALWAYS` permission?

Would be a nice feature to add.

**Comment by zoontek** [comment]
@Gra55h0pper As this library handle iOS 9+, `Bluetooth Always` is required when you request `Bluetooth Peripheral` on iOS 13+: https://github.com/react-native-community/react-native-permissions/blob/master/ios/BluetoothPeripheral/RNPermissionHandlerBluetoothPeripheral.m

What really missing is `Bluetooth Central` permission (which will also fallback to `Bluetooth Always` on iOS 13)

**Comment by HansBouwmeester** [comment]
@zoontek Thanks much! I think I'm starting to understand. So if I request (and get) `peripheral` permission this implies I also got `always` permission? So even though my App is using Bluetooth as `central` rather than `peripheral` (i.e. the App is not turning on the BLE radio to advertise its presence to the environment), I can just ask for `peripheral` permission?

**Comment by zoontek** [comment]
@Gra55h0pper Now you can (with the `2.0.4`) 🙂

**Comment by HansBouwmeester** [comment]
> @Gra55h0pper Now you can (with the `2.0.4`) 🙂

Great! Will upgrade.

**Comment by agestaun** [comment]
This should be reopened, the NSBluetoothPeripheralUsageDescription has been deprecated on iOS 13 and higher. When I ask for the peripheral permission in a device running iOS 16, the library returns UNAVAILABLE. And if I request it, it returns UNAVAILABLE too.

https://developer.apple.com/documentation/bundleresources/information_property_list/nsbluetoothperipheralusagedescription

The library should add the BLUETOOTH_ALWAYS permission.

**Comment by mikehardy** [comment]
:thinking: maybe related: https://github.com/zoontek/react-native-permissions/issues/407

Also:

>  The library should add the BLUETOOTH_ALWAYS permission.

Should read: "I will propose a PR to add BLUETOOTH_ALWAYS permission" --> https://github.com/zoontek/react-native-permissions/issues/407
