### ISSUE TITLE
Trying to use a slightly modified recipe for multiple check (with request instead of check) doesn't work as expected.

### ISSUE THREAD

**Issue by nadav2051** [zoontek/react-native-permissions#373]
# Bug

Trying to use the multiple request recipe, the first time I call the function it prompts permission for one of the permissions, and fails automatically for the other.
The second time I'll call the function, the first one would be granted (if the user has selected it as such during the first call), and the user will be prompted with the second permission request.

## Environment info
React native info output:

```bash
System:
    OS: macOS Mojave 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
    Memory: 842.53 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.6.0 - /usr/local/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.5.0 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 11.2/11B52 - /usr/bin/xcodebuild
  npmPackages:
    @react-native-community/cli: ^1.9.5 => 1.12.0 
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.4 => 0.60.4
```

Library version: 2.0.3

## Steps To Reproduce

1. Call the request multiple permission functions

...

Describe what you expected to happen:

1. User will be prompted for camera or gallery permission.
2. User will be prompted for the second permission requested.

## Reproducible sample code

```
getCameraAndGalleryPermissions() {
        const camera = Platform.select({
            android: PERMISSIONS.ANDROID.CAMERA,
            ios: PERMISSIONS.IOS.CAMERA,
        });

        const gallery = Platform.select({
            android: PERMISSIONS.ANDROID.READ_EXTERNAL_STORAGE,
            ios: PERMISSIONS.IOS.MEDIA_LIBRARY,
        });


        return Promise.all([request(camera), request(gallery)])
            .then(([cameraStatus, galleryStatus]) => 
                galleryStatus === RESULTS.GRANTED && cameraStatus === RESULTS.GRANTED);
    }
```

**Comment by zoontek** [comment]
@nadav2051 That's precisely why the request recipe is different https://github.com/react-native-community/react-native-permissions/blob/master/README.md#request-multiples-permissions

checks can be done in parallel. requests can't.

**Comment by nadav2051** [comment]
Roger that, thank you!
