### ISSUE TITLE
RNPermission null in react-native windows uwp

### ISSUE THREAD

**Issue by SelvaraniAlagumuthu** [zoontek/react-native-permissions#374]
Hi,

i just try to use react-native-qrcode-scanner for my react-native application. For this i just link react-native-camera and react-native-permissions. Its working fine in android. But i try to use in windows i am getting RNPermissions null becuase of your library supports android and ios. how to resolve this issue in uwp.

**Comment by mikehardy** [comment]
`An unified permissions API for React Native on iOS and Android.` https://github.com/react-native-community/react-native-permissions/blob/master/README.md#L9

I'm not sure this is the library you are looking for - it has no windows implementation

**Comment by zoontek** [comment]
`how to resolve this issue in uwp`. I guess, by creating a full Windows implementation? 😄
I don't have the skills to do it, neither the devices to test it, but PR are welcomed!
