### ISSUE TITLE
What is best practice to ask for location permission

### ISSUE THREAD

**Issue by vvusts** [zoontek/react-native-permissions#378]
Hi,

I have just upgraded to RN60 and 2.x of this module I just wanted to ask for advice on best practice when app **can allow always or whenInUse** (app work for both but with background work something else in background) permission for locations and to be **compatible on IOS 12 & 13**.
I ask for it like this now:
```
request(
      Platform.select({
        android: PERMISSIONS.ANDROID.ACCESS_FINE_LOCATION,
        ios: PERMISSIONS.IOS.LOCATION_ALWAYS,
      })
    )
```
Is this enough for this scenario or I need to add something else?

**Comment by zoontek** [comment]
@vvusts No that's exactly what's need to be done 🙂
