### ISSUE TITLE
Documentation missing for new important iOS Info.plist keys to avoid app crash upon requesting permission

### ISSUE THREAD

**Issue by jln-dk** [zoontek/react-native-permissions#38]
As of Xcode 8 and React Native 0.33 it is now **necessary to add kit specific "permission" keys** to your Xcode `Info.plist` file, in order to make `requestPermission` work. Otherwise your app crashes when requesting the specific permission. I discovered this after days of frustration.

Apple Developer Forum thread about the issue: https://forums.developer.apple.com/thread/48959

**The solution is:**
Open Xcode > Info.plist > Add a key (starting with "Privacy - ...") with your kit specific permission. The value for the key is optional.

**Example:**
If you need Contacts permission you have to add the key "Privacy - Contacts Usage Description".

<img width="338" alt="screen shot 2016-09-21 at 13 13 21" src="https://cloud.githubusercontent.com/assets/5707542/18704973/3cde3b44-7ffd-11e6-918b-63888e33f983.png">

It might be helpful to add to the documentation.

**Comment by yonahforst** [comment]
@jesperlndk - thanks for discovering this and for documenting the fix. I've added it to the readme. 🍻

**Comment by jln-dk** [comment]
No problem! Thanks 🍻
