### ISSUE TITLE
Provide means of differentiating between Provisional Always and Full Always for iOS 13 location permissions

### ISSUE THREAD

**Issue by zacharyweidenbach** [zoontek/react-native-permissions#383]
# Feature Request
On iOS 13, a 'provisional Always' permission is granted when the user selects `Allow While Using App`. When performing a check to determine the permission level currently granted to location, the results are identical for both `when in use` and `always` on iOS 13. 

### Current Behavior
Permission Level: Always
```
await check(PERMISSIONS.IOS.LOCATION_ALWAYS); // granted
await check(PERMISSIONS.IOS.LOCATION_WHEN_IN_USE); // granted
```

Permission Level: Allow While Using App (Provisional Always)
```
await check(PERMISSIONS.IOS.LOCATION_ALWAYS); // granted
await check(PERMISSIONS.IOS.LOCATION_WHEN_IN_USE); // granted
```
Similarly, there should be some way to differentiate between when the permissions are set to Allow Once, and When In Use.

## Why it is needed
I would like to reflect the settings in the iOS Settings > MyApp > Location inside the app itself. I should be able to show when the state of location permission is `Never`, `Allow Once`, `While Using the App` and `Always` without having to send the user to the phone's settings. I should be able to see, without ambiguity, the phone's location permissions in order to conditionally mount/unmount location tracking components only when 'Full Always' permissions has been given.

## Possible implementation
This probably isn't the best way to solve this ambiguity, but one idea would be to add two more IOS permission constants:
`PERMISSIONS.IOS.LOCATION_PROVISIONAL_ALWAYS`
`PERMISSIONS.IOS.LOCATION_ONCE`

That both return `unavailable` when called on ios versions < iOS 13

### Code sample
on versions of iOS >= iOS 13.x
Permission Level: Allow While Using App (Provisional Always)
```
await check(PERMISSIONS.IOS.LOCATION_ALWAYS); // granted
await check(PERMISSIONS.IOS.LOCATION_WHEN_IN_USE); // granted
await check(PERMISSIONS.IOS.LOCATION_PROVISIONAL_ALWAYS); // granted
await check(PERMISSIONS.IOS.LOCATION_ONCE); // blocked
```

Permission Level: Always Allow (full always)
```
await check(PERMISSIONS.IOS.LOCATION_ALWAYS); // granted
await check(PERMISSIONS.IOS.LOCATION_WHEN_IN_USE); // granted
await check(PERMISSIONS.IOS.LOCATION_PROVISIONAL_ALWAYS); // blocked
await check(PERMISSIONS.IOS.LOCATION_ONCE); // blocked
```

Permission Level: Allow Once
```
await check(PERMISSIONS.IOS.LOCATION_ALWAYS); // blocked
await check(PERMISSIONS.IOS.LOCATION_WHEN_IN_USE); // granted
await check(PERMISSIONS.IOS.LOCATION_PROVISIONAL_ALWAYS); // blocked
await check(PERMISSIONS.IOS.LOCATION_ONCE); // granted
```

Permission Level: Never
```
await check(PERMISSIONS.IOS.LOCATION_ALWAYS); // blocked
await check(PERMISSIONS.IOS.LOCATION_WHEN_IN_USE); // blocked
await check(PERMISSIONS.IOS.LOCATION_PROVISIONAL_ALWAYS); // blocked
await check(PERMISSIONS.IOS.LOCATION_ONCE); // blocked
```

On versions of iOS < iOS 13.x
Permission Level: Allow While Using App
```
await check(PERMISSIONS.IOS.LOCATION_ALWAYS); // blocked
await check(PERMISSIONS.IOS.LOCATION_WHEN_IN_USE); // granted
await check(PERMISSIONS.IOS.LOCATION_PROVISIONAL_ALWAYS); // unavailable
await check(PERMISSIONS.IOS.LOCATION_ONCE); // unavailable
```

Permission Level: Always Allow
```
await check(PERMISSIONS.IOS.LOCATION_ALWAYS); // granted
await check(PERMISSIONS.IOS.LOCATION_WHEN_IN_USE); // granted
await check(PERMISSIONS.IOS.LOCATION_PROVISIONAL_ALWAYS); // unavailable
await check(PERMISSIONS.IOS.LOCATION_ONCE); // unavailable
```

Permission Level: Never
```
await check(PERMISSIONS.IOS.LOCATION_ALWAYS); // blocked
await check(PERMISSIONS.IOS.LOCATION_WHEN_IN_USE); // blocked
await check(PERMISSIONS.IOS.LOCATION_PROVISIONAL_ALWAYS); // unavailable
await check(PERMISSIONS.IOS.LOCATION_ONCE); // unavailable
```

An alternative format for deriving this information could be to have a special method, similar to notifications' `checkNotifications`.
Something like 
```
import { checkLocationPermissionType } from 'react-native-permissions';
const permissionType = await checkLocationPermissionType(); // oneOf type string [ 'always', 'provisionalAlways', 'whenInUse', 'once', 'never' ]
```

**Comment by zoontek** [comment]
@zacharyweidenbach, In theory, you are right: the library should return what's inside the user settings.
But in practice, it is simply not possible, and it's exactly why Apple introduces these changes on iOS 13: the app authors shouldn't care about which decision took the user (also because a lot of apps request `location always` even if they don't really need it).

"Always provisional" or "Once" doesn't exist in the `CLAuthorizationStatus` enum (https://developer.apple.com/documentation/corelocation/clauthorizationstatus?language=objc), and it's by design to ensure user privacy. You have to deal with the permission you have at an instant T.

**Comment by stephen-standridge** [comment]
Any update on this @zoontek ?

It looks like those were added to the enum.

**Comment by zoontek** [comment]
@stephen-standridge Not really, no 😅. We can't do what Apple does not allowing us to do
