### ISSUE TITLE
[Android] Rationale is not shown on first permission request

### ISSUE THREAD

**Issue by vrazn** [zoontek/react-native-permissions#385]
# Bug

The rationale is not shown on the first android permission request.

## Environment info

React native info output:

```bash
info
  React Native Environment Info:
    System:
      OS: macOS 10.14.6
      CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
      Memory: 557.08 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
      Watchman: 4.5.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
      Android SDK:
        API Levels: 22, 23, 24, 25, 26, 27, 28
        Build Tools: 23.0.1, 23.0.2, 23.0.3, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.2, 27.0.3, 28.0.2, 28.0.3, 29.0.0, 29.0.0, 29.0.0, 29.0.2
        System Images: android-23 | Google APIs Intel x86 Atom, android-26 | Google Play Intel x86 Atom, android-27 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.8.6 => 16.11.0
      react-native: 0.59.9 => 0.59.9
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

Library version: 2.0.4

## Steps To Reproduce

1. Call
```
request(
    Platform.select({
      android: PERMISSIONS.ANDROID.CAMERA,
      ios: PERMISSIONS.IOS.CAMERA,
    }),
    {
      title: 'Title',
      message: 'Message',
    },
  )
```
2. Reject permission
3. Make the call again
...

Describe what you expected to happen:

The rationale should be shown before each permission request (including the first one).

Describe what happened:

The rationale was not shown, instead the permissions dialog was immediately shown to the user.
On every consecutive call, the rationale is being shown, the problem exists only for the first one.

**Comment by zoontek** [comment]
@vrazn Yes and it's totally normal. We delegate the request to PermissionAndroid React Native embedded module (https://facebook.github.io/react-native/docs/permissionsandroid#request).

See Android documentation for more details : https://developer.android.com/training/permissions/requesting

> One approach you might use is to provide an explanation only if the user has already denied that permission request. Android provides a utility method, shouldShowRequestPermissionRationale(), that returns true if the user has previously denied the request, and returns false if a user has denied a permission and selected the Don't ask again option in the permission request dialog, or if a device policy prohibits the permission.
