### ISSUE TITLE
Invalid RNPermission 'ios.permission.LOCATION_WHEN_IN_USE'. should be one of: ( )

### ISSUE THREAD

**Issue by miaoyumeng** [zoontek/react-native-permissions#387]
version message:
react:16.8.3,
react-native:0.59.5,
Xcode:11.2,
Cocoapods:1.8.4,

my step:
1.`npm install react-native-permissions --save`
2.add 
```
pod 'RNPermissions', :path => '../node_modules/react-native-permissions'
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
  pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone.podspec"
  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways.podspec"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse.podspec"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary.podspec"
```
to the podfile
3.pod install
4.add some permission information to the Info.plist
5.add check permission code to .js file

Attention：
I've tried everything in issues or readme, and nothing works for me, what's wrong with me?

**Comment by miaoyumeng** [comment]
my podfile
```
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
# use_frameworks!
target 'sfApp' do
  # Comment the next line if you don't want to use dynamic frameworks


  # Pods for sfApp
pod 'React', :path => '../node_modules/react-native', :subspecs => [
   'Core',
   'CxxBridge', # Include this for RN >= 0.47
   'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
   'RCTText',
   'RCTImage',
   'RCTNetwork',
   'RCTActionSheet',
   'RCTGeolocation',
   'RCTPushNotification',
   'RCTLinkingIOS',
   'RCTSettings',
   'RCTVibration',
   'RCTWebSocket', # Needed for debugging
   'RCTAnimation', # Needed for FlatList and animations running on native UI thread
   # Add any other subspecs you want to use in your project
]
# Explicitly include Yoga if you are using RN >= 0.42.0
pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec',:modular_headers => false
pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec',:modular_headers => false

  pod 'QBImagePickerController', :path => '../node_modules/react-native-image-crop-picker/ios/QBImagePicker/QBImagePickerController.podspec'
  pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'
  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'
  pod 'Picker', :path => '../node_modules/react-native-picker'
  pod 'react-native-amap3d', path: '../node_modules/react-native-amap3d/lib/ios'
  
  
  pod 'RNPermissions', :path => '../node_modules/react-native-permissions'
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
  pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone.podspec"
  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways.podspec"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse.podspec"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary.podspec"

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end

```

**Comment by miaoyumeng** [comment]
Hi,@zoontek 
`Check that you linked at least one permission handler.`
What does this sentence mean？
I've already added `RNPermission.xcodeproj` to the `Libraries,` and added `LibRNPermissions.a` to the `Link Binary With Libraries`, and run `pod install` successfully, what else must I do？

**Comment by zoontek** [comment]
> I've already added RNPermission.xcodeproj to the Libraries, and added LibRNPermissions.a to the Link Binary With Libraries, and run pod install successfully, what else must I do？

First, you don't need to install the core (`pod 'RNPermissions', :path => '../node_modules/react-native-permissions'`) with CocoaPods **and** with `react-native-link`. Remove `RNPermission.xcodeproj` from your `Libraries`.

Please send a screenshot of what's correctly linked in your project, like this:

<img width="282" alt="Screenshot 2019-12-17 at 11 24 26" src="https://user-images.githubusercontent.com/1902323/70987354-fe915080-20bf-11ea-852a-df607bf4cbf7.png">

> Check that you linked at least one permission handler.

That you added at least one handler in your `Podfile` (like `pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"`)

**Comment by miaoyumeng** [comment]
> > I've already added RNPermission.xcodeproj to the Libraries, and added LibRNPermissions.a to the Link Binary With Libraries, and run pod install successfully, what else must I do？
> 
> First, you don't need to install the core (`pod 'RNPermissions', :path => '../node_modules/react-native-permissions'`) with CocoaPods **and** with `react-native-link`. Remove `RNPermission.xcodeproj` from your `Libraries`.
> 
> Please send a screenshot of what's correctly linked in your project, like this:
> 
> <img alt="Screenshot 2019-12-17 at 11 24 26" width="282" src="https://user-images.githubusercontent.com/1902323/70987354-fe915080-20bf-11ea-852a-df607bf4cbf7.png">
> 
> > Check that you linked at least one permission handler.
> 
> That you added at least one handler in your `Podfile` (like `pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"`)

Thanks for your reply
react-native :0.59.5, so I add `pod 'RNPermissions', :path => '../node_modules/react-native-permissions'` to podfile
I have removed `RNPermission.xcodeproj` and unlinked, but it's the same error

This is my screenshot
![E4A24739-8344-4BAE-A096-F1EC6656353F](https://user-images.githubusercontent.com/28642711/70989681-fefd0c00-20fe-11ea-87e1-133e538d6625.png)

Thanks

**Comment by zoontek** [comment]
Everything seems OK. Close Xcode, nuke the `DerivedData` folder: https://stackoverflow.com/questions/18933321/can-i-safely-delete-contents-of-xcode-derived-data-folder

**Comment by miaoyumeng** [comment]
> Everything seems OK. Close Xcode, nuke the `DerivedData` folder: https://stackoverflow.com/questions/18933321/can-i-safely-delete-contents-of-xcode-derived-data-folder

Woo~~  It worked for me, thank you very much

**Comment by zoontek** [comment]
@miaoyumeng No problem, I'm used to Xcode weird behavior 😄
