### ISSUE TITLE
Support for android.permission.USE_BIOMETRIC

### ISSUE THREAD

**Issue by tomisykora** [zoontek/react-native-permissions#388]
# Feature Request

I would like to see support for android.permission.USE_BIOMETRIC to be able to check and request access to biometric data on Android devices

## Why it is needed

To be able to check and request access to biometric data on Android devices.

## Possible implementation

Adding new constants USE_BIOMETRIC under ANDROID permissions key, something like
```
...
USE_BIOMETRIC: "android.permission.USE_BIOMETRIC";
...
```

### Code sample

Mentioned above

**Comment by zoontek** [comment]
@T0mi [`USE_BIOMETRIC`](https://developer.android.com/reference/android/Manifest.permission#USE_BIOMETRIC) protection level is set to `normal`, so it should not be requestable (only `dangerous` permission are requestable).

Try adding `<uses-permission android:name="android.permission.ACCEPT_HANDOVER" />` to your `AndroidManifest.xml`, it should be enough.

**Comment by tomisykora** [comment]
Thanks @zoontek , closing this as your answer helped me! 😊
