### ISSUE TITLE
"Should be one of: ()" message could be more explicit

### ISSUE THREAD

**Issue by MoOx** [zoontek/react-native-permissions#389]
# Feature Request

If the list is empty (no handler correctly added), the message could be more explicit

## Why it is needed

- This will avoid us new users to be confused
- This will avoid new issue with this "Should be one of: ()"

## Possible implementation

Just detect that the list is empty and change the message to something like

```
No permissions handler detected. Did you linked the one you needed correctly?
Maybe you didn't reinstall the app properly, clean your cache & build & rebuild your app.
```

**Comment by zoontek** [comment]
This is tricky since it happens during RCTConvert enum mapping step even before I could check it's value: https://github.com/facebook/react-native/blob/v0.61.5/React/Base/RCTConvert.m#L250

**Comment by zoontek** [comment]
Fixed in [the last version](https://github.com/react-native-community/react-native-permissions/releases/tag/2.1.0) 🎉
