### ISSUE TITLE
openSettings().then() doesn't wait until user returns from settings

### ISSUE THREAD

**Issue by adteague** [zoontek/react-native-permissions#392]
# Bug
In version 1.1.1, when I executed `RNPermissions.openSettings()` the `.then()` method would not execute until a user came back to the app from settings or the app became in the foreground (atleast in iOS). When I switched to version 2.0.8, the `.then()` method executes once the app settings have opened. Is there a way to get the old functionality to work again? Thanks.

## Environment info

System:
    OS: macOS 10.15.2
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 1.05 GB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.13.0 - ~/.nvm/versions/node/v10.13.0/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v10.13.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Xcode: 11.3/11C29 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1

React native info output:
_N/A_

Library version: 2.0.8

## Steps To Reproduce

1. Use and run `openSettings()` method in app.
...

Describe what you expected to happen:

1. In version '1.1.' `.then()` would run after the user has returned to the app from settings in iOS
2. In version '2.0.8' `.then()` runs once settings have been launched in iOS

## Reproducible sample code

```
RNPermissions.openSettings()
      .then(() => {
        this.checkPushNotifications();
        // console.log('Finished opening settings');
      })
      .catch(() => {
        this.triggerSnackbar('Error attempting to open settings.');
      });
```

**Comment by zoontek** [comment]
It's not a bug. On the old version, we have two methods: `canOpenSettings` and `openSettings`. Now we have only one that will be rejected if it's not possible.

To perform an action when the app is getting focus back, you can use AppState: https://facebook.github.io/react-native/docs/appstate

**Comment by adteague** [comment]
Awesome. Thanks @zoontek!

**Comment by mateussmohamed** [comment]
@adteague you can share your solution? Im have a same problem.

**Comment by adteague** [comment]
@mateussmohamed Here's the abbreviated version...

```
import {AppState} from 'react-native';

state = {
  appState: AppState.currentState,
}

componentDidMount() {
  AppState.addEventListener('change', this.handleAppStateChange);
}

componentWillUnmount() {
  AppState.removeEventListener('change', this.handleAppStateChange);
}

handleAppStateChange = nextAppState => {
  const {appState} = this.state;
  if (appState.match(/inactive|background/) && nextAppState === 'active') {
    this.checkPushNotifications();
  }
  this.setState({appState: nextAppState});
};
```

**Comment by adteague** [comment]
I basically store in the component state when the app goes into the background and then when it becomes active again I check for changes in their permissions (in this case push notifications)

**Comment by mateussmohamed** [comment]
same after added the state controller in component(Screen). My app continues reloading after user changes permissions in IOS settings, only if user changes the permissions. If user dont changes, when back to app the end screen is maintained on previous state.

some possibility this problem be related the React Navigation?

**Comment by adteague** [comment]
I'm not exactly sure what you are trying to accomplish with your code. The solution I provided worked perfectly for what I was seeking to accomplish; which was to check if there were any permission changes after the app comes back into focus from the background.

**Comment by mateussmohamed** [comment]
My app has a rule, where user can only use if the camera permission is enabled. Case the user denied the ask for the camera permission, a screen is displayed with the explanations regarding the use of the camera. In this screen I execute  `openSettings` so that user enables the permission. Upon returning to App after the enabled my App is being reloading.

My abbreviated version..


```javascript
export default function CameraPermission() {
  const [appState, setAppState] = useState(AppState.currentState)

  async function handleOpenSettings() {
    await openSettings()
  }

  const handleAppStateChange = async nextAppState => {
    if (appState.match(/inactive|background/) && nextAppState === 'active') {
      const cameraPermission = await checkCameraPermissions()

      console.log('cameraPermission', cameraPermission)
    }

    setAppState(nextAppState)
  }

  useEffect(() => {
    AppState.addEventListener('change', handleAppStateChange)

    return () => {
      AppState.removeEventListener('change', handleAppStateChange)
    }
  }, [])

  return ()
}
```

**Comment by mateussmohamed** [comment]
my app flow, for better understanding...

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/12900896/78070296-e93fe980-7371-11ea-8f17-26e56890bfd4.gif)

**Comment by adteague** [comment]
Sorry, I've provided all the insights I know and a solution that should work for everyone. Without having your code/app I can't help any further

**Comment by isoamylol** [comment]
> It's not a bug. On the old version, we have two methods: `canOpenSettings` and `openSettings`. Now we have only one that will be rejected if it's not possible.
> 
> To perform an action when the app is getting focus back, you can use AppState: https://facebook.github.io/react-native/docs/appstate

Thanks!
