### ISSUE TITLE
Something went wrong while linking. Error: ENOENT: no such file or directory, open 'react-native-permissions/ios/RNPermissions.xcodeproj/project.pbxproj'

### ISSUE THREAD

**Issue by thomasbariabas1** [zoontek/react-native-permissions#396]
### **Bug**

React-native-permissions version: 1.2.1

React Native info output :
```
    System:
      OS: macOS 10.15.1
      CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
      Memory: 533.37 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.15.0 - ~/.nvm/versions/node/v11.15.0/bin/node
      npm: 6.7.0 - ~/.nvm/versions/node/v11.15.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
      Android SDK:
        API Levels: 26, 28, 29
        Build Tools: 26.0.0, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.1, 27.0.2, 27.0.3, 28.0.3, 29.0.2
        System Images: android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.3/11C29 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.6 => 16.8.6 
      react-native: ^0.59.5 => 0.59.10 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native: 0.59.5
```

I run the application and got the following error:

![Screenshot_20200103-131325_Citizen](https://user-images.githubusercontent.com/22024464/72076269-f2cf2d80-32fd-11ea-9103-f549639a2947.jpg)
 
When i tried to link the project,  i get the following error:

`error Something went wrong while linking. Error: ENOENT: no such file or directory, open '/node_modules/react-native-permissions/ios/RNPermissions.xcodeproj/project.pbxproj' 
`

So I linked the library manually in the XCode, and now the `react-native link` shows that the react-native-permission is linked, but the error `NativeModule.RNPermissions is null` is still there. 

I tried both on Android and ios.

**Comment by mikehardy** [comment]
I would use module version 2+ here, with jetifier in `-r` mode per the README

**Comment by zoontek** [comment]
> So I linked the library manually in the XCode, and now the react-native link shows that the react-native-permission is linked, but the error NativeModule.RNPermissions is null is still there.

Try cleaning your Xcode build folder (Command + Option + Shift + K).

I also recommend version 2.x 🙂

**Comment by 1280103995** [comment]
same here. RN 0.59.9，permission 1.1.1

**Comment by zoontek** [comment]
I'm closing this since version 1.x is not supported anymore: https://github.com/react-native-community/react-native-permissions#support
