### ISSUE TITLE
How should i manually link it in Ios project if i'm not using pods?

### ISSUE THREAD

**Issue by vishgoel007** [zoontek/react-native-permissions#397]
# Question

**Comment by zoontek** [comment]
You can still drag'n'drop files (RNPermissions.(h,m) and handler). But Pods is the way to go for RN 0.60+

**Comment by vishgoel007** [comment]
@zoontek  Do i need to drag'n'drop handlers (with folders or just h,m files) into RNPermissions.xcodeproj ?

**Comment by zoontek** [comment]
No into your project directly

**Comment by vishgoel007** [comment]
@zoontek  Sorry i don't understand, i'm a noob. What i have done so far is installed react-native-permissions and ran the command react-native link react-native-permissions  and now i don't understand where i need to put handlers in my project. Please, can you elaborate a little more ?

**Comment by vishgoel007** [comment]
@zoontek Thanks, fixed.

**Comment by hjtgzh** [comment]
> @zoontek Thanks, fixed.

@vishgoel007 Can you share the specific operation？

**Comment by hjtgzh** [comment]
Here are the detailed operations：https://github.com/react-native-community/react-native-permissions/issues/348
