### ISSUE TITLE
NativeModule.RNPermissions is null when using Expo

### ISSUE THREAD

**Issue by nik-sloop** [zoontek/react-native-permissions#399]
Expo version: 36.0.0
React-Native version: 0.61.4
React-Native-Permissions version: 2.0.9

I am trying to build an app using expo and throws this error:

 "if (RNPermissions == null) {
  throw new Error(`react-native-permissions: NativeModule.RNPermissions is null. To fix this issue try these steps:
• Run \`react-native link react-native-permissions\` in the project root.
• Rebuild and re-run the app.
• If you are using CocoaPods on iOS, run \`pod install\` in the \`ios\` directory and then rebuild and re-run the app. You may also need to re-open Xcode to get the new pods.
• Check that the library was linked correctly when you used the link command by running through the manual installation instructions in the README.
* If you are getting this error while unit testing you need to mock the native module. Follow the guide in the README.
If none of these fix the issue, please open an issue on the Github repository: https://github.com/react-native-community/react-native-permissions`);
} "

The app works fine when I build it without using expo. 

Any ideas? 

Thanks

**Comment by mikehardy** [comment]
expo + native modules = does not work
I believe with the bare workflow it might be possible, but in general if you want native code you need to eject. Expo won't work with native modules.

**Comment by nik-sloop** [comment]
That's unfortunate... Thanks

**Comment by mikehardy** [comment]
just to be clear - expo actually has a ton of native modules *inside* the expo ecosystem, those all work. It's non-expo native modules that don't work. I would be surprised if there was not some expo permissions module - chat with them and you'll probably get a solution that works while using expo

**Comment by BasilJohn** [comment]
HI i get this error even with out expo..RN version     "react-native": "^0.59.8",
    "react-native-permissions": "^2.0.9",

**Comment by mikehardy** [comment]
@BasilJohn everyone gets this error when the module is not linked in correctly. You must have a project config / module install issue of some sort.

**Comment by BasilJohn** [comment]
> @BasilJohn everyone gets this error when the module is not linked in correctly. You must have a project config / module install issue of some sort.

Thank you..I am checking

**Comment by hjtgzh** [comment]
> > @BasilJohn everyone gets this error when the module is not linked in correctly. You must have a project config / module install issue of some sort.
> 
> Thank you..I am checking


I encountered the same problem and the same version number as you, did you solve it?

**Comment by mustapha-ghlissi** [comment]
Here is the solution [https://github.com/zoontek/react-native-permissions/issues/429#issuecomment-1500121670]
