### ISSUE TITLE
Invalid RNPermission 'ios.permission.LOCATION_ALWAYS' should be one of

### ISSUE THREAD

**Issue by vvscode** [zoontek/react-native-permissions#404]
# Question

In my code I have

```ts
import { request, PERMISSIONS } from 'react-native-permissions';
// ...
const backgroundLocationPermission = Platform.select({
  ios: PERMISSIONS.IOS.LOCATION_ALWAYS,
  android: PERMISSIONS.ANDROID.ACCESS_BACKGROUND_LOCATION,
});
// ...
request(backgroundLocationPermission)
```
it gives me

![Simulator Screen Shot - iPhone 8 - 2 - 2020-01-23 at 11 11 20](https://user-images.githubusercontent.com/6904368/72972715-9deae700-3dd4-11ea-960f-83ef23b6d6b6.png)

Potentially related links (which didn't help to me):
https://github.com/react-native-community/react-native-permissions#%EF%B8%8F-if-you-encounter-the-error-invalid-rnpermission-x-should-be-one-of-
https://github.com/react-native-community/react-native-permissions/issues/326

Why? How to fix?

**Comment by zoontek** [comment]
@vvscode Please submit your Podfile.

**Comment by vvscode** [comment]
@zoontek  sure

[Podfile.txt](https://github.com/react-native-community/react-native-permissions/files/4102328/Podfile.txt)

**Comment by zoontek** [comment]
```ruby
 permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'RNPermissions', :path => "../node_modules/react-native-permissions/RNPermissions.podspec"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse.podspec"
```

As I though, you linked the wrong permission handler. If you ask for `PERMISSIONS.IOS.LOCATION_ALWAYS`, you need to link `pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways.podspec"`

Then run `pod install`, clean your Xcode build, re-build: everything should be fine 😄
