### ISSUE TITLE
Android: dangerous permissons (reboot)

### ISSUE THREAD

**Issue by HonzaJiran** [zoontek/react-native-permissions#405]
# Question

Hi,
is there any way how to ask user for "dangerous" permissions such as `REBOOT`?
https://developer.android.com/reference/android/Manifest.permission.html#REBOOT

**Comment by zoontek** [comment]
@HonzaJiran Hi! No, I'm afraid not.

> Not for use by third-party applications.

This library only allows you to request permissions flagged with `Protection level: dangerous`, which need runtime validation from the user.
