### ISSUE TITLE
check(Permissions.PERMISSIONS.IOS.LOCATION_ALWAYS) returns granted even for While in Use on latest ios

### ISSUE THREAD

**Issue by bars0um** [zoontek/react-native-permissions#406]
# Bug

Version: 2.0.2

On iOS 13.2.2 iPhone 11

1 - change app location permission settings to While Using the App

![image](https://user-images.githubusercontent.com/39853587/73359849-6e434f80-42aa-11ea-9d8b-97ad3525515e.png)

2- perform check for Always Allow:

![image](https://user-images.githubusercontent.com/39853587/73359922-9337c280-42aa-11ea-8771-48ddd2f2ae59.png)

Library reports that the permission is granted although this is not the case!

![image](https://user-images.githubusercontent.com/39853587/73359979-a9de1980-42aa-11ea-9fa4-accf90f9114e.png)

## Environment info

```
System:
    OS: macOS Mojave 10.14.4
  Binaries:
    Node: 10.15.0 - /usr/local/bin/node
    npm: 6.4.1 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1   
  IDEs:
    Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.4 => 0.61.4 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

Library version: 2.0.2

## Steps To Reproduce

1. on iOS Set App Location permission to While Using the App
2. Use library to check permission for "Always Allow"
3. Note that you are informed that the permission is granted 

Describe what you expected to happen:

1. on iOS Set App Location permission to While Using the App
2. Use library to check permission for "Always Allow"
3. You are informed that the permission is denied

## Reproducible sample code

```
           // Are we authorized to use location?
            await Permissions.check(Permissions.PERMISSIONS.IOS.LOCATION_ALWAYS).then(async response => {

                console.vialog('location is ' + response)
                if (response === Permissions.RESULTS.GRANTED) {
                    this.setState({ authorizedLocation: true })
```

**Comment by bars0um** [comment]
This behavior doesn't seem to be happening on version 2.0.9. Does patch level updates require a binary reinstall?

**Comment by bars0um** [comment]
I've tried upgrading to latest version 2.0.9 but the behavior is the same or random at best, sometimes it works properly, sometimes it doesn't...depending on what my initial selection was....

**Comment by zoontek** [comment]
@bars0um Unfortunately that's not an issue, but the system behavior. Check this issue and the answer: https://github.com/react-native-community/react-native-permissions/issues/383

**Comment by bars0um** [comment]
@zoontek Thanks for your reply...

I see, so we basically don't really know which type of permission has been granted, only that something's been granted relating to location settings...hmmm...not sure how to work with this. 

Currently we require users to enable always allow so that background location tasks can be executed,...with the "While Using the App" selection those tasks don't seem to fire. We will have to go back to the drawing board for that one, I guess there should be a way to run location-based events in the background with the "While Using the App" permission...

**Comment by zoontek** [comment]
@bars0um I recommend the `requestAlwaysAuthorization` documentation about this: https://developer.apple.com/documentation/corelocation/cllocationmanager/1620551-requestalwaysauthorization?language=objc

It's useful to learn the difference between `Provisional Always` and `Temporary When in Use`

**Comment by bars0um** [comment]
Thank you Mathieu. Will review the doc, also the explanation for what “while using the app” really means was useful as well: (https://support.apple.com/en-us/HT203033) although it would be nice to find an article that explains how the OS handles the case technically.
