### ISSUE TITLE
request(Permissions.PERMISSIONS.IOS. BLUETOOTH_PERIPHERAL) returns unavailable after pressing `OK` on iOS version 13

### ISSUE THREAD

**Issue by BohdanIvanov** [zoontek/react-native-permissions#407]
Hello everyone!

I've faced an issue regarding `request` functionality in iOS. I'm trying to request the Bluetooth service permission and after pressing `OK` to allow my application to use the Bluetooth, the request returned `Unavailable`, when I'm expecting to receive `Granted` status. After that, any attempt to enable Bluetooth ends with the app crash. I will add a screenshot below. On pressing `Don't allow` it returns `Blocked` status as it should. It basically means that functionality is not available for usage, even with allowing to use it. Does anyone have a similar issue?

Thank you in advance.

**Steps to reproduce:**
1) Launch app with `react-native-permissions` library
2) Perform `request(PERMISSIONS.IOS.BLUETOOTH_PERIPHERAL)`
3) Press `OK`. The request returns the `unavailable` response
4) Enable Bluetooth

**Received error message:**

<img width="338" alt="Screenshot 2020-02-01 at 09 44 19" src="https://user-images.githubusercontent.com/20393150/73588894-7df3ab80-44d7-11ea-8d30-c8706b2cbe4a.png">

**NOTES:**
- Using a real device (iPhone XS)
- iOS 13.3 version
- Both NSBluetoothAlwaysUsageDescription and NSBluetoothPeripheralUsageDescription were added to Info.plist

**Comment by zoontek** [comment]
@BohdanIvanov Are you working in the simulator? Please fill the issue template for more informations.

**Comment by BohdanIvanov** [comment]
@zoontek I'm using actual devices. Did check on iPhone XS multiple times.
`await request(PERMISSIONS.IOS.BLUETOOTH_PERIPHERAL)` returns an `unavailable` response after `OK` was pressed.

**Comment by zoontek** [comment]
@BohdanIvanov Did you added bluetooth-peripheral in your app supported capabilities?

**Comment by BohdanIvanov** [comment]
@zoontek Didn't notice any bluetooth-peripheral option in capabilities inside of Xcode. Can you please share a screenshot?

**Comment by zoontek** [comment]
Sure (Bluetooth peripheral = Acts as a Bluetooth LE accessory)

<img width="642" alt="Screenshot 2020-02-04 at 10 22 36" src="https://user-images.githubusercontent.com/1902323/73731226-66ffc400-4738-11ea-87b8-8177bde59532.png">

<img width="661" alt="Screenshot 2020-02-04 at 10 22 44" src="https://user-images.githubusercontent.com/1902323/73731235-6b2be180-4738-11ea-9975-1a5092a75786.png">

**Comment by zoontek** [comment]
@BohdanIvanov Any progress?

**Comment by BohdanIvanov** [comment]
@zoontek Sorry that couldn't answer earlier. For now, I've decided to go another way, without using the `request` method. I'll try to test in the nearest time and will let you know. Thank you :)

**Comment by ireshdudeja** [comment]
I tried the mentioned steps but bluetooth permissions are not working. I am using iOS 14.2

**Comment by dorthwein** [comment]
Also seeing this :( not working ios 14.

**Comment by mikehardy** [comment]
The critical question @dorthwein is this I think:

> @BohdanIvanov Did you added bluetooth-peripheral in your app supported capabilities?

...additionally it appears the example app tests every single one, does the example app demonstrate this one? Worth confirming, and if it does, does the example app work?

**Comment by esiltu** [comment]
Does it still work on iOS real device for Bluetooth on iOS 17.5 if I have followed all steps above?

@zoontek

**Comment by zoontek** [comment]
@esiltu Yes

**Comment by esiltu** [comment]
If you're encountering the issue where requesting Bluetooth permission returns `unavailable`, add this line to your `iOS -> Podfile`: `pod 'Permission-BluetoothPeripheral', :path => "../node_modules/react-native-permissions/ios/BluetoothPeripheral"` and rebuild your app to resolve the issue. I'm using version 17.5.

@zoontek thanks !

**Comment by zoontek** [comment]
@esiltu Or read the documentation (iOS setup especially)
