### ISSUE TITLE
The permission is denied and not requestable anymore

### ISSUE THREAD

**Issue by kamrankamrani** [zoontek/react-native-permissions#409]
hi,
i'm working in android emulator and
i requested the PERMISSIONS.ANDROID.READ_PHONE_STATE, the emulator is not asked the permission and the permission is blocked . console is printed :

"The permission is denied and not requestable anymore"

after that i can not even request the permission. what am i supposed to do with blocked and not requested permissions?
why is this happened and should i reinstall app again to request again the permission?

**Comment by zoontek** [comment]
@kamrankamrani Hi 👋
Please fill the issue template of this issue will be closed.

Edit: you can reinstall the app to reset permissions or open app settings to change them. This package even have a `openSettings()` method to cover this use case
