### ISSUE TITLE
Add Version Support Table

### ISSUE THREAD

**Issue by dangnelson** [zoontek/react-native-permissions#41]
I'm working on a standard for displaying version support on React-Native module README files. I would love your feedback: [react-native-version-support-table](https://github.com/dangnelson/react-native-version-support-table/)

**Comment by yonahforst** [comment]
that's a nice idea. It looks great to me!

**Comment by dangnelson** [comment]
Thanks! Let me know if you end up using it, I'm going to try to keep a running list of repositories at the bottom of my README that are currently supporting it.

**Comment by yonahforst** [comment]
will do. I'll add it tomorrow

**Comment by yonahforst** [comment]
added!
