### ISSUE TITLE
Install without use pod

### ISSUE THREAD

**Issue by TechSupportPlugnotes** [zoontek/react-native-permissions#413]
# Question

Hello, it's possible to use and install without using pods.
Because my projet not use podfiles and when i want to install with this, I have multiple error.
Exemple : Library not found for -lPermission-Calendars

**Comment by zoontek** [comment]
@TechSupportPlugnotes Hi. Only Cocoapods is supported out of the box. If you still want to avoid it, you still can drag and drop files in your project (by reference). `RNPermissions.{h,m}` are mandatory, each couple of `XPermissionHandler.{h,m}` add support for one type of permission.

**Comment by hjtgzh** [comment]
> @TechSupportPlugnotes Hi. Only Cocoapods is supported out of the box. If you still want to avoid it, you still can drag and drop files in your project (by reference). `RNPermissions.{h,m}` are mandatory, each couple of `XPermissionHandler.{h,m}` add support for one type of permission.

@zoontek Is there a detailed api？
