### ISSUE TITLE
Library not found for -lPermission-******

### ISSUE THREAD

**Issue by TechSupportPlugnotes** [zoontek/react-native-permissions#414]
# Question

So, if this plugins is out of box to use CocoaPods, have you an idea why i have this error ?

"Library not found for -lPermission-*******"

React-native 0.59.10. And the projet not use Pods. So i forgot maybe a step.

**Comment by zoontek** [comment]
@TechSupportPlugnotes Unlink RNPermissions.xcodeproj, drag and drop files. Also, please don't open new issues for questions like this. Posting on closed ones / StackOverflow is OK if you only want programming help 🙂

**Comment by TechSupportPlugnotes** [comment]
Ok sorry, when i saw that my issus was closed, i was thinking that i do create a new one :).
What do you mean by drag and drop files ?
Where ? Which files ?
no realy need helps :), juste that i upgrated your plugin from 0.2.7 so that more just different.
and i never use pods before !

> @TechSupportPlugnotes Unlink RNPermissions.xcodeproj, drag and drop files. Also, please don't open new issues for questions like this. Posting on closed ones / StackOverflow is OK if you only want programming help 🙂

**Comment by zoontek** [comment]
If you don't want to struggle with Cocoapods, follow these instructions: https://github.com/react-native-community/react-native-permissions/issues/348#issuecomment-541423154. Don't forget to drag and drop `RNPermissions.{h,m}, and avoid linking the package.

**Comment by TechSupportPlugnotes** [comment]
oh thanks, i read a multiple pots and i didn't find this ... so sorry !

**Comment by abdullateef97** [comment]
@zoontek I'm I allowed to comment on this thread sice it's closed
Getting this error `ld: library not found for -lPermission-LocationWhenInUse
` and I have followed the instructions you gave on [#348(comment)](https://github.com/react-native-community/react-native-permissions/issues/348#issuecomment-541423154)
but i still get the same error.
Any help would be appreciated

**Comment by abdullateef97** [comment]
@TechSupportPlugnotes were you able to fix this

**Comment by senol-keskin** [comment]
I am getting same errors. I have tried couple of things but still same,
 RN version 0.63.2
