### ISSUE TITLE
Location services off return unaviliable v2.0.6

### ISSUE THREAD

**Issue by vvusts** [zoontek/react-native-permissions#415]
I check location permission like:
```
const whileInUseAllowed = await check(
    Platform.select({
      android: PERMISSIONS.ANDROID.ACCESS_FINE_LOCATION,
      ios: PERMISSIONS.IOS.LOCATION_WHEN_IN_USE,
    }),
  );
  const alwaysAllowed = await check(
    Platform.select({
      android: PERMISSIONS.ANDROID.ACCESS_FINE_LOCATION,
      ios: PERMISSIONS.IOS.LOCATION_ALWAYS,
    }),
  );

return whileInUseAllowed == RESULTS.GRANTED || alwaysAllowed == RESULTS.GRANTED;
```

Bu in the following scenarion:
1. Installed app and gave location permission
2. Go to iphone settings privacy and turn off location services
3. Back to the app I am getting `unavailable`.

Is this normal behavior does `unavailable` mean location services are off or this is a bug or I am doing something wrong?

_So if I gave permission and disabled location services I need to differ this two as I asked user to go to settings to enable but it is enables just location services is off._

**Comment by zoontek** [comment]
@vvusts It's the wanted behavior, you are not doing something wrong

**Comment by vvusts** [comment]
@zoontek what is wanted behavior? So `unavailable` means location services are off from settings > privacy > location service?

**Comment by zoontek** [comment]
Yes. See https://github.com/react-native-community/react-native-permissions/blob/master/ios/LocationWhenInUse/RNPermissionHandlerLocationWhenInUse.m#L25

**Comment by vvusts** [comment]
Ah it's clear when look at that code. But I think this is not really intuitive maybe can be added as a note in documentation.
Thanks a lot :)
