### ISSUE TITLE
Error: Notifications permission pod is missing

### ISSUE THREAD

**Issue by ugrdursun** [zoontek/react-native-permissions#418]
Having this issue when try to get notifications

`Error: Notifications permission pod is missing`

As i checked from issues this one is closed at 2.0.1 but im receiving this at 2.0.6.

Despite I added this manually to my podfile :
`  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications.podspec"`,

Any thoughts ?

**Comment by zoontek** [comment]
@ugrdursun Did you run `pod install`, clean your project build artifacts?

**Comment by ugrdursun** [comment]
> @ugrdursun Did you run `pod install`, clean your project build artifacts?

Yes i ran pod install but what do you mean by clean your project ?

**Comment by zoontek** [comment]
@ugrdursun Run `npx react-native-clean-project --remove-iOS-build --remove-iOS-pods`

**Comment by ugrdursun** [comment]
> @ugrdursun Run `npx react-native-clean-project --remove-iOS-build --remove-iOS-pods`

Yeah just tried and its still same. Location Permission is working fine by the way

**Comment by ugrdursun** [comment]
OK I solved the problem.

I deleted everything inside of `~/Library/Developer/Xcode/DerivedData` folder manually and rebuilded app via xCode, it started working.

**Comment by mikehardy** [comment]
If you hard run react-native-clean-project, it would have done that for you as well as a few other obscure things that will solve other caching-related issues. Strongly recommended for CI, and any time you have an otherwise unexplainable problem...
