### ISSUE TITLE
Cocoapods 1.9.0 and xCode 11.3.1 Conflicts

### ISSUE THREAD

**Issue by kyytiPetteri** [zoontek/react-native-permissions#420]
# Bug

Ran into the following issue when updating to Cocoapods `1.9.0` 

`NameError - uninitialized constant Pod::Target::BuildType` 

Seems that `Pod::Target::BuildType` is deprecated and update should be `Pod::BuildType`. Figured to post it here since Readme is giving different instuctions

## Environment info

React native info output:

```
System:
    OS: macOS 10.15.3
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 947.76 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 28
      Build Tools: 28.0.3
      System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: ^0.61.5 => 0.61.5
```

Library version: 2.0.9

### Prerequisites:
Pod file includes `use_frameworks` 
Use the `pre_install` method provided from Readme to use static frameworks

## Steps To Reproduce

1. Update Cocoapods to 1.9.0
2. Install fails
...

Describe what you expected to happen:

1. Install succeeds

**Comment by zoontek** [comment]
@kyytiPetteri Did you tried

```ruby
use_frameworks! :linkage => :static
```

As seen in: http://blog.cocoapods.org/CocoaPods-1.9.0-beta/

**Comment by zoontek** [comment]
@kyytiPetteri Ok, I tried it with CocoaPods 1.9. We should edit the README / example project Podfile to:

```ruby
$dynamic_frameworks = []

pre_install do |installer|
  installer.pod_targets.each do |pod|
    if !$dynamic_frameworks.include?(pod.name)
      puts "Link #{pod.name} as static_library"
      def pod.build_type;
        # Uncomment one line depending on your CocoaPods version
        # Pod::BuildType.static_library # >= 1.9
        # Pod::Target::BuildType.static_library # < 1.9
      end
    end
  end
end
```

**Comment by zoontek** [comment]
Done! Thanks 🙂 https://github.com/react-native-community/react-native-permissions#%EF%B8%8F-if-you-encounter-the-error-invalid-rnpermission-x-should-be-one-of-
