### ISSUE TITLE
Permissions.check for 'Location always' returns 'granted' after selecting "allow once"

### ISSUE THREAD

**Issue by Desteel** [zoontek/react-native-permissions#421]
Platform: iOS
Device: Simulator iPad Air
Environment: Xcode 11.1
React Native: 0.59.8

> Allow while using app -> "(provisional) always" will be granted, then later a popup will inform the user "this app uses location in background, continue allowing it?"
Allow Once -> "always" will not be granted, but "when in use" will be, then the permission will be reset on next app launch
Dont Allow -> permission blocked

Hello.
So, I call the permission request for the `ios.permission.LOCATION_ALWAYS`

```javascript
class GeolocationService {
  // ...

  private requestPermission = async () => {
    const status = await Permissions.request("ios.permission.LOCATION_ALWAYS");
    this.hasPermissions = status === "granted";
  };

  public runService = async () => {
    await this.requestPermission();
    this.isActive = true;

    this.geolocator.runGeolocator();
  };
}
```
`Permissions.request` returns status as 'blocked' with 'allow once'
In the future, I call the check when the application state changes, but `setTimeout` work too.

```javascript
setTimeout(async() => {
   const status = await Permissions.check("ios.permission.LOCATION_ALWAYS");
   this.hasPermissions = status === "granted";
}, 1000)
```

And `Permissions.check` returns `granted`.

Why?

**Comment by zoontek** [comment]
@Desteel Hi. This already has been explained here: https://github.com/react-native-community/react-native-permissions/issues/379

**Comment by Desteel** [comment]
Thank you, but that doesn't explain this behavior

```javascript
// allow once
await Permissions.request("ios.permission.LOCATION_ALWAYS"); // blocked
await Permissions.check("ios.permission.LOCATION_ALWAYS"); // blocked
setTimeout(async() => {
   await Permissions.check("ios.permission.LOCATION_ALWAYS"); // granted
}, 1000)
```
Maybe I misunderstood something?

**Comment by zoontek** [comment]
@Desteel Did you tried on a real device? Simulators can have a lot of quirks with permissions 😞

**Comment by Desteel** [comment]
@zoontek yep, i tried on iPad 10.2

**Comment by zoontek** [comment]
@Desteel on iOS 13 too? Are location services enabled? This is a really odd behavior, I will try to reproduce it

**Comment by Desteel** [comment]
@zoontek yep, iPad 10.2. iOS 13.1, location services enabled.
```
"react-native": "0.59.8",
"react-native-permissions": "^2.0.9",
```

```javascript
// allow once
await Permissions.request("ios.permission.LOCATION_ALWAYS"); // blocked
await Permissions.check("ios.permission.LOCATION_ALWAYS"); // blocked
setTimeout(async() => {
   await Permissions.check("ios.permission.LOCATION_ALWAYS"); // granted
}, 1000)

// allow while using app
await Permissions.request("ios.permission.LOCATION_ALWAYS"); // granted
await Permissions.check("ios.permission.LOCATION_ALWAYS"); // granted
```

I also reproduced this in the root component `App.tsx`

```javascript
  public async componentDidMount() {
    let test = await Permissions.request("ios.permission.LOCATION_ALWAYS"); // blocked
    console.log(test);
    let test2 = await Permissions.check("ios.permission.LOCATION_ALWAYS"); // blocked
    console.log(test2);

    setTimeout(async () => {
      let test3 = await Permissions.check("ios.permission.LOCATION_ALWAYS"); // granted
      console.log(test3);
    }, 1000);
  }
```

**Comment by Desteel** [comment]
I think the problem is in the `Permissions.request`, because I installed 'react-native-location' and used a `RNLocation.requestPermission` from the library and it worked correctly. 
Also, after that, `Permissions.check` returns the correct value.

**Comment by zoontek** [comment]
@Desteel Once the request status did change, `check` is called by the `request` method: https://github.com/react-native-community/react-native-permissions/blob/master/ios/LocationAlways/RNPermissionHandlerLocationAlways.m#L66 so there shouldn't be any inconsistency at one second interval. I will check the source code of `react-native-location`

**Comment by Desteel** [comment]
@zoontek 
I'm sorry I misled you about the 'react-native-location'. Library methods have the same behavior.

```javascript
// allow once
await RNLocation.requestPermission({
      ios: "always"
    }).then(granted => {
      console.log(granted); // false
    });

await RNLocation.checkPermission({
        ios: "always"
      }).then(granted => {
        console.log(granted); // false
      });

setTimeout(async () => {
      await RNLocation.checkPermission({
        ios: "always"
      }).then(granted => {
        console.log(granted); // true
      });
    }, 1000);
```

**Comment by zoontek** [comment]
@Desteel I think this is a quirk in iOS, but I'm not sure on how we can detect this…

**Comment by Desteel** [comment]
@zoontek thanks anyway
