### ISSUE TITLE
[iOS] Background App Refresh permission

### ISSUE THREAD

**Issue by mcgomez** [zoontek/react-native-permissions#423]
# Question
I'm wondering if it's possible to access the permission state of `Background App Refresh` within an apps settings.
<img width="523" alt="Screen Shot 2020-03-12 at 9 58 50 AM" src="https://user-images.githubusercontent.com/7349769/76529284-76b1ad00-6448-11ea-867d-9c8bf0e463cf.png">

**Comment by zoontek** [comment]
@mcgomez Hi 👋 Not as I know!

**Comment by mikehardy** [comment]
https://stackoverflow.com/a/19138393/9910298

```objective-c
if ([[UIApplication sharedApplication] backgroundRefreshStatus] == UIBackgroundRefreshStatusAvailable) {

    NSLog(@"Background updates are available for the app.");
}else if([[UIApplication sharedApplication] backgroundRefreshStatus] == UIBackgroundRefreshStatusDenied)
{
    NSLog(@"The user explicitly disabled background behavior for this app or for the whole system.");
}else if([[UIApplication sharedApplication] backgroundRefreshStatus] == UIBackgroundRefreshStatusRestricted)
{
    NSLog(@"Background updates are unavailable and the user cannot enable them again. For example, this status can occur when parental controls are in effect for the current user.");
}
```

**Comment by zoontek** [comment]
@mikehardy It could be checked, but not requested. We should add it anyway.

**Comment by mikehardy** [comment]
https://github.com/jamesisaac/react-native-background-task#statusasync

https://github.com/transistorsoft/react-native-background-fetch/ (status method)

I would not add it, react-native-background-fetch is a module I personally use and is well-maintained, since it's not a permission I'd stay focused with this module and tell people to use that one
