### ISSUE TITLE
[iOS] Why it's needed to be build as static library or have modular headers

### ISSUE THREAD

**Issue by celtaheaven** [zoontek/react-native-permissions#424]
I'm developing a framework through .podspec that uses react-native technologies but I'm facing problems with however configurations I try with RNPermissions. I want to know why it's needed to be built in those specific variants (static library or having modular headers).

**Comment by zoontek** [comment]
Because every other config we tried with Cocoapods results in Xcode not founding the headers files.

**Comment by celtaheaven** [comment]
Thank you! This is something I'm looking forward to help. If I see something I'll notice the community, thanks again!
