### ISSUE TITLE
Idea for [iOS]: Simplify the Podspec to make it single

### ISSUE THREAD

**Issue by celtaheaven** [zoontek/react-native-permissions#426]
I don't know if it's the communities objective, but in iOS forcing frameworks to be built static tends to go bad for many reasons, mainly in stuff that uses React Native. I've managed to use the RNPermissions without forcing it to be static, in a variant where I've deleted all the #define verifications inside the RNPermission{h,m} and changing the main podspec to work alone.

Podfile for the app that uses the feature:
```
platform :ios, '9.0'
source 'https://bitbucket.org/private-info/private-specs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AppDoGu
  pod 'FullyOperatingReactNativeFeature', :git => 'https://bitbucket.org/private-info/private-feature.git', :tag => '2.0.0'
end
```

Inside the FullyOperatingReactNativeFeature.podspec:
```s.dependency 'Simplified-RNPermissions'```

Simplified-RNPermissions.podspec:

```
Pod::Spec.new do |s|
  s.name                      = "Simplified-RNPermissions"
  s.dependency                  "React"
  # ...
  s.homepage                  = "https://bitbucket.org/private-info/simplified-rnpermissions.git"

  s.platform                  = :ios, "9.0"
  s.ios.deployment_target     = "9.0"
  s.tvos.deployment_target    = "11.0"
  s.requires_arc              = true

  s.source                    = { :git => "https://bitbucket.org/private-info/simplified-rnpermissions.git", :tag => s.version }
  s.source_files              = "ios/**/*.{h,m}" # This change did all the work
end
```

It's something. If its unintended to do changes like this, maybe just warn in the README that it needs to be built with modular_headers or statically.

**Comment by zoontek** [comment]
@celtaheaven What do you mean by `#define`? `if __has_include` checks?

If I correctly understand what you are suggesting, you want to remove the headers presence tests and embedding all `*PermissionHandler.{h,m}` files by default. It will never be done for the simple fact that embedding code to request unused permissions does not pass the App store checks.

Instructions about `modular_headers` are already in the `README`: https://github.com/react-native-community/react-native-permissions#%EF%B8%8F-if-you-encounter-the-error-invalid-rnpermission-x-should-be-one-of-

You can also enforce static build for permissions handlers only (the lib core don't need to be build statically), if you want:

```ruby
use_frameworks!

pre_install do |installer|
  installer.pod_targets.each do |pod|
    if pod.name.start_with?("Permission-")
      def pod.build_type;
        # Uncomment one line depending on your CocoaPods version
        # Pod::BuildType.static_library # >= 1.9
        # Pod::Target::BuildType.static_library # < 1.9
      end
    end
end
```
