### ISSUE TITLE
react-native-permissions: NativeModule.RNPermissions is null. To fix this issue try these steps

### ISSUE THREAD

**Issue by BasilJohn** [zoontek/react-native-permissions#429]
react-native-permissions: NativeModule.RNPermissions is null. To fix this issue try these steps

Getting this error even without expo

React Native Version:    "react-native": "^0.59.8",
    "react-native-permissions": "^2.0.9",

Installed and followed manual linking instructions.Still getting the same error.

**Comment by dgana** [comment]
@BasilJohn I got the same error until I add the Podfile for notification without add Info.plist

**Comment by BasilJohn** [comment]
> @BasilJohn I got the same error until I add the Podfile for notification without add Info.plist

@dgana what about android ?

**Comment by BasilJohn** [comment]
@dgana  can you please tell me how to fixed it on IOS? 
until I add the Podfile for notification without add Info.plist--I did not get this line

**Comment by zoontek** [comment]
@BasilJohn Follow this part of the documentation: https://github.com/react-native-community/react-native-permissions/blob/master/README.md#-manual-linking

**Comment by dgana** [comment]
@BasilJohn But i'm still getting an error when i add Podfile ``` pod 'Permission-Notifications', :path => "../node_modules/react-native-permissions/ios/Notifications.podspec"```


```
NativeFirebaseError: [messaging/unknown] no valid “aps-environment” entitlement string found for application
    at FirebaseMessagingModule.requestPermission (http://192.168.0.187:8081/index.bundle?platform=ios&dev=true&minify=false:164729:28)
    at registerForPushNotificationsAsync$ (http://192.168.0.187:8081/index.bundle?platform=ios&dev=true&minify=false:159780:77)
    at tryCatch (http://192.168.0.187:8081/index.bundle?platform=ios&dev=true&minify=false:25461:19)
    at Generator.invoke [as _invoke] (http://192.168.0.187:8081/index.bundle?platform=ios&dev=true&minify=false:25637:24)
    at Generator.prototype.<computed> [as next] (http://192.168.0.187:8081/index.bundle?platform=ios&dev=true&minify=false:25504:23)
    at tryCatch (http://192.168.0.187:8081/index.bundle?platform=ios&dev=true&minify=false:25461:19)
    at invoke (http://192.168.0.187:8081/index.bundle?platform=ios&dev=true&minify=false:25537:22)
    at http://192.168.0.187:8081/index.bundle?platform=ios&dev=true&minify=false:25567:13
    at tryCallTwo (http://192.168.0.187:8081/index.bundle?platform=ios&dev=true&minify=false:26826:7)
```

I'm trying to add ```"@react-native-firebase/messaging": "^6.3.4"``` actually but got the error below. And so I have to install ```"react-native-permissions": "^2.0.10"```

```
2020-03-20 18:38:56.311 [error][tid:com.facebook.react.JavaScript] Error: react-native-permissions: NativeModule.RNPermissions is null. To fix this issue try these steps:
• If you are using CocoaPods on iOS, run `pod install` in the `ios` directory and then rebuild and re-run the app. You may also need to re-open Xcode to get the new pods.
* If you are getting this error while unit testing you need to mock the native module. Follow the guide in the README.
If none of these fix the issue, please open an issue on the Github repository: https://github.com/react-native-community/react-native-permissions
```

But still no luck. My Android remote notification still works very well btw using firebase server
see https://github.com/invertase/react-native-firebase/issues/2657

**Comment by zoontek** [comment]
The first error is not related to this lib: https://stackoverflow.com/a/33015254

For the second one, please submit your Podfile

**Comment by BasilJohn** [comment]
> @BasilJohn Follow this part of the documentation: https://github.com/react-native-community/react-native-permissions/blob/master/README.md#-manual-linking
@zoontek  tried this..but I get the same error

**Comment by zoontek** [comment]
@BasilJohn Did you clean your Xcode cache after correctly linking the lib?

**Comment by BasilJohn** [comment]
> @BasilJohn Did you clean your Xcode cache after correctly linking the lib?

Im getting this in android ..haven't looked into iOS yet

**Comment by zoontek** [comment]
> > @BasilJohn Did you clean your Xcode cache after correctly linking the lib?
> 
> Im getting this in android ..haven't looked into iOS yet

Your Gradle cache then? Uninstall the app, clean and build it again.

**Comment by dgana** [comment]
Currently i got this error below

```
Error: Notifications permission pod is missing
    at Object.fn [as requestNotifications] (NativeModules.js:99)
    at requestNotifications (index.js:145)
    at registerForPushNotificationsAsync$ (index.js:32)
    at tryCatch (runtime.js:45)
    at Generator.invoke [as _invoke] (runtime.js:274)
    at Generator.prototype.<computed> [as next] (runtime.js:97)
    at tryCatch (runtime.js:45)
    at invoke (runtime.js:135)
    at runtime.js:145
    at tryCallOne (core.js:37)
```
Podfile
```
  pod 'Permission-Notifications', :path => "../node_modules/react-native-permissions/ios/Notifications.podspec"
```
What's the prerequisite for remote notification iOS btw?
Thank you for the lib

**Comment by zoontek** [comment]
@dgana Are you, by any chance, using Expo?

**Comment by dgana** [comment]
@zoontek no i'm not using expo. running on real device iOS 13
```
"react": "16.9.0",
"react-native": "0.61.5",
"react-native-permissions": "^2.0.10"
```

**Comment by zoontek** [comment]
@dgana Give your complete Podfile, not just one line

**Comment by dgana** [comment]
```
platform :ios, '9.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'GasSensorApp' do
  # Pods for GasSensorApp
  pod 'Permission-Notifications', :path => "../node_modules/react-native-permissions/ios/Notifications.podspec"

  pod 'FBLazyVector', :path => '../node_modules/react-native/Libraries/FBLazyVector'
  pod 'FBReactNativeSpec', :path => '../node_modules/react-native/Libraries/FBReactNativeSpec'
  pod 'RCTRequired', :path => '../node_modules/react-native/Libraries/RCTRequired'
  pod 'RCTTypeSafety', :path => '../node_modules/react-native/Libraries/TypeSafety'
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'ReactCommon/jscallinvoker', :path => '../node_modules/react-native/ReactCommon'
  pod 'ReactCommon/turbomodule/core', :path => '../node_modules/react-native/ReactCommon'
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'


  target 'GasSensorAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  use_native_modules!
end

target 'GasSensorApp-tvOS' do
  # Pods for GasSensorApp-tvOS

  target 'GasSensorApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

**Comment by zoontek** [comment]
@dgana If you run `pod install`, try closing Xcode, delete the `DerivedData` folder: https://stackoverflow.com/a/18933382

**Comment by dgana** [comment]
@zoontek done already now my error is

```
NativeFirebaseError: [messaging/unregistered] You must be registered for remote notifications before calling get token, see messaging().registerForRemoteNotifications() or requestPermission().
    at FirebaseMessagingModule.getToken (http://192.168.0.187:8081/index.bundle?platform=ios&dev=true&minify=false:160608:28)
    at registerForPushNotificationsAsync$ (http://192.168.0.187:8081/src/screen/Home/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=true&runModule=false&shallow=true:98:77)
    at tryCatch (http://192.168.0.187:8081/index.bundle?platform=ios&dev=true&minify=false:29245:19)
    at Generator.invoke [as _invoke] (http://192.168.0.187:8081/index.bundle?platform=ios&dev=true&minify=false:29421:24)
    at Generator.prototype.<computed> [as next] (http://192.168.0.187:8081/index.bundle?platform=ios&dev=true&minify=false:29288:23)
    at tryCatch (http://192.168.0.187:8081/index.bundle?platform=ios&dev=true&minify=false:29245:19)
    at invoke (http://192.168.0.187:8081/index.bundle?platform=ios&dev=true&minify=false:29321:22)
    at http://192.168.0.187:8081/index.bundle?platform=ios&dev=true&minify=false:29331:15
    at tryCallOne (http://192.168.0.187:8081/index.bundle?platform=ios&dev=true&minify=false:3244:14)
```
My code
```
import messaging from '@react-native-firebase/messaging';

const registerForPushNotificationsAsync = async () => {
      try {
        messaging().registerForRemoteNotifications();
        const hasPermission = await messaging().hasPermission();
        console.log('HAS PERMISSION ', hasPermission);
        if (hasPermission) {
          await requestNotifications(['alert', 'badge', 'sound']);
          const apnToken = await messaging().getAPNSToken();
          console.log('APN TOKEN ', apnToken);
          const fcmToken = await messaging().getToken();
          console.log('FCM TOKEN ', fcmToken);
        } else {
          await messaging().requestPermission();
          console.log('REQUEST PERMISSION');
        }
      } catch (error) {
        console.log(error);
      }
    };
```

I have no idea sorry. Can you show me maybe how you handle to get the FCM token?. If i put await in `messaging().registerForRemoteNotifications();` the code below doesn't run.

My status is ```granted``` when calling ```await requestNotifications([
            'alert',
            'badge',
            'sound',
          ])```

**Comment by zoontek** [comment]
@dgana This is a totally different error than the one issued. Next time consider seriously creating a new issue instead of publishing in other ones, it will be less confusing.

Requesting the notification permission [already register your app for remote notifications](https://github.com/react-native-community/react-native-permissions/blob/2.0.10/ios/Notifications/RNPermissionHandlerNotifications.m#L129).

You mix `react-native-permissions` handlers and other libs for checking/requesting permissions. As system permissions APIs are…hum…bad, we have to store requested one in app storage, and the other libs ignore that (same the other way).

```ts
// this is enough to get the token, normally
const getToken = (): Promise<string | void> =>
  requestNotifications(["alert"])
    .then(({ status }) => (status === RESULTS.GRANTED ? messaging().getToken() : Promise.resolve()))
    .catch(error => console.error(error));
```

**Comment by dgana** [comment]
@zoontek Okay noted Thanks!

**Comment by amdixit** [comment]
I am new to react native and I am trying to run an existing project. My project doesn't use PodFile. When I try to build the project using Xcode, it builds fine but crashes with the below error. Please assist:

[error][tid:com.facebook.react.JavaScript] react-native-permissions: NativeModule.RNPermissions is null. To fix this issue try these steps:
• If you are using CocoaPods on iOS, run `pod install` in the `ios` directory and then rebuild and re-run the app. You may also need to re-open Xcode to get the new pods.
* If you are getting this error while unit testing you need to mock the native module. Follow the guide in the README.
If none of these fix the issue, please open an issue on the Github repository: https://github.com/react-native-community/react-native-permissions

**Comment by amdixit** [comment]
here is the version info:
react-native-cli: 2.0.1
react-native: 0.59.5

node: v10.17.0

package.json dependencies:

  "dependencies": {
    "@react-native-community/async-storage": "^1.6.2",
    "radio-button-react-native": "^1.1.6",
    "react": "16.8.3",
    "react-native": "0.59.5",
    "react-native-animatable": "^1.3.3",
    "react-native-camera": "^2.5.0",
    "react-native-datepicker": "^1.7.2",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-keyboard-aware-scroll-view": "^0.9.1",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-permissions": "^1.1.1",
    "react-native-qrcode-scanner": "^1.2.3",
    "react-native-reanimated": "^1.7.0",
    "react-native-screens": "^2.4.0",
    "react-native-splash-screen": "^3.2.0",
    "react-navigation": "^3.1.3",
    "react-redux": "^7.1.1",
    "redux": "^4.0.4",
    "redux-thunk": "^2.3.0"
  }

**Comment by zoontek** [comment]
@amdixit You need at least Cocoapods to link permissions handlers. Follow https://github.com/react-native-community/react-native-permissions#-manual-linking to link the library core. I'm closing this since the original issue is "solved". It's not directly an issue with the lib, but a bad install / bad cache state.

You can find a lot of infos on multiples React Native libraries, like [this one](https://github.com/react-native-community/react-native-geolocation/issues/69#issuecomment-561496055).

**Comment by ValerCh** [comment]
> @zoontek done already now my error is
> 
> ```
> NativeFirebaseError: [messaging/unregistered] You must be registered for remote notifications before calling get token, see messaging().registerForRemoteNotifications() or requestPermission().
>     at FirebaseMessagingModule.getToken (http://192.168.0.187:8081/index.bundle?platform=ios&dev=true&minify=false:160608:28)
>     at registerForPushNotificationsAsync$ (http://192.168.0.187:8081/src/screen/Home/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=true&runModule=false&shallow=true:98:77)
>     at tryCatch (http://192.168.0.187:8081/index.bundle?platform=ios&dev=true&minify=false:29245:19)
>     at Generator.invoke [as _invoke] (http://192.168.0.187:8081/index.bundle?platform=ios&dev=true&minify=false:29421:24)
>     at Generator.prototype.<computed> [as next] (http://192.168.0.187:8081/index.bundle?platform=ios&dev=true&minify=false:29288:23)
>     at tryCatch (http://192.168.0.187:8081/index.bundle?platform=ios&dev=true&minify=false:29245:19)
>     at invoke (http://192.168.0.187:8081/index.bundle?platform=ios&dev=true&minify=false:29321:22)
>     at http://192.168.0.187:8081/index.bundle?platform=ios&dev=true&minify=false:29331:15
>     at tryCallOne (http://192.168.0.187:8081/index.bundle?platform=ios&dev=true&minify=false:3244:14)
> ```
> 
> My code
> 
> ```
> import messaging from '@react-native-firebase/messaging';
> 
> const registerForPushNotificationsAsync = async () => {
>       try {
>         messaging().registerForRemoteNotifications();
>         const hasPermission = await messaging().hasPermission();
>         console.log('HAS PERMISSION ', hasPermission);
>         if (hasPermission) {
>           await requestNotifications(['alert', 'badge', 'sound']);
>           const apnToken = await messaging().getAPNSToken();
>           console.log('APN TOKEN ', apnToken);
>           const fcmToken = await messaging().getToken();
>           console.log('FCM TOKEN ', fcmToken);
>         } else {
>           await messaging().requestPermission();
>           console.log('REQUEST PERMISSION');
>         }
>       } catch (error) {
>         console.log(error);
>       }
>     };
> ```
> 
> I have no idea sorry. Can you show me maybe how you handle to get the FCM token?. If i put await in `messaging().registerForRemoteNotifications();` the code below doesn't run.
> 
> My status is `granted` when calling `await requestNotifications([ 'alert', 'badge', 'sound', ])`

And how did you do it?

**Comment by oleg-moseyko** [comment]
ANDROID
react-native-permissions: NativeModule.RNPermissions is null. To fix this issue try these steps

Getting this error even without expo

$ react-native info
info Fetching system and libraries information...
(node:36570) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
System:
    OS: macOS 10.15.5
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 247.81 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.2.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.8.4 - /Applications/MAMP/Library/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Python: 2.7.13 - /Applications/MAMP/Library/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.0 => 0.62.0 
  npmGlobalPackages:
    *react-native*: Not Found

> > > @BasilJohn Did you clean your Xcode cache after correctly linking the lib?
> > 
> > 
> > Im getting this in android ..haven't looked into iOS yet
> 
> Your Gradle cache then? Uninstall the app, clean and build it again.

did not help

**Comment by andrelmlins** [comment]
I'm getting this error on android

**Comment by oleg-moseyko** [comment]
@zoontek 
any idea?

ANDROID
react-native-permissions: NativeModule.RNPermissions is null. To fix this issue try these steps

Getting this error even without expo

**Comment by mikehardy** [comment]
Try it with the example. This is always the result of incorrect project integration, and the example is integrated correctly so it should work and prove it works. If it works and your project does not work, examine the auto-linking configuration in your android build.gradle files.

**Comment by andrelmlins** [comment]
Hello @oleg-moseyko , I managed to solve it in my case. React-native-permissions is dependent on another library that I use. When adding react-native-permissions as a project dependency the error disappeared.

**Comment by oleg-moseyko** [comment]
@mikehardy 
project works well if i deploy it  to other ubuntu pc but on mac i get this bullshit only for android (ios ok)

**Comment by jeff-g-work** [comment]
am getting the same error message (without manual linking) and this fixed it for me https://github.com/zoontek/react-native-permissions/issues/324#issuecomment-538768035

**Comment by michael0793** [comment]
> @dgana Are you, by any chance, using Expo?

Im using expo and i get this error react-native permissions:NativeModule.RNPermissions is null. Im using android device


shows loadmodukleImplementation under call stack guarded load module

**Comment by jessanKhan** [comment]
@zoontek  Hi I am using expo. and also getting this error. I don't have any package which needs linking. still getting this error. Please help. 
my package.json look like this 
{
  "name": "RNFoodDeliveryDriver",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@pusher/chatkit-client": "^1.13.1",
    "@react-native-community/netinfo": "^4.4.0",
    "axios": "^0.19.0",
    "expo": "36.0.0",
    "pusher-js": "^5.0.2",
    "react": "16.9.0",
    "react-native": "0.61.2",
    "react-native-config": "^0.11.7",
    "react-native-geocoding": "^0.4.0",
    "react-native-geolocation-service": "^3.1.0",
    "react-native-gesture-handler": "^1.4.1",
    "react-native-gifted-chat": "^0.11.0",
    "react-native-maps": "0.25.0",
    "react-native-maps-directions": "^1.7.3",
    "react-native-modal": "^11.4.0",
    "react-native-permissions": "^3.0.1",
    "react-native-pusher-push-notifications": "git+http://git@github.com/ZeptInc/react-native-pusher-push-notifications#v.2.4.0-zept-master",
    "react-native-reanimated": "^1.3.0",
    "react-native-screens": "^1.0.0-alpha.23",
    "react-navigation": "^4.0.10",
    "react-navigation-stack": "^1.9.4"
  },
  "devDependencies": {
    "@babel/core": "^7.6.3",
    "@babel/runtime": "^7.6.3",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-jest": "^24.9.0",
    "eslint": "^6.5.1",
    "jest": "^24.9.0",
    "metro-react-native-babel-preset": "^0.56.0",
    "react-test-renderer": "16.9.0"
  },
  "jest": {
    "preset": "react-native"
  }
}

**Comment by Luckygirlllll** [comment]
Is there any update about this issue? I'm getting the same error in Android.

**Comment by zoontek** [comment]
@Luckygirlllll This error doesn't really exists / happen. If it happen, it means that:

1) The module is not correctly linked
2) You can't use native modules (ex: non-bare Expo)
3) You perform tests and you forgot to mock the native module

**Comment by Luckygirlllll** [comment]
@zoontek this issue kind of exist because, I'm not using linking, because  I'm using "react-native": "0.63.4", so all linking is done automatically, I don't use Expo, I don't do tests. 

However, I got errors during the install, because react-native-permissions was complaining that I don't have latest version of RN, so during install I used  --legacy-peer-deps, I'm wonder is that could cause a problem.

<img width="632" alt="Screenshot 2021-05-06 at 12 43 44" src="https://user-images.githubusercontent.com/10096433/117285797-b3204380-ae68-11eb-88af-9c25db60b005.png">

**Comment by zoontek** [comment]
@Luckygirlllll `--legacy-peer-deps` cannot bring this issue, it's just about silencing a warning.
Did you perform a `pod install` / clean the build caches before running your app again?

**Comment by Luckygirlllll** [comment]
@zoontek Yes, IOS is working correctly, the problem is only with Android.

**Comment by zoontek** [comment]
@Luckygirlllll OK, similarly, did you cleaned the Gradle cache? (check https://github.com/pmadruga/react-native-clean-project)

**Comment by Luckygirlllll** [comment]
@zoontek yes, multiple times.

**Comment by zoontek** [comment]
@Luckygirlllll Ok, then publish a reproduction repository because we are not able to reproduce this.

**Comment by mikehardy** [comment]
This is always and forever an auto-linking problem. Perhaps build.gradle is missing the call out to the react-native CLI gradle. It's definitely not a problem with the module, it's a problem with the project every single time

https://github.com/facebook/react-native/blob/1e39d8b82985849de15a8a744cefddb657bb5861/template/android/app/build.gradle#L84

**Comment by Qazafi-Dev** [comment]
i am getting this error in android i tried to link qrcode scanner manually but it didnot i am using react native cli

**Comment by ahsan-abrar** [comment]
> i am getting this error in android i tried to link qrcode scanner manually but it didnot i am using react native cli

did you find a solution getting the same while using qrcode scanner.

**Comment by rajAmukhliS** [comment]
mock `react-native-permissions` in `jest.setup.js` file as shown below

```
jest.mock('react-native-permissions', () =>
  require('react-native-permissions/mock'),
);
```

**Comment by yashpokar** [comment]
Following https://github.com/zoontek/react-native-permissions#ios helped me solve this problem even when I was not working with IOS, just wanted to test in android device I did this which solved my problem.

```swift
target 'YourAwesomeProject' do

  # …

  permissions_path = '../node_modules/react-native-permissions/ios'

  # Keep only permissions which you really want in production
  pod 'Permission-AppTrackingTransparency', :path => "#{permissions_path}/AppTrackingTransparency"
  pod 'Permission-BluetoothPeripheral', :path => "#{permissions_path}/BluetoothPeripheral"
  pod 'Permission-Calendars', :path => "#{permissions_path}/Calendars"
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-Contacts', :path => "#{permissions_path}/Contacts"
  pod 'Permission-FaceID', :path => "#{permissions_path}/FaceID"
  pod 'Permission-LocationAccuracy', :path => "#{permissions_path}/LocationAccuracy"
  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
  pod 'Permission-MediaLibrary', :path => "#{permissions_path}/MediaLibrary"
  pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone"
  pod 'Permission-Motion', :path => "#{permissions_path}/Motion"
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
  pod 'Permission-PhotoLibraryAddOnly', :path => "#{permissions_path}/PhotoLibraryAddOnly"
  pod 'Permission-Reminders', :path => "#{permissions_path}/Reminders"
  pod 'Permission-Siri', :path => "#{permissions_path}/Siri"
  pod 'Permission-SpeechRecognition', :path => "#{permissions_path}/SpeechRecognition"
  pod 'Permission-StoreKit', :path => "#{permissions_path}/StoreKit"

end
```

**Comment by KeyG94** [comment]
My issue ressolved by adding both 

Note, I am using it with qrcode-scanner dependency

`jest.mock('react-native-qrcode-scanner', () => jest.fn());`

and

```
jest.mock('react-native-permissions', () =>
  require('react-native-permissions/mock'),
);
```

**Comment by Yandamuri** [comment]
> This is always and forever an auto-linking problem. Perhaps build.gradle is missing the call out to the react-native CLI gradle. It's definitely not a problem with the module, it's a problem with the project every single time
> 
> https://github.com/facebook/react-native/blob/1e39d8b82985849de15a8a744cefddb657bb5861/template/android/app/build.gradle#L84

Do you mean the above mentioned line is missing in the projects where this issue is occurring?

**Comment by mikehardy** [comment]
@Yandamuri it *usually* is. The general solution is: create a new react-native project from scratch (`npx react-native init SimpleTestProject && cd SimpleTestProject` then add a module (`yarn add react-native-permissions`). Now compare the files in that project with yours and find the auto-linking error.

**Comment by grantdevon** [comment]
I am having the same issue on android

**Comment by Manouli** [comment]
![image](https://user-images.githubusercontent.com/6332957/225886759-3a807c9e-a577-4f54-b12a-9f4eda5a8fa3.png)


I get this error only when codepushing!

**Comment by umutlaguler** [comment]
> react-native-permissions: NativeModule.RNPermissions is null. To fix this issue try these steps
> 
> Getting this error even without expo
> 
> React Native Version: "react-native": "^0.59.8", "react-native-permissions": "^2.0.9",
> 
> Installed and followed manual linking instructions.Still getting the same error.

did you find any solution I am still getting this same error please help me!!

**Comment by umutlaguler** [comment]
> My issue ressolved by adding both
> 
> Note, I am using it with qrcode-scanner dependency
> 
> `jest.mock('react-native-qrcode-scanner', () => jest.fn());`
> 
> and
> 
> ```
> jest.mock('react-native-permissions', () =>
>   require('react-native-permissions/mock'),
> );
> ```

You have added both but where ?? Please answer me! It's TOO important for me

**Comment by rajAmukhliS** [comment]
>in jest.setup.js file

**Comment by rajAmukhliS** [comment]
in jest.setup.js file bro

**Comment by harendrasaini01** [comment]
> jest.mock('react-native-permissions', () =>
>   require('react-native-permissions/mock'),
> );

Where can I add in the react-native project ....

**Comment by joshuayoes** [comment]
For those working with this library in a monorepo, a better strategy is to use

```js
// jest.config.js
module.exports = {
  // ... other config
  moduleNameMapper: {
    'react-native-permissions': '<rootDir>/node_modules/react-native-permissions/mock',
  },
};
```

This will ensure that you use the mock even if `react-native-permissions` is installed in other workspace node_modules

**Comment by mustapha-ghlissi** [comment]
To resolve this issue, you need just to downgrade the package version to a previous version: 

`yarn add react-native-permissions@3.7.3`

**Comment by zoontek** [comment]
@mustapha-ghlissi This is not a valid solution.

**Comment by mustapha-ghlissi** [comment]
@zoontek  I tried it, it works fine, else which one is the official ?

**Comment by zoontek** [comment]
@mustapha-ghlissi The usual one: Clearing your build cache (or mock the module if it's in tests). This has been reported a lot of times and the answer has always been the same: https://github.com/zoontek/react-native-permissions/issues?q=is%3Aissue+RNPermissions+is+null 😕

Just try with a fresh setup. Create a new app, add `react-native-permissions`. If it doesn't occur, that means that it's not an issue with the library and that it is fine (and that you should) use the latest version.

**Comment by julianD77** [comment]
We had this issue on our project recently, and the solution for us was to do a **clean clone** of our repo to a new directory. The `RNPermissions is null error` that was perviously continually occurring for us on one specific developer's build environment (despite many cleans of build caches, node_module etc) then no longer occurred. 

So for people running into the same problem where the library integration seems to match the details in the doc, and you have already tried cleaning all caches and intermediate build files (https://github.com/pmadruga/react-native-clean-project mentioned above looks useful for this) then it seems worthwhile to clone your project to a new directory and see if that gets you beyond this issue.
