### ISSUE TITLE
Example File error on iOS

### ISSUE THREAD

**Issue by dangnelson** [zoontek/react-native-permissions#43]
Getting the following build error for mipmap-mdli on iOS

`Argument list too long: recursive header expansion failed at` ... `/node_modules/react-native-permissions/Example/android/app/src/main/res/mipmap-mdpi.`

If I remove the Example file everything builds correctly.

**Comment by yonahforst** [comment]
Thanks for reporting this. i just merged #54 that should fix this. Gonna close this, if it's still an issue, just reopen it
