### ISSUE TITLE
TypeError: (0 , _reactNativePermissions.check) is not a function

### ISSUE THREAD

**Issue by HamzaIkram2727** [zoontek/react-native-permissions#439]
Hi,
I imported check results and permissions from react native permissions. But all are undefined in the project scope. I know this is a problem with linking. Although react-native link react-native-permissions gives me this error "ENOENT: no such file or directory, open '../node_modules/react-native-permissions/ios/RNPermissions.xcodeproj/project.pbxproj'". So I manually linked the library as I am not using pods. Can someone please let me know what I missed. Any help will be appreciated.

**Comment by zoontek** [comment]
Closed for non-respect of the issue template.
