### ISSUE TITLE
TypeError: (0 , _reactNativePermissions.check) is not a function

### ISSUE THREAD

**Issue by HamzaIkram2727** [zoontek/react-native-permissions#440]
Hi,
I imported check results and permissions from react native permissions. But all are undefined in the project scope. I know this is a problem with linking. Although react-native link react-native-permissions gives me this error "ENOENT: no such file or directory, open '../node_modules/react-native-permissions/ios/RNPermissions.xcodeproj/project.pbxproj'". So I manually linked the library as I am not using pods. Can someone please let me know what I missed. Any help will be appreciated.

`React Native Environment Info:
    System:
      OS: macOS 10.15.1
      CPU: (8) x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
      Memory: 722.38 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 13.11.0 - ~/.nvm/versions/node/v13.11.0/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.13.7 - ~/.nvm/versions/node/v13.11.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
      Android SDK:
        API Levels: 23, 24, 25, 26, 27, 28
        Build Tools: 23.0.1, 25.0.3, 27.0.3, 28.0.2, 28.0.3
        System Images: android-27 | Intel x86 Atom_64, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5977832
      Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.8.6 => 16.8.6 
      react-native: ^0.59.2 => 0.59.10 
    npmGlobalPackages:
      react-native-cli: 2.0.1`

**Comment by zoontek** [comment]
👉 If you are using Expo, this package will not work.
👉 Version 1.x is not supported anymore.

This library require CocoaPods to install permission handlers on iOS (by linking just the core, you can't request anything - it's a safety to avoid your app being refused when you submitting it to the App store).

This looks like a bad install. Please check duplicate issues: https://github.com/react-native-community/react-native-permissions/issues?q=is%3Aissue+RNPermissions+null+
