### ISSUE TITLE
[TypeError: undefined is not an object (evaluating 'RNP.available.includes')]

### ISSUE THREAD

**Issue by dev-intellisoft** [zoontek/react-native-permissions#442]
Hello everyone I am getting an error while trying to run this piece of code in my project 

```js
getCameraRollPermission = async () => {
        try
        {
            let permission;
            if (isAndroid()) {
                permission = await this.getPermission(
                    Permissions.PERMISSIONS.ANDROID.READ_EXTERNAL_STORAGE
                );
            } else {
                permission = await this.getPermission(
                    Permissions.PERMISSIONS.IOS.PHOTO_LIBRARY
                );
            }
            return permission === Permissions.RESULTS.GRANTED;
        }
        catch ( e )
        {
            console.log ( `---->`, e )
        }
    };
```

The error message says 
[TypeError: undefined is not an object (evaluating 'RNP.available.includes')]

 "react-native-app-settings": "^2.0.1",
"react-native": "0.61.2",

node v12.10.0

Some tips?

**Comment by zoontek** [comment]
@dev-intellisoft What is the `getPermission` function? You didn't provide a lot of context… next time try to be a bit more explicit please.

If you just updated the library version, be sure you cleaned the project : `cd android && ./gradlew clean`

**Comment by zoontek** [comment]
Closed due to inactivity.

**Comment by ericmatte** [comment]
I also get this error sometime after upgrading to version `2.1.5` when doing
```js
await Permissions.check(Platform.OS === 'ios' ? Permissions.PERMISSIONS.IOS.CAMERA : Permissions.PERMISSIONS.ANDROID.CAMERA)
```
on an iOS simulator.

This error does not happen on version `2.0.8`.

**Comment by lakjeewa-rightapps** [comment]
If you updated this package do these,

Try deleting all the node modules - >clear npm cache - > install node modules again -> do  'npx react-native start --reset-cache' -> then do an 'npm run anrdroid' or 'npm run ios'

Worked for me!!!

**Comment by chenop** [comment]
Still got this issue in android only, ios is ok.

**Comment by mikehardy** [comment]
Project integration issue of some sort, these "native module is null" ones always are.
Either JS bundle doesn't match native code (maybe codepush is in play?)
Or you have some cached build artifacts or something
npx react-native-clean-project perhaps

**Comment by chenop** [comment]
Thanks @mikehardy for replying - npx react-native-clean-project did not resolve the issue :-(
