### ISSUE TITLE
Returns Block in android even if the permission is granted in the settings

### ISSUE THREAD

**Issue by eldareini** [zoontek/react-native-permissions#445]
I want to send the user to the settings if he block the permission so he will activate the permission from there. it works great on IOS, but in android, after I blocked the permission and granted the permission in the settings if I check the permission, I get "blocked" instead of "granted".
What should I do?

**Comment by zoontek** [comment]
@eldareini Please fill the [issue template](https://github.com/react-native-community/.github/blob/master/.github/ISSUE_TEMPLATE/bug_report.md). I'm not supposed to guess what's your environment.

**Comment by eldareini** [comment]
@zoontek  
sorry, you are right

System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 571.56 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 13.11.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.13.7 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: ^0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1

Library version: 2.1.0

**Comment by zoontek** [comment]
@eldareini Thanks. I published a [fix](https://github.com/react-native-community/react-native-permissions/commit/5f0f576da7a89fd3f9bf62f2b43a511c1b67b69d), as version [2.1.2](https://github.com/react-native-community/react-native-permissions/releases/tag/2.1.2)

Please update and check if it solves your issue 🙂

**Comment by eldareini** [comment]
@zoontek Thanks, that fixes the issue 🙂
