### ISSUE TITLE
TypeError: (0, _reactNativePermissions.checkMultiple) is not a function

### ISSUE THREAD

**Issue by wootwoot1234** [zoontek/react-native-permissions#447]
I'm getting the following error.  

I've deleted my DerivedData folder, node_modules, re-installed pods, deleted the app and rebuilt it but still get this error.  I have the following version installed:

`"react-native-permissions": "^2.1.2"`

I'm importing `checkMultiple` like this:

`import {openSettings, PERMISSIONS, checkMultiple} from "react-native-permissions";`

What am I doing wrong?

```
TypeError: (0, _reactNativePermissions.checkMultiple) is not a function. (In '(0, _reactNativePermissions.checkMultiple)([_reactNativePermissions.PERMISSIONS.IOS.CAMERA, _reactNativePermissions.PERMISSIONS.IOS.PHOTO_LIBRARY])', '(0, _reactNativePermissions.checkMultiple)' is undefined)

onload
    Viewer.js:183:39
tryCatch
    runtime.js:45:36
invoke
    runtime.js:274:29
tryCatch
    runtime.js:45:36
invoke
    runtime.js:135:27
PromiseImpl$argument_0
    runtime.js:170:16
tryCallTwo
    core.js:45:6
doResolve
    core.js:200:22
Promise
    core.js:66:11
callInvokeWithMethodAndArg
    runtime.js:169:15
enqueue
    runtime.js:192:38
exports.async
    runtime.js:219:8
onload
    Viewer.js:177:8
useEffect$argument_0
    Viewer.js:197:14
commitHookEffectList
    ReactNativeRenderer-dev.js:18008:31
commitPassiveHookEffects
    ReactNativeRenderer-dev.js:18061:28
invokeGuardedCallbackImpl
    ReactNativeRenderer-dev.js:286:4
invokeGuardedCallback
    ReactNativeRenderer-dev.js:497:2
flushPassiveEffectsImpl
    ReactNativeRenderer-dev.js:21577:27
unstable_runWithPriority
    scheduler.development.js:818:23
scheduleCallback$argument_1
    ReactNativeRenderer-dev.js:21431:29
workLoop
    scheduler.development.js:762:41
flushWork
    scheduler.development.js:717:23
_flushCallback
    scheduler.development.js:56:17
_callTimer
    JSTimers.js:135:14
callTimers
    JSTimers.js:387:16
__callFunction
    MessageQueue.js:425:19
__guard$argument_0
    MessageQueue.js:112:6
__guard
    MessageQueue.js:373:10
callFunctionReturnFlushedQueue
    MessageQueue.js:111:4
callFunctionReturnFlushedQueue
    [native code]:0
```

**Comment by zoontek** [comment]
@wootwoot1234 Please respect the issue template. I need to know on which platform.

**Comment by wootwoot1234** [comment]
I’m sorry. I didn’t see a template. I’m using iOS.

**Comment by zoontek** [comment]
The template is [the comment written inside the textarea](https://raw.githubusercontent.com/react-native-community/.github/master/.github/ISSUE_TEMPLATE/bug_report.md) when you create an issue.

Try cleaning your bundler cache. Run metro with `react-native start --reset-cache`

**Comment by wootwoot1234** [comment]
I don’t use the `react-native` command-line script. I use `npx react-native run-ios` to run the app but `watchman watch-del-all` fixed the issue.  Sorry for the trouble and thanks for the help.  I'll use the template next time.  :)

**Comment by zoontek** [comment]
@wootwoot1234 RN apps have multiples caches layers (metro, watchman, Xcode, Gradle, etc.). I recommend setting up [react-native-clean-project](https://github.com/pmadruga/react-native-clean-project) in your project, it will avoid you a lot of headaches in the future 🙂

**Comment by wootwoot1234** [comment]
Installing it now.  Thanks for the tip.  I took a 3-year break from developing apps so I really appreciate the advice.  Let me know if you have any other tips.
