### ISSUE TITLE
WRITE_EXTERNAL_STORAGE always return blocked

### ISSUE THREAD

**Issue by amorino** [zoontek/react-native-permissions#448]
# Bug

Bug on Android.

Installed the library, asked for WRITE_EXTERNAL_STORAGE on Android and accept the permission. The result returned "blocked", and even when I go to Settings and check the App Permission there, the permission is allowed, the RN App always return blocked.

## Environment info

`react-native info` output:

```bash
React Native Environment Info:
    System:
      OS: macOS 10.15.3
      CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
      Memory: 805.23 MB / 32.00 GB
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 8.11.4 - ~/.nvm/versions/node/v8.11.4/bin/node
      Yarn: 1.22.0 - /usr/local/bin/yarn
      npm: 5.6.0 - ~/.nvm/versions/node/v8.11.4/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
      Android SDK:
        API Levels: 23, 27, 28, 29
        Build Tools: 28.0.3, 29.0.2
        System Images: android-29 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.4/11E146 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.10 => 0.59.10
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

Library version: 2.1.2

## Steps To Reproduce

1. Installed the plugin
2. Manual linking it
3. Check permission WRITE_EXTERNAL_STORAGE
4. Ask for permission WRITE_EXTERNAL_STORAGE
5. Accept permission
6. Permission always return blocked
...

Describe what you expected to happen:

1. After accepting permission, return granted.

## Reproducible sample code

```
const permission = await request(PERMISSIONS.ANDROID.WRITE_EXTERNAL_STORAGE);
console.warn(permission); // Always return blocked, even the fist time that the dialog is accepted
```

**Comment by zoontek** [comment]
@amorino You didn't mention [this step](https://github.com/react-native-community/react-native-permissions#android). Did you respect it? If you forgot, you'll need to uninstall the app to reset the `blocked` permissions list.

Edit: Please post your AndroidManifest.xml

**Comment by LaVey1337** [comment]
I have the same issue

**Comment by LaVey1337** [comment]
Hi, I've solved this problem.

` <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" tools:node="replace"/>`

**Comment by lesydat** [comment]
> Hi, I've solved this problem.
> 
> ` <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" tools:node="replace"/>`

I can't build android app if add tools:node="replace"

**Comment by chenop** [comment]
Stumble this issue in Galaxy emulator SDK 33.
Already have WRITE_EXTERNAL_STORAGE in my AndroidManifest.xml

What could be the issue?

```
const granted = await request(
			PERMISSIONS.ANDROID.WRITE_EXTERNAL_STORAGE,
			{
				title,
				message
			},
		);
		
		console.log({ granted }); // --> granted: "blocked"
		return (granted === RESULTS.GRANTED);
```

**Comment by chenop** [comment]
Here is how I solved the isse - basically for sdk 33 and above - no need to ask for permission:

```
import { PERMISSIONS, request, RESULTS } from 'react-native-permissions';
import { Platform } from 'react-native';

const androidSDKVersion = Platform.Version;
const isAndroid13OrHigher = androidSDKVersion >= 33;

export const requestStoragePermission = async () => {
	if (Platform.OS === 'ios')
		return true;

	if (isAndroid13OrHigher)
		return true;
	
	try {
		const granted = await request(
			PERMISSIONS.ANDROID.WRITE_EXTERNAL_STORAGE,
			{
				title,
				message
			},
		);

		return (granted === RESULTS.GRANTED);
	} catch (err) {
		console.warn(err);
		return false;
	}
};

```
