### ISSUE TITLE
How to Activate GPS Icon after generating permeation?

### ISSUE THREAD

**Issue by anastely** [zoontek/react-native-permissions#451]
I want to appear GPS Icon on the status bar when I open app or screen that's contain Map, So I add a function that asks a user at the first time to allow Location permission and it's work very well and I can get Lat/Long but GPS "Location" Icon did not activate so how can I force an app to activate this icon?

[screenshot](https://i.imgur.com/u7t0cxL.png)

Code
```

import {PERMISSIONS, request} from 'react-native-permissions'; // v 2.1.2


  askForLocation = () => {
    request(PERMISSIONS.ANDROID.ACCESS_FINE_LOCATION)
      .then(() => this.getLocation())
      .catch(err => console.error(err));
  };




  getLocation = async () => {
    const {companyLocation, Domain} = this.props.navigation.state.params;
    Geolocation.getCurrentPosition(
      position => {
        this.setState(
          {
            mapData: {
              latitude: position.coords.latitude,
              longitude: position.coords.longitude,
              latitudeDelta: 0.015,
              longitudeDelta: 0.0121,
            },
            markerData: {
              latitude: position.coords.latitude,
              longitude: position.coords.longitude,
              latitudeDelta: 0.015,
              longitudeDelta: 0.0121,
            },

            error: null,
          },
          () => {
            let {
              latitudeDelta,
              longitudeDelta,
              ...userLocation
            } = this.state.mapData;

            let howFar = Math.round(haversine(userLocation, companyLocation));
            howFar > Domain
              ? (alert('Sorry, We not work in your area.'),
                this.setState({next: false}))
              : null;
          },
        );
      },
      error => this.setState({error: error.message}),
    );
    this.watchID = Geolocation.watchPosition(
      position => {
        const latitude = position.coords.latitude;
        const longitude = position.coords.longitude;
        this.setState({
          latitude,
          longitude,
          latitudeDelta: 0.015,
          longitudeDelta: 0.0121,
        });
      },
      err => {
        console.log('getCurrentPosition.error', err);
      },
      {
        enableHighAccuracy: true,
        timeout: 8000,
        maximumAge: 1000,
      },
    );
  };
```

**Comment by zoontek** [comment]
@anastely It's not because the user give you the permission to use `FINE_LOCATION` that you will have complete control over the GPS (You only have the right to consume precise location coordinates when the user want to activate its GPS)

**Comment by anastely** [comment]
@zoontek  Hmm, So, in this case, i can't active the GPS icon?

**Comment by zoontek** [comment]
@anastely Fortunately, no.

**Comment by anastely** [comment]
Fortunately! Why?

**Comment by zoontek** [comment]
@anastely Because it would be terrible if every application you use could enable your GPS programmaticaly to know precisely where you are, when they want.

**Comment by mikehardy** [comment]
I think this is backwards, if I understand correctly you *want* the GPS icon active? As in you are trying to communicate to the user that you use GPS so it's obvious? That's not a bad thing, you want the system to let the user know if you are using GPS. However that is controlled by the system, it will show up when you fetch a location. So if you want the icon, ask the system for a location and it should show up

**Comment by zoontek** [comment]
@mikehardy If you look at the posted screenshot, it's not the location consumption icon in the status bar (which appears automatically when an app requests your fine location), but the GPS functionality toggle (which is not togglable programmatically)

**Comment by anastely** [comment]
As you say it should appear automatically when request location so it does not appear with me after request! 

But when I active the GPS icon manually I can see my app and location icon in the status bar well! 

Check this screenshots, please 
1-
https://imgur.com/xwMl7Vn

2-
https://imgur.com/QPyVFi1

**Comment by zoontek** [comment]
@alvelig That's because this icon only appears when an app tries to obtain your precise coordinates (`FINE_LOCATION`).

If you don't toggle your GPS on, your phone cannot have these precise coordinates, only coarse ones: In this case, the status bar icon will not appear and your app will receive coordinates that can be approximate. That's normal, and not tied to the permission system.

It does not appear automatically when requesting location, it appears when:
1) The user accepted the fine location request
2) Your app listen to this fine location
3) The phone GPS is turned on (if not, your app will receive approximate coordinates and the user will not be warn about it because it does not use as much battery as the GPS does)

**Comment by anastely** [comment]
@zoontek 
Well, just to prevent a misunderstanding 

> 1. The User accepted the fine location request

```
askForLocation = () => {
request(PERMISSIONS.ANDROID.ACCESS_FINE_LOCATION)
      .then(() => this.getLocation())
      .catch(err => console.error(err));
  };
```

In this case, I request it right, "imagine user accepted the request"?
So it's should appear right?

**Comment by zoontek** [comment]
@anastely Not necessarily.

It should appear **ONLY** if you listen for location (`Geolocation.getCurrentPosition` -> will appear once / `Geolocation.watchPosition` -> will appear at interval) **AND** if the user has turned his GPS ON.

**Comment by yasicmd** [comment]
https://github.com/Richou/react-native-android-location-enabler
