### ISSUE TITLE
[Android] Location permission check does not provide the proper response on location services disabled

### ISSUE THREAD

**Issue by federicomiralles** [zoontek/react-native-permissions#452]
d# Bug
After granting the location permission whenever the location services are disabled, the check method keeps returning **granted** instead of the correct one which according to [Android flow](https://github.com/react-native-community/react-native-permissions#android-flow), **unavailable**.

Library version: **2.1.1**

**Comment by zoontek** [comment]
Duplicate of https://github.com/react-native-community/react-native-permissions/issues/365
I'm closing this one, reopen the other since it's more detailed.

**Comment by HansBouwmeester** [comment]
This bug is still there in v3.0.3. And #365 was closed by a bot.

**Comment by mikehardy** [comment]
@Gra55h0pper it's not a bug in the library, it's not a permission, it doesn't belong here
what you want is here https://github.com/react-native-device-info/react-native-device-info#getAvailableLocationProviders

**Comment by HansBouwmeester** [comment]
@mikehardy Thanks for the pointer. I'm using react-native-device already so then it'll be easy to detect whether whether the user turned the location switch to 'Off' in the system settings.

I'm not sure I understand/agree it doesn't belong here though?

**Comment by mikehardy** [comment]
It's not a permission
It is a device setting
So it is in the right place

**Comment by HansBouwmeester** [comment]
To have permissions to be granted to services that are unavailable doesn’t make sense to me. 
The way I look at this switch is that when it’s off, the location permission should not be considered *available* in the context of the flows in the manual. Thus, the check should return RESULTS.UNAVAILABLE. Quoting from the manual this would mean: “This feature is not available (on this device / in this context).”

**Comment by mikehardy** [comment]
But they operate independently, and typically if a permission is removed from your app, your app restarts whereas if the device GPS status changes, nothing happens to your app. I see your point of view but I at least believe it conflates different things, combining them in a way that destroys useful information with regard to the actual state of the system. I personally wouldn't work on it and would feel - as a fellow consumer of this library - irritated if the behavior changed to merge device location status with app location permission status.

**Comment by HansBouwmeester** [comment]
I see your points and can certainly live with that. It may be a good idea for the documentation to explain that ‘GRANTED’ does not imply ‘AVAILABLE’ and give the pointer to react-native-device-info.

**Comment by mikehardy** [comment]
> It may be a good idea for the documentation to explain that ‘GRANTED’ does not imply ‘AVAILABLE’ and give the pointer to react-native-device-info.

Sure! Hit that pencil / edit button on the docs - this repo merges sensible PRs at great speed
