### ISSUE TITLE
Throws checking PERMISSIONS.IOS.FACE_ID if face id is locked out

### ISSUE THREAD

**Issue by java-james** [zoontek/react-native-permissions#453]
# Bug

Checking `PERMISSIONS.IOS.FACE_ID` after too many face id attempts throws error with error.code "-8". I would expect this to return as `unavailable` or similar. 

## Environment info

`react-native info` output:

```bash
info Fetching system and libraries information...
System:
    OS: macOS 10.15.3
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 5.09 GB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.19.0 - ~/.nvm/versions/node/v10.19.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v10.19.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5977832
    Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.4 => 0.61.4
```

Library version: 2.0.10

## Steps To Reproduce

1. Try face id incorrectly until user is locked out
2. Call `check(PERMISSIONS.IOS.FACE_ID)`

Describe what you expected to happen:

1. A status of the permission
2. Error is thrown with error.code of "-8"

## Reproducible sample code

```
const faceIdPermission = Platform.select({
  ios: PERMISSIONS.IOS.FACE_ID,
});
export const testCheckPermission = async (): Promise<PermissionStatus> => {
  // Throws if face id is locked out
  return await check(faceIdPermission);
};
```

**Comment by zoontek** [comment]
I published a [new version](https://github.com/react-native-community/react-native-permissions/releases/tag/2.1.3) with a fix. Can you check it?

**Comment by java-james** [comment]
Thanks for the quick reply. Will get back to you shortly re fix
