### ISSUE TITLE
Permission popup does not appear when requesting microphone permission on iOS 10

### ISSUE THREAD

**Issue by alfonsocj** [zoontek/react-native-permissions#455]
# Bug
Trying to request permission "PERMISSIONS.IOS.MICROPHONE" on iOS 10.3.1 does not trigger the permission popup, even when the permission === RESULTS.DENIED.

## Environment info

`react-native info` output:

```bash
System:
    OS: macOS 10.15.2
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 79.58 MB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.11.3 - ~/.nvm/versions/node/v10.16.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.7.5 - /Users/fonz/.rvm/gems/ruby-2.4.1/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 17, 22, 23, 25, 26, 27, 28, 29
      Build Tools: 23.0.1, 23.0.2, 25.0.0, 25.0.2, 26.0.1, 26.0.2, 27.0.3, 28.0.3, 29.0.0, 29.0.2
      System Images: android-17 | Intel x86 Atom, android-17 | Google APIs Intel x86 Atom, android-18 | Intel x86 Atom, android-19 | Intel x86 Atom, android-23 | Google APIs Intel x86 Atom, android-25 | Google APIs ARM 64 v8a, android-25 | Google APIs ARM EABI v7a, android-25 | Google APIs Intel x86 Atom, android-25 | Google Play Intel x86 Atom, android-26 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6308749
    Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_152 - /usr/bin/javac
    Python: 3.7.7 - /usr/local/opt/python/libexec/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 2.1.2

## Steps To Reproduce

on iOS 10.3.1,

1. `const permissionResult = await request(permission);`
2. permissionResult is DENIED

Describe what you expected to happen:
1. `const permissionResult = await request(permission);`
2. Popup appears asking the user for Mic permission
3. permissionResult is GRANTED or BLOCKED depending on the user's feedback

**Comment by mikehardy** [comment]
This may not help you at all, or you may have already tried it, but are you certain you've started from a clean slate with regard to permissions? https://developer.apple.com/library/archive/qa/qa1906/_index.html

**Comment by zoontek** [comment]
Do you, by any chance, using only a simulator? If my memory is good, microphone permission is broken on iOS 10 w. simulator (but fortunately, not on device)

**Comment by zoontek** [comment]
See duplicate issue: https://github.com/react-native-community/react-native-permissions/issues/58

**Comment by alfonsocj** [comment]
@zoontek you might be right. I’m using a simulator. I do not have an actual device with iOS 10.

**Comment by zoontek** [comment]
I reassure you, I have one (an iPhone 5C) and everything works correctly on device 🙂

**Comment by heartdisappointing** [comment]
> This may not help you at all, or you may have already tried it, but are you certain you've started from a clean slate with regard to permissions? https://developer.apple.com/library/archive/qa/qa1906/_index.html





https://opencodes.space/questions/unlocking-the-power-of-your-devices-microphone-with
