### ISSUE TITLE
Requesting Bluetooth permissions always returns "denied"

### ISSUE THREAD

**Issue by daveyjones** [zoontek/react-native-permissions#458]
# Bug

Requesting Bluetooth permissions always returns "denied" on an iPad mini 2 running iOS 12.4.6 (the highest iOS version currently available for this device). The user is never prompted for permissions.

## Environment info

`react-native info` output:

```bash
System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz
    Memory: 1.40 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.14.1 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 25, 26, 28, 29
      Build Tools: 25.0.0, 26.0.2, 28.0.3, 29.0.2
      System Images: android-28 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6308749
    Xcode: 11.4/11E146 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_222 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 2.1.4

## Steps To Reproduce

1. Request Bluetooth permissions
2. The returned result is "denied"

Describe what you expected to happen:

1. Request Bluetooth permissions
2. The user is prompted to grant Bluetooth permissions
3. The returned response is either "granted" or "blocked"

## Reproducible sample code

```js
request(PERMISSIONS.IOS.BLUETOOTH_PERIPHERAL).then(result => {
    console.warn(result)
})
```

**Comment by daveyjones** [comment]
My workaround is to check the iOS version before making the request (since Bluetooth permissions were not required prior to iOS 13), but it seems like this is something that should be handled internally by the library.
```js
if (Platform.OS == "ios" && parseInt(Platform.Version, 10) > 12) {
    request(PERMISSIONS.IOS.BLUETOOTH_PERIPHERAL).then(result => {
        console.warn(result)
    })
} else {
    console.warn("Permissions not required.")
}
```

**Comment by zoontek** [comment]
@daveyjones Hi. Are you trying to request Bluetooth Peripheral permission or Bluetooth permission in general?
On iOS <= 12, the second one doesn't exist (see [CBManager documentation](https://developer.apple.com/documentation/corebluetooth/cbmanager/3377595-authorization), it's a new API on iOS 13+), so we have to use [CBPeripheralManager](https://developer.apple.com/documentation/corebluetooth/cbperipheralmanager/1616317-authorizationstatus), which will return `denied` if you don't add the capability:

<img width="435" alt="Screenshot 2020-05-03 at 10 57 56" src="https://user-images.githubusercontent.com/1902323/80910029-2ca0c580-8d2d-11ea-8003-ce1821eea3a5.png">

Which correspond to:

<img width="358" alt="Screenshot 2020-05-03 at 10 59 09" src="https://user-images.githubusercontent.com/1902323/80910039-3a564b00-8d2d-11ea-9aa5-942f640e61cd.png">

**Comment by daveyjones** [comment]
@zoontek Thanks for the response! This is good to know.
