### ISSUE TITLE
Android ':react-native-permissions:bundleLibCompileDebug'

### ISSUE THREAD

**Issue by keremcubuk** [zoontek/react-native-permissions#461]
# Question

I'm getting an error when try to **`react-native run-android`**. I tried these steps.
- `$ npm install --save react-native-permissions`
- I tried with `npx jetifier` and without `npx-jetifier`
- `cd android && ./gradlew clean`
- Gradle Sync
- `react-native run-android` or run from Android Studio

But still get the following error.

![Screen Shot 2020-05-06 at 11 20 18](https://user-images.githubusercontent.com/29661833/81153456-9c13f080-8f8b-11ea-8102-daa591bd9291.png)

```javascript
node_modules/react-native-permissions/android/build/intermediates/compile_only_not_namespaced_r_class_jar/debug/R.jar
```

## Environment Info

```shell
System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Memory: 2.38 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29
      Build Tools: 26.0.2, 28.0.0, 28.0.3, 29.0.0
      System Images: android-24 | Google Play Intel x86 Atom, android-26 | Google Play Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: 20.0.5594570
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6308749
    Xcode: 11.0/11A420a - /usr/bin/xcodebuild
  npmPackages:
    react: ^16.13.1 => 16.13.1 
    react-native: 0.61.5 => 0.61.5 
```

**Comment by zoontek** [comment]
@keremcubuk Hi. Did you perform a `rm -rf android/app/build`?

**Comment by keremcubuk** [comment]
Yes. I did. I removed all old build and cache files. @zoontek

**Comment by zoontek** [comment]
You only said `./gradlew clean` which does not perform the same tasks. That's why I asked.

**Comment by keremcubuk** [comment]
Ok. No problem

**Comment by keremcubuk** [comment]
Hi, I **solve the problem** with the remove all of these file. If I don't remove ***.iml** files. It is not works.

1.  Close Android Studio
2. Remove react-native-permissions
3. Remove all of these file under **Android** folder:
    ```
    myApp
    └── android
        ├── .gradle
        └── .idea
        └── myApp.iml
        └── build
        │
        └── app
            └── build
            └── app.iml
    ```
4. Install react-native-permissions
   ```shell
   npm install react-native-permissions --save
   ```
5. GradleSync & Build Again
6. Run
