### ISSUE TITLE
Requesting IOS.LOCATION_ALWAYS only enables while using app

### ISSUE THREAD

**Issue by lukemcgregor** [zoontek/react-native-permissions#462]
# Bug

When I request LOCATION_ALWAYS on iOS the dialog displayed doesn't have the option of always. Instead it acts as if I have requested LOCATION_WHEN_IN_USE.

## Environment info

`react-native info` output:

```bash
System:
    OS: macOS 10.15.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 199.14 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.13.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 28, 29
      Build Tools: 28.0.3, 29.0.3
      System Images: android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_242 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: x.x.x

## Steps To Reproduce

1. npx react-native init PermissionsPlayground
2. yarn add react-native-permissions
3. pod file as per readme (eg all permissions)
4. Info.plist
```
	<key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
	<string>YOUR TEXT</string>
	<key>NSLocationAlwaysUsageDescription</key>
	<string>YOUR TEXT</string>
	<key>NSLocationWhenInUseUsageDescription</key>
	<string>YOUR TEXT</string>
```
5. `import { request, PERMISSIONS } from 'react-native-permissions';`
6. add a permissions request for LOCATION_ALWAYS in the top of the root component
   eg: 
```
const App: () => React$Node = () => {  request(PERMISSIONS.IOS.LOCATION_ALWAYS).then((res) => {
    console.log('permissions:', res);
  });

  return (
...
```
7. `cd ios && pod install && cd .. && yarn iOS`

## Expected:

A permissions prompt with an always option

## Actual:
![Simulator Screen Shot - iPhone 11 - 2020-05-07 at 15 40 19](https://user-images.githubusercontent.com/1284608/81252127-3140e300-9079-11ea-8c1a-eb8c766c2d9e.png)

**Comment by zoontek** [comment]
It's perfectly normal on iOS 13.
Later, it will ask your user "App is using your location in background, do you allow it?"

Check the Apple documentation for more informations: https://developer.apple.com/documentation/corelocation/choosing_the_location_services_authorization_to_request

You might also forget to tick "Background location updates" in your app capabilities.

![D833CF08-84E6-4473-9BBD-5E4632D21B68](https://user-images.githubusercontent.com/1902323/81263683-6715a580-9040-11ea-8034-56da4f5b15a4.png)

**Comment by lukemcgregor** [comment]
Thanks @zoontek 

My demo app didn't have that ticked (real one did though) so I changed it but it still prompts the same.

The second prompt was the behaviour I was hoping to avoid if possible. I wanted the prompt to show in conjunction with the user turning tracking mode on not at some time later as a prompt without context when the app isn't even in foreground. It sounds like this isn't supported in iOS which is a shame.

**Comment by zoontek** [comment]
This prompt is normal and impossible to avoid. It's a privacy change on iOS 13+.
