### ISSUE TITLE
iOS "Location Always" returns unavailable always in the real device

### ISSUE THREAD

**Issue by samitha9125** [zoontek/react-native-permissions#463]
# Bug report

## Summary
iOS device (iPhone 6s) returns unavailable for "Location Always" all the time.
## Environment info

System:
    OS: macOS 10.15.4
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 985.29 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.11.4 - /usr/local/bin/node
    npm: 6.14.2 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 26.0.2, 26.0.3, 27.0.3, 28.0.3
      System Images: android-22 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom, android-26 | Google Play Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6308749
    Xcode: 11.3/11C29 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    create-react-native-module: 0.16.0
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7

Library version: 2.1.4

## Steps to reproduce
const result = await check(PERMISSIONS.IOS.LOCATION_ALWAYS).then(results => results);
console.log(result);

Describe what you expected to happen:

console.log should return either "denied" or "granted". But it returns "unavailable". So I requested Location_when_in_use and it worked fine. Then again requested LOCATION_ALWAYS and again it showed "unavailable". So I manually changed permissions to Always in settings and tried to check locations again and console log printed "unavailable" again.

Then I downgrade the library version to 2.0.10 and check again. It started to work fine.

Seems like there is an issue with 2.1.4 version or some versions from 2.0.10. Also that did not work with checkMultiple too.

**Comment by zoontek** [comment]
@samitha9125 Hi. Are you sure you added background location update capability? It makes no sense to ask for `LOCATION_ALWAYS` if it's not enabled.

![D95A333A-FCBC-40A3-9314-B7886FF572AF](https://user-images.githubusercontent.com/1902323/82130496-1fbfaf80-97cc-11ea-9770-79862c6b2c98.png)

**Comment by samitha9125** [comment]
@zoontek hi. Yes I did. It worked fine(react-native-permissions 2.1.4)on the Simulator but not in the real device. So I downgraded the version to 2.0.10 and everything started to work fine.

**Comment by zoontek** [comment]
This is strange since there are absolutely no changes in the Location always handler or the module.ios.ts file since 2.1.0: https://github.com/react-native-community/react-native-permissions/compare/2.1.0...2.1.4

Could you submit your Podfile?

Edit: I tried on a real device (iPhone XR, iOS 13.4.1), couldn't reproduce (it return ``blocked`)
Did you tried to compile the example app to check?

**Comment by samitha9125** [comment]
@zoontek  I pasted my podfile below. Also I did not use the example app because another package that I use for background locations tracking does request these permissions if I have not requested them from the user already. that package permissions handling works without any issue for Location Always permission but react-native-permission does not. So I don't think that occurs because of a device issue.

Devices I used - iPhone 6s(13.4.1) and iPhone 11 (13.4.1)

```ruby
platform :ios, '10.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

target 'SampleApp' do
  # Pods for SampleApp
  pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'ReactCommon/jscallinvoker', :path => "../node_modules/react-native/ReactCommon"
  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  # React Native Permissions dependencies
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways.podspec"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse.podspec"

  # React Native Maps dependencies
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'

  # React Native thirdparty dependencies
  pod 'react-native-geolocation', path: '../node_modules/@react-native-community/geolocation'
  
  target 'ArakshaDriverAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  use_native_modules!
  use_unimodules!(exclude: [
    'expo-face-detector',
    'expo-constants',
    'expo-file-system',
    'expo-permissions',
    'expo-app-loader-provider',
    'unimodules-barcode-scanner-interface',
    'unimodules-camera-interface',
    'unimodules-face-detector-interface',
    'unimodules-file-system-interface',
    'unimodules-sensors-interface',
    'unimodules-task-manager-interface'
  ])
end

target 'SampleApp-tvOS' do
  # Pods for SampleApp-tvOS

  target 'SampleApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

**Comment by zoontek** [comment]
> Also I did not use the example app because another package that I use for background locations tracking does request these permissions if I have not requested them from the user already.

That's exactly why I would like you to test the example app. To ensure that it's not an incompatibility with other libs. Currently, you have two libs to handle location permission: that's not useful and dangerous. `react-native-permissions` internal state can't communicate with `react-native-geolocation` internal state.

Use one or the other, not both at the same time.

**Comment by zoontek** [comment]
I just tried with both libs (`react-native-permissions` to check / request permission, `@react-native-community/geolocation` to **only** get the position) and everything went well (on a real device).

Check the code here: https://github.com/zoontek/rn-location-permission-example/blob/master/App.js#L13

Edit: Post your `Info.plist` too.

![Image from iOS](https://user-images.githubusercontent.com/1902323/82143089-96e35b00-9841-11ea-9a88-434b6eb680e2.png)

**Comment by pawtalpet** [comment]
In my simulator too it returns "unavailable" always.

**Comment by samitha9125** [comment]
@zoontek Thank you so much for your unbelievable support. Really appreciate it. I use [background geolocation](https://github.com/mauron85/react-native-background-geolocation) to acquire user location when user is not using the app. That package itself manage permissions but only if we have not granted those permissions in advance. 
I don't like random popups of permission dialogs because that would be so annoying for a user. That's why I prefer react-native-permissions which grant the capability prior to the feature request.

My Info plist.

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>en</string>
	<key>CFBundleDisplayName</key>
	<string>$(PRODUCT_NAME)</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>$(PRODUCT_NAME)</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>$(MARKETING_VERSION)</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLName</key>
			<string>com.sample.sampleapp</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>sample-app</string>
			</array>
		</dict>
	</array>
	<key>CFBundleVersion</key>
	<string>$(CURRENT_PROJECT_VERSION)</string>
	<key>ITSAppUsesNonExemptEncryption</key>
	<false/>
	<key>LSApplicationQueriesSchemes</key>
	<array>
		<string>comgooglemaps</string>
	</array>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
		<key>NSExceptionDomains</key>
		<dict>
			<key>localhost</key>
			<dict>
				<key>NSExceptionAllowsInsecureHTTPLoads</key>
				<true/>
			</dict>
		</dict>
	</dict>
	<key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
	<string>Driver app can share your location with parents only when you are on a journy.</string>
	<key>NSLocationAlwaysUsageDescription</key>
	<string>Driver app can share your location with parents only when you are on a journy.</string>
	<key>NSLocationWhenInUseUsageDescription</key>
	<string>App easily can locate your position on map once you allow this.</string>
	<key>NSMotionUsageDescription</key>
	<string>Araksha Driver uses Motion for location optimizations.</string>
	<key>UIAppFonts</key>
	<array>
		<string>Lato-Black.ttf</string>
		<string>Lato-Bold.ttf</string>
		<string>Lato-Light.ttf</string>
		<string>Lato-Regular.ttf</string>
		<string>Roboto-Bold.ttf</string>
		<string>Roboto-Light.ttf</string>
		<string>Roboto-Medium.ttf</string>
		<string>Roboto-Regular.ttf</string>
		<string>Roboto-Thin.ttf</string>
		<string>Roboto-Italic.ttf</string>
	</array>
	<key>UIBackgroundModes</key>
	<array>
		<string>location</string>
	</array>
	<key>UILaunchStoryboardName</key>
	<string>LaunchScreen</string>
	<key>UIRequiredDeviceCapabilities</key>
	<array>
		<string>armv7</string>
	</array>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
	</array>
	<key>UIUserInterfaceStyle</key>
	<string>Light</string>
	<key>UIViewControllerBasedStatusBarAppearance</key>
	<false/>
</dict>
</plist>

```


@pawtalpet check [this issue](https://github.com/react-native-community/react-native-permissions/issues/361). It will solve your problem :)

**Comment by zoontek** [comment]
Everything seems fine in your plist. Could you try building the repro repo app on your iPhone to check if you have the same result as me?

**Comment by mikehardy** [comment]
I use this module in front of react-native-background-geolocation-android as well for the same reason. It works fine. Note that on new iOS the user has to actually go in to settings and manually grant always, all you can do is check here and direct the user with a dialog then open the app's settings (a different API, built in to react-native if I recall correctly) then re-check.

I was working in that area of my project just last week, all works.

**Comment by samitha9125** [comment]
@mikehardy Actually that is exactly what I did for my current project because of new iOS feature. But it did not work very well with react-native-permissions 2.1.4 version but 2.0.10 version.
@zoontek I'll use the example app and give you a feedback soon :)

**Comment by samitha9125** [comment]
@zoontek I created two projects (RN 0.62.2 and RN 0.61.5) and tried to do the same thing. react-native-Permissions worked as expected in both projects. But I have no idea why it is not working in my original project.

**Comment by zoontek** [comment]
First, avoid using both libs to request permissions in your code (only use react-native-permissions for this)

Then try resetting your phone permissions: https://www.addictivetips.com/ios/reset-all-app-permissions-on-ios/

**Comment by samitha9125** [comment]
I will do that. Thank you so much for your awesome support. I'll close the issue now since this is not related to this library :)

**Comment by zoontek** [comment]
@samitha9125 No problem. I hope you'll find the cause of it!

**Comment by taylorkline** [comment]
> Currently, you have two libs to handle location permission: that's not useful and dangerous. react-native-permissions internal state can't communicate with react-native-geolocation internal state.
> 
> Use one or the other, not both at the same time.

This comment was helpful to me as well 💯 

I also have `react-native-geolocation` installed and it was automatically requesting background permissions after I updated the Info.plist - thought it was this library. 

But it was easy to fix: https://github.com/react-native-geolocation/react-native-geolocation#setrnconfiguration

Perhaps it would be even worth a mention in this library's README that other libraries may conflict. I think https://github.com/react-native-geolocation/react-native-geolocation is probably pretty common.

**Comment by oskarhertzman** [comment]
for anybody still having this issue, an extensive cleaning did the trick for me:

`
"ios:clean": "rm -rf ~/Library/Caches/CocoaPods && rm -rf Pods && rm -rf ~/Library/Developer/Xcode/DerivedData/* && cd ios && xcodebuild clean && pod cache clean --all && pod deintegrate && pod setup && pod install --verbose && cd ..",
`

**Comment by mikehardy** [comment]
@oskarhertzman sounds like you want `npx react-native-clean-project`...
(or in future `npx react-native clean` -- https://github.com/react-native-community/cli/blob/master/packages/cli-clean/CHANGELOG.md)
