### ISSUE TITLE
React Native iOS Photo Library Access working on simulator but showing unavailable on real device

### ISSUE THREAD

**Issue by sujithsomraaj** [zoontek/react-native-permissions#466]
I tried to access the photo library through react-native permissions when I run on my simulator it works fine with no issues, but when I try to use it on my real device through XCODE build using an USB Connection, it says the feature is unavailable. I cannot access my photo_library on a real device.

My Simulator Version: iOS 13.5
My Physical Device VErsion: iOS 13.3.1

Development Versions: macOS Catalina 10.15.4
Using React Native CLI
React Native Permissions:    "^2.1.4"

I tried using 2.1.5 still have the same issue.

My Code is correct as it worked on a simulator.

**Comment by zoontek** [comment]
@SujithStellargoldcoin Hi. `unavailable` response for photo library === [`PHAuthorizationStatusRestricted`](https://developer.apple.com/documentation/photokit/phauthorizationstatus/phauthorizationstatusrestricted?language=objc)

According to the documentation,

> Parental controls or institutional configuration profiles can restrict the user’s ability to grant photo library access to an app.

Could you check both?

**Comment by sujithsomraaj** [comment]
Hi @zoontek I got that resolved. In my mobile parent control options was enabled. Thanks for your prompt response.

**Comment by sujithsomraaj** [comment]
For any one having this issue ===> GO TO SETTINGS ---> SCREEN TIME --> Content & Privacy Restrictions---> Photos --> Allow.

That could solve this issue
