### ISSUE TITLE
NSLocationWhenInUsage always returning unavailable

### ISSUE THREAD

**Issue by mrousavy** [zoontek/react-native-permissions#467]
# Bug report

## Summary

The `NSLocationWhenInUsage` description always returns `unavailable`, even on real devices. When I show a `MapView` from `react-native-maps` with `showUserLocation: true`, the user's location is shown, so it is available. `react-native-permissions` just returns unavailable.

My Podfile:

```ruby
# ...
permissions_path = '../node_modules/react-native-permissions/ios'
pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse.podspec"
# ...
```

My Info.plist:

```xml
<!-- ... -->
<key>NSLocationWhenInUseUsageDescription</key>
<string>$(PRODUCT_NAME) needs your location to find items near you. A location will only be stored when you choose to by creating a post.</string>
<!-- ... -->
```

## Environment info

`react-native info` output:

```bash
info Fetching system and libraries information...
System:
    OS: macOS 10.15.5
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 13.85 GB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.3.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 25, 28, 29
      Build Tools: 28.0.3, 29.0.3, 30.0.0
      System Images: android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_252 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: `^2.1.5`

## Steps to reproduce

1. Ask for permission using `check(PERMISSIONS.IOS.LOCATION_WHEN_IN_USE)`
2. Check result value

Describe what you expected to happen:

1. It should return `blocked`, `denied` or `granted` on my device.

## Reproducible sample code

```ts
const result = await check(PERMISSIONS.IOS.LOCATION_WHEN_IN_USE);
if (result === 'unavailable') console.error('permission unavailable')
```

**Comment by mrousavy** [comment]
Screenshot of location being enabled in settings:

![Screenshot 2020-06-01 at 11 56 57](https://user-images.githubusercontent.com/15199031/83398124-0c812680-a3ff-11ea-8f64-c105c928b21f.png)

In the app it still returns `unavailable`. Geolocation, Maps, etc. APIs work fine.

**Comment by zoontek** [comment]
Might be similar to https://github.com/react-native-community/react-native-permissions/issues/463

Try to run https://github.com/zoontek/rn-location-permission-example on your device.

**Comment by mrousavy** [comment]
@zoontek Yes, the example works fine for me, but I'm not doing anything else in my app than in the example app. Are there any known issues causing this?

**Comment by zoontek** [comment]
Are you sure everything in ran in sequence?

check permission -> `denied` -> request permission -> `granted` -> **only then** starts geolocation service / display map

**Comment by mrousavy** [comment]
Yes, because the `check` function already returns `unavailable`. If I try to call geolocation after `check` returns unavailable, it displays the correct position. It's just the permissions API that's not working I'm guessing

**Comment by zoontek** [comment]
I just gave it a quick try and it works perfectly.

![image](https://user-images.githubusercontent.com/1902323/83404256-9d113400-a40a-11ea-9120-f06898a6297e.png)

My issue is different somehow: the permission check is OK, the geolocation watcher start but I can't have my position on the map (maybe related to Apple Maps vs Google Maps)

**Comment by zoontek** [comment]
![image](https://user-images.githubusercontent.com/1902323/83405450-d054c280-a40c-11ea-955d-048037ae0c3f.png)

`react-native-maps` seems to have few issues regarding user location, but if a watch the geolocation and place a marker it works quite well.

**EDIT**: It does works: There was a typo: `show(s)UserLocation`.

No issues with permissions. The code is pushed here: https://github.com/zoontek/rn-location-permission-example

Could you create a repository with the minimum amount of code to recreate your issue?

**Comment by mrousavy** [comment]
@zoontek hmm, apparently it is an issue on my side. I don't know what's causing it, but on a clean repository with minimal code I can't reproduce the issue..
I'll keep you updated.

**Comment by tr3v3r** [comment]
@mrousavy hi! 
Did you manage to find the root cause of the issue?
After disabling hermes we also start facing this problem..
