### ISSUE TITLE
Request BLUETOOTH or BLUETOOTH_ADMIN permission on Android

### ISSUE THREAD

**Issue by mrousavy** [zoontek/react-native-permissions#468]
# Question

How do I request for bluetooth permission on Android? On iOS I would use `PERMISSIONS.IOS.BLUETOOTH_PERIPHERAL`, but on Android there is no such property...

The manifest permissions are:

```xml
<uses-permission android:name="android.permission.BLUETOOTH" />
<uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />
```

**Comment by zoontek** [comment]
You don't have to, they are not dangerous permissions: https://developer.android.com/guide/topics/permissions/overview

Just put them in your Manifest.
