### ISSUE TITLE
"undetermined" (not "denied") is returned after selecting "never ask again" in Android permission dialog

### ISSUE THREAD

**Issue by SimenCodes** [zoontek/react-native-permissions#47]
Thanks for this great little library!

Just a little bug I've run into:
On Android, shouldShowRequestPermissionRationale indicates whether we should explain to the user why we need the permission, not whether the user has been presented with the permission dialog.

It returns false in two cases:
1. We have not asked the user for this perimssion yet.
2. We have asked the user for this permission at least two times, and the user selected "never ask again" last time we tried.

As a result, if a user selects "never ask again", getPermissionStatus and requestPermission will return "undetermined" instead of "denied".

Code:
[ReactNativePermissionsModule.java#L64](https://github.com/yonahforst/react-native-permissions/blob/master/android/src/main/java/com/joshblour/reactnativepermissions/ReactNativePermissionsModule.java#L64)

**Comment by yonahforst** [comment]
Hi @SimenCodes, thanks for the report. I just ran into this myself and I'm not sure how to address it.

So far, `shouldShowRequestPermissionRationale` seems like the only way to differentiate between `undetermined` and `denied`. Not sure how to catch cases where the user selected "never as again". 

Did you end up finding a solution?

**Comment by SimenCodes** [comment]
Well, I actually ended up using RN's build-in PermissionsAndroid module, and modifying my app to work the way permissions are intended to work on Android.

**Comment by yonahforst** [comment]
@SimenCodes - this lib is actually using the built-in module on android as well. The only difference is that we default to `undetermined` and try to be clever about knowing when it's actually `denied` by checking `shouldShowRequestPermissionRationale`. But it doesn't work in the case you mentioned above.

I guess we could store something in `SharedPreferences` or `AsyncStorage`. Anyone care to comment if this is a good or bad idea?

**Comment by SimenCodes** [comment]
@yonahforst The problem with this approach is that we are forcing the Android permission model into the iOS model. It's doable, and I've seen many posts on SO doing the SharedPreferences thing to achieve this.

I guess this depends on the app you are developing, but I found the best solution for my app was to do this the Android way on Android devices. First, I ask Android if I should show a rationale. If it says yes, I do so. Then I request the permission. If I get "granted" as a response, that's great. Otherwise I move on as best I can without that permission.

**Comment by yonahforst** [comment]
@SimenCodes - I'm releasing version 1.0.0 shortly that will return status `restricted` if the user selects 'Never ask me again'
