### ISSUE TITLE
Flow type support: When using flow, all the imports are typed as "any"

### ISSUE THREAD

**Issue by sanjaypojo** [zoontek/react-native-permissions#470]
# Bug report

## Summary
When imported in a project that uses flow, all imports (`check`, `PERMISSION` etc.) are typed as `any`. I couldn't find types on `flow-typed` either. Do we need to do something to get flow types working? 

## Environment info

`react-native info` output:

```bash
System:
    OS: macOS 10.15.5
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 1.82 GB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.7.0 - /var/folders/0x/ns6pjcs10bbbnt5785379x580000gq/T/yarn--1591121753728-0.9415676398251946/node
    Yarn: 1.22.4 - /var/folders/0x/ns6pjcs10bbbnt5785379x580000gq/T/yarn--1591121753728-0.9415676398251946/yarn
    npm: 6.14.5 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 26.0.2, 27.0.3, 28.0.2, 28.0.3
      System Images: android-22 | Google APIs Intel x86 Atom, android-24 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    create-react-native-app: 2.0.2
    react-native-create-library: 3.1.2
    react-native-rename: 2.4.0
```

Library version: 2.1.5

## Steps to reproduce
1. Import library, add `//@flow` at the top of the file
2. Add flow VSCode plugin.
3. Hover on any import and you'll see they're typed as `any`.
4. Use an incorrect dictionary object like `PERMISSIONS.IOS.RANDOM` and you'll get no flow errors.

## Reproducible sample code

```js
// @flow

import {PERMISSIONS} from "react-native-permissions"

// No flow errors
console.log(PERMISSIONS.RANDOM.RANDOM)
```

**Comment by zoontek** [comment]
There's no Flow types available. It should be straightforward to create them from TS typings and submit them on `flow-typed`.

**Comment by sanjaypojo** [comment]
@zoontek is there a `d.ts` file I can use? Happy to run through `flowgen` and submit to `flow-typed` :)

**Comment by zoontek** [comment]
Yeah, everything is published. Check https://unpkg.com/browse/react-native-permissions@2.1.5/lib/typescript/ + https://unpkg.com/browse/react-native-permissions@2.1.5/lib/typescript/index.d.ts

**Comment by sanjaypojo** [comment]
Just figured out how to generate the `d.ts` file, will PR to flow-typed and link here as well!

**Comment by PauliusLiekis** [comment]
I added a couple of declarations that increased flow coverage to the level that was enough for me :D Here are my declarations if anyone needs:
[react-native-permissions_vx.x.x.js.zip](https://github.com/react-native-community/react-native-permissions/files/4858739/react-native-permissions_vx.x.x.js.zip)
