### ISSUE TITLE
Customized permission dialog

### ISSUE THREAD

**Issue by HarshitMadhav** [zoontek/react-native-permissions#471]
# Feature request

Hi Thank you for this awesome package but I was wondering if there is a way to customize the dialog box of permission?

**Comment by zoontek** [comment]
@HarshitMadhav Hi. No, this is a system alert. But you can create a modal before, like https://github.com/ivanvorobei/SPPermissions (use a `<Modal />` with buttons and `check` / `request` methods)

**Comment by ignacioiglesias43** [comment]
> @HarshitMadhav Hi. No, this is a system alert. But you can create a modal before, like https://github.com/ivanvorobei/SPPermissions (use a `<Modal />` with buttons and `check` / `request` methods)

Hi, do you have an example for this?

**Comment by codal-mpawar** [comment]
@joenoon @corymsmith @trestrantham @darinwilson @nevir  can we do a Customized permission dialog android?
