### ISSUE TITLE
NativeModule.RNPermissions is null

### ISSUE THREAD

**Issue by bsapalo** [zoontek/react-native-permissions#472]
# Bug report

## Summary

I've followed all the steps in this repo, but I ran into a weird issue with my Podfile. It says "NativeModule.RNPermission is null." However, my Podfile contains an RNPermissions pod. I've tried running pod install within the ./ios folder and opening the xcode workspace as well, but nothing has resolved this error. Thank you for your help! (below are the error message and my Podfile)

## Environment info

`react-native info` output:

> OS: macOS 10.15.4
>     CPU: (4) x64 Intel(R) Core(TM) i7-5650U CPU @ 2.20GHz
>     Memory: 830.14 MB / 8.00 GB
>     Shell: 3.2.57 - /bin/bash
>   Binaries:
>     Node: 12.18.0 - /usr/local/bin/node
>     Yarn: 1.22.4 - /usr/local/bin/yarn
>     npm: 6.14.4 - /usr/local/bin/npm
>     Watchman: 4.9.0 - /usr/local/bin/watchman
>   SDKs:
>     iOS SDK:
>       Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
>     Android SDK:
>       API Levels: 29
>       Build Tools: 29.0.3
>   IDEs:
>     Android Studio: 3.6 AI-192.7142.36.36.6392135
>     Xcode: 10.1/10B61 - /usr/bin/xcodebuild
>   npmPackages:
>     react: ~16.9.0 => 16.9.0
>     react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4
>   npmGlobalPackages:
>     create-react-native-app: 3.1.1
>     react-native-cli: 2.0.1
>     react-native-create-library: 3.1.2

## Steps to reproduce

1. create react native project using expo
2. install & link react-native-permissions using yarn (including README.md steps) 
3. implement an onPress function that requests microphone permissions

Describe what you expected to happen:

1. I expected that a screen would appear with the button

## Reproducible sample code

This is the onPress function I used in one of my screens.

`const handleMicrophonePermission = async () => {
    const res = await check(PERMISSIONS.IOS.MICROPHONE);

    if (res === RESULTS.GRANTED) {
      setPermissionGranted(true);
    } else if (res === RESULTS.DENIED) {
      const res2 = await request(PERMISSIONS.IOS.MICROPHONE);
      res2 === RESULTS.GRANTED
        ? setPermissionGranted(true)
        : setPermissionGranted(false);
    }
  };`

![Screen Shot 2020-06-07 at 5 35 58 PM](https://user-images.githubusercontent.com/35281537/84215618-a8540780-aa7b-11ea-83a9-f8d38b9dd7b3.png)
![Screen Shot 2020-06-07 at 5 39 12 PM](https://user-images.githubusercontent.com/35281537/84215620-a9853480-aa7b-11ea-9b35-df1d3f80f636.png)

**Comment by zoontek** [comment]
Are you using Expo [managed or bare workflow](https://docs.expo.io/introduction/managed-vs-bare/#workflow-comparison)? Expo managed workflow simply doesn't support any native module.

Use https://docs.expo.io/versions/v37.0.0/sdk/permissions/ or switch to bare React Native.

**Comment by zoontek** [comment]
Next time think about search instead of opening a duplicate issue: https://github.com/react-native-community/react-native-permissions/issues?q=is%3Aissue+RNPermissions+null+

This is exactly identical: https://github.com/react-native-community/react-native-permissions/issues/399
