### ISSUE TITLE
After setting Notify in Setting page , the check result is always blocked

### ISSUE THREAD

**Issue by urtheone** [zoontek/react-native-permissions#473]
# Bug report

## 
  SDKs:
    iOS SDK:
      Platforms: iOS 13.1, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29
      Build Tools: 23.0.1, 23.0.2, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.3, 29.0.2
      System Images: android-24 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.61.5 

Library version: ^2.0.10

## Steps to reproduce

1. request the camera permission，and deny it(never ask again),
2. then to the setting page and change camera to notify,
3. then return to the app, the check result is always blocked,the right result is denied,and when request it should notify the dialog for user.

**Comment by gabimoncha** [comment]
@urtheone I have the same problem with Location permission. How did you manage to solve it?

**Comment by gabimoncha** [comment]
Nevermind. I saw the fix in #445
