### ISSUE TITLE
No Android permission "WRITE_SETTINGS"

### ISSUE THREAD

**Issue by samuthekid** [zoontek/react-native-permissions#474]
# Question

Came across this lib while implementing permissions in a project, but I was surprised the "WRITE_SETTINGS" option is not available.

Searched for issues with the keyword but got none.
What am I missing?

Thanks :)

**Comment by zoontek** [comment]
Hi 👋
For now, this lib supports `dangerous` level permissions on Android only.

**Comment by samuthekid** [comment]
Hi 👋 
Oh I see. I really like the `check()` and `require()` flow, and thought that would be great to have that for all permissions.
In this case, I needed to change the device brightness, and if the permission was denied, I want to redirect the user to that part of the settings app to allow a better UX.
