### ISSUE TITLE
React Native access app notification permission

### ISSUE THREAD

**Issue by aghahuseynov** [zoontek/react-native-permissions#477]
I want to reach the permissions shown in the picture. How can I do with React Native?
How can I get permission without sending the user to the setting screen?
(Show on Lock Screen , Display pop-up windows while running int the background, Display pop-up window)
![not](https://user-images.githubusercontent.com/22603943/85286578-8f941a80-b49b-11ea-99cf-f8d469cbd339.jpg)

Best Regards

**Comment by zoontek** [comment]
@aghahuseynov Hi. Check the permissions available on Android: https://developer.android.com/reference/android/Manifest.permission

If the permission level isn't "dangerous", you don't need to use this lib to request it, just it in AndroidManifest.
If it's not in the list, it's not requestable through the app, and the user will have to go to settings.

**Comment by aghahuseynov** [comment]
@zoontek  thanks for answer.
But I couldn't find the permission I should add to my manifest file (https://developer.android.com/reference/android/Manifest.permission).

how does whatsapp get this permission without asking the user or going to the settings screen

![2020-06](https://user-images.githubusercontent.com/22603943/85293496-1817b880-b4a6-11ea-8ddb-521359c1b800.jpg)

**Comment by zoontek** [comment]
These are not permissions, but notification settings.

**Comment by zoontek** [comment]
Check https://stackoverflow.com/questions/32174191/show-notifications-on-lock-screen. I'm closing this since it's not an issue related to this library but more of a question. StackOverflow is probably a better platform for this.

**Comment by devSarika** [comment]
> I want to reach the permissions shown in the picture. How can I do with React Native?
> How can I get permission without sending the user to the setting screen?
> (Show on Lock Screen , Display pop-up windows while running int the background, Display pop-up window)
> ![not](https://user-images.githubusercontent.com/22603943/85286578-8f941a80-b49b-11ea-99cf-f8d469cbd339.jpg)
> 
> Best Regards

hey ! Im also searching the same. Did you find anyway? Please help me

**Comment by aghahuseynov** [comment]
@devSarika no I could not find
