### ISSUE TITLE
Getting Unavaiable everytime on ios simulator for PHOTO_LIBRARY

### ISSUE THREAD

**Issue by mayankmittal242** [zoontek/react-native-permissions#478]
I have used this 'ios.permission.PHOTO_LIBRARY' in my code but every time I'm getting response as unavailable. Please help

React native version: 0.62.2
My Simulator Version: iOS 11.3.1

Development Versions: macOS Catalina 10.15.3
Using React Native CLI
React Native Permissions: "^2.1.5"

**Comment by zoontek** [comment]
Please publish some code + your Podfile

**Comment by mikehardy** [comment]
Some permissions are subject to restriction from parental controls as well, making the unavailable for the current user

**Comment by nikoloz110** [comment]
had the same issue, fixed after, deleting podfile.lock, podfile, running pod install and re-building it project
