### ISSUE TITLE
Permission popup appears during app startup on ios

### ISSUE THREAD

**Issue by ketan-kumar** [zoontek/react-native-permissions#479]
I used this library to get the notification permission on device but every time i install the app or rebuild it, permission popup appears automatically on app startup, however it was not happening when i was on version 1.1.1 . can anyone shed some light?

React native version: 0.59.4
ios device: iOS 12.4.5 (ipod touch)

Development Versions: macOS Catalina 10.15.4
React Native Permissions: "^2.0.0"

**Comment by ed-sparkes** [comment]
@ketan-kumar how did you resolve this, i am getting similair
