### ISSUE TITLE
Permission popup appears during app startup on ios

### ISSUE THREAD

**Issue by ketan-kumar** [zoontek/react-native-permissions#480]
I used this library to get the notification permission on device but every time i install the app or rebuild it, permission popup appears automatically on app startup, however it was not happening when i was on version 1.1.1 . can anyone shed some light on this?

React native version: 0.59.4
ios device: iOS 12.4.5 (ipod touch)

Development Versions: macOS Catalina 10.15.4
React Native Permissions: "^2.0.0"

**Comment by zoontek** [comment]
Where do you trigger the permissions request?
Please provide some code or this issue will be closed.

**Comment by ketan-kumar** [comment]
@zoontek Thanks for reply.
Here is the wrapper around the lib functions according to need.
```
import {checkNotifications, requestNotifications, openSettings} from 'react-native-permissions';
import Log from './log';

module.exports = {
  requestPermissions() {
    return new Promise(resolve => {
      requestNotifications(['alert', 'sound', 'badge']).then(response => {
        let permission = false
        if (response.status === 'granted') {
          permission = true
        }
        const logData = {
          title: 'App asked for notification',
          message: {
            notificationStatus: permission
          }
        }
        Log.save(logData);
        if (permission) {
          resolve('Allowed');
        } else {
          resolve('Not Allowed');
        }
      })
    });
  }
}
```

and i call the function `requestPermissions` when user press on the permission dialogues delivered from the server and then this function call open the permission popup. here the things are working fine. no complaints at all!!

here is the function call: (this will be called when user press on particular dialogues for the permission)
```
if (inputRequest.type === 'permission_popup_open') {
          const response = await Permission.requestPermissions();
          this.handleActionPermissionButton(response);
          this.resetExecutionTime();
        }
```

but the problem is when i reinstall the app(by uninstalling) or update the app, then permission popup appears regardless the `requestPermissions` function call.

here is the pods:
```
  pod 'RNPermissions', :path => '../node_modules/react-native-permissions'
  permissions_path = '../node_modules/react-native-permissions/ios'

  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications.podspec"
```

However, it was working before when i was on version `1.1.1` but after upgrading to `2.0.0` i'm facing this.
I reckon, this is not the problem with the code. this is more with the delegates or pods.Thanks!!!

**Comment by kg-currenxie** [comment]
@zoontek  I just came across this a swell. I'm *not* calling `requestNotifications` or even `checkNotifications()` anywhere. The popup comes up every time i delete the app and reinstall
```
"react-native-permissions": "3.6.1"
"react-native": "0.70.4"
```

device is iOS 16.1
