### ISSUE TITLE
Android notification permissions "granted", even on first install

### ISSUE THREAD

**Issue by jcarioti** [zoontek/react-native-permissions#482]
# Bug report

## Summary

On a fresh install of our React Native application on Android 10 (Pixel 3a), the `checkNotifications` call returns a status of `granted`. This is unexpected since we have yet to ask the OS for notifications permissions.

Calling `requestNotifications(['alert', 'sound']` yields the same result: `granted` without ever having asked for permissions.

If I go to the Android app-info section for our app, it says "Permissions: No Permissions Granted". Am I missing something here?

## Environment info

Android Pixel 3a - Android 10 

`react-native info` output:

```bash
System:
    OS: macOS 10.15.5
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 47.82 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.8.4 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 28, 29
      Build Tools: 28.0.3, 29.0.2, 29.0.3
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6392135
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_232 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^16.13.1 => 16.13.1 
    react-native: ^0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 2.1.5

## Steps to reproduce

1. Run `checkNotifications` from within a React Native app running on a Pixel 3a device with Android 10

Describe what you expected to happen:

1. The status returned should be something other than 'granted' until the user grants the permission

## Reproducible sample code

```
    const { status } = await checkNotifications();

    if (['denied', 'blocked'].includes(status)) {
      // We expect this on the first run of a freshly installed app...
      this.setState({ hasNotificationPermission: false });
    } else {
      // ... but we're always ending up here, even when app hasn't been granted any permissions yet
      this.setState({ hasNotificationPermission: true });
    }
```

**Comment by JenssRey** [comment]
Hi,

I'm facing the same issue. Can you maybe share what you did in order to fix and close this issue?

**Comment by marudy** [comment]
Same here. @jcarioti @zoontek any insights on that?

@JenssRey did you manage to work it out ?

Thanks,
Tasos

**Comment by marudy** [comment]
I should note here that `granted` as an initial value is not the problem as in Android this is the default behavior. The problem for me is that even after blocking for application settings it still remains on value `granted` while it should be `denied`.

**Comment by jcarioti** [comment]
> Hi,
> 
> I'm facing the same issue. Can you maybe share what you did in order to fix and close this issue?

> Same here. @jcarioti @zoontek any insights on that?
> 
> @JenssRey did you manage to work it out ?
> 
> Thanks,
> Tasos

The issue was me not understanding that Android push notifications are always "granted" by the system. You don't have to ask the user for permissions to enable push notifications.

**Comment by zoontek** [comment]
The [example](https://github.com/react-native-community/react-native-permissions/tree/master/example) is particularly useful to understand each permission mecanism :)
