### ISSUE TITLE
check(PERMISSIONS.IOS.LOCATION_WHEN_IN_USE) always returns unavailable!

### ISSUE THREAD

**Issue by mrousavy** [zoontek/react-native-permissions#483]
# Bug report

## Summary

This problem has been opened here before and closed because the author forgot to add the Pods to the Podfile, but I didn't.

Everytime I run 

```ts
const permissionStatus = await check(PERMISSIONS.IOS.LOCATION_WHEN_IN_USE);
```

I get `'unavailable'` as a result. The odd thing is, that it does work on my Simulator where it returns `'denied'` at first, then I can call `request`. On my actual iPhone 11 device running iOS 13 it does return `'unavailable'` immediately.

I have added the descriptions to `Info.plist`:

```xml
<key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
<string>$(PRODUCT_NAME) needs your location to find items near you. A location will only be stored when you choose to by creating a post.</string>
<key>NSLocationWhenInUseUsageDescription</key>
<string>$(PRODUCT_NAME) needs your location to find items near you. A location will only be stored when you choose to by creating a post.</string>
```

I also added both Always and WhenInUse permissions to my `Podfile`:

```ruby
permissions_path = '../node_modules/react-native-permissions/ios'
pod 'Permission-BluetoothPeripheral', :path => "#{permissions_path}/BluetoothPeripheral.podspec"
pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse.podspec"
pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways.podspec"
```

And I have ran `pod install`.

## Environment info

`react-native info` output:

```bash
info Fetching system and libraries information...
(node:12653) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
System:
    OS: macOS 10.15.5
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 1.28 GB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.4.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.6 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 25, 28, 29
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.0, 30.0.0, 30.0.0
      System Images: android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: 21.2.6472646
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_252 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.0 => 0.63.0 
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: ^2.1.5

## Steps to reproduce

1. Add `NSLocationWhenInUseUsageDescription` tag to `Info.plist`
2. Add `Permission-LocationWhenInUse` podspec to `Podfile` 
3. Run `pod install`
4. Run app on device
5. Call `check(PERMISSIONS.IOS.LOCATION_WHEN_IN_USE)`
6. Immediately receive `unavailable` for some reason

Describe what you expected to happen:

1. I should receive `denied` at first so I can call `request` after that!

## Reproducible sample code

```ts
const permissionStatus = await check(PERMISSIONS.IOS.LOCATION_WHEN_IN_USE);
```

**Comment by mrousavy** [comment]
And yes, I have also tested it with https://github.com/zoontek/rn-location-permission-example - same problem! It immediately returns `unavailable` for `check()`.

**Comment by zoontek** [comment]
Hi. Have you checked if `Location services` are enabled on your device?

<img src="https://user-images.githubusercontent.com/1902323/87524489-86583100-c688-11ea-8aae-78800e27be62.jpg" 
 width="400px" />

**Comment by mrousavy** [comment]
Yes, location services are enabled. They're also enabled for the App specifically.

**Comment by zoontek** [comment]
Try uninstalling all applications with a similar namespace start (ex: "com.facebook") from your device, or reset your device permissions.

**Comment by HansBouwmeester** [comment]
I've seen "unavailable" being reported for iOS camera access permissions on my iPhone 11 Pro (running iOS 13). I'm not sure what causes it (I'm sure the camera access permission in the iOS settings menu is ON). I'm working around it by ignoring "unavailable" results for devices/permission-types where I know availability is not a concern (i.e. effectively proceeding as if access is "granted").

I don't know what could cause it, but it does seem an 'unavailable' result does not necessarily mean the feature is not available on the device.

@zoontek How do I reset the device permissions? I've tried just turning it 'OFF' and then back 'ON' but that didn't fix it.

**Comment by zoontek** [comment]
@Gra55h0pper Here's a tutorial https://www.addictivetips.com/ios/reset-all-app-permissions-on-ios/

**Comment by HansBouwmeester** [comment]
@zoontek Thanks! I tried it but it didn't make a difference.

However, I realized I forgot to add the Camera permission path to my Podfile. 
`pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"`
I haven't had a chance to try yet, but could that perhaps explain the behavior I'm seeing?

**Comment by zoontek** [comment]
@Gra55h0pper Yes

**Comment by cabelin** [comment]
> # Bug report
> ## Summary
> This problem has been opened here before and closed because the author forgot to add the Pods to the Podfile, but I didn't.
> 
> Everytime I run
> 
> ```ts
> const permissionStatus = await check(PERMISSIONS.IOS.LOCATION_WHEN_IN_USE);
> ```
> 
> I get `'unavailable'` as a result. The odd thing is, that it does work on my Simulator where it returns `'denied'` at first, then I can call `request`. On my actual iPhone 11 device running iOS 13 it does return `'unavailable'` immediately.
> 
> I have added the descriptions to `Info.plist`:
> 
> ```
> <key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
> <string>$(PRODUCT_NAME) needs your location to find items near you. A location will only be stored when you choose to by creating a post.</string>
> <key>NSLocationWhenInUseUsageDescription</key>
> <string>$(PRODUCT_NAME) needs your location to find items near you. A location will only be stored when you choose to by creating a post.</string>
> ```
> 
> I also added both Always and WhenInUse permissions to my `Podfile`:
> 
> ```ruby
> permissions_path = '../node_modules/react-native-permissions/ios'
> pod 'Permission-BluetoothPeripheral', :path => "#{permissions_path}/BluetoothPeripheral.podspec"
> pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse.podspec"
> pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways.podspec"
> ```
> 
> And I have ran `pod install`.
> 
> ## Environment info
> `react-native info` output:
> 
> ```shell
> info Fetching system and libraries information...
> (node:12653) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
> (Use `node --trace-warnings ...` to show where the warning was created)
> System:
>     OS: macOS 10.15.5
>     CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
>     Memory: 1.28 GB / 32.00 GB
>     Shell: 5.7.1 - /bin/zsh
>   Binaries:
>     Node: 14.4.0 - /usr/local/bin/node
>     Yarn: 1.22.4 - /usr/local/bin/yarn
>     npm: 6.14.6 - /usr/local/bin/npm
>     Watchman: 4.9.0 - /usr/local/bin/watchman
>   Managers:
>     CocoaPods: 1.9.3 - /usr/local/bin/pod
>   SDKs:
>     iOS SDK:
>       Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
>     Android SDK:
>       API Levels: 25, 28, 29
>       Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.0, 30.0.0, 30.0.0
>       System Images: android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
>       Android NDK: 21.2.6472646
>   IDEs:
>     Android Studio: 4.0 AI-193.6911.18.40.6514223
>     Xcode: 11.5/11E608c - /usr/bin/xcodebuild
>   Languages:
>     Java: 1.8.0_252 - /usr/bin/javac
>     Python: 2.7.16 - /usr/bin/python
>   npmPackages:
>     @react-native-community/cli: Not Found
>     react: 16.13.1 => 16.13.1 
>     react-native: 0.63.0 => 0.63.0 
>   npmGlobalPackages:
>     *react-native*: Not Found
> ```
> 
> Library version: ^2.1.5
> 
> ## Steps to reproduce
> 1. Add `NSLocationWhenInUseUsageDescription` tag to `Info.plist`
> 2. Add `Permission-LocationWhenInUse` podspec to `Podfile`
> 3. Run `pod install`
> 4. Run app on device
> 5. Call `check(PERMISSIONS.IOS.LOCATION_WHEN_IN_USE)`
> 6. Immediately receive `unavailable` for some reason
> 
> Describe what you expected to happen:
> 
> 1. I should receive `denied` at first so I can call `request` after that!
> 
> ## Reproducible sample code
> ```ts
> const permissionStatus = await check(PERMISSIONS.IOS.LOCATION_WHEN_IN_USE);
> ```

Same problem here! I followed the permission reset tutorial and it still doesn't work

**Comment by brassotron** [comment]
I've also been experiencing this issue, I found that it resolved itself after doing the following.

1. Erase all content and settings for the device in the **Hardware** options for the iOS Simulator.
2. Delete the Derived Data for your application in `~/Library/Developer/Xcode/DerivedData`.

I hope this was helpful!

**Comment by tallpants** [comment]
Can we close this @Gra55h0pper @zoontek ?

**Comment by SamiChab** [comment]
I have the same problem here. On Android (real device, Android 8.1) and iOS (iPhone 11 Pro Max Simulator).
Can anyone help?

**Comment by YogeshSinghNegi** [comment]
Is this resolved, even I am facing this similar issue?

**Comment by oscarcornejo** [comment]
Same problem!! :(

**Comment by nguyentuanit97** [comment]
Same

**Comment by ABespolov** [comment]
1) update pod file
  ```
permissions_path = '../node_modules/react-native-permissions/ios'
  
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone"
```
2) Clean cache `pod cache clean --all`
3) Clean build folder `XCode -> Product -> Clean build folder`
4) Run `pod install` 

It should help

**Comment by lucas0205** [comment]
FYI for those who need to change the pod file for location when in use: 
`pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"`

**Comment by MrFoxxz** [comment]
I am having the same problem with the permissions, I am working with an iphone 13 with ios 15.0 the permissions of microphone, location, media library are giving "unavailable", but the permission of the camera if it is giving me option to be able to guarantee it

**Comment by mikehardy** [comment]
I never understand why people post on closed issues without sufficient information to reproduce (https://stackoverflow.com/help/minimal-reproducible-example) like an App.js that would reproduce it when coupled with an `npx react-native init RNPermTest` and an install of react-native-permissions :thinking:

**Comment by ghost** [comment]
@MrFoxxz were you able to figure it out why is always returning "unavailable"?

**Comment by vanhungoz** [comment]
> @MrFoxxz were you able to figure it out why is always returning "unavailable"?

@gilsonviana-modus remove Pods, podlock, after that pod install againt. it worked for me

**Comment by Egehanozsoy** [comment]
Any updates on this issue, still having this.

**Comment by mikehardy** [comment]
@Egehanozsoy please refer to my comment here https://github.com/zoontek/react-native-permissions/issues/483#issuecomment-940125938 on this issue that was closed nearly 2 years ago

**Comment by akul-srivastava** [comment]
For anyone using Location Permission and getting `unavailable` everytime.
Just add following line in your Podfile

```
pod 'Permission-LocationWhenInUse', :path => "../node_modules/react-native-permissions/ios/LocationWhenInUse.podspec" 
```

1. Delete old Pods folder and Podfile.lock
2. pod install
3. Run you app

**Comment by oskarhertzman** [comment]
for anybody still having this issue, an extensive cleaning did the trick for me, add this to scripts in package.json and run:

`npm run ios:clean`

  or 

`yarn run ios:clean`
```
"ios:clean": "rm -rf ~/Library/Caches/CocoaPods && rm -rf Pods && rm -rf ~/Library/Developer/Xcode/DerivedData/* && cd ios && xcodebuild clean && pod cache clean --all && pod deintegrate && pod setup && pod install --verbose && cd ..",
```

**Comment by CoderKing2705** [comment]
Facing the same issue it is returning `unavailable` if I add this line `check(PERMISSIONS.IOS.LOCATION_WHEN_IN_USE)`. I do not know how to resolve this, and I am not getting **permission to enable the location**. 

```
    let result;
    if (Platform.OS === 'ios') {
      result = await check(PERMISSIONS.IOS.LOCATION_WHEN_IN_USE);
    } else if (Platform.OS === 'android') {
      result = await check(PERMISSIONS.ANDROID.ACCESS_FINE_LOCATION);
    }

    if (result === RESULTS.GRANTED) {
      setLocationEnabled(true);
      setModalVisible(false);
    } else {
      setLocationEnabled(false);
      setModalVisible(true);
    }```

**Comment by mahesh970098** [comment]
Try This 
   import Geolocation from 'react-native-geolocation-service';
   const resuts=await Geolocation.requestAuthorization('whenInUse')
   resuts=='granted'

It works for me!
