### ISSUE TITLE
ios pod install error

### ISSUE THREAD

**Issue by mmorcc** [zoontek/react-native-permissions#484]
pod install 
Analyzing dependencies
[!] Unable to find a specification for `RNPermissions` depended upon by `Permission-PhotoLibrary`

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

**Comment by mikehardy** [comment]
As a guess you have a broken upgrade from RN59 to RN60+ and don't have auto-linking working.
If you can reproduce this based off the example in this project it's a module problem, but in the most clear terms this is a local project problem with your integration of native modules to react-native, and not a problem in this module

**Comment by oferRounds** [comment]
@mmorcc have you found any solution? Seeing this also after upgrading to React Native 0.63.4 + react-native-permissions 3.0.0

**Comment by mmorcc** [comment]
> @mmorcc have you found any solution? Seeing this also after upgrading to React Native 0.63.4 + react-native-permissions 3.0.0

i sovled by use verison ^2.1.5
