### ISSUE TITLE
changge the readMefile

### ISSUE THREAD

**Issue by mmorcc** [zoontek/react-native-permissions#486]
add 
react-native link react-native-permissions
 then modify podfile like this 
  pod 'RNPermissions', :path => '../node_modules/react-native-permissions'

  pod 'Permission-Camera', :path => "../node_modules/react-native-permissions/ios/Camera.podspec"
  pod 'Permission-PhotoLibrary', :path => "../node_modules/react-native-permissions/ios/PhotoLibrary.podspec"

**Comment by zoontek** [comment]
The README reflects install process for RN 0.60+
