### ISSUE TITLE
Undefined symbols for architecture arm64:   "_OBJC_CLASS_$_RNPermissionHandlerPhotoLibrary", referenced from:objc-class-ref in libRNPermissions.a(RNPermissions.o) in react native ios

### ISSUE THREAD

**Issue by thtRajasthaniGuy** [zoontek/react-native-permissions#487]
Enviroment info
System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
    Memory: 232.40 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29
      Build Tools: 27.0.3, 28.0.3, 29.0.2, 29.0.3
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_222 - /usr/bin/javac
    Python: 2.7.10 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.1 => 0.62.1 
  npmGlobalPackages:
    *react-native*: Not Found

**.  Android works perfectly, but I get this error on building my iOS app: i also try manual linking , drag and drop permission.xcodeproj file in libeary, delete path buildSetting -> libeary path  but no solution.**

                  ld: warning: directory not found for option '- 
                    L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-5.0/iphoneos' 
                    Undefined symbols for architecture arm64:
                    "_OBJC_CLASS_$_RNPermissionHandlerPhotoLibrary", referenced from:
                    objc-class-ref in libRNPermissions.a(RNPermissions.o)
                    "_OBJC_CLASS_$_RNPermissionHandlerMediaLibrary", referenced from:
                  objc-class-ref in libRNPermissions.a(RNPermissions.o)
                    "_OBJC_CLASS_$_RNPermissionHandlerFaceID", referenced from:
                    objc-class-ref in libRNPermissions.a(RNPermissions.o)
                    "_OBJC_CLASS_$_RNPermissionHandlerLocationWhenInUse", referenced from:
                    objc-class-ref in libRNPermissions.a(RNPermissions.o)
                   "_OBJC_CLASS_$_RNPermissionHandlerCamera", referenced from:
                    objc-class-ref in libRNPermissions.a(RNPermissions.o)
                    ld: symbol(s) not found for architecture arm64
                    clang: error: linker command failed with exit code 1 (use -v to see invocation)

here is my pod file:

                     platform :ios, '10.0'
                     require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

                   def add_flipper_pods!
                   version = '~> 0.33.1'
                  pod 'FlipperKit', version, :configuration => 'Debug'
                  pod 'FlipperKit/FlipperKitLayoutPlugin', version, :configuration => 'Debug'
                  pod 'FlipperKit/SKIOSNetworkPlugin', version, :configuration => 'Debug'
                 pod 'FlipperKit/FlipperKitUserDefaultsPlugin', version, :configuration => 'Debug'
                  pod 'FlipperKit/FlipperKitReactPlugin', version, :configuration => 'Debug'
                 end

                def flipper_post_install(installer)
                installer.pods_project.targets.each do |target|
                if target.name == 'YogaKit'
                target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '4.1'
                           end
                      end
                 end
            end

           target 'HealthKangaroo' do
       
           pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
           pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
           pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
           pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
           pod 'React', :path => '../node_modules/react-native/'
          pod 'React-Core', :path => '../node_modules/react-native/'
          pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
          pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
          pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
          pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
         pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
         pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
         pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
         pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
         pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
         pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
        pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
        pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'

         pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
        pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
        pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
        pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
       pod 'ReactCommon/callinvoker', :path => "../node_modules/react-native/ReactCommon"
       pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
       pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga', :modular_headers => true

       pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
       pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
       pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

       pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

        target 'HealthKangarooTests' do

           pod 'RNPermissions', :path => '../node_modules/react-native-permissions'
           permissions_path = '../node_modules/react-native-permissions/ios'
            pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
            pod 'Permission-FaceID', :path => "#{permissions_path}/FaceID.podspec"
            pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse.podspec"
            pod 'Permission-MediaLibrary', :path => "#{permissions_path}/MediaLibrary.podspec"
            pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary.podspec"
    
        inherit! :complete
      
      end
  
  

           use_native_modules!

         add_flipper_pods!
         post_install do |installer|
          flipper_post_install(installer)
         end
    end

       pre_install do |installer|
       installer.pod_targets.each do |pod|
        if pod.name.eql?('RNPermissions') || pod.name.start_with?('Permission-')
          def pod.build_type;
            Pod::BuildType.static_library # >= 1.9
           # Pod::Target::BuildType.static_library # < 1.9
              end
          end
       end
    end

**Comment by zoontek** [comment]
Hi 👋. Please respect the template and format the issue correctly.

**Comment by thtRajasthaniGuy** [comment]
my apologies @zoontek  can you please again check it?

**Comment by mikehardy** [comment]
You appear to have included the pods. Strange it's not working. When I have one of those ":shrug: I dunno" issues on Xcode I start with `npx react-native-clean-project`

**Comment by zoontek** [comment]
@govind1530 Does `npx react-native-clean-project` did the trick for you?

**Comment by thtRajasthaniGuy** [comment]
I reinstall the library

**Comment by choijiho0021** [comment]
I have same problem.

`cd ios`
`rm -rf Pods`
`rm Podfile.lock`
`pod install`

now  It's working.

**Comment by mikehardy** [comment]
@choijiho0021 you might like https://github.com/pmadruga/react-native-clean-project

**Comment by vmobeedeveloper** [comment]
@mikehardy working for me
