### ISSUE TITLE
checkMultiple only siry crash

### ISSUE THREAD

**Issue by ease-space** [zoontek/react-native-permissions#488]
checkMultiple permission with other permission and Siri  => crash without show errors in console or debuger. Tested on emulator. Info.plist NSSiriUsageDescription for Siri permission and other added. Pod installed. Cache cleared.

**Comment by zoontek** [comment]
@maystrenkoYurii Please respect the issue template. Also, check that Siri entitlement is setted up: https://stackoverflow.com/questions/41217838/sirikit-crashes-use-of-the-class-from-an-app-requires-the-entitlement-com-appl
