### ISSUE TITLE
iOS 14 precise location permission

### ISSUE THREAD

**Issue by taschik** [zoontek/react-native-permissions#489]
# Feature request

With iOS 14 Apple introduces the ability to provide an app with an approximate location of the device. For tracking apps e.g. fitness apps, it would be essential to check whether accessing a precise location has been granted.

## Why it is needed

Without a precise location some apps might not be able to fulfill their purpose.

**Comment by zoontek** [comment]
@taschik I would accept a PR.

**Comment by gabimoncha** [comment]
I would really appreciate it if we can prioritise this. I offer myself to test it, but cannot contribute with code as I'm not a native developer.

**Comment by taschik** [comment]
I am happy to test too! I currently don't have the time to contribute with a PR. I hope someone might have time and implement the feature.

**Comment by mikehardy** [comment]
Put a bounty on it to attract native developers perhaps https://www.bountysource.com/ - just a suggestion on something you can do as direct action, not at all a requirement or official policy or anything of the sort

**Comment by zoontek** [comment]
> I would really appreciate it if we can prioritise this. I offer myself to test it, but cannot contribute with code as I'm not a native developer.

Sadly we don't use this kind of feature in our company app, so it will not be a priority on my roadmap 😕

As @mikehardy said, it's still possible to attract native developers on BountySource. You can also hire an iOS freelancer to handle the pull request, or consider a one time sponsorship to lock the time needed to implement and test this feature.

**Comment by adapptor-kurt** [comment]
I've made some changes for this, please take a look.  It doesn't quite match the normal `request` pattern because it requires a purpose key that references a Plist string, so the change is maybe not as trivial as other permissions.

**Comment by zoontek** [comment]
I published a first beta for `3.0.0`: https://www.npmjs.com/package/react-native-permissions/v/3.0.0-beta.0
The migration guide is available here: https://github.com/zoontek/react-native-permissions/blob/3.0.0/MIGRATION.md

Thanks again @adapptor-kurt for your work :)
