### ISSUE TITLE
requestPermission will not register if permission has already been requested once (even if it was authorized)

### ISSUE THREAD

**Issue by jtewright** [zoontek/react-native-permissions#49]
This may or may not be a general problem, but it's problematic for our app and diverges from how React Native's built-in PushNotificationsIOS works, so I wanted to raise it.

https://github.com/yonahforst/react-native-permissions/blob/master/permissions/RNPNotification.m#L49

This stops registerForRemoteNotifications / registerForRemoteNotificationTypes being called if the user has been asked for permission already. When users log out of our app we unregister their push endpoint. When they log in again this line prevents them being registered because the user defaults flag will be true.

**Comment by jtewright** [comment]
Related to this, it seems that this package won't recognize that push notification permission has been granted unless it was granted via this package.. If you request permission through React Native's PushNotificationsIOS this package will still return 'undetermined' when you check permissions.

https://github.com/yonahforst/react-native-permissions/blob/master/permissions/RNPNotification.m#L42

**Comment by jtewright** [comment]
I now realize the reason for this setup is to be able to know when the permission is 'undetermined' :)

We've had a scenario where UserDefaults get cleared and permissions are authorized, but this package will return 'undetermined' in that scenario. I think the best thing you could do is double check that the permission is not authorized when you think it's 'undertmined'. You won't be able to tell if it's denied though..

Then if it's authorized I think this package still needs to execute the register event to generate the push token, as mentioned in the first comment above.

**Comment by kesha-antonov** [comment]
+1

**Comment by yonahforst** [comment]
Hi @jtewright, thanks for your suggestion! I've implemented it in 892d1f0
