### ISSUE TITLE
[v2] Android Photo Access

### ISSUE THREAD

**Issue by dorthwein** [zoontek/react-native-permissions#493]
I am documenting this to save someone else the confusion I ran into. 

It was unclear what permissions are needed to view the Android Photo Library until I stumbled along this issue: [277](https://github.com/react-native-community/react-native-permissions/pull/277) 

Anyway, incase someone else runs into this what you are looking for is `PERMISSIONS.ANDROID.WRITE_EXTERNAL_STORAGE`

Hope that helps someone!

**Comment by jacquesdev** [comment]
Adding this issue in for reference too, which helped me https://github.com/zoontek/react-native-permissions/issues/448
