### ISSUE TITLE
Detect the difference between never-asked-for-the-permission to previously asked-and-denied

### ISSUE THREAD

**Issue by oferRounds** [zoontek/react-native-permissions#494]
# Question
Hi, it used to be that if a permission hasn’t been requested in the past, and it’s now being checked for, the result would be 'undetermined'. I upgraded now to v2, and it seems it was unified with 'denied'

How can I tell the difference between these two different states, when asked/check for the first time? not sure about Android, but at least on iOS, the old way matched the iOS way (being able to tell between these two)

**Comment by oferRounds** [comment]
Sorry, my bad. Missed the 'blocked'

**Comment by th0r0nd0r** [comment]
@oferRounds did you get things working by using 'blocked' as a proxy for 'undetermined'? I'm having trouble deciphering the iOS flowchart on the README. it seems we'll bet 'blocked' if:

Checking permissions:
- the permission is 'not requestable'

Requesting permissions:
- the request was denied (seems like this case should instead be 'denied')

I just want to check if the system prompt has been shown or not. I know the info is accessible natively but it seems convoluted here.
