### ISSUE TITLE
IOS - FaceID Check always return "unavailable"

### ISSUE THREAD

**Issue by DaniShalash** [zoontek/react-native-permissions#499]
# Bug report

## Summary

Checking FaceID permission (PERMISSIONS.IOS.FACE_ID) always return false.
On all cases:
* Fresh Install of the app.
* After Disabling the permission from system settings.
* After Enabling the permission from system settings.

## Environment info

react-native: 0.63.2
react-native-permissions: 2.1.5
iOS: 13.3.1
xCode: 11.6
iPhoneX: MQAD2AH/A

`react-native info` output:

```bash
# System:
    OS: macOS 10.15.4
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 51.33 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.6.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.7 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.8.4 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 21, 26, 28, 29
      Build Tools: 28.0.3, 29.0.1, 29.0.3
      System Images: android-26 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_241 - /Library/Java/JavaVirtualMachines/jdk1.8.0_241.jdk/Contents/Home/bin/javac
    Python: 2.7.15 - /usr/local/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.2 => 0.63.2 
  npmGlobalPackages:
    *react-native*: Not Foundpaste it here
```

Library version: 2.1.5

## Steps to reproduce

1. Create a react-native project
2. install react-native-permissions 2.1.5
3. `cd ios && pod install`
4. Create a simple button, and inPress: `check(PERMISSIONS.IOS.FACE_ID)`
5. 'check' will return `RESULTS. UNAVAILABLE `

Describe what you expected to happen:

'check' should return `RESULTS.DENIED` on a fresh install

## Reproducible sample code

I couldn't provide a sample code at the moment.

**Comment by zoontek** [comment]
Could you provide your Podfile?

**Comment by Mhd-Emad** [comment]
I'm facing the same issue with the following:

->PERMISSIONS.IOS.PHOTO_LIBRARY
->PERMISSIONS.IOS.MOTION
->PERMISSIONS.IOS.LOCATION_ALWAYS
->PERMISSIONS.IOS.LOCATION_WHEN_IN_USE

Alsway UNAVAILABLE

**Comment by Mhd-Emad** [comment]
Hi @DaniShalash 

Have you tried to remove the "derived data" for your application in ~/Library/Developer/Xcode/DerivedData?

**Comment by nhatnguyenbp** [comment]
I have same issue

**Comment by AngelTrinidad** [comment]
I have the same issue

**Comment by AngelTrinidad** [comment]
Well, upgrade to version 3 and clear the build folder in xcode, fix the problem for me

**Comment by aureosouza** [comment]
Still have same issue here, always getting `unavailable` using version 3.6.1 of react-native-permissions on iOS 16.0.2 when using `request(PERMISSIONS.IOS.FACE_ID)`. Although if we use other solutions like `react-native-biometrics`or `expo-local-authentication` it prompts correctly for FaceId permission. We have as well NSFaceIDUsageDescription correctly defined in Info.plist.

**Comment by MDG-MMeksasi** [comment]
still always return unavailable, on version "react-native-permissions": "^3.4.0", and ios 16.1.1 Iphone 12 Pro how come it's closed

**Comment by aureosouza** [comment]
@MDG-MMeksasi we were able to fix by adding to Podfile:

```
permissions_path = '../node_modules/react-native-permissions/ios'
pod 'Permission-FaceID', :path => "#{permissions_path}/FaceID"
```

**Comment by scarlac** [comment]
For version 3.8.4, you may be using "reactNativePermissionsIOS" in the package.json file instead of the Podfile changes. Please check that `"FaceID",` like so:
```js
{
  "dependencies": { /* ... */ }
  "reactNativePermissionsIOS": [
    /* ... */
    "FaceID"
  ],
}
```
Then:
1. Run `react-native setup-ios-permissions` or `npx react-native setup-ios-permissions`
2. Delete your derived data (`~/Library/Developer/Xcode/DerivedData`) or use Xcode's "Clean Build Folder" (Shift+CMD+K)
3. Re-build
