### ISSUE TITLE
Add js file for Android so it doesn't crash

### ISSUE THREAD

**Issue by corymsmith** [zoontek/react-native-permissions#5]
I'm attempting to use this module along with react-native-android-permissions, the issue is that requiring this module throws the following error.

![screenshot 2016-06-02 14 09 01](https://cloud.githubusercontent.com/assets/7315/15759361/9cac7a60-28cb-11e6-8388-079cfd0390ba.png)

I've forked and fixed it by adding a `ReactNativePermissions.android.js` as placeholder.

Would you accept a PR?

**Comment by yonahforst** [comment]
merged pull request. thank yoU!
