### ISSUE TITLE
Android: "Never Ask Again" Permission returning "denied" instead of "blocked" 

### ISSUE THREAD

**Issue by NMahendroo** [zoontek/react-native-permissions#504]
# Bug report

## Environment info

`react-native info` output:

```bash
# System:
    OS: macOS 10.15.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
    Memory: 64.78 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.2.0 - /usr/local/bin/node
    npm: 6.14.7 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.1, 30.0.2
      System Images: android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.12.0 => 16.12.0 
    react-native: 0.61.5 => 0.61.5
```

Library version: 2.2.0

## Steps to reproduce

1. Used "check" function to check if the location permission is denied with "Never Ask Again"

Describe what you expected to happen:

1. Promise to return value as "blocked", but the code always returned "denied"

## Reproducible sample code

```
check(Platform.select({
            android: PERMISSIONS.ANDROID.ACCESS_FINE_LOCATION,
            ios: PERMISSIONS.IOS.LOCATION_WHEN_IN_USE,
        })).then(response => {
        switch (response) {
            case 'granted': //do my work
                break;
            case 'unavailable': //do my work
                break;
            case 'denied': //do my work
                break;
            case 'blocked': //do my work
                break;
        }
    }).catch(ex => {
        console.log("Permission Check Error", ex)
    })
```

**Comment by NMahendroo** [comment]
@zoontek do we have any fix for above mentioned issue?

**Comment by zoontek** [comment]
Through you posted a solution here: https://github.com/react-native-community/react-native-permissions/issues/505 (it's the same code)

**Comment by zoontek** [comment]
Did you request the permission with react-native-permissions too?

**Comment by NMahendroo** [comment]
@zoontek it is not the same thing, the solution that I posted there was something different kindly review both. The solution that I mentioned was for RNPermissions.isAvaialable is undefined.

But this is the issue related to Android, I was getting “denied” instead of “blocked” after denying the location permission opting “Never ask again”.
It seems the bug in 2.1.0 and 2.2.0, I tried with both the versions.

And yes I requested the permission with the same library

**Comment by zoontek** [comment]
Which device do you actually use? (+ OS version)

**Comment by NMahendroo** [comment]
> Which device do you actually use? (+ OS version)

I tested on emulator 
Nexus 5X with API 29
Pixel 3XL with API 30

**Comment by zoontek** [comment]
Please give it a try on real devices.

**Comment by NMahendroo** [comment]
> Please give it a try on real devices.

Sure I’ll update you after giving a try on real device as well.

**Comment by NMahendroo** [comment]
Hey @zoontek 

I tried testing it on real device as well the result is same, it seems bug with library.

Device: Moto G (2nd Generation)
OS: Marshmallow
Last Security Patch: 1 August 2016

**Comment by zoontek** [comment]
I just gave it a quick try on my Xiaomi A2, it works flawlessly.

<img width="300" src="https://user-images.githubusercontent.com/1902323/91732335-6503c380-eba8-11ea-9177-65bf6095ec1d.png" />

- What permission are you trying to request?
- Could you publish your `AndroidManifest.xml`?
- Did you tried the example app?

**Comment by NMahendroo** [comment]
I didn't request, I tried checking

```
 check(
        Platform.select({
            android: PERMISSIONS.ANDROID.ACCESS_FINE_LOCATION,
            ios: PERMISSIONS.IOS.LOCATION_WHEN_IN_USE,
        }),
    )
```

In Android Manifest the permission is there

 ```
<uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" />
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
```

I didn't try the TestApp.

**Comment by zoontek** [comment]
@NMahendroo I don't get it, if you don't request it, how did you set it in "Never ask again" state?
Try to play with the example app to understand how you have to articulate your code to use the lib.

**Comment by NMahendroo** [comment]
@zoontek 

I requested the location from Native Code, I have created a Bridge in Android.

But needed to check the current state of location permission that's why I used the "check" method provided by this library.

**Comment by zoontek** [comment]
This will not work. I asked you if you used the lib for requesting, you said yes (https://github.com/react-native-community/react-native-permissions/issues/504#issuecomment-683267165)

There is a reason: no API exists on Android to check if the permission is requestable or not except to store requested permissions in `SharedPreferences`

**Comment by i-m-aman** [comment]
I am checking the Camera permission, It is giving me RESULTS.BLOCKED. But the dialog still appears. and when the hit deny. The request Permission result is giving me RESULTS.DENIED. So, if the user again opens the apps, I will get RESULTS.BLOCKED and I have written different codes for handling when Perm is BLOCKED, but the user still can allow or deny the Perm. My code will not work properly. Tested on Pixel API 29 (Real Device).

**Comment by xclidongbo** [comment]
the same error.

**Comment by KrifaYounes** [comment]
same error
never permission returned blocked someone have an idea how to fix that ?

**Comment by poormohammadi** [comment]
Removing `tools:node="remove"` from AndroidManifest.xml fixed mine.
Replace 
`<uses-permission tools:node="remove" android:name="android.permission.CAMERA"/>` 
with 
`<uses-permission android:name="android.permission.CAMERA"/>`

**Comment by haidev01** [comment]
@NMahendroo I have the same issue, did you resolve this issue?

**Comment by Amarpsp10** [comment]
still, same issue returning `Never Ask Again` without asking!

**Comment by MAKARD** [comment]
2023, the issue is still here, reproducible on Emulator and on real devices (at least Samsung and Pixel)

**Comment by Amarpsp10** [comment]
hi @MAKARD , i resolved this problem by making these changes : 

1. adding legacy true in AndroidManifest

         .....
         <application
           android:requestLegacyExternalStorage="true"
         ....

2. Add this for permissions

         <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"  tools:node="replace"/>

3. make sure you have this attribute in above menifast tag 

         xmlns:tools="http://schemas.android.com/tools"
