### ISSUE TITLE
RNPermissions.isAvailable is undefined not a function

### ISSUE THREAD

**Issue by NMahendroo** [zoontek/react-native-permissions#505]
# Solution
RNPermissions.isAvailable is undefined not a function, issue comes up in version number 2.1.0, 2.2.0. While trying to check available permission.

I couldn't find the answer anywhere but I resolved it, so I am putting this in here

The promise returned by check function should have its "then" as well as "catch", in my code catch was missing that's why I was facing the said issue. It might help someone

**Code with Issue**

```
check(
        Platform.select({
            android: PERMISSIONS.ANDROID.ACCESS_FINE_LOCATION,
            ios: PERMISSIONS.IOS.LOCATION_WHEN_IN_USE,
        }),
    ).then(response => {
        switch (response) {
            case 'granted': //do my work
                break;
            case 'unavailable': //do my work
                break;
            case 'denied': //do my work
                break;
            case 'blocked': //do my work
                break;
        }
    })
```

**Working Code**

```
check(
        Platform.select({
            android: PERMISSIONS.ANDROID.ACCESS_FINE_LOCATION,
            ios: PERMISSIONS.IOS.LOCATION_WHEN_IN_USE,
        }),
    ).then(response => {
        switch (response) {
            case 'granted': //do my work
                break;
            case 'unavailable': //do my work
                break;
            case 'denied': //do my work
                break;
            case 'blocked': //do my work
                break;
        }
    }).catch(ex => {
        console.log("Permission Check Error", ex)
    })
```

**Comment by zoontek** [comment]
`isAvailable` is not a method exposed by this library (not in the documentation either)

**Comment by NMahendroo** [comment]
> `isAvailable` is not a method exposed by this library (not in the documentation either)

I also tried to search for the said method in my code as well but couldn’t find anything 

See my import for “check”

import { request, PERMISSIONS, openSettings, checkNotifications, requestNotifications, NotificationOption, check } from "react-native-permissions"

It got solved the moment I added the catch in promise.
