### ISSUE TITLE
Support for new limited access permission to media library (iOS 14) 

### ISSUE THREAD

**Issue by mtshv** [zoontek/react-native-permissions#508]
# Feature request
A new privacy feature in iOS 14 enables users to give an app access to a limited number of photos, instead of having to hand over the keys to their entire photo library.
![image](https://user-images.githubusercontent.com/11422166/92040252-2bd17c00-ed7f-11ea-9acd-5d7246690ac3.png)

The latest 2.2.0 version of react-native-permissions does not recognize the new PHOTO_LIBRARY permission type, in other words, right now we can not tell if the user granted full access or limited, both scenarios will result in `granted` status.

## Why it is needed
The problem I see: on iOS we ask for permissions only once. So if the user chooses this new option to give access to selected photos (for example gust to try it out) and then does not select any photos, or select only several, we won't be able to determine this and ask again for full access to Photos. The user would need to go to iOS setting and change camera roll permission to “Full Access” for the app.

If we could know that the user has granted limited access to Photo Libary we could react to this scenario.

## Possible implementation
Unfortunately, I am not familiar with native development, so I can not offer a solution at the moment, but I found this PR made by the expo team https://github.com/expo/expo/pull/9423

Here is an analogous issue from expo repo for reference: https://github.com/expo/expo/issues/9027

Is the implementation of this feature something, that we could expect before the release os iOS 14?

**Comment by Pingou** [comment]
Anyone working on this? It seem like a big issue to me, I can expect that plenty of users will not understand why they can only use the few photos they previously gave access permissions to, and the app will not be able to ask for permission again.

**Comment by zoontek** [comment]
@mtshv For now, I implemented a naive answer (`granted`) in the latest version (`2.2.2`). Discussion for proper implementation is available here: https://github.com/zoontek/react-native-permissions/pull/522

**Comment by zoontek** [comment]
I published a first beta for `3.0.0`: https://www.npmjs.com/package/react-native-permissions/v/3.0.0-beta.0
The migration guide is available here: https://github.com/zoontek/react-native-permissions/blob/3.0.0/MIGRATION.md 🙂
