### ISSUE TITLE
Logic Error in Location Permission

### ISSUE THREAD

**Issue by norman-kapschefsky** [zoontek/react-native-permissions#51]
Hi,
from my perspective there is a problem with the location permission and their options (always, whenInUse). I my app the `location` permission with option `always` is required but if the user sets it manually to `whenInUse` via device settings the permission request responses `authorized`. I've debugged a bit and found the reason in [RNPLocation.m](https://github.com/yonahforst/react-native-permissions/blob/4a94a298e3ac66e71c33522b7c39c3c6aee6a4c7/permissions/RNPLocation.m). When doing a `request` the first thing that is done is checking the status via `getStatus`.  There, in both cases (always and whenInUse) `authorized` is returned.

```
...
        case kCLAuthorizationStatusAuthorizedAlways:
        case kCLAuthorizationStatusAuthorizedWhenInUse:
            return RNPStatusAuthorized;
...
```

Now there is no logic in `request` method that does check the option parameter (`always`) that I have passed. That's why I get `authorized` from the api even it was **not** set to `always` in settings.

Please have an eye on it.

Thanks in advance. Norman

**Comment by daveols** [comment]
Not sure if this helps for your use case @norman-kapschefsky but I was able to only show "Never" or "Always" in the location services settings for my app to get around this, so `authorized` is guaranteed to be the "Always" permission.

Just remove `NSLocationWhenInUseUsageDescription` key from your `Info.plist`

Of course, if you're trying to offer both "While using the app" and "Always" options this won't be useful.

**Comment by jensellfors** [comment]
I am having the same problem, `Permissions.requestPermission('location', 'always')` returns `authorized` which is incorrect when I have set it to whenInUse in Settings.

@daveols your solution doesn't work for us since we allow people to use either always or whenInUse.

**Comment by yonahforst** [comment]
@jenshandersson @norman-kapschefsky - I'm now checking the type in `requestPermission` so if you request `always`, and it's authorized for `whenInUse`, it will return denied.

```js
    Permissions.getPermissionStatus('location')
      .then(response => {
         if (response == 'authorized') {
           return Permissions.requestPermission('location', 'always')
           // if permission was changed to whenInUse, this will return 'denied'
         }
        return response
      });

```

What do you think? does that solve this problem?

**Comment by jensellfors** [comment]
@yonahforst that works for me but it would be nice to be able to send `type` in getPermissionStatus too :) Thanks for the update!

**Comment by yonahforst** [comment]
yes, I'll have a think about the best way to do that.

**Comment by ParthGrover777** [comment]
I want to use two alerts approach for asking "whenInUse" and "always" both in two different alerts as per requirement. But if "whenInUse" type alert already appears once then another alert for "always" permission does not appear.
