### ISSUE TITLE
 Invalid ios permission "ios.permission.CAMERA,ios.permission.PHOTO_LIBRARY". Must be one of

### ISSUE THREAD

**Issue by xiao-shu-sheng** [zoontek/react-native-permissions#516]
"react": "16.13.1",
"react-native": "0.63.2",
"react-native-permissions": "^2.0.9",

Podfile

source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'roshi' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'roshiTests' do
    inherit! :complete
  end

 
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'roshi-tvOS' do

  target 'roshi-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

Info.plist
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>zh_CN</string>
	<key>CFBundleDisplayName</key>
	<string>随护护理版</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>$(PRODUCT_NAME)</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>1.0</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleVersion</key>
	<string>1</string>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
		<key>NSExceptionDomains</key>
		<dict>
			<key>localhost</key>
			<dict>
				<key>NSExceptionAllowsInsecureHTTPLoads</key>
				<true/>
			</dict>
		</dict>
	</dict>
	<key>NSCameraUsageDescription</key>
	<string>请允许使用您的相机</string>
	<key>NSPhotoLibraryUsageDescription</key>
	<string>如果不允许，您将无法正常获得手机相册里的照片。</string>
	<key>NSMicrophoneUsageDescription</key>
	<string>请允许使用您的麦克风</string>
	<key>NSLocationWhenInUseUsageDescription</key>
	<string></string>
	<key>UIRequiredDeviceCapabilities</key>
	<array>
		<string>armv7</string>
	</array>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
	</array>
	<key>UIViewControllerBasedStatusBarAppearance</key>
	<false/>
</dict>
</plist>

**Comment by qg-hs** [comment]
> "react": "16.13.1",
> "react-native": "0.63.2",
> "react-native-permissions": "^2.0.9",
> 
> Podfile
> 
> source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
> 
> require_relative '../node_modules/react-native/scripts/react_native_pods'
> require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
> 
> platform :ios, '10.0'
> 
> target 'roshi' do
> config = use_native_modules!
> 
> use_react_native!(:path => config["reactNativePath"])
> 
> target 'roshiTests' do
> inherit! :complete
> end
> 
> use_flipper!
> post_install do |installer|
> flipper_post_install(installer)
> end
> end
> 
> target 'roshi-tvOS' do
> 
> target 'roshi-tvOSTests' do
> inherit! :search_paths
> # Pods for testing
> end
> end
> 
> Info.plist
> 
> CFBundleDevelopmentRegion zh_CN CFBundleDisplayName 随护护理版 CFBundleExecutable $(EXECUTABLE_NAME) CFBundleIdentifier $(PRODUCT_BUNDLE_IDENTIFIER) CFBundleInfoDictionaryVersion 6.0 CFBundleName $(PRODUCT_NAME) CFBundlePackageType APPL CFBundleShortVersionString 1.0 CFBundleSignature ???? CFBundleVersion 1 LSRequiresIPhoneOS NSAppTransportSecurity NSAllowsArbitraryLoads NSExceptionDomains localhost NSExceptionAllowsInsecureHTTPLoads NSCameraUsageDescription 请允许使用您的相机 NSPhotoLibraryUsageDescription 如果不允许，您将无法正常获得手机相册里的照片。 NSMicrophoneUsageDescription 请允许使用您的麦克风 NSLocationWhenInUseUsageDescription UIRequiredDeviceCapabilities armv7 UISupportedInterfaceOrientations UIInterfaceOrientationPortrait UIViewControllerBasedStatusBarAppearance

您好   解决了吗

**Comment by xiao-shu-sheng** [comment]
没有,毫无头绪

**Comment by xiao-shu-sheng** [comment]
不知道那个地方出了问题

**Comment by qg-hs** [comment]
> 不知道那个地方出了问题

I tried version 2.0. + but it didn't work

**Comment by xiao-shu-sheng** [comment]
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'roshi' do

  permissions_path = '../node_modules/react-native-permissions/ios' //权限路径
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary.podspec" //这是你需要权限
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"    //这是你需要权限

  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'roshiTests' do
    inherit! :complete
  end

  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'roshi-tvOS' do

  target 'roshi-tvOSTests' do
    inherit! :search_paths
  end
end

**Comment by xiao-shu-sheng** [comment]
我是忘记了加这个才会报错，你把你你需要的加进去看看会不会报错了

**Comment by xiao-shu-sheng** [comment]
你的解决了木有？ @LiangQiangQiang

**Comment by qg-hs** [comment]
> 你的解决了木有？ @LiangQiangQiang
刚刚才试 还真是这个问题 😁   我的也弄好了  谢谢啦
