### ISSUE TITLE
Always getting unavailbe in ios camera permission

### ISSUE THREAD

**Issue by TaraSinghDanu** [zoontek/react-native-permissions#518]
Added 
permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"

added in info.plist file

but still I am always getting unavailable

**Comment by TaraSinghDanu** [comment]
without giving any solution how @zoontek  this is closed

**Comment by zoontek** [comment]
Duplicate + no respect of the issue template

**Comment by TaraSinghDanu** [comment]
@zoontek   no respect of the issue template means?
