### ISSUE TITLE
Always getting unavailbe in ios camera permission

### ISSUE THREAD

**Issue by TaraSinghDanu** [zoontek/react-native-permissions#520]
# Bug report

I am always getting unavailabe when trying to get camera permission status on ios device

Below is my code

const res = await check(PERMISSIONS.IOS.CAMERA);
    console.log('res', res)
    if (res === RESULTS.GRANTED) {
      setCameraGranted(true);
    } else if (res === RESULTS.DENIED) {
      const res2 = await request(PERMISSIONS.IOS.CAMERA);
      res2 === RESULTS.GRANTED ? setCameraGranted(true) : setCameraGranted(false);
    }

## Environment info

`react-native info` output:

```bash
System:
    OS: macOS 10.15.5
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 1.37 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29
      Build Tools: 23.0.1, 28.0.3, 29.0.0, 29.0.2, 29.0.3
      System Images: android-28 | Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6392135
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

Library version:2.2.0

I have added

permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
in pod file & pod install

added 
 <key>NSCameraUsageDescription</key>
  <string>YOUR TEXT</string>

in plist file.

**Comment by mikehardy** [comment]
https://github.com/react-native-community/react-native-permissions/issues?q=is%3Aissue+unavailable+is%3Aclosed

try `npx react-native-clean-project` after altering pods like that if it is still unavailable

**Comment by TaraSinghDanu** [comment]
@mikehardy  I have gone through all the past issues to unavailable but nothing worked.

**Comment by TaraSinghDanu** [comment]
Aactually the pods were not installed properly.

**Comment by mikehardy** [comment]
@TaraSinghDanu with no offense intended at all - as this is a common error I have made myself! - that's why it's the first thing we always emphasize, fully clean project and check pod install etc. It's such a common error. Glad you're moving forward and good luck with your project
