### ISSUE TITLE
iOS 14: LOCATION_WHEN_IN_USE and LOCATION_ALWAYS not working

### ISSUE THREAD

**Issue by kuraydev** [zoontek/react-native-permissions#521]
# Bug report

## Summary

In iOS 14, `LOCATION_WHEN_IN_USE` and `LOCATION_ALWAYS` permission not working properly. It can requestable but nothing comes back from the permission side. I cannot check whether or not permission is given. 

## Environment info

`react-native info` output:

```bash
System:
    OS: macOS 10.15.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 64.89 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.7 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK:
      Android NDK: 20.1.5948944
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 12.0/12A7209 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.12.0 => 16.12.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-asset: 2.0.0
    react-native-create-library: 3.1.2
    react-native-git-upgrade: 0.2.7
    react-native-rename: 2.4.1
    react-native: 0.59.10
```

Library version: 2.2.0

## Steps to reproduce

Simpy run the code segment: 

```js
 request(PERMISSIONS.IOS.LOCATION_WHEN_IN_USE).then((result) => {
    if (result === RESULTS.BLOCKED) showSettingsAlert(type);
    return result;
  });
```

Describe what you expected to happen:

- Get the permission is granted or not.

**Comment by zoontek** [comment]
Tested on iOS 14 right now without any issue:

<img src="https://user-images.githubusercontent.com/1902323/93786556-c101bb00-fc2f-11ea-8c83-c575c8c7c187.png" width="400" />

<img src="https://user-images.githubusercontent.com/1902323/93786526-b6dfbc80-fc2f-11ea-824e-fe786ff2687c.png" width="400" />

Are you tried to cleanup your build artifacts before recompiling for iOS 14?

**Comment by kuraydev** [comment]
> Tested on iOS 14 right now without any issue:
> 
> <img alt="" width="400" src="https://user-images.githubusercontent.com/1902323/93786556-c101bb00-fc2f-11ea-8c83-c575c8c7c187.png">
> 
> <img alt="" width="400" src="https://user-images.githubusercontent.com/1902323/93786526-b6dfbc80-fc2f-11ea-824e-fe786ff2687c.png">
> 
> Are you tried to cleanup your build artifacts before recompiling for iOS 14?

I will cleanup and re-try. If it still not works, I will share a minimal repo with you. Thank you so much for the quick reply. Really need this to work :)

**Comment by kuraydev** [comment]
@zoontek,
It works great on real devices but on the iOS 14 with the latest XCode (Currently 12.0) not working well. The request modal closes extremely fast therefore, it cannot be pressable. I was able to press it one or two times within so many trials. 

I just closed the issue but there is a problem on the Simulator tho. (Only on Location requests)

Thank you for the support @zoontek :)

**Comment by kuraydev** [comment]
@zoontek, Actually it really kills the development process when the location permission cannot be accepted or even rejected. Can you test it out on your side in the latest simulator? @zoontek

**Comment by zoontek** [comment]
@WrathChaos I didn't tried the latest simulator, but barely use it because of all the quirks it currently have.

**Comment by IronTony** [comment]
I have tested on both Simulator and real device with iOS 14 and I can confirm that is not working 😢

**Comment by kuraydev** [comment]
> I have tested on both Simulator and real device with iOS 14 and I can confirm that is not working 😢

It works on the real device from my side but completely not working on simulator :(

**Comment by IronTony** [comment]
@WrathChaos can you please post your configuration or similar? I cannot set ALWAYS using the package

**Comment by zoontek** [comment]
@IronTony Did you tried the example project?

**Comment by IronTony** [comment]
@zoontek Yes on a real device. Unfortunately it doesn't ask for "Always" in the location, as you can see (unfortunately it doesn't record the popup).

Small clip:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/3645225/93980445-ebae5980-fd7e-11ea-933a-a9fe33a2df8a.gif)


In the popup I can see this:
![93980297-ba358e00-fd7e-11ea-9e6d-fd867704efdb](https://user-images.githubusercontent.com/3645225/93980697-42b42e80-fd7f-11ea-8452-e6a19e8ccf4a.jpeg)

**Comment by kuraydev** [comment]
> @WrathChaos can you please post your configuration or similar? I cannot set ALWAYS using the package

Yep it does not even work for ALWAYS one but it does work with WHEN_IN_USE on real device.

**Comment by IronTony** [comment]
@zoontek  I found something strange while debugging on real iOS14 device.
I am asking these permissions:
`[PERMISSIONS.IOS.LOCATION_ALWAYS, PERMISSIONS.IOS.LOCATION_WHEN_IN_USE, PERMISSIONS.IOS.MOTION]`

The package opens this ![popup](https://user-images.githubusercontent.com/3645225/93980697-42b42e80-fd7f-11ea-8452-e6a19e8ccf4a.jpeg)

And if I press `Allow While Using App` (because there is no `Always`) I see these permissions from debugger:
`{ios.permission.LOCATION_ALWAYS: "granted", ios.permission.LOCATION_WHEN_IN_USE: "unavailable", ios.permission.MOTION: "granted"}`

but my settings on the iPhone tells me something different:
![IMG_6FFF6CD42F9A-1](https://user-images.githubusercontent.com/3645225/94135130-49b46d00-fe63-11ea-92ac-ed39305a4b52.jpeg)

**Comment by zoontek** [comment]
@IronTony First, you don't need to ask for `PERMISSIONS.IOS.LOCATION_ALWAYS` and `PERMISSIONS.IOS.LOCATION_WHEN_IN_USE`, only one of them.

Secondly, this behavior is "normal" on iOS (that might sound silly 😅). Check some Apple docs:
- https://developer.apple.com/documentation/corelocation/cllocationmanager/1620551-requestalwaysauthorization#3578736

When you request an `always` permission, iOS will display `Allow While Using App` / `Allow Once` /  `Don’t Allow`

👉 If you choose `Allow While Using App`, a `Provisional Always` permission will be granted. Programmatically, we receive `CLAuthorizationStatus.authorizedAlways`. The user will see "While Using" in settings, and later will be prompted that your app is using his location in background:

![](https://cms.qz.com/wp-content/uploads/2019/09/ios-13-locations-tesla-1920x982.jpg?quality=75&strip=all&w=1200&h=900&crop=1)

👉 If you choose `Allow Once`, a `When in use` permission will be granted. If you restart the app, the permission will be requestable again.

**Comment by zoontek** [comment]
Regarding the issue, I did a massive Xcode cleanup (trashed the `DerivedData` directory), and I am unable to reproduce the immediately closing permission popup after that, on device **and** on simulator.
Everything seems to works correctly (even if the notion of correctness given by Apple is super weird)

<img width="545" alt="Screenshot 2020-09-26 at 18 55 04" src="https://user-images.githubusercontent.com/1902323/94346318-1a9d2780-002c-11eb-8efa-d8f9af5a1ee7.png">

**Comment by kuraydev** [comment]
> Regarding the issue, I did a massive Xcode cleanup (trashed the `DerivedData` directory), and I am unable to reproduce the immediately closing permission popup after that, on device **and** on simulator.
> Everything seems to works correctly (even if the notion of correctness given by Apple is super weird)
> 
> <img alt="Screenshot 2020-09-26 at 18 55 04" width="545" src="https://user-images.githubusercontent.com/1902323/94346318-1a9d2780-002c-11eb-8efa-d8f9af5a1ee7.png">

I will make a reproducible example for you this weekend.

**Comment by IronTony** [comment]
@zoontek thank you so much for the explanation and sorry if I didn't write suddenly. I read the Apple Docs yesterday and yes it is silly.
Really appreciated your explanation.
Thank you so much also for the hint about the requests permissions

**Comment by kuraydev** [comment]
@zoontek, I've found the problem. It's all my fault. My business logic breaks the `react-native-permissions`. I was also using `react-native-gps-state` for better handling but it breaks the request modal. I removed the gps-state logic and it works like a charm!

Thank you so much @zoontek. Awesome work!

**Comment by Stophface** [comment]
> @IronTony First, you don't need to ask for `PERMISSIONS.IOS.LOCATION_ALWAYS` and `PERMISSIONS.IOS.LOCATION_WHEN_IN_USE`, only one of them.
> 
> Secondly, this behavior is "normal" on iOS (that might sound silly 😅). Check some Apple docs:
> 
>     * https://developer.apple.com/documentation/corelocation/cllocationmanager/1620551-requestalwaysauthorization#3578736
> 
> 
> When you request an `always` permission, iOS will display `Allow While Using App` / `Allow Once` / `Don’t Allow`
> 
> 👉 If you choose `Allow While Using App`, a `Provisional Always` permission will be granted. Programmatically, we receive `CLAuthorizationStatus.authorizedAlways`. The user will see "While Using" in settings, and later will be prompted that your app is using his location in background:
> 
> ![](https://camo.githubusercontent.com/e8357168f4c8e754adfd940fc065520de838a21a80001839d5e740c18893ec67/68747470733a2f2f636d732e717a2e636f6d2f77702d636f6e74656e742f75706c6f6164732f323031392f30392f696f732d31332d6c6f636174696f6e732d7465736c612d31393230783938322e6a70673f7175616c6974793d37352673747269703d616c6c26773d3132303026683d3930302663726f703d31)
> 
> 👉 If you choose `Allow Once`, a `When in use` permission will be granted. If you restart the app, the permission will be requestable again.

This, this should really stand somewhere in the docs. That could have saved me some complicated logic and headache how to handle these two requests ;)

**Comment by mikehardy** [comment]
@Stophface in "open source" the word "should" is best re-written as "here's a link to the PR" :-), the documents are open source and you could propose a change to them using the github web flow easily, exactly where developers need to see them since you just went through the process you probably have a perfect perspective on that

**Comment by Stophface** [comment]
@mikehardy Working on it

**Comment by Stophface** [comment]
@zoontek I have edited the `README` according to this #566. I cloned the project, made a new branch. But I am not allowed to push to your repository. I also have the updated `README` in a clone of the repository in my git https://github.com/Stophface/react-native-permissions. Do you want to include it?

**Comment by kuraydev** [comment]
@Stophface you can open a new Pull Request from your cloned repo then @zoontek can review and push it on official repo.

**Comment by Stophface** [comment]
@WrathChaos I am not sure how to open a Pull Request from my Repo. I cannot choose this Repo..

**Comment by kuraydev** [comment]
@Stophface 
![image](https://user-images.githubusercontent.com/6813862/107772110-ced5eb00-6d4c-11eb-8bfe-e0d8aad00170.png)

Fork the project, make the difference, commit and push the code on your forked repo and then come to this screen. You should see your repo/branch in this part.

**Comment by Stophface** [comment]
@WrathChaos I have not worked with Github in quite a while and did not find the `fork` button.
https://github.com/zoontek/react-native-permissions/pull/568

**Comment by jingyazh** [comment]
How can I get the example project?
