### ISSUE TITLE
A way to check if the system prompt has been shown for a given permission (iOS)

### ISSUE THREAD

**Issue by th0r0nd0r** [zoontek/react-native-permissions#523]
# Feature request

A way to check if the system prompt has been shown for a given permission (iOS)

## Why it is needed

I know this info is accessible natively, and I believe it used to be in this package under `undetermined`. Forgive me if I'm just misinterpreting the flowchart but there doesn't seem to be a deterministic way to check if the system prompt has been shown. There is a status called `BLOCKED` but the way I read the chart it means the following:

Checking permissions:
- the permission is 'not requestable'

Requesting permissions:
- the request was denied (seems like this case should instead be 'denied')

<img width="699" alt="Screen Shot 2020-09-30 at 9 03 49 AM" src="https://user-images.githubusercontent.com/29419913/94710673-f4ada680-02fb-11eb-9b7a-9374e4f67fee.png">

Again sorry if I'm just misreading this. Does `not requestable` === `system prompt hasn't been shown`?

**Comment by th0r0nd0r** [comment]
oh I think I get it. so the `BLOCKED` status is returned for iOS if the prompt has been seen and permissions denied? Whereas `DENIED` actually indicates that the prompt has not yet been shown?

**Comment by zoontek** [comment]
@th0r0nd0r Exactly! `BLOCKED` means that the permission has been requested, denied and is not requestable anymore. You  now have to encourage your user to open app settings to update the permission status.

`DENIED` means that the permission is requestable.

**Comment by th0r0nd0r** [comment]
Thanks for the explanation!
