### ISSUE TITLE
What is the correct setup for NSLocationAlwaysAndWhenInUseUsageDescription? 

### ISSUE THREAD

**Issue by hakkikonu** [zoontek/react-native-permissions#525]
Hello, I want to check `NSLocationAlwaysAndWhenInUseUsageDescription` permission. For my app Location permission must be **Always**. But `NSLocationAlwaysUsageDescription` Deprecated

How can I check 'always' allow location?

**Comment by zoontek** [comment]
You install the pod Permission-LocationAlways, setup `NSLocationAlwaysAndWhenInUseUsageDescription` and request PERMISSIONS.IOS.LOCATION_ALWAYS.

**Comment by hakkikonu** [comment]
NSLocationAlwaysUsageDescription Deprecated ?

**Comment by zoontek** [comment]
If you targets iOS 11+, yes. If you target iOS 10+, set both.

**Comment by hakkikonu** [comment]
thanks for your suggestion. i will try it
