### ISSUE TITLE
NSLocationAlwaysAndWhenInUseUsageDescription should be supported

### ISSUE THREAD

**Issue by hakkikonu** [zoontek/react-native-permissions#526]
According to Apple docs (https://developer.apple.com/documentation/corelocation/requesting_authorization_for_location_services)

`NSLocationAlwaysUsageDescription` Deprecated.

To check location 'always' status

we need `NSLocationAlwaysAndWhenInUseUsageDescription`

**Comment by zoontek** [comment]
It is: https://github.com/zoontek/react-native-permissions/blob/98e8f03ff746f8d3108239e19b12ce5cf0ab94ff/ios/LocationAlways/RNPermissionHandlerLocationAlways.m#L18
