### ISSUE TITLE
Stop AppState 'change' call while request for permission.

### ISSUE THREAD

**Issue by ashok-sl** [zoontek/react-native-permissions#528]
I am changing the app screen when the app in the inactive state using RN AppState.

My issue is whenever I request for any permission (Camera, Location etc.). It changes the AppState to the inactive state.

How do I stop the appstate handler call while requesting for permission?

 #436 

I have checked this issue but it won't much help for me.  My permission code and screen change code are on different screens.

**Comment by zoontek** [comment]
@ashok-sl Hi 👋
The permission request modal is not a part of your app, but a part of the system. The `AppState` module is right then: your app is in the background (losing focus) when you request a permission.

You can't prevent the `change` event, but you can add a state to indicate that you are currently requesting a permission, and ignore the change event in this case.
