### ISSUE TITLE
Android 10 does not request for permissions

### ISSUE THREAD

**Issue by lutakyn** [zoontek/react-native-permissions#531]
Android 10 does not request for permissions but the lower versions do ask for permissions

## Environment info
`react-native info` output:

```bash
OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz
    Memory: 114.93 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.13.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 24, 25, 26, 27, 28
      Build Tools: 26.0.2, 27.0.3, 28.0.3
      System Images: android-19 | Intel x86 Atom, android-21 | Google APIs Intel x86 Atom, android-22 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom, android-24 | Google Play Intel x86 Atom, android-27 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 11.3.1/11C505 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.1 => 0.61.1 
  npmGlobalPackages:
    create-react-native-app: 2.0.2
    react-native-git-upgrade: 0.2.7
```

Library version: 2.1.5

## Steps to reproduce

After installing library, I made multiple requests for other permissions like location, contacts. Nothing happens. But on the lower versions of Android,persmission are asked

Describe what you expected to happen:

I expect the App to request for permissions

**Comment by zoontek** [comment]
Which buildToolsVersion / targetSDK etc are set in your build.gradle? Android 10 is API 29.

**Comment by lutakyn** [comment]
targetSdkVersion 28,buildToolsVersion "28.0.1"

**Comment by zoontek** [comment]
Bump it to API 29 and retry

**Comment by kongjeey** [comment]
I have the same issue. I have buildToolsVersion = "29.0.2", targetSdkVersion = 29, react-native 0.63.2 and I'm testing it on android 11. Anything lower than android 10 works. If I add packages.add(new RNPermissionsPackage()); in MainApplication, it will crash the app (error: Native module RNPermissions tried to override RNPermissionsModule. Check the getPackages() method in MainApplication.java, it might be that module is being created twice.) So if I remove that line of code from MainApplication, app runs, (if I remove this, lower versions of android won't work) but it never asks me location permission. (permission status is always denied)

**Comment by zoontek** [comment]
@kongjeey @lutakyn The Android part of this library is just a proxy to react-native PermissionsAndroid. If something goes wrong, I suggest updating react native first to the latest version.

You can use https://react-native-community.github.io/upgrade-helper/ to do it. If you have the current version but you updated your app in the past, you might miss something in the Android config scripts.

I'm currently using the library with Android 10 too without any issues (react-native 0.63), even with Android 11.

**Comment by kongjeey** [comment]
@lutakyn I found the reason. So it was okay for me to remove `packages.add(new RNPermissionsPackage());` in MainApplication. Then I changed my code. Instead of `check` then `request` location permission, I just used `request(PERMISSIONS.ANDROID.ACCESS_FINE_LOCATION)` right away... I suggest double checking your logic.

**Comment by firdaussoberi** [comment]
> @lutakyn I found the reason. So it was okay for me to remove `packages.add(new RNPermissionsPackage());` in MainApplication. Then I changed my code. Instead of `check` then `request` location permission, I just used `request(PERMISSIONS.ANDROID.ACCESS_FINE_LOCATION)` right away... I suggest double checking your logic.

Strange, me too. check and request don't prompt anything on Android11. request straight away will prompt the permission on my android11 emulator.

Maybe my RN version is old, 0.60.4. library v 2.2.2

**Comment by AlexKwak** [comment]
I've got the same problem with Android 10: my app does not ask for permission, but sets(!) the permission for location to 'granted'. This should not even be possible, as from Android 6 on requesting a fine location requires the explicit permission from the user.
However, when manually setting the permission in the device itself to 'denied', the app DOES ask for permission.

Could you please reopen this issue?
regards, Alex.

**Comment by zoontek** [comment]
@AlexKwak As I could not reproduce the issue, I would love to have a small repository with the minimum amount of code necessary to reproduce what you say, if you can find a bit of time 🙂

**Comment by AlexKwak** [comment]
Hi, thanks for your extremely quick reply :-)

A small repo for this problem could be a problem as my code is part of a rather lage repo.
I will see what I can do in my limited time.

BTW, upgrading to 3.0.0-beta did not fix the problem.

Regards, Alex.

**Comment by zoontek** [comment]
@AlexKwak I understand that, but it will allow isolation of the issue, and if you cannot reproduce this too on a clean, lean, project, will indicate that the issue might not be with the library.

**Comment by AlexKwak** [comment]
@Sjaak: Op mijn testtoestel met Android 10 wordt bij een verse installatie geen toestemming gevraagd, maar wel door de app gegeven. Na handmatig op het toestel de toestemming terug te trekken wordt bij het starten van de app wel naar de toestemming gevraagd. Dit is niet conform de Android strategie waarbij voor een locatie altijd expliciet toestemming van de gebruiker gevraagd wordt.
