### ISSUE TITLE
 Request location permission "ALWAYS" on Android

### ISSUE THREAD

**Issue by victor9645** [zoontek/react-native-permissions#534]
When I request the location permission in android, it doesn't give me the option to give location permission "always"

**Comment by sangameshrently** [comment]
@zoontek In Android 10 & 11 it shows below options only.

<img width="453" alt="Screenshot 2020-10-27 at 12 58 30 AM" src="https://user-images.githubusercontent.com/46704888/97272778-9f2bc300-17ef-11eb-8168-26907a690d97.png">

**Comment by mikehardy** [comment]
This is a design choice from Google. The flow you must follow now is to if you target API30 and want always is to request permission then attempt to upgrade it with a new rationale. 

Please examine this thread for exactly how to do things in a way that you will not be rejected https://github.com/transistorsoft/react-native-background-geolocation/issues/1149

https://transistorsoft.github.io/react-native-background-geolocation-android/interfaces/_react_native_background_geolocation_android_.config.html#backgroundpermissionrationale

react-native-permissions here does not handle this for you and my guess is it will not handle it until someone in the community implements it in a quality PR (could be you!)

Hope this helps

**Comment by mikehardy** [comment]
(ios behaves similarly now actually - you request location once permission then you re-request for always in order to upgrade it if I understand correctly)
