### ISSUE TITLE
Add event listener for permissions change

### ISSUE THREAD

**Issue by hsavit1** [zoontek/react-native-permissions#535]
# Feature request

## Why it is needed
It would be excellent to be able to listen for changes in permission status, so that I can write a `usePermissions(permission)` hook.

## Possible implementation

[This project](https://github.com/3sidedcube/react-native-location-permissions/blob/master/ios/RNLocationPermissions.m) has the feature that im suggesting, but only for ios location permissions 

### Code sample

```
    useEffect(() => {
        Permissions.addEventListener("change", handlePermissionsStateChange)
        return () =>
            Permissions.removeEventListener("change", handlePermissionsStateChange)
    }, [permissionState])

```

**Comment by zoontek** [comment]
@hsavit1 This is hardly doable since not every permission handler could listen for status change.
Even the location one is not currently possible: The location manager is destroyed immediately once the permission check / request is done 😕

I suggest using `AppState` to perform a `checkMultiple` when the app regain focus: https://reactnative.dev/docs/appstate/#addeventlistener

**Comment by aboveyunhai** [comment]
@hsavit1  @zoontek  depending on the implementation, if you just want to make sure things run correctly. A easy way might be just put a permission check guard function before all your own functions that require specific permissions, skip the guard if permissions are granted. By this way you don't need to worry about permission changes at any time. I believe this doesn't even require any extra implementations from this package.

**Comment by zoontek** [comment]
@aboveyunhai That's exactly what is recommended by Apple / Google. I'm closing this since it's not really doable.

**Comment by paragspacetotech** [comment]
i guess we can write some custom hook to check using appState here is my implementation 
`import {AppState} from 'react-native';
import {useEffect, useState} from 'react';
import {Permission, check} from 'react-native-permissions';

const usePermissionListener = (
  requestePermission: Permission,
): [boolean, React.Dispatch<boolean>] => {
  const [status, setPermissionStatus] = useState<boolean>(false);

  useEffect(() => {
    const listener = AppState.addEventListener('change', async state => {
      if (state === 'active') {
        const result = await check(requestePermission);
        if (result === 'granted' || result === 'limited') {
          setPermissionStatus(true);
        } else if (result === 'denied' || result === 'blocked') {
          setPermissionStatus(false);
        }
      }
    });
    return () => {
      listener.remove();
    };
  }, [requestePermission, setPermissionStatus]);
  return [status, setPermissionStatus];
};

export default usePermissionListener;`

**Comment by jamalSlider** [comment]
Appstate will not work if user **enable/disable** location from **notification center**

**Comment by paragbarsar99** [comment]
Yes there are some limitations but the current approach does the work in most of the case.
Do you mean by disabling gps ? From the notification center.

**Comment by jamalSlider** [comment]
> Yes there are some limitations but the current approach does the work in most of the case. Do you mean by disabling gps ? From the notification center.

Yes

**Comment by zoontek** [comment]
@jamalSlider Enabling / disabling location doesn't change the permission status.

**Comment by jamalSlider** [comment]
> [@jamalSlider](https://github.com/jamalSlider) Enabling / disabling location doesn't change the permission status.

`import DeviceInfo from 'react-native-device-info';`
`const isLocationEnabled = await DeviceInfo.isLocationEnabled();`

this is how we can check if device location is enabled or not. Is there any way we can listen to this change?? we can call this on app state changes but the issue is android user can change it from notification center.
