### ISSUE TITLE
android dialog when permission is blocked

### ISSUE THREAD

**Issue by samaneh-kamalian** [zoontek/react-native-permissions#536]
# Bug report

## Summary

when call
`let result = await check(PERMISSIONS.ANDROID.READ_EXTERNAL_STORAGE);`
and result is `RESULTS.BLOCKED` , android dialog is opened.

## Environment info

`react-native info` output:
info Fetching system and libraries information...
System:
    OS: Linux 5.4 Ubuntu 18.04.5 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i5 CPU       M 480  @ 2.67GHz
    Memory: 272.98 MB / 7.63 GB
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 12.18.3 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: 4.9.0 - /home/linuxbrew/.linuxbrew/bin/watchman
  SDKs:
    Android SDK:
      API Levels: 23, 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 1.8.0_272 - /usr/bin/javac
    Python: 2.7.17 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: ^4.12.0 => 4.12.0 
    react: 16.13.1 => 16.13.1 
    react-native: ^0.63.2 => 0.63.2 
  npmGlobalPackages:
    *react-native*: Not Found

Library version: 2.2.2

Describe what you expected to happen:

I want to show my dialog that have a go to settings button!

**Comment by zoontek** [comment]
@samaneh-kamalian First, hello. Could you add more context?

**Comment by zoontek** [comment]
It seems that everything is normal here, if it returns `RESULTS.BLOCKED`, uses an `Alert` (https://reactnative.dev/docs/alert) + `openSettings()` to display a dialog to open app settings.

```js
let result = await check(PERMISSIONS.ANDROID.READ_EXTERNAL_STORAGE);

if (result === RESULTS.BLOCKED) {
  Alert.alert(
    'Open settings',
    'In order to grant permission, which is super needed, please open settings and…',
    [
      {
        text: 'Cancel',
        onPress: () => console.log('Cancel Pressed'),
        style: 'cancel',
      },
      {text: 'Open settings', onPress: openSettings},
    ],
    {cancelable: false},
  );
}
```

**Comment by samaneh-kamalian** [comment]
Thanks for your quick answer. 
It works well but to coordinate with the rest of the project, I want to use the dialogue I created myself but android default dialogue is opened and my dialogue is not shown. 
Is there any way?

**Comment by zoontek** [comment]
Please provide more code than just a single line.

**Comment by samaneh-kamalian** [comment]
```
    async requestStoragePermission() {

        let result = await check(PERMISSIONS.ANDROID.READ_EXTERNAL_STORAGE);
        if (result === RESULTS.GRANTED)
            return true;
        else if (result === RESULTS.BLOCKED) {
            this.setState({
                dialogVisible: true,
                dialogTitle: ApplicationTexts.UiTexts.changePermissionTitle,
                dialogContent: ApplicationTexts.UiTexts.changePermissionContent,
                actionOfFirstBtnOfDialog: this.inVisibleDialog,
                textOfFirstBtnOfDialog: ApplicationTexts.UiTexts.changePermissionAction_noAction,
                appearSecondBtnForDialog: true,
                actionOfSecondBtnOfDialog: this.goToSettingsPage,
                textOfSecondBtnOfDialog: ApplicationTexts.UiTexts.changePermissionAction_goToSettingsPage
            });
        }
        else if (result === RESULTS.DENIED) {
            let granted = await request(PERMISSIONS.ANDROID.READ_EXTERNAL_STORAGE);
            if (granted === RESULTS.GRANTED)
                return true;
            else
                return false;

        }

    }
```

**Comment by zoontek** [comment]
I guess something like this will work:

```js

async function requestStoragePermission() {
  const result = await check(PERMISSIONS.ANDROID.READ_EXTERNAL_STORAGE);

  if (result === RESULTS.GRANTED) {
    return true;
  }

  if (result === RESULTS.UNAVAILABLE) {
    return false;
  }

  if (result === RESULTS.DENIED) {
    return (await request(PERMISSIONS.ANDROID.READ_EXTERNAL_STORAGE)) === RESULTS.GRANTED;
  }

  if (result === RESULTS.BLOCKED) {
    return new Promise((resolve) => {
      Alert.alert(
        'Open settings',
        'In order to grant permission, which is super needed, please open settings and…',
        [
          {
            text: 'Cancel',
            onPress: () => console.log('Cancel Pressed'),
            style: 'cancel',
          },
          {text: 'Open settings', onPress: () => resolve(openSettings())},
        ],
        {cancelable: false},
      );
    });
  }
}
```

**Comment by samaneh-kamalian** [comment]
Perfect. thanks a lot.
