### ISSUE TITLE
Add USE_FULL_SCREEN_INTENT for android

### ISSUE THREAD

**Issue by redexp** [zoontek/react-native-permissions#539]
# Feature request

Add [USE_FULL_SCREEN_INTENT](https://developer.android.com/reference/android/Manifest.permission#USE_FULL_SCREEN_INTENT)

## Why it is needed

To create full screen notification (usually over lock screen for voip apps)

**Comment by zoontek** [comment]
The documentation say that its `Protection level` is `normal`.
You don't need to request it at runtime.

**Comment by zoontek** [comment]
See https://developer.android.com/about/versions/10/behavior-changes-10

> This is a normal permission, so the system automatically grants it to the requesting app.

**Comment by redexp** [comment]
@zoontek thanks, you right

**Comment by vivkikkk** [comment]
+ 1 Now Android 34 Request

**Comment by KolissnikBogdan** [comment]
check android 14 change log, + 1
