### ISSUE TITLE
iOS 14 APP_TRACKING_TRANSPARENCY request not showing up?

### ISSUE THREAD

**Issue by tarouboy** [zoontek/react-native-permissions#544]
# Bug report

When I run request(PERMISSIONS.IOS.APP_TRACKING_TRANSPARENCY) it doesn't show up a dialog like other permission.

## Environment info

iOS 14 simulator & device

`react-native info` output:

```bash
# paste it here
```
react: 16.13.1 => 16.13.1 
react-native: 0.63.3 => 0.63.3 
Library version: 2.2.2

## Steps to reproduce

1. just call request(PERMISSIONS.IOS.APP_TRACKING_TRANSPARENCY)

Describe what you expected to happen:

1. expect a dialog and let user to grant permission

**Comment by zoontek** [comment]
@tarouboy Did you read this? Probably a duplicate: https://github.com/zoontek/react-native-permissions/issues/541#issuecomment-731221451

**Comment by tarouboy** [comment]
Sorry I missed. I tried to search but didn't use the right keyword. Thank you for pointing out.

**Comment by zoontek** [comment]
No problem!
