### ISSUE TITLE
Camera permissions on iOS 14 not behaving as expected if user blocks permission

### ISSUE THREAD

**Issue by Rehubbard** [zoontek/react-native-permissions#545]
## Summary
 If a user denies camera permissions (PERMISSIONS.IOS.CAMERA), `check` and `request` do NOT return `RESULTS.DENIED`. Which is what I expected them to return if the user denies camera permission by pressing "Don't Allow".

It works locally when I test on Xcode with a device running iOS 14. But it breaks and behaves as described when I test in TestFlight. Which is the really strange part.

## Environment info

Library version: 3.0.0-beta.2

## Steps to reproduce

1. Run app in production-like environment (Testflight) on iOS 14
2. Call `check` or `request` to prompt for camera permission
3. Deny permissions by pressing "Don't Allow"

Describe what you expected to happen:

1. User selects "Don't Allow" when prompt for camera permissions
2. I expect to be the promise to resolve with RESULTS.BLOCKED and to be able to handle it accordingly

## Reproducible sample code

Here's where I call `check` and `request`. It's a simple method that checks permissions and requests if necessary. Returns `true` or `false` based on permissions. It's returning  `true` when I expect it to return `false` for permission denied.

```
const checkCameraPermissions = () => {
  const permission = isAndroid
    ? PERMISSIONS.ANDROID.CAMERA
    : PERMISSIONS.IOS.CAMERA
  return check(permission).then((result) => {
    switch (result) {
      case RESULTS.DENIED:
        return request(permission, {
          title: 'Camera Permission ',
          message:
            'App needs access to your camera for your profile photo and photo tasks in various jobs.'
        }).then((result) => {
          if (result === RESULTS.GRANTED) {
            return true
          } else {
            return false
          }
        })
      case RESULTS.GRANTED:
        return true
      case RESULTS.BLOCKED:
        return false
      default:
        return false
    }
  })
}
```

**Comment by zoontek** [comment]
Hi. I couldn't reproduce it, even with a production app.

**Comment by JohnTheo13** [comment]
ios version > 14 camera permissions return unavailable

**Comment by KhimGurung** [comment]
Best thing you can do is, check if it is blocked or not and if the result is blocked simply alert user asking to unblock from setting manually.
```
            if(result === RESULTS.BLOCKED)
                Alert.alert("Camera is blocked!", "Please go to the setting and unblock it.")
```

**Comment by tkmin** [comment]
```
import { Alert, Linking } from 'react-native';
...
Alert.alert(
  "blocked",
  "go to setting and unblock it",
  [
    { text: 'no', style: 'cancel' },
    { text: 'ok', onPress: Linking.openSettings },
  ]
);
```
