### ISSUE TITLE
openLimitedPhotoLibraryPicker callback when done

### ISSUE THREAD

**Issue by romancxx** [zoontek/react-native-permissions#552]
# Feature request

Hey, great package, it's been really helpful to develop my app. I'm currently using the `openLimitedPhotoLibraryPicker` method to handle a case where users want to update their selection. I would find really helpful a callback when the user is done with updating his selected photos. 

## Why it is needed

Since I can't know when the user is done by using `.then()` it's hard for my app to know when to re get the camera roll pictures to see the new selected pictures in the result. 

## Possible implementation

Adding a `onFinish` callback param to the function would do the job.
Or `.then()` should be called only when selection is finished 

Thanks again for this package, have a good day!

**Comment by zoontek** [comment]
@Nazort The native code does not offer this kind of callback. The only way to do it is currently to wait for the `AppState` status change. This could be done on the native side, but also on the JS side.

**Comment by romancxx** [comment]
@zoontek Thanks for the quick answer and advice, I will implement something using `AppState` then

**Comment by romancxx** [comment]
I've tried doing something using AppState but with a `listenener` listening on state change, it does not get trigger when the modal is opened or closed, the app stays active at all time.

**Comment by gabriprat** [comment]
I also tried with `AppState` listeners with no luck. Also with navigation and layout events. I found no way of detecting that the user is done with updating his selected photos. Can we reopen the issue?

**Comment by thuannv-wrethink** [comment]
Can not find out a solution for this issue. Can someone help me?

**Comment by OmarBasem** [comment]
If native code does not offer this kind of callback, and the app state does not change, then how other apps like Instagram do it?

**Comment by OmarBasem** [comment]
From Apple's documentation: "Any changes the user applies to their limited library selection trigger a PHPhotoLibraryChangeObserver update that you can observe to see the changes to their selection."

**Comment by mohamed2m2018** [comment]
I think openLimitedPhotoLibraryPicker is with no use without the callback after selection.
@zoontek

**Comment by mikehardy** [comment]
Sounds like a PR might prove the point and stand a chance of integration!

**Comment by andvalsol** [comment]
why this issue was closed? Has this callback been implemented?

**Comment by mikehardy** [comment]
@andvalsol I don't recall seeing a PR from you?

The original author closed it, because they were satisfied:

> Thanks for the quick answer and advice, I will implement something using AppState then

And the comment trail appears to have died here:

> Sounds like a PR might prove the point and stand a chance of integration!

All of this is self-evident from reading the comments.
