### ISSUE TITLE
IOS Crash

### ISSUE THREAD

**Issue by basith374** [zoontek/react-native-permissions#56]
Hi i am new to IOS development. I installed `react-native-permissions` but the ios simulator app wont start now. 

* when running from xcode, this shows
![screen shot 2016-12-24 at 7 35 00 pm](https://cloud.githubusercontent.com/assets/10130692/21467345/21e04186-ca10-11e6-932f-c1fd67fabdc0.png)

* when running `react-native run-ios`, this shows
`An error was encountered processing the command (domain=NSMachErrorDomain, code=-308):
The operation couldn’t be completed. (Mach error -308 - (ipc/mig) server died)`

I followed your steps correctly:
1. npm install --save react-native-permissions
2. rnpm link

what am i missing here?

**Comment by KarlosQ** [comment]
The solution for this error is create the Privacy description in Xcode.

To fix this go to Xcode -> Targets Name of your project -> Info -> Create new Key with the permission example Privacy - Photo Library Usage Description

**Comment by yonahforst** [comment]
Thanks @KarlosQ!
