### ISSUE TITLE
Error: react-native-permissions: NativeModule.RNPermissions is null

### ISSUE THREAD

**Issue by michael0793** [zoontek/react-native-permissions#560]
I get below error, how to fix im trying to work on making a qr code scanner 

Error: react-native-permissions: NativeModule.RNPermissions is null. To fix this issue try these steps:
  • If you are using CocoaPods on iOS, run `pod install` in the `ios` directory and then clean, rebuild and re-run the app. You may also need to re-open Xcode to get the new pods.
  • If you are getting this error while unit testing you need to mock the native module. You can use this to get started: https://github.com/react-native-community/react-native-permissions/blob/master/mock.js
  If none of these fix the issue, please open an issue on the Github repository: https://github.com/react-native-community/react-native-permissions
Module.../../../../../../../../../Desktop/SVAVOT/SVAVOTPROJECT/node_modules/react-native-permissions/lib/module/index.js
C:/Users/PC/Desktop/SVAVOT/SVAVOTPROJECT/index.ts:6
  3 | import {module} from './module';
  4 | 
  5 | if (NativeModules.RNPermissions == null) {
> 6 |   throw new Error(`react-native-permissions: NativeModule.RNPermissions is null. To fix this issue try these steps:
  7 |   • If you are using CocoaPods on iOS, run \`pod install\` in the \`ios\` directory and then clean, rebuild and re-run the app. You may also need to re-open Xcode to get the new pods.
  8 |   • If you are getting this error while unit testing you need to mock the native module. You can use this to get started: https://github.com/react-native-community/react-native-permissions/blob/master/mock.js
  9 |   If none of these fix the issue, please open an issue on the Github repository: https://github.com/react-native-community/react-native-permissions`);
View compiled
__webpack_require__
C:/Users/PC/Desktop/SVAVOT/SVAVOTPROJECT/webpack/bootstrap:789
  786 | };
  787 | 
  788 | // Execute the module function
> 789 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  790 | 
  791 | // Flag the module as loaded
  792 | module.l = true;

**Comment by zoontek** [comment]
Hello 👋 Please search for duplicate issues first: https://github.com/zoontek/react-native-permissions/issues?q=is%3Aissue+null
