### ISSUE TITLE
Requesting a permission doesn't display on top of current react native view

### ISSUE THREAD

**Issue by ghost** [zoontek/react-native-permissions#561]
# Bug report

## Summary

When requesting permissions the popup is displayed in the base view controller / activity, instead of on top of the current react native screen. At the moment it displays on top of the initial screen when the app is powered app and then go back to where the user is before requesting the permission. 

It would be better if it's shown on top of the react native view context.

## Environment info
Android, iOS 

Library version: 3.0.0

## Steps to reproduce
1. Request any permission
2. The permission modal is displayed on top of lunching screen instead of current react native screen

Describe what you expected to happen:
1. Request any permission
2. The permission modal is displayed on top current react native screen

**Comment by zoontek** [comment]
I don't understand the issue. Could you provide more context (does it happen on Android, on iOS? Which OS version? Do you have a screen video capture)? Which other libs are you using?

**Comment by ghost** [comment]
Let's say my splash screen is dark like this, and that I request a permission from another screen, when it displays the permission modal it shows it on top of the splash screen as below. It happens on Android and iOS and the version doesn't matter as it happens regardless of that. I'm using the latest version 3.0.0

<img width="459" alt="Screen Shot 2021-01-22 at 3 56 23 PM" src="https://user-images.githubusercontent.com/3595076/105441038-9bafb700-5ccc-11eb-9ec9-733ebd452750.png">

**Comment by zoontek** [comment]
@proverbface Which lib are you using for your splash screen? (PS: This is not recommended to ask for permissions while the splash screen is visible, and your issue is probably not related to this library - but we can try to resolve it)

**Comment by ghost** [comment]
This issue was not an issue with this library. Thanks for the support and the awesome work. Closing this issue.
