### ISSUE TITLE
Overlay permission already granted in android

### ISSUE THREAD

**Issue by arbab-io** [zoontek/react-native-permissions#562]
# Feature request

I hope you all doing fine but I am not please help me I am facing an issue and it has been headache for me. Actually issue is related to react native overlay permission current progress is we have to ask user manually for the permission but I want something like WhatsApp, In which system automatically grants the overlay permission in any android version. Any link or any thought of you will be helpful to me

**Comment by zoontek** [comment]
@arbabr96 Hi, could you provide more informations about your request?

**Comment by arbab-io** [comment]
> @arbabr96 Hi, could you provide more informations about your request?

I want to create a service which ask and grant 4 to 5 permissions by clicking one button

**Comment by anniewey** [comment]
@zoontek is there a way to request for draw overlay permission?
