### ISSUE TITLE
PERMISSIONS.ANDROID.ACCESS_BACKGROUND_LOCATION not triggering a prompt

### ISSUE THREAD

**Issue by nschild** [zoontek/react-native-permissions#570]
# Bug report

## Summary
PERMISSIONS.ANDROID.ACCESS_BACKGROUND_LOCATION not triggering a prompt

## Environment info

`react-native info` output:

```bash
(node:8124) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
System:
    OS: macOS 11.2.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 329.77 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.15.5 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.11 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 29, 30
      Build Tools: 29.0.2, 30.0.3
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_282 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: ^0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 3.0.0

## Steps to reproduce
1) fresh install app or reset all permissions to "ask"
2) request for background permission

Describe what you expected to happen:
to get a prompt

## Reproducible sample code
```
const requestBackgroundLocationPermissions = () => {
  const permissionsKey = Platform.OS === 'ios' ? PERMISSIONS.IOS.LOCATION_ALWAYS : PERMISSIONS.ANDROID.ACCESS_BACKGROUND_LOCATION;
  Permissions.request(permissionsKey).then((response: PermissionStatus) => {
    console.log('response', response) // denied

  })
  .catch((err: any) => console.log(err));
};
```

**Comment by naru200** [comment]
https://developer.android.com/reference/android/Manifest.permission#ACCESS_BACKGROUND_LOCATION

> Allows an app to access location in the background. If you're requesting this permission, you must also request either ACCESS_COARSE_LOCATION or ACCESS_FINE_LOCATION. Requesting this permission by itself doesn't give you location access.

You have to request ACCESS_COARSE_LOCATION or ACCESS_FINE_LOCATION too.

try this:

```
const permissionsKeys =
  Platform.OS === 'ios'
    ? [PERMISSIONS.IOS.LOCATION_ALWAYS]
    : [PERMISSIONS.ANDROID.ACCESS_BACKGROUND_LOCATION, PERMISSIONS.ANDROID.ACCESS_FINE_LOCATION]; // or ACCESS_COARSE_LOCATION
Permissions.requestMultiple(permissionsKeys).then((response: PermissionStatus) => {
  console.log('response', response)

})
```

**Comment by zoontek** [comment]
@naru200 is right. It's weird, but it's the official API 🤷🏻‍♂️

**Comment by Yandamuri** [comment]
@naru200 is this really working for you to open prompt for `PERMISSIONS.ANDROID.ACCESS_BACKGROUND_LOCATION`?

When tired to request for both `ACCESS_BACKGROUND_LOCATION` and `ACCESS_FINE_LOCATION` nothing is happening.

**Comment by panda6412** [comment]
@zoontek Is this issue resolved, I request both PERMISSIONS.ANDROID.ACCESS_BACKGROUND_LOCATION and PERMISSIONS.ANDROID.ACCESS_FINE_LOCATION, but still nothing show on Android 11.

Is anything I missed :( ?

**Comment by Jenovas** [comment]
@panda6412 I'd recommend reading about the permission changes that were introduced in Android 11. https://developer.android.com/training/location/permissions#background

![image](https://user-images.githubusercontent.com/1244154/177965143-96339d76-0a7f-463a-91d6-9df6242624b3.png)

**Comment by roni-castro-shipt** [comment]
> [@panda6412](https://github.com/panda6412) I'd recommend reading about the permission changes that were introduced in Android 11. https://developer.android.com/training/location/permissions#background
> 
> ![image](https://user-images.githubusercontent.com/1244154/177965143-96339d76-0a7f-463a-91d6-9df6242624b3.png)


Updated link
https://developer.android.com/about/versions/11/privacy/location#request-background-location-separately

<img width="908" height="200" alt="Image" src="https://github.com/user-attachments/assets/81a66312-4f9b-4f78-8b2f-d5c73009a3af" />
