### ISSUE TITLE
Readme misleading for android user manual link import com.zoontek.rnpermissions.RNPermissionsPackage

### ISSUE THREAD

**Issue by zico4reel** [zoontek/react-native-permissions#574]
Hi Everyone,

I couldn't tell for sure were to add this issue under, but the Readme for manual linking is kinda misleading

as it is no longer
`import com.zoontek.rnpermissions.RNPermissionsPackage;`

but now
 `import com.reactnativecommunity.rnpermissions.RNPermissionsPackage;`

I am not sure who this might help, but to who ever this is relevant to, I wish you best of luck and good luck

**Comment by zico4reel** [comment]
Also, I will love to add if you're facing the RNPermission null thing on Android, while working on a windows OS or any other OS it may pop up, I think it is simply best you manual link

**Comment by zoontek** [comment]
@zico4reel Are you using v3 (current version, current README)? Did you clean your Gradle cache?

Because the namespace is correct: https://github.com/zoontek/react-native-permissions/blob/3.0.1/android/src/main/java/com/zoontek/rnpermissions/RNPermissionsPackage.java#L1

**Comment by zico4reel** [comment]
Hi, my apologies, I just checked, it is version 2.2.2, as it was installed as a dependency package.

**Comment by zoontek** [comment]
@zico4reel Check the documentation for your version here: https://github.com/zoontek/react-native-permissions/tree/2.2.2
