### ISSUE TITLE
App Tracking Transparency Permissions return Granted for ios < 14

### ISSUE THREAD

**Issue by jonathangilbert02** [zoontek/react-native-permissions#575]
# Bug report

## Summary

When using ios < 14 and checking PERMISSIONS.IOS.APP_TRACKING_TRANSPARENCY value, it returns GRANTED. 

Since the feature is not available pre ios 14 device as per apple, I would expect it to be UNAVAILABLE.

## Environment info

Library version: 3.0.0

## Steps to reproduce

1. Check PERMISSIONS.IOS.APP_TRACKING_TRANSPARENCY with an ios version < 14
2. Result is GRANTED

Describe what you expected to happen:

1. Check PERMISSIONS.IOS.APP_TRACKING_TRANSPARENCY with an ios version < 14
2. Result is UNAVAILABLE.

## Reproducible sample code

```
import {check, PERMISSIONS, RESULTS} from 'react-native-permissions';

check(PERMISSIONS.APP_TRACKING_TRANSPARENCY)
  .then((result) => {
    switch (result) {
      case RESULTS.UNAVAILABLE:
        console.log('This feature is not available (on this device / in this context)');
        break;
      case RESULTS.DENIED:
        console.log('The permission has not been requested / is denied but requestable');
        break;
      case RESULTS.LIMITED:
        console.log('The permission is limited: some actions are possible');
        break;
      case RESULTS.GRANTED:
        console.log('The permission is granted');
        break;
      case RESULTS.BLOCKED:
        console.log('The permission is denied and not requestable anymore');
        break;
    }
  })
  .catch((error) => {
    // …
  });
```

**Comment by zoontek** [comment]
On iOS 14, it uses https://developer.apple.com/documentation/adsupport/asidentifiermanager/1614148-advertisingtrackingenabled?language=objc instead.

Which was, if you check the warning, the previous way of checking it 🙂

**Comment by jonathangilbert02** [comment]
With the current module documentation I was expecting to see RESULTS.UNAVAILABLE since the feature was not available prior to ios 14. 

I understand there was a parameter _isAdvertisingTrackingEnabled_  as you mentioned but if i'm not mistaken there is no permission request related to it, so receiving RESULTS.GRANTED/RESULTS.DENIED could be quite misleading since the permission is not requestable or was not requested on version prior to ios 14

**Comment by zoontek** [comment]
@jonathangilbert02 `APP_TRACKING_TRANSPARENCY` is just the new name, but it the replacement of `isAdvertisingTrackingEnabled`. If you use the check / request pattern it will work flawlessly with any iOS version. That's the goal, not having to handle OS retrocompatibility.
