### ISSUE TITLE
Can we delay WRITE/READ_EXTERNAL_STORAGE permission requests until a specific time, rather than app launch?

### ISSUE THREAD

**Issue by trackwell-mike** [zoontek/react-native-permissions#578]
# Bug report

## Summary

Our project uses both `READ_EXTERNAL_STORAGE` and `WRITE_EXTERNAL_STORAGE` permissions so we can have a user select images from their phone's image gallery, and save to the gallery/storage.

The problem is that when the user installs the app and the app FIRST LAUNCHES, it requests these permissions. We would rather show this permission request when they perform an action that actually requests access to the gallery/storage. **Is this possible?**

<img width="300" src="https://user-images.githubusercontent.com/61172689/111799850-c61f8a00-88a1-11eb-9038-59245b747807.png">

```bash
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
```

## Environment info

`react-native info` output:

```bash
System:
    OS: macOS 11.2.3
    CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
    Memory: 1.86 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 15.9.0 - ~/.nvm/versions/node/v15.9.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.5.3 - ~/.nvm/versions/node/v15.9.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 29, 30
      Build Tools: 29.0.2, 30.0.1, 31.0.0
      System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_282 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: ^4.14.0 => 4.14.0 
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 3.0.1

**Comment by zoontek** [comment]
Hi! Where do you perform the `request()` call?

**Comment by trackwell-mike** [comment]
Hi @zoontek - Thanks for getting back to me. I needed to double-check with my team, but we do not call `request()` at app initialization. I'm not sure if this shot helps, but we call the `request()` function (line 854 in the screenshot) inside another function we use for asking the save option in Save Photo and Preview.

![](https://user-images.githubusercontent.com/61172689/111989658-71ba1b80-8ae8-11eb-9c40-f62af320b3f5.png)

**Comment by zoontek** [comment]
@trackwell-mike And are you sure this method is not called at start?

Did you tried the example app to check if a similar issue happen on the same testing conditions?

https://github.com/zoontek/react-native-permissions/tree/master/example

**Comment by trackwell-mike** [comment]
@zoontek Thank you for your quick reply. We haven't tried the example app. I'm positive we are not calling this method at start.

*   The only place we are calling `request()` is in this `hasAndroidPermission()` function, and 
*   The only place we're calling that is in `savePicture()` function, and
*   The only place we're calling that is when the user is opening the camera.

![](https://user-images.githubusercontent.com/61172689/111994222-ea6fa680-8aed-11eb-9cfb-327a8e110f21.png)

![](https://user-images.githubusercontent.com/61172689/111994705-71bd1a00-8aee-11eb-8e20-62bd9f2da9f6.png)

![](https://user-images.githubusercontent.com/61172689/111994656-5f42e080-8aee-11eb-8cf0-624ccbeef127.png)

**Comment by zoontek** [comment]
@trackwell-mike Could you try the example app? I cannot reproduce the issue.

**Comment by mikehardy** [comment]
I don't reproduce this either. Permissions are not requested *by this module* unless and until you run the request API. This is project-specific, maybe some other project module doing it.

**Comment by trackwell-mike** [comment]
@mikehardy - Thanks for chiming in as well. (Also appreciate your help getting `react-native-fbsdk` forked for the new SDK)

We are going to completely remove `react-native-permissions` from our project and see if that still causes the permission request. If it does, we'll know it's another library requesting it (like Instabug or something else we might be using). We should have done this prior to writing you guys, but I appreciate you double-checking that the library doesn't request permission prior to calling `request()`. /cc @zoontek

**Comment by zoontek** [comment]
Thanks for the confirmation!
