### ISSUE TITLE
requesting permission for microphone fails using the ios simulator

### ISSUE THREAD

**Issue by anttitakalahti** [zoontek/react-native-permissions#58]
calling:
      Permissions.requestPermission('microphone')
      .then((permissionMicrophone) => {
        console.log('permissionMicrophone:', permissionMicrophone);

results in:
2017-01-02 09:22:26.381 [info][tid:com.facebook.react.JavaScript] 'permissionMicrophone:', 'undetermined'

when using the simulator. It also does not show microphone in the settings where permissions are handled. 

![screen shot 2017-01-02 at 9 22 42](https://cloud.githubusercontent.com/assets/837046/21585648/607beddc-d0cd-11e6-9dd3-04e26bdf6047.png)

Anyone else seeing this? I wonder if this is an issue with the xcodes simulator since it works fine using an actual device.

**Comment by rikner** [comment]
thx for mentioning. did not try it on an actual device and thought it doesn't work at all
btw: 
 "react-native": "^0.38.0",
"react-native-permissions": "^0.2.5",

**Comment by mzmiric5** [comment]
yup I'm seeing the same issue on RN 0.40. Works fine on device but not working on the simulator

**Comment by yonahforst** [comment]
This seems to be a known issue with iOS  -http://stackoverflow.com/questions/18957643/requestrecordpermission-does-nothing?rq=1.

I'll add it to the readme.
