### ISSUE TITLE
RECORD_AUDIO permission on Android does not show prompt and is automatically granted.

### ISSUE THREAD

**Issue by abdulajet** [zoontek/react-native-permissions#581]
# Bug report

## Summary

When requesting the `RECORD_AUDIO` permission for android it shows no prompt and is automatically granted even though it needs to be explicitly requested https://developer.android.com/training/permissions/requesting

When i run the app from android studio the prompt shows as expected. 

## Environment info

`react-native info` output:

```bash
System:
    OS: macOS 11.2.1
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 46.33 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.18.2 - ~/.nvm/versions/node/v12.18.2/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 7.7.0 - ~/.nvm/versions/node/v12.18.2/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /Users/aajetunmobi/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 23, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.3
      System Images: android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7199119
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_282 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.4 => 0.63.4
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 3.0.1

## Steps to reproduce

1. run the project with `npx react-native run-android
2. See no prompt
3. delete the app
4. run from android studio
5. see prompt

Describe what you expected to happen:

1. run the project with `npx react-native run-android
2. See prompt

## Reproducible sample code
https://github.com/abdulajet/rnptest

**Comment by zoontek** [comment]
@abdulajet Hi! Do you use a particular version of Android? (modified by Samsung or else). When it returns `granted`, is using the microphone really possible or is it a false positive?

**Comment by abdulajet** [comment]
I am using a pixel 4 emulator on API version 30. The microphone works, only issue if the lack of prompt

**Comment by zoontek** [comment]
@abdulajet And the check method also return granted? By using the check / request pattern, it's not really an issue for the library 🙂

**Comment by abdulajet** [comment]
> it's not really an issue for the library

likely an issue with react-native then?

Thanks for the quick response

**Comment by zoontek** [comment]
I think it's more an issue with the Android version on your device. Neither React Native or this library can bypass the Android permissions system.

Edit: I saw you use the emulator. Did you tried on a real device?

**Comment by abdulajet** [comment]
excellent point.

i don't have a device, will try next week. feel free to close the issue 🙂

**Comment by zoontek** [comment]
@abdulajet Ok let's do that. Don't hesitate to publish feedbacks once you tried 🙂
