### ISSUE TITLE
Which version supports 0.59?

### ISSUE THREAD

**Issue by lyrpromax** [zoontek/react-native-permissions#583]
I'm working on integrating QR code scanning on RN 0.59, but unfortunately I can't find a support version for 0.59

**Comment by mikehardy** [comment]
git blame the version line in the README - it says 1.2.x were the last versions that supported pre-0.60

https://github.com/zoontek/react-native-permissions/blame/4d0bb99a57a618e8f298d41a9036a4a573167b7e/README.md
