### ISSUE TITLE
Is there a way to use this using RN version 59.9?

### ISSUE THREAD

**Issue by ericksondelacruz** [zoontek/react-native-permissions#585]
## Summary

I am having this kind of issue [!] Unable to find a specification for `RNPermissions` depended upon by `Permission-Camera` when I am trying to run `pod install`. 

I don't know if this version supported RN version 59.9.

## Environment info

`react-native info` output:

```bash
React Native Environment Info:
    System:
      OS: macOS 10.15.7
      CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
      Memory: 81.86 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.0.0 - /usr/local/bin/node
      Yarn: 1.6.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 28, 29
        Build Tools: 28.0.3, 29.0.2
        System Images: android-28 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5977832
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.8.3 => 16.8.3 
      react-native: ^0.59.9 => 0.59.10 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
```

Library version: 3.0.1

**Comment by ericksondelacruz** [comment]
1. Add `pod 'RNPermissions', :path => '../node_modules/react-native-permissions'` in Podfile
2. In RNPermissions.podspec replace "React-Core" with "React/Core"

**Comment by mikehardy** [comment]
Just a thought - jcenter is going away in a month or so, meaning android builds that don't update to handle it will simply start failing completely in a couple weeks.

I think it's more important to get on current versions for reasons like that then it is to hack support in to old versions - I'd very concerned if I wasn't ready + able to take current version bumps into my app at the moment.

https://github.com/react-native-community/releases/issues/221#issuecomment-822024961
