### ISSUE TITLE
REQUEST:  requestNotifications on Android to behave similarly to the iOS counterpart

### ISSUE THREAD

**Issue by daniel112** [zoontek/react-native-permissions#589]
# Feature request

On iOS, calling `requestNotifications` actually triggers the callback for the push token, but on Android it only returns the `status`.
- https://github.com/zoontek/react-native-permissions/blob/7bc22a975aa17dbbbfa21b5c83852f0f12d1f7ac/src/methods.android.ts#L91
- 
This is minor because I can just utilize the library `react-native-push-notifications`, but for consistency sake I think it would be great. If this was done on purpose, then I'd be curious as to why

on Android, update `requestNotifications` to behave the same way as the iOS counterpart

## Why it is needed

It would be great to have for consistency

## Possible implementation

* Similar implementation as iOS via call to `NativeModule`

**Comment by zoontek** [comment]
Notifications cannot be requested on Android, so the request is basically just a check on this platform.

**Comment by florian-milky** [comment]
would be nice if that would be more clearly stated in the docs!

**Comment by mikehardy** [comment]
@florian-milky if there is anything that could be improved in the docs you can just hit the edit button on whichever page needs the help and propose a fix directly - most open source documentation is corrected/improved directly in exactly that way by users for users

**Comment by florian-milky** [comment]
@mikehardy thanks for the hint I created one
