### ISSUE TITLE
Allow Once results to BLOCKED

### ISSUE THREAD

**Issue by Ruzen1** [zoontek/react-native-permissions#591]
# Bug report

## Summary

When the [Allow Once]is clicked, it results to BLOCKED. Is this correct move? If not can you please tell me what the problem might be?

## Environment info

`react-native info` output:

```bash
# paste it here
System:
    OS: macOS 11.2.3
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 35.42 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.6.0 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/Cellar/yvm/4.1.3/shim/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.3
      System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.3 => 0.61.3 
  npmGlobalPackages:
    react-native-ci-tools: 1.1.0
    react-native-cli: 2.0.1
```

Library version: ^2.0.3

## Steps to reproduce

```
   const response = await PermissionIos.request(PermissionIos.PERMISSIONS.IOS.LOCATION_ALWAYS)
   console.log(response)

```
1. I make a request.
2. User Clicks on Allow Once

Describe what you expected to happen:

1. I just want to confirm if [BLOCKED] is really supposed to be shown when the user clicks on 'Allow Once'
2. …

**Comment by zoontek** [comment]
Yes. https://github.com/zoontek/react-native-permissions#about-ios-location_always-permission
You have to check the status of `WHEN_IN_USE` after that.

**Comment by Ruzen1** [comment]
@zoontek Thank you so much for the reply.  I did understand about the link you have sent. 
I want Allow Once to work too. Could you please suggest me? Right now, if the user chooses, allow once, it doesnt respond with a location

**Comment by Ruzen1** [comment]
@zoontek its super related with https://github.com/zoontek/react-native-permissions/issues/569

**Comment by ryanjwessel** [comment]
I would agree with @Ruzen1 that this does not seem like the expected behavior of this request. I am seeing the same thing, that selecting "Allow Once" results in "Blocked", on version 3.3.1 of this library.

I would expect that if the user selects "Allow Once", then the permission is technically granted until they close the app. When the app is re-opened, the permission would no longer be granted.

**Comment by LuanNguyen-HnL** [comment]
Any update with 'Allow Once' Option? I'm stuck with this

**Comment by zoontek** [comment]
@LuanNguyenHNL 

> You have to check the status of WHEN_IN_USE after that.

**Comment by LuanNguyen-HnL** [comment]
> @LuanNguyenHNL
> 
> > You have to check the status of WHEN_IN_USE after that.

ok thanks, let me try!
