### ISSUE TITLE
Is it possible to change the permission title and description in Android?

### ISSUE THREAD

**Issue by Yandamuri** [zoontek/react-native-permissions#592]
# Feature request

Let's say my name  "RN App". when request camera permission message displays like this -- "Allow RN App to take photos and videos". I want to change this title and want to add description for permission.

## Why it is needed

Changing title and adding description will be more meaningful to use before approving permission.

## Possible implementation

I am not really sure about it at the moment.

### Code sample

       {
              title: "Cool Photo App Camera Permission",
             message:  "Cool Photo App needs access to your camera " +
                              "so you can take awesome pictures.",
             buttonNeutral: "Ask Me Later",
             buttonNegative: "Cancel",
             buttonPositive: "OK"
      }

Please refer this link
https://reactnative.dev/docs/permissionsandroid#request

**Comment by zoontek** [comment]
@Yandamuri Common man, it's in the doc, read it at least! https://github.com/zoontek/react-native-permissions#request You might not think it, but maintainers time is valuable.

**Comment by zoontek** [comment]
@Yandamuri Yes, it's in the doc: https://github.com/zoontek/react-native-permissions#request

**Comment by Yandamuri** [comment]
@zoontek Thank you for your response. it seems like typescript code. Can I use it in javascript as shown below?

const rationale = {
  title: "App want to access camera";
  message: "Camera Permission";
  buttonPositive: "OK";
  buttonNegative?: "Deny";
 };

request(permission: PERMISSIONS.IOS.LOCATION_ALWAYS, rationale).then((result) => {
  // …
});

**Comment by zoontek** [comment]
Yes

**Comment by hanifmhd** [comment]
> @zoontek Thank you for your response. it seems like typescript code. Can I use it in javascript as shown below?
> 
> const rationale = {
> title: "App want to access camera";
> message: "Camera Permission";
> buttonPositive: "OK";
> buttonNegative?: "Deny";
> };
> 
> request(permission: PERMISSIONS.IOS.LOCATION_ALWAYS, rationale).then((result) => {
> // …
> });

@zoontek can you help me, i'm writing the same code like above, but it's not working for Android & iOS, what am i missing?
```
 useEffect(() => {
   initPermission();
 }, []);

const initPermission = async () => {
    const statusCamera = await requestPermission(
      permissionCamera,
      dataCamera,
    ).then(value => {
      return value;
    });
    if (statusCamera !== RESULTS.GRANTED) {
      setCameraStatus(statusCamera);
    }
  };

const dataCamera = {
  title: 'We Would Like to Access the Camera',
  message:
    'This allows you to enter the room or take pictures of important documents.',
  buttonPositive: 'Allow',
  buttonNegative: "Don't Allow",
};

const permissionCamera = Platform.select({
  ios: PERMISSIONS.IOS.CAMERA,
  android: PERMISSIONS.ANDROID.CAMERA,
});

const requestPermission = (param, rationale) =>
  new Promise((resolve, reject) => {
    // rationale is the object value that will be passed to be title and message
    // https://github.com/zoontek/react-native-permissions#request
    request(param, rationale)
      .then(result => {
        resolve(result);
      })
      .catch(error => reject(error));
  });
```

it just shows up the default OS permission, not my custom title and message

**Comment by zoontek** [comment]
@hanifmhd Check what is a rationale in Android docs: https://developer.android.com/training/permissions/requesting#workflow_for_requesting_permissions
