### ISSUE TITLE
Getting installation error

### ISSUE THREAD

**Issue by mantu-designersx** [zoontek/react-native-permissions#594]
# Bug report

## Summary

I update from react native 0.62.0 to 0.63.3  and tried to install react native permissions but it is giving me installation errors. My project is based on typescript

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: Afridom@0.0.1
npm ERR! Found: react@16.13.1
npm ERR! node_modules/react
npm ERR!   react@"16.13.1" from the root project
npm ERR!   peer react@">=16.13.1" from react-native-permissions@3.0.3
npm ERR!   node_modules/react-native-permissions
npm ERR!     react-native-permissions@"*" from the root project
npm ERR!   1 more (react-native)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"17.0.1" from react-native-windows@0.64.5
npm ERR! node_modules/react-native-windows
npm ERR!   peer react-native-windows@">=0.62.0" from react-native-permissions@3.0.3
npm ERR!   node_modules/react-native-permissions
npm ERR!     react-native-permissions@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/ios/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ios/.npm/_logs/2021-04-29T05_50_44_372Z-debug.log
```

## Environment info

`react-native info` output:

```bash
System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770S CPU @ 3.10GHz
    Memory: 591.52 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 15.12.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.11.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 25, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.1
      System Images: android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7199119
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_262 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: x.x.x

## Steps to reproduce

- Upgrade to 0.63.3 to meet the minimum requirement to install this library but got error trying to install this library.

Describe what you expected to happen:
- Install it as a normal library using npm install

**Comment by zoontek** [comment]
@mantu-designersx  This is an issue with `npm` 7.

Use `npm install --legacy-peer-deps`

**Comment by mantu-designersx** [comment]
@zoontek Thanks sir It is fixed now. I was stuck for the last 5 hours.

**Comment by galaxyreal** [comment]
Thanks, @zoontek

**Comment by PupoSDC** [comment]
Could you please elaborate how this is an issue with `npm 7` ? 
This feature signals that there is something wrong with the declared peer dependencies. is this feature failing here, and an issue should be opened with npm, or is this package peer dependencies requiring a review?

**Comment by mikehardy** [comment]
This is not specific to this module, nothing about this issue will cause a change here so it should be pursued with other dependencies.

You may scan the peer dependencies list of *this* module to ensure that *this* module has correct peer dependencies set, then if you want to use npm 7 without the "ignore" flag mentioned above you have to make sure all your other modules pull in peer dependencies that are also in the same range.

Here you can see minimums are specified but the range is open above the minimums. Very easy to satisfy.

https://github.com/zoontek/react-native-permissions/blob/540af291422768bc043ebab0a5c5c91aef9f9020/package.json#L62-L65

That's work you'll do, against your codebase and all your modules.

**Comment by PupoSDC** [comment]
Thanks for the reply. 

Indeed the npm error is not very clear and it makes it look like it's this modules fault, when in fact it's not. 
Thank you for your explanation!
