### ISSUE TITLE
apple reject my update after adding APP_TRACKING_TRANSPARENCY

### ISSUE THREAD

**Issue by elirangoshen** [zoontek/react-native-permissions#595]
# Bug report

## Summary

I added APP_TRACKING_TRANSPARENCY permission to use admob in ios 14+.
apple rejected the update because of the reason that if user choosing do not allow he's getting a message encourage him to allow it.

i think that when user choosing do not allow it shouldn't add another dialog

I think that the behaviour and dialog is getting from the library so i think it can be issue. 
It's a bug imo because without it its nit possible to update apps in appstore. 

thats the message i got from apple : 
Guideline 5.1.1 - Legal - Privacy - Data Collection and Storage

We noticed your app includes App Tracking Transparency permissions requests, but it encourages or directs users to accept tracking. Specifically, your app directs the user to accept tracking in the following way(s):

- A message asks users to reconsider their decision after they deny permission.

Permission requests give users control of their personal information. It is important to respect their decision about how their data is used.

Next Steps

To resolve this issue, please revise the permission request process in your app so that the user is not inappropriately encouraged or directed to accept tracking.

If necessary, you may provide more information about why you are requesting permission to track before the request appears. If the user is trying to use a feature in your app that won't function without tracking, you may include a notification to inform the user and provide a link to the Settings app.
## Environment info

`react-native info` output:

```bash
System:
    OS: macOS 11.2.3
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 150.52 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.13.0 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 14.0.1 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.2 => 0.63.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 3.0.3

## Steps to reproduce

Describe what you expected to happen:

when user choosing not allow he shouldn't see any more messages

**Comment by zoontek** [comment]
Did you tried it? What happen when you refuse the `APP_TRACKING_TRANSPARENCY` permission?

**Comment by elirangoshen** [comment]
I'm sorry its no the issue.. the thing that apple reject  is because apple saw the consent i need to show to eea countries users.. I'll try to talk to them about it.

**Comment by zoontek** [comment]
Edit: I tried it, there is no such thing as this message:

https://user-images.githubusercontent.com/1902323/116531907-f403df80-a8df-11eb-8a48-8549b3d90dfc.MP4

**Comment by mikehardy** [comment]
I am only posting this since this is *the* react-native permissions library :-), and App Tracking Transparency is a big deal, and lots of people use react-native-firebase. The firebase-ios-sdk under react-native-firebase just released an update that *allows* you to do Analytics without IDFA so you don't necessarily have to do ATT, and I just released support for it in react-native-firebase 11.4.1

So perhaps there are people that can avoid the need for this permission

Otherwise, requesting it with this library should work fine :-). Carry on ;-)
