### ISSUE TITLE
Android ACTIVITY_RECOGNITION permission doesn't display Alert window

### ISSUE THREAD

**Issue by nkulic** [zoontek/react-native-permissions#598]
## Summary

When requesting permission for `PERMISSIONS.ANDROID.ACTIVITY_RECOGNITION` it resolves as "denied" without alert displayed, yet when the same code is tested with different permission argument (e.g. ** PERMISSIONS.ANDROID.CAMERA**), Alert is displayed as expected.

## Environment info

`react-native info` output:

```bash
System:
    OS: macOS 11.2.2
    CPU: (8) arm64 Apple M1
    Memory: 72.20 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.1 - ~/.nvm/versions/node/v14.16.1/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.16.1/bin/yarn
    npm: 7.11.2 - ~/.nvm/versions/node/v14.16.1/bin/npm
    Watchman: 4.9.0 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.3
      System Images: android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom_64, android-30 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7199119
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
```

Library version: 3.0.3

## Steps to reproduce

Call the following function (that is all I'm doing)

``` const handleLocationPermission = async () => {
  try {
    const result = await request(PERMISSIONS.ANDROID.ACTIVITY_RECOGNITION);

    switch (result) {
      case RESULTS.GRANTED:
        console.log('GRANTED');
        break;
      case RESULTS.DENIED:
        console.log('DENIED');
        break;
      case RESULTS.BLOCKED:
        console.log('BLOCKED - OPEN SETTINGS');
        break;
      case RESULTS.UNAVAILABLE:
        console.log('PERMISSION NOT AVAILABLE ON THIS DEVICE’);
        break;
      case RESULTS.LIMITED:
        console.log('LIMITED');
        break;
      default:
        console.log('PERMISSION ERROR');
    }
  } catch (err) {
    Alert.alert('Error occurred');
  }
};
```

Describe what you expected to happen:

1. I expect to get Alert window for `PERMISSIONS.ANDROID.ACTIVITY_RECOGNITION` permission.

**Comment by zoontek** [comment]
@nkulic Did you added `<uses-permission android:name="com.google.android.gms.permission.ACTIVITY_RECOGNITION" />` to your AndroidManifest?

See Android documentation: https://developer.android.com/about/versions/10/privacy/changes#physical-activity-recognition

**Comment by nkulic** [comment]
> @nkulic Did you added `<uses-permission android:name="com.google.android.gms.permission.ACTIVITY_RECOGNITION" />` to your AndroidManifest?
> 
> See Android documentation: https://developer.android.com/about/versions/10/privacy/changes#physical-activity-recognition

Yes I did, I have also tried with `<uses-permission android:name="android.permission.ACTIVITY_RECOGNITION" />`
But it still resolves to `denied`. I need this permission in order to use gyroscope, magnetometer and accelerometer

Testing on Samsung Galaxy S9+ (Android 10)

**Comment by mikehardy** [comment]
I can't reproduce this @nkulic. My app uses ACTIVITY_RECOGNITION and when I revoked it just now or tested a fresh install on an Android 10 emulator, the prompt pops up just fine.

**Comment by zoontek** [comment]
I couldn't reproduce this either. Maybe you should link to a minimal reproduction repository, @nkulic

**Comment by nkulic** [comment]
> I can't reproduce this @nkulic. My app uses ACTIVITY_RECOGNITION and when I revoked it just now or tested a fresh install on an Android 10 emulator, the prompt pops up just fine.



> I couldn't reproduce this either. Maybe you should link to a minimal reproduction repository, @nkulic

I will create a reproduction soon. And one more issue that I have is, when I'm requesting multiple permissions, and this is what is happening:

**First case:**
1. First request call - I grant permission for camera and deny permission for location
- Good and expected output: `DENIED` 

2. Second request call - I press deny and do not ask again for location
- Bad and unexpected output: `DENIED` (should be `BLOCKED`)

**Second case:**
1. First request call - I deny permission for camera and grant permission for location
- Good and expected output: `DENIED` 

> 

2. Second request call - I press deny and do not ask again for camera
- Good and expected output: `BLOCKED`
```
      const results = await requestMultiple([
        PERMISSIONS.ANDROID.CAMERA,
        PERMISSIONS.ANDROID.ACCESS_FINE_LOCATION,
      ]);

      if (
        results[PERMISSIONS.ANDROID.CAMERA] === RESULTS.GRANTED &&
        results[PERMISSIONS.ANDROID.ACCESS_FINE_LOCATION] === RESULTS.GRANTED
      ) {
        console.log("GRANTED");
      } else if (
        results[PERMISSIONS.ANDROID.CAMERA] === RESULTS.BLOCKED ||
        results[PERMISSIONS.ANDROID.ACCESS_FINE_LOCATION] === RESULTS.BLOCKED
      ) {
        console.log('BLOCKED');
      } else if (
        results[PERMISSIONS.ANDROID.CAMERA] === RESULTS.DENIED ||
        results[PERMISSIONS.ANDROID.ACCESS_FINE_LOCATION] === RESULTS.DENIED
      ) {
        console.log('DENIED');
      } else {
        Alert.alert('ERROR');
      }
```

**Comment by mikehardy** [comment]
separate issues deserve seperate issues I think - and a self-contained App.js that can drop in to the example here for reproduction would be excellent

**Comment by nkulic** [comment]
> I can't reproduce this @nkulic. My app uses ACTIVITY_RECOGNITION and when I revoked it just now or tested a fresh install on an Android 10 emulator, the prompt pops up just fine.



> I couldn't reproduce this either. Maybe you should link to a minimal reproduction repository, @nkulic

I have fixed the issue. I haven't rebuilt the app properly and changes I've done to **AndroidManifest.xml** didn't applied, that is why it always resulted as "Denied"

**Comment by captncanary** [comment]
If I'm targetting Android 13 but want Activity Recognition to work as far down as Android 9, which permissions should I put in the manifest and what behaviour should I expect when requesting the permission in Android 9? All is working fine in 10+ but I can't get the permission in 9. Check status on 9 is unavailable.
