### ISSUE TITLE
check(PERMISSIONS.ANDROID.ACCESS_***_LOCATION) should check the android system location setting

### ISSUE THREAD

**Issue by HansBouwmeester** [zoontek/react-native-permissions#601]
See #365 which was never fixed. (v3.0.3).

Summary: after turning off the main android location permissions "master switch" the ACCESS_FINE_LOCATION and ACCESS_COURSE_LOCATION permission checks still return 'granted'.

Also #452.

**Comment by zoontek** [comment]
@Gra55h0pper Is this really a bug? In my memories, `checkNotifications` and `requestNotifications` properly return the corrects status of the permission, and the permission is still requestable (prompted to the user).

The location might be unavailable after, but it's not a permission issue. Thee switch you turn off is not a "permission switch" but a "location services" switch.

**Comment by HansBouwmeester** [comment]
Hi @zoontek, see #452. In the strict sense I agree this is not a bug as I understand the OS grants access to the service although they may be (temporarily) unavailable due to the switch setting. 

It may be a good idea for the documentation to explain that ‘GRANTED’ does not imply ‘AVAILABLE’ and give the pointer to react-native-device-info?

**Comment by mikehardy** [comment]
PRs for docs are possible with a few clicks on the web 🙏

**Comment by zoontek** [comment]
I'm closing this since the PR was not created.
