### ISSUE TITLE
Tried to use permissions API but the host Activity doesn't implement PermissionAwareActivity

### ISSUE THREAD

**Issue by irohitb** [zoontek/react-native-permissions#606]
I am getting this error when trying to use request/request multiple 

> Tried to use permissions API but the host Activity doesn't implement PermissionAwareActivity

Not sure if this is a bug or not but if someone can share any ideas on how to fix, that would be super helpful. 

I am on `  react-native": "0.63.4"` and ` react-native-permissions: "^3.0.3"`. 

Thanks :)

**Comment by mikehardy** [comment]
I'm guessing that you can't reproduce this in the example.
You may have some sort of mixed native / react-native app with an Activity that is not ReactActivity?
You will need to produce some sort of reproduction example for help, it appears you have deleted the issue template, and "Sample Code" was part of it.
