### ISSUE TITLE
Location Always second modal not popping out in IOS

### ISSUE THREAD

**Issue by IamNotHuman** [zoontek/react-native-permissions#607]
# Bug report

## Summary

My use case is to route the user to home screen after he enables location always. Reading the docs there is a second modal that should come out after enabling the first one with "usage only when app is opened" but it doesn't come out and it only returns as if the user did enable the location always. After a while (30 minutes or so) the modal sometimes comes out but that is not the expected behaviour.

 

## Environment info

`react-native info` output:

```bash
System:
    OS: macOS 11.2.3
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 112.46 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.1.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.11.2 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 21, 22, 23, 24, 25, 26, 27, 28, 29, 30
      Build Tools: 21.1.2, 29.0.0, 29.0.1, 29.0.2, 29.0.3, 30.0.3
      System Images: android-21 | ARM EABI v7a, android-21 | Intel x86 Atom, android-21 | Intel x86 Atom_64, android-21 | Google APIs ARM EABI v7a, android-21 | Google APIs Intel x86 Atom, android-21 | Google APIs Intel x86 Atom_64, android-29 | Automotive with Play Store Intel x86 Atom, android-29 | Android TV Intel x86 Atom, android-29 | Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64, android-30 | Google APIs ARM 64 v8a, android-30 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom_64, android-30 | Google Play ARM 64 v8a, android-30 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom_64, android-S | Google APIs ARM 64 v8a, android-S | Google APIs Intel x86 Atom_64, android-S | Google Play ARM 64 v8a, android-S | Google Play Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7199119
    Xcode: 12.3/12C33 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_282 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

```

Library version: 3.0.3

## Steps to reproduce

1. run requestIOSLocationPermissions function
2. press on enable locations when in app
3. second modal will not popup and you will get a response as if you have the permission

Describe what you expected to happen:

1. Promp first modal to allow location only when app is in use
2. Promp second modal to allow location always
3. Receive location permission
4. route to home screen 

## Reproducible sample code

export const checkIOSLocationPermissions = () : Promise<boolean> => {
    return check(PERMISSIONS.IOS.LOCATION_ALWAYS)
      .then(async (statuses) => {
        if (statuses === RESULTS.GRANTED) {
          if(SYSTEM_VERSION >= 14){
            const isAccuracyFull = await checkIOSAccuracy();
            return isAccuracyFull ? true : false;
          }
          return true;
        }
        return false;
      })
  }

  export const requestIOSLocationPermissions = () : Promise<boolean> => {
    return request(PERMISSIONS.IOS.LOCATION_ALWAYS).then((statuses) => {
      if (statuses === RESULTS.GRANTED) {
        return true
      }
      return false
    })
    .catch((error) => {
      console.log('ERROR-requestIOSLocationPermissions', error )
      return false
    })
  }

**Comment by zoontek** [comment]
The modal will appear later with a message "App has been using your location in the background", when your app is closed.
That's the expected behaviour, see the Apple documentation: https://developer.apple.com/documentation/corelocation/cllocationmanager/1620551-requestalwaysauthorization#3578736
