### ISSUE TITLE
Android requestMultiple not handling blocked state properly

### ISSUE THREAD

**Issue by Iskander508** [zoontek/react-native-permissions#608]
# Bug report

## Summary

When using the `requestMultiple` and clicking the `Do not ask again` OS checkbox. The method returns state `RESULTS.DENIED` while it should be `RESULTS.BLOCKED` in some cases.

## Environment info

`react-native info` output:

```bash
System:
    OS: macOS 11.3.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 262.54 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.12 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 31.0.0
      System Images: android-19 | Intel x86 Atom, android-23 | Intel x86 Atom_64, android-24 | Intel x86 Atom_64, android-29 | Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7199119
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_271 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 3.0.3

## Steps to reproduce

1. Request 2 permissions using the `requestMultiple` (for example `PERMISSIONS.ANDROID.CAMERA` and `PERMISSIONS.ANDROID.RECORD_AUDIO`)
2. accept first (camera) and decline second (audio) -> this correctly ends with `[GRANTED, DENIED]`
3. Call the same request again (now only the audio permission is prompted). Check the `Don't ask again` checkbox and decline the audio permission again.
4. The request incorrectly results in `[GRANTED, DENIED]`

What you expected to happen:
The second call should result in `[GRANTED, BLOCKED]`

Reproduced on Android 8.0 (Sony Xperia X)

**Comment by zoontek** [comment]
Thanks, i just published version 3.0.4 with it: https://github.com/zoontek/react-native-permissions/releases/tag/3.0.4
