### ISSUE TITLE
No podspec found for `Permission-Camera`

### ISSUE THREAD

**Issue by indapublic** [zoontek/react-native-permissions#615]
# Bug report

## Environment info

`react-native info` output:

```bash
System:
    OS: macOS 11.2.3
    CPU: (8) arm64 Apple M1
    Memory: 160.75 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.14.0 - ~/.nvm/versions/node/v15.14.0/bin/node
    Yarn: 1.22.10 - /opt/homebrew/bin/yarn
    npm: 7.7.6 - ~/.nvm/versions/node/v15.14.0/bin/npm
    Watchman: 4.9.0 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 12.5/12E5244e - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.64.1 => 0.64.1
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 2.2.2

## Steps to reproduce

1. Install library
```
npm install --save react-native-permissions
```

2. Change Podfile
```
permissions_path = '../node_modules/react-native-permissions/ios'
pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
```

3. Install pods
```cd ios && pod install```

Receive error during install pods

```
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
[!] No podspec found for `Permission-Camera` in `../node_modules/react-native-permissions/ios/Camera`
```

**Comment by indapublic** [comment]
Ok, react-native-permissions should be 3.x version, but I have 2.x installed from npm 🤔

**Comment by indapublic** [comment]
Fixed after upgrade to 3.0.4. Closed

**Comment by jliukai** [comment]
hey im having this same problem. but my version is    "react-native-permissions": "^3.6.1"

do you have another fix?

react-native info
```
info Fetching system and libraries information...
System:
    OS: macOS 11.4
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 219.20 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.15.1 - /var/folders/16/18z66k9j4_n61127f922z2t40000gn/T/yarn--1664511148400-0.2220978739352466/node
    Yarn: 1.22.10 - /var/folders/16/18z66k9j4_n61127f922z2t40000gn/T/yarn--1664511148400-0.2220978739352466/yarn
    npm: 8.11.0 - /usr/local/bin/npm
    Watchman: 2022.06.27.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 29, 30, 31
      Build Tools: 30.0.2, 30.0.3
      System Images: android-31 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8815526
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 15.0.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: ^0.66.0 => 0.66.4
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by ortonomy** [comment]
Suggest double check the correct podfile for your version of react native.

**Comment by Oladapodaniel** [comment]
> Fixed after upgrade to 3.0.4. Closed

This worked for me

**Comment by seeksolution-llp** [comment]
use  "react-native-permissions": "^3.0.0"

**Comment by FouadMagdy01** [comment]
I was facing the same issue, but my problem was that i configured the package with an old docs
i fount these lines in `Podfile`
`  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways.podspec"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse.podspec"
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
  pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone.podspec"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary.podspec"
`

i removed them and then added this
`  setup_permissions([
  'AppTrackingTransparency',
  'Bluetooth',
  'Calendars',
  'CalendarsWriteOnly',
  'Camera',
  'Contacts',
  'FaceID',
  'LocationAccuracy',
   'LocationAlways',
   'LocationWhenInUse',
  'MediaLibrary',
   'Microphone',
   'Motion',
  'Notifications',
  'PhotoLibrary',
  'PhotoLibraryAddOnly',
  'Reminders',
  'Siri',
  'SpeechRecognition',
  'StoreKit',
])
`

change the permissions with the ones you want
