### ISSUE TITLE
Android app refused

### ISSUE THREAD

**Issue by X-Titouan** [zoontek/react-native-permissions#617]
I'm trying to publish my app on the play store.

My app get refused and I received this mail :

https://i.stack.imgur.com/z2dPa.png

Here is my manifest :

https://i.stack.imgur.com/chkOk.png

To add context, my app is used by sport event participant to send an sos to rescuers if they are lost or injured. (ACCESS_COARSE_LOCATION & ACCESS_FINE_LOCATION permissions). In case of poor LTE network (3G/4G) the sos is sent by SMS (SEND_SMS permission).

Also, the organizer can locate a user on demand, without any interaction from the participant. For exemple if the oranizer has no news from someone since several hours, he asks for the participant's location, our backend sends a cloud message to the app, the app wakes up, calculates his position and sends it back to the backend. (ACCESS_BACKGROUND_LOCATION permission).

To finish, the organizer can also sends push notification to participants containing files (READ_EXTERNAL_STORAGE & WRITE_EXTERNAL_STORAGE permissions).

Here is a (french) short video showing how we ask user for permissions. What is important is that we ask location permission and as we need the "Always" choice, we display a tutorial showing how to set it on settings.

https://youtu.be/DBBUBTnQwws

On the android Play Console, I filled two Permissions Declaration Forms, one for the location permission and one for the sms permission. I also give test account credentials.

The problem now is that I have no clue where is the problem... Do you have any ideas ?

**Comment by zoontek** [comment]
This is not related to the library. On iOS, it's important not embedding unused permissions but on Android the system is agnostic.

EDIT: Publish at least code for each call to `request` and `requestMultiple` in your app.

**Comment by X-Titouan** [comment]
I'm sorry, I'm not used to post my problems, but android team gave me no indication on how to solve this and react-native-permission community seems to be benevolent and expert on this subject ! :D

This is the code for location permission request :

Android 29+
https://pastebin.com/EbyuJdnA
Android 28
https://pastebin.com/yCxie2M1

For sms:

https://pastebin.com/Ytwr0T8N

For storage:

https://pastebin.com/2wn6ZtDQ

And to display modals which ask for user permissions:

`if (!sendSmsPermissionState.success || sendSmsPermissionState.data !== RESULTS.GRANTED) && sendSmsPermissionIsAskable) {
setDisplaySendSmsPermissionModal(true);
}`

If the permission is not granted and the user didn't click on the skip button, I show the permission modal. When he click on the authorize button on the modal, I request for the permission.

I don't use "Rationale" as I use the request multiple function, do you think it can be the problem source ?

**Comment by zoontek** [comment]
You never request location permission, only checking it?

**Comment by X-Titouan** [comment]
Sorry, I updated the post with the good code

**Comment by zoontek** [comment]
Ask Google which permission request is not prompted and ask for it.

**Comment by X-Titouan** [comment]
I opened multiple requests to ask for more informations, they never replied yet, I will let you know when they will :)

But you are right, I should identify first which permission is concerned. I could delete all permissions exexpt one, publish the app, then add another one, but it takes 2 days eveytimes and it will destroy all the code base as I will have to delete also all the features who are using thoses permission...
