### ISSUE TITLE
checkNotifcations triggers the Notification Permission Prompt

### ISSUE THREAD

**Issue by phillipkey** [zoontek/react-native-permissions#619]
# Bug report

## Summary
When using the checkNotifications function, the application immediately asks for permission to send push notifications.

## Environment info

`react-native info` output:

```bash
    OS: macOS 11.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 269.30 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v14.16.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /Users/phillipkey/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 23, 24, 25, 26, 27, 28, 29, 30
      Build Tools: 28.0.3, 29.0.0, 29.0.2, 29.0.3, 30.0.3
      System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_282 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: x.x.x

## Steps to reproduce

1. import { checkNotifications } from 'react-native-permissions'
2. invoke the function to get the value and observe the permissions prompt is displayed.

Describe what you expected to happen:

1. Get the result of the permission
2. Do not prompt the user for the notification permission.

## Reproducible sample code

```
   private checkPermission = () => {
        checkNotifications().then(({status}) => {
            if (status === RESULTS.DENIED || status === RESULTS.UNAVAILABLE) {
                // return some component
            }
        })
    }
```

**Comment by zoontek** [comment]
@phillipkey Hello. Could you give more details? The platform, the OS version if it's in the simulator or a real device? Which model?

**Comment by phillipkey** [comment]
@zoontek  sure. This is on an iPhone 12 simulator running iOS 14

**Comment by zoontek** [comment]
@phillipkey Could you try on a real device? Simulators are not able to debug push notifications.

**Comment by phillipkey** [comment]
@zoontek I know that push notifications are not available on simulators. I will check on an actual device, but the issue is not with push notification functionality. This is about the permission itself being requested when I check the status of this permission.

**Comment by zoontek** [comment]
@phillipkey Yes but as notifications API are not correctly implemented, I'd rather ask for a device check first.

**Comment by zoontek** [comment]
@phillipkey Did you tried?
