### ISSUE TITLE
Requesting ACCESS_BACKGROUND_LOCATION is not showing any prompt

### ISSUE THREAD

**Issue by Yandamuri** [zoontek/react-native-permissions#620]
# Bug report

## Summary

As far as I know when ACCESS_BACKGROUND_LOCATION permission is requested below screen screen must be rendered.

<img width="407" alt="Screenshot 2021-06-22 at 7 53 33 PM" src="https://user-images.githubusercontent.com/31983789/123049127-da34d380-d41c-11eb-9bc2-e1a86da2f01d.png">

Instead, Below screen is opening

![Screenshot_1624429628](https://user-images.githubusercontent.com/31983789/123049216-f2a4ee00-d41c-11eb-91db-39cd4a7e9de4.png)

Which is app permissions screen in settings.

This is how my Androidmanifest.xml looks like

         <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" />
         <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />

## Environment info

react: 16.13.1 => 16.13.1 
react-native: 0.63.2 => 0.63.2 
react-native-permissions=> 3.0.3

## Steps to reproduce

       1.request([PERMISSIONS.ACCESS_FINE_LOCATION]).then((statuses) => {}); accept location
       2.Then request([PERMISSIONS.ANDROID.ACCESS_BACKGROUND_LOCATION]).then((statuses) => {});
       3.This time you can see that you are taken app permissions screen(which is displayed above)

Describe what you expected to happen:

I want first screen which I have attached here to be shown when ACCESS_BACKGROUND_LOCATION is requested.

## Reproducible sample code

Since My project is complex, I am unable to mention any code here.

**Comment by zoontek** [comment]
@Yandamuri  Please do a search first next time: https://github.com/zoontek/react-native-permissions/issues/570

**Comment by Yandamuri** [comment]
@zoontek I have already tried the solution mentioned in the  [#570](https://github.com/zoontek/react-native-permissions/issues/570).

When tired to request for both ACCESS_BACKGROUND_LOCATION and ACCESS_FINE_LOCATION nothing is happening.

That is the reason why I posted this issue.

**Comment by stephenheron** [comment]
@zoontek We are actually seeing the same thing, requesting both ACCESS_BACKGROUND_LOCATION and ACCESS_FINE_LOCATION results in nothing happening. The requestMultiple response looks like this: 

`{"android.permission.ACCESS_BACKGROUND_LOCATION": "denied", "android.permission.ACCESS_FINE_LOCATION": "blocked"}`

We have had to add the workaround of requesting 'ACCESS_FINE_LOCATION' first, then requesting 'ACCESS_BACKGROUND_LOCATION' in a separate request call. This does work but its not very user friendly.

**Comment by Yandamuri** [comment]
@stephenheron Yes, This approach is not user friendly and for App Store reviews also, It might be confusing.

@zoontek Is there any way to directly request for `ACCESS_BACKGROUND_LOCATION`?

**Comment by realfelixyu** [comment]
Why is this closed?

**Comment by Jenovas** [comment]
@realfelixyu because it is not a bug, this is how Android works. You most first request Foreground Location from the user and only when the user accepts Foreground Location can your App ask for Background Location which the user must manually set in the App Settings.
