### ISSUE TITLE
No permission handler detected error

### ISSUE THREAD

**Issue by teckbeng-payboy** [zoontek/react-native-permissions#621]
Hi,

Is it possible to get rid of this error without set up at least one permission in the podlock file? 

The reason is I don't want the application to automatically prompt the permission on the initial launch.

Thanks in advance

**Comment by zoontek** [comment]
This is not how it works. Just don't call the `request` methods at launch.
You can safely add all the handlers you need, just delay the request. Check the example project or read the documentation to understand how it works.
