### ISSUE TITLE
Mock Library not working

### ISSUE THREAD

**Issue by Pinwheeler** [zoontek/react-native-permissions#622]
# Bug report

## Summary

Using the provided mock results in a crash

### How I'm Mocking
```javascript
import mock from "react-native-permissions/mock"
jest.mock("react-native-permissions", () => {
  return mock
})

```

## Environment info

`react-native info` output:

```bash
System:
    OS: macOS 11.4
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 439.87 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.8.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 7.5.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /Users/anthonydreessen/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: javac 14 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^17.0.1 => 17.0.1
    react-native: ^0.64.0 => 0.64.1
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: ^3.0.4

## Steps to reproduce

1. Try to run the tests after downloading the project and running `npm i`

Describe what you expected to happen:

1. I am able to run the tests using the provided mock

## Reproducible sample code

https://github.com/Pinwheeler/PermissionsError

**Comment by zoontek** [comment]
@Pinwheeler Hello. I tried the reproducible code, it does not crash, but output a very clear and detailled Jest error:

<img width="1167" alt="Screenshot 2021-06-29 at 09 05 19" src="https://user-images.githubusercontent.com/1902323/123752614-40a47080-d8b9-11eb-8c0e-e28cc0d46f2b.png">

If you follow the instructions and search a bit, you find this page in the Jest documentation, about how testing RN apps: https://jestjs.io/docs/tutorial-react-native#transformignorepatterns-customization

```js
const transformIgnoreModules = [
  '@react-native/polyfills',
  'react-native',
  'react-native-permissions',
];

module.exports = {
  projects: [
    {
      name: 'react',
      preset: 'react-native',
      setupFilesAfterEnv: ['<rootDir>/mockPermissions.js'],
      transformIgnorePatterns: [
        `node_modules/(?!(${transformIgnoreModules.join('|')})/)`,
      ],
    },
  ],
};
```

**Comment by rajAmukhliS** [comment]
mock `react-native-permissions` in `jest.setup.js` file as shown below

```
jest.mock('react-native-permissions', () =>
  require('react-native-permissions/mock'),
);
```

**Comment by TanKucukhas** [comment]
```
  SyntaxError: Unexpected token 'export'

      44 |
      45 | jest.mock('react-native-permissions', () =>
    > 46 |   require('react-native-permissions/mock'),
         |   ^
      47 | );
      48 |
      ```
      
With require this is what I'm getting

**Comment by AbdelhalimAhmed** [comment]
I hope that might help you. comment https://github.com/zoontek/react-native-permissions/issues/432#issuecomment-1562774404
