### ISSUE TITLE
requestMultiple does nothing when requesting for FINE_LOCATION and BACKGROUND_LOCATION

### ISSUE THREAD

**Issue by Yandamuri** [zoontek/react-native-permissions#623]
# Bug report

## Summary

`requestMultiple` is introduced to request multiple permissions at a time and it is working as expected except for location permissions. when I request for `FINE_LOCATION` and `BACKGROUND_LOCATION`.

## Environment info

react: 16.13.1 => 16.13.1 
react-native: 0.63.2 => 0.63.2 
react-native-permissions => 3.0.3

## Steps to reproduce

Please run the below snippet

        
            requestMultiple([PERMISSIONS.ANDROID.ACCESS_FINE_LOCATION,       
                   PERMISSIONS.ANDROID.ACCESS_BACKGROUND_LOCATION]).then(
                   (statuses) => {
              
                  },
           );

Describe what you expected to happen:

I am expecting below screen to be rendered when request for both permission. (I a not sure if it is even possible).

<img width="277" alt="Screenshot 2021-06-29 at 5 24 58 PM" src="https://user-images.githubusercontent.com/31983789/123793165-0e1d6680-d8ff-11eb-979d-11e52d97f9e9.png">

## Reproducible sample code

                 requestMultiple([PERMISSIONS.ANDROID.ACCESS_FINE_LOCATION,       
                   PERMISSIONS.ANDROID.ACCESS_BACKGROUND_LOCATION]).then(
                   (statuses) => {
              
                    },
                );

In this [comment](https://github.com/zoontek/react-native-permissions/issues/570#issuecomment-783732735) some one mentioned that it' working. I tried exactly what is mentioned there but not working for me.

And some user [commented here](https://github.com/zoontek/react-native-permissions/issues/620#issuecomment-866690012) that `requestMultiple` not working for them too.

Please correct me If am doing any mistake in usage of `requestMultiple` . Thank you.

**Comment by zoontek** [comment]
I tried the reproducible sample code and it worked on my device. Do you target at least API Level 29 ?

**Comment by Yandamuri** [comment]
@zoontek 
Please excuse for the lengthy comment. I am struggling a lot with these permissions since I am new to RN and don't have any expose to native code.

Surprisingly `requestMultiple` is working But not as I explained in the question. And I found a strange thing

If I target api level 29, following windows is opening

<img width="354" alt="Screenshot 2021-06-30 at 11 33 43 AM" src="https://user-images.githubusercontent.com/31983789/123909983-70c24100-d997-11eb-8d2b-0ecfef6e9062.png">

IF I choose any option other than deny, then following window is opening

<img width="354" alt="Screenshot 2021-06-30 at 10 59 23 AM" src="https://user-images.githubusercontent.com/31983789/123910107-9c452b80-d997-11eb-99e5-60d1e1b84f35.png">

If I target api level 30 user is taken to setting page as shown in below image

![Screenshot_1624429628](https://user-images.githubusercontent.com/31983789/123910623-59d01e80-d998-11eb-9b7d-8c965e857ad0.png)

I found two things here,

1. when background location is requested, api 29 is displaying in app dialogue window, but api 30 is taking to settings page
2. The following window where location permission(either "Allow only while using app" or "Allow all the time") can be granted in a single window is never opened either in api 29 or api 30.

<img width="277" alt="Screenshot 2021-06-29 at 5 24 58 PM" src="https://user-images.githubusercontent.com/31983789/123911534-8a648800-d999-11eb-84ee-0830e4382245.png">

Now, I keep my requirement  in simple words. I am targeting api 30( as per android guidelines all new apps must target api 30)
 
**My first priority is**, I want following window to be  opened when I request for  `FINE_LOCATION and BACKGROUND_LOCATION`. 

<img width="277" alt="Screenshot 2021-06-29 at 5 24 58 PM" src="https://user-images.githubusercontent.com/31983789/123912853-2b077780-d99b-11eb-95e6-36ebc837063c.png">

so that user can choose what they want in a single window.

**My second priority is**,  at least following window to be opened(Which is already opening in api 29 but not in api 30)

<img width="354" alt="Screenshot 2021-06-30 at 10 59 23 AM" src="https://user-images.githubusercontent.com/31983789/123913197-8e91a500-d99b-11eb-992c-ec4f1d5fb993.png">

But I don't want user to be taken to settings page at all.

Please let me know if any one of above two scenarios is possible.

**Comment by zoontek** [comment]
That's an android issue, not related to the lib which is just a 1:1 mapping over the API.

**Comment by Yandamuri** [comment]
@zoontek in that case,  in your mobile also user is taken to settings page when request for `BACKGROUND_LOCATION` in android 11?

**Comment by zoontek** [comment]
I didn't tried it because I have no legit use case for background location, but there is no specific code for this permission.

**Comment by Yandamuri** [comment]
@zoontek 
I checked with some other app with api 29 and api 30. same thing is happening as I explained. Seems like they have changed the in api 30. Hence, Closing this issue . And thank you so much for your cooperation.

**Comment by mikehardy** [comment]
@Yandamuri you will want to become very familiar with the Android changes pages, this is the background education: https://developer.android.com/about/versions/11/privacy/location

(they release a document set like this for every version, they're actually pretty good reads, and serve as reasonable introductions to native on Android. Apple releases nothing like this unfortunately)

**Comment by Yandamuri** [comment]
@mikehardy Great Mikehardy. Thank you so much for that.
