### ISSUE TITLE
Undefined symbol: _OBJC_CLASS_$_RNPermissionHandlerLocationAccuracy

### ISSUE THREAD

**Issue by ricoalex** [zoontek/react-native-permissions#627]
<img width="249" alt="Screen Shot 2021-07-01 at 21 43 46" src="https://user-images.githubusercontent.com/59092868/124144827-811d0d80-dab6-11eb-8625-b10e1386693f.png">

I Have error after install React Native Permissions 
Can I Have solutions , please ? 
Thank you

**Comment by zoontek** [comment]
Hi. You can search for solutions in duplicate issues, it's related to your cache.
