### ISSUE TITLE
Add detailed explanation for SDK versions (Android)

### ISSUE THREAD

**Issue by nonameolsson** [zoontek/react-native-permissions#63]
Hi!
Great package, good work!

I was having a problem, but when I started writing this issue I figured it out.

As you can see in the screenshot, the result is different. To the left is your example app, and my app is to the right. I have copied your code exactly, but still get different result.

<img width="907" alt="screen shot 2017-01-12 at 10 29 55" src="https://cloud.githubusercontent.com/assets/1493018/21884060/1acf80b8-d8b2-11e6-9b01-3403e45c7bf5.png">

They are running on the same emulator, with Android SDK 25. 

Answer: It is confusing to have SDK versions in both `AndroidManifest.xml` and `android/app/build.gradle`. I removed them from `AndroidManifest.xml` and updated values in `build.gradle`
`AndroidManifest.xml`:
```
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
    <uses-permission android:name="android.permission.CAMERA"/>
    <uses-permission android:name="android.permission.RECORD_AUDIO"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.READ_CONTACTS"/>
    <uses-permission android:name="android.permission.READ_CALENDAR"/>

    // I removed following lines
    /*
    <uses-sdk
        android:minSdkVersion="18"
        android:targetSdkVersion="23" />
    */
```

`android/app/build.gradle`
```
...
android {
    compileSdkVersion 25 // Changed to latest SDK
    buildToolsVersion "23.0.1"

    defaultConfig {
        applicationId "com.suvapp"
        minSdkVersion 16 // Decreased this to allow older devices use the app
        targetSdkVersion 25 // Target latest SDK
...
```

This isn't a bug, but I think that people who are new to configure Android apps will have a hard time understanding how to use permissions at runtime. 

Do you @yonahforst think this is something that could be added to README?

**Comment by yonahforst** [comment]
good point! I've removed those lines from the Example manifest in 5de5d9
