### ISSUE TITLE
CocoaPods could not find compatible versions for pod "Permission-PhotoLibrary"

### ISSUE THREAD

**Issue by minh-dai** [zoontek/react-native-permissions#630]
in my podfile: 

platform :ios, '9.0'
use_frameworks
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'Notarax' do
  # Pods for Notarax
  pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'ReactCommon/jscallinvoker', :path => "../node_modules/react-native/ReactCommon"
  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'rn-fetch-blob',
    :path => '../node_modules/rn-fetch-blob'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'
  #pod 'RNPermissions', :path => '../node_modules/react-native-permissions'

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
  pod 'Permission-PhotoLibraryAddOnly', :path => "#{permissions_path}/PhotoLibraryAddOnly"

  post_install do |installer|
        ## Fix for XCode 12.5
        find_and_replace("../node_modules/react-native/React/CxxBridge/RCTCxxBridge.mm",
          "_initializeModules:(NSArray<id<RCTBridgeModule>> *)modules", "_initializeModules:(NSArray<Class> *)modules")
        find_and_replace("../node_modules/react-native/ReactCommon/turbomodule/core/platform/ios/RCTTurboModuleManager.mm",
           "RCTBridgeModuleNameForClass(module))", "RCTBridgeModuleNameForClass(Class(module)))")
    end
  
  target 'NotaraxTests' do
    inherit! :search_paths
    # Pods for testing
  end

  use_native_modules!
end

target 'Notarax-tvOS' do
  # Pods for Notarax-tvOS

  target 'Notarax-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

def find_and_replace(dir, findstr, replacestr)
  Dir[dir].each do |name|
      text = File.read(name)
      replace = text.gsub(findstr,replacestr)
      if text != replace
          puts "Fix: " + name
          File.open(name, "w") { |file| file.puts replace }
          STDOUT.flush
      end
  end
  Dir[dir + '*/'].each(&method(:find_and_replace))
end

**Comment by mikehardy** [comment]
Hi there!
The formatting here is very difficult to follow. Could you edit it and add triple-ticks enclosing it, with ruby as the language?

Example

```ruby
# this is a ruby comment
```

More importantly, the full *text* (please not an image) of the error message in important.
But even most importantly, this will be a project-specific issue. There is no problem with the module and you can (and should!) verify the same by cloning the repo and running the example app. That should be the first step really prior to filing any bug, and if the example runs then you just need to find the difference between it and your project and you're set.

**Comment by zoontek** [comment]
1. Please respect the issue template or this will be closed
2. Format your code to improve readability
3. Don't forget to run a `pod install`
4. Clean The Xcode cache using [react-native-clean-project](https://github.com/pmadruga/react-native-clean-project)

**Comment by minh-dai** [comment]
I add the library step by step, I have cleaned and run pod install, then in terminal show error. I don't know why the error

**Comment by zoontek** [comment]
@minh-dai Respect the issue template, send a proper and complete Podfile, this one is impossible to debug.

**Comment by markssiw11** [comment]
when you use the 3.0.0 release you have to remove the ".podspec" extensions in your Podfile.
//
https://github.com/zoontek/react-native-permissions/releases/tag/3.0.0 Breaking Change => .podspec extension is no longer required in your Podfile
