### ISSUE TITLE
[Android] Add ACCESS_MEDIA_LOCATION permission

### ISSUE THREAD

**Issue by fabyeah** [zoontek/react-native-permissions#635]
# Feature request

It looks like this permission for Android is currently still missing. 

## Why it is needed

The permission is needed to access location tags of media: https://developer.android.com/training/data-storage/shared/media#media-location-permission

**Comment by mikehardy** [comment]
I was curious so I just looked. It appears you just need to add it to https://github.com/zoontek/react-native-permissions/blob/master/android/src/main/java/com/zoontek/rnpermissions/RNPermissionsModule.java and https://github.com/zoontek/react-native-permissions/blob/master/src/permissions.android.ts - you can reach right into node_modules and give it a try

Use patch-package to persist your work while you're testing it, post up a PR - might take roughly the same time as opening the issue, android-only permissions look pretty fast to implement

**Comment by fabyeah** [comment]
@mikehardy thanks for the tip! Didn't know about `patch-package`, that's pretty nifty. I made the changes in `src` and `dist` folder and to `android/src/main/java/com/zoontek/rnpermissions/RNPermissionsModule.java` but unfortunately I only get `unavailable` as result for the check :( 
I guess the android part of the package has to be properly built, as I can't edit the `android/build` folder binaries? I don't know how to do that.

**Comment by mikehardy** [comment]
There should be java files in there? They are built every time you start react native for android in debug and mode

**Comment by fabyeah** [comment]
I'm just guessing here that maybe this is the relevant file `/node_modules/react-native-permissions/android/build/intermediates/javac/release/classes/com/zoontek/rnpermissions/RNPermissionsModule.class`, which I can't open in my editor.

Or the problem could lie somewhere else..

I will try and fork the repo, make changes and install from github. Then the package _should_ be properly set up. (If simply adding the missing permission does actually work).

**Comment by mikehardy** [comment]
```
mike@bistromath:~/work/Kullki/ksocialscore/packages/public-app/node_modules/react-native-permissions/android/src/main/java/com/zoontek/rnpermissions (p2p-features) % ls -lat
total 28-permissions/android/src/main/java/com/zoontek/rnpermissions (p2p-featur
drwxrwxr-x 2 mike mike  4096 Jun 27 21:21 ./
drwxrwxr-x 3 mike mike  4096 Jun 27 21:21 ../
-rw-r--r-- 1 mike mike 15475 Jun 23 08:47 RNPermissionsModule.java
-rw-r--r-- 1 mike mike   682 Jun 23 08:47 RNPermissionsPackage.java

```

**Comment by fabyeah** [comment]
Yep, the first file, `RNPermissionsModule.java` i modified already.

**Comment by mikehardy** [comment]
Perfect. The class files will be rebuilt for you when you `yarn android` (or the equivalent).
If it doesn't do what you're expecting, then the code isn't correct.
Add `System.err.println("your message here");` in the java and watch `adb logcat` as needed to see where things go in the control flow, and how your permission is handled, similar to `console.log('your message');` in javascript

**Comment by mikehardy** [comment]
Here's a PR to pattern off #655 - can ignore the example update parts and just focus on the bluetooth-specific parts, should work

**Comment by hectoruiz** [comment]
Hi @mikehardy ! Could you add these changes in a new library version? Thanks

**Comment by mikehardy** [comment]
No, I cannot. I'm out of work for free time for a while. I do collaborate on PRs though, as I always appreciate when others give back to the community vs just taking. Cheers

**Comment by hectoruiz** [comment]
Done! https://github.com/zoontek/react-native-permissions/pull/669
