### ISSUE TITLE
Camera Check shows Granted when there's no Camera

### ISSUE THREAD

**Issue by dozsolti** [zoontek/react-native-permissions#637]
# Bug report

## Summary

Checking the camera on Android Emulator shows permission granted even if there's no camera.

## Environment info

`react-native info` output:

```bash
System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-4771 CPU @ 3.50GHz
    Memory: 9.31 GB / 31.88 GB
  Binaries:
    Node: 15.5.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.3.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 23, 26, 28, 29, 30
      Build Tools: 23.0.1, 26.0.2, 28.0.3, 29.0.2, 30.0.3, 31.0.0
      System Images: android-22 | Google APIs Intel x86 Atom, android-23 | Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6953283
    Visual Studio: Not Found
  Languages:
    Java: 1.8.0_275
    Python: 2.7.16
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: ~0.63.4 => 0.63.4
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 3.0.5

## Steps to reproduce

1. Install this module
2. Request & Accept the android camera permission on an emulator
3. Remove the cameras from the emulator (Go to Your emulator's settings > Show Advanced Settings > Set the Front and Back Camera to None)
4. Check for the camera

Describe what you expected to happen:

1. It should return UNAVAILABLE instead of GRANTED

**Comment by zoontek** [comment]
The permission is granted, if you re-add a camera you could use it.
This library is not about features detection, only permissions 🙂
