### ISSUE TITLE
RN 0.65.1 && react-native-permissions 3.0.5 combo gives No permission handler detected.

### ISSUE THREAD

**Issue by markl-vesper** [zoontek/react-native-permissions#641]
### Bug summary

RN 0.65.1 helloworld app works fine till "react-native-permissions": "3.0.5" is added to package.json

yarn install - OK
pod install - OK
run-ios - fails with 

```
No permission handler detected.

• Check that you link at least one permission handler in your Podfile.
• Uninstall this app, delete your Xcode DerivedData folder and rebuild it.
• If you use `use_frameworks!`, follow the workaround guide in the project README.

-[RNPermissions constantsToExport]
    RNPermissions.m:210
__57-[RCTModuleData gatherConstantsAndSignalJSRequireEnding:]_block_invoke
RCTUnsafeExecuteOnMainQueueSync
-[RCTModuleData gatherConstantsAndSignalJSRequireEnding:]
-[RCTModuleData gatherConstants]
__49-[RCTCxxBridge _prepareModulesWithDispatchGroup:]_block_invoke
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
-[UIApplication _run]
UIApplicationMain
main
start
```

the podFile format is VERY different from previous RN projects. This is the 1st time we have tries to use 0.65.1 because we are trying to fix a permissions issue funny enough. 

We load all the base packages we want and build the app and the app runs fine. As soon as we add permissions package it all blows up with this error.

Everything looked to have been fine during yarn install and pod install with no errors reporting regarding linking 

### Library version

0.65.1

### Environment info

```shell
System:
    OS: macOS 11.4
    CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
    Memory: 38.89 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.12.0 - ~/.nvm/versions/node/v12.13.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 26, 28, 29
      Build Tools: 28.0.3, 29.0.3
      System Images: android-28 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5977832
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_231 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.65.1 => 0.65.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

1. react-native init helloWorld
2. cd helloWorld
3. add base packages as per sample dependencies attached
4. yarn install
5. cd ios
6. pod install
7. cd ..
8. react-native run-ios (app builds, loads to sim OK)
9. add react-native-permissions to package.json
10. yarn install
11. cd ios
12. pod install
13. cd ..
14. react-native run-ios (app builds and loads but immediately throw the handler error

### Reproducible sample code

```js
dependencies

  "dependencies": {
    "@aws-amplify/pushnotification": "^2.1.5",
    "@invertase/react-native-apple-authentication": "^1.0.0",
    "@react-native-community/art": "1.2.0",
    "@react-native-community/async-storage": "1.12.0",
    "@react-native-community/masked-view": "0.1.11",
    "@react-native-community/netinfo": "6.0.0",
    "@react-native-community/push-notification-ios": "^1.0.6",
    "amazon-cognito-identity-js": "^3.2.4",
    "appcenter-cli": "2.10.0",
    "aws-amplify": "2.2.5",
    "aws-appsync": "^3.0.2",
    "aws-sdk": "2.972.0",
    "cardinal-direction": "1.1.1",
    "convert-radix64": "^0.2.0",
    "convert-units": "2.3.4",
    "core-js": "3",
    "es6-symbol": "^3.1.3",
    "fast-text-encoding": "1.0.3",
    "geodesy": "^2.2.0",
    "graphql": "14.5.8",
    "graphql-tag": "2.10.1",
    "haversine": "^1.1.1",
    "joi": "17.3.0",
    "jsc-android": "241213.1.0",
    "lodash": "^4.17.15",
    "mobx": "5.15.4",
    "mobx-react": "6.1.8",
    "moment": "2.29.1",
    "numeral": "^2.0.6",
    "prop-types": "^15.7.2",
    "react": "17.0.2",
    "react-native": "0.65.1",
    "react-native-permissions": "3.0.5"
  },

podFile

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'cortexMonitoring' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  target 'cortexMonitoringTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
  end
end
```

**Comment by zoontek** [comment]
Hi. Indeed there is no permission handler in your Podfile?
Did you read the documentation?

**Comment by markl-vesper** [comment]
yes i noticed that ommision sorry. i added it and it still crashes

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'cortexMonitoring' do
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"

  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  target 'cortexMonitoringTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
  end
end

**Comment by zoontek** [comment]
You added it, run a `pod install`, cleaned the Xcode cache and relaunched your app?

**Comment by markl-vesper** [comment]
yes its looking great now

thanks for support
