### ISSUE TITLE
while importing permissions in podfile

### ISSUE THREAD

**Issue by tasad-7** [zoontek/react-native-permissions#642]
### Bug summary

**File Directory Resolution**
Issue is when you follow instructions for importing permissions in your podfile the commands should implicitly direct you to the correct file but instead it does not and I get the error saying 
**"[!] No podspec found for `Permission-Notifications` in `../node_modules/react-native-permissions/ios/Notifications.podspec`"**
The Fix is simple and you should just add the right file directory which in my case I changed the following commands
 
permissions_path = '../node_modules/react-native-permissions/ios'
pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications/Permission-Notifications.podspec"

### Library version

3.0.5

### Environment info

```shell
System:
    OS: macOS 11.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 2.00 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.0.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.0.3 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 31
      Build Tools: 31.0.0
      System Images: android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7486908
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.1 => 0.64.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

Adding the following commands in your iOS/Podfile
 
permissions_path = '../node_modules/react-native-permissions/ios'
pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"

1- issue is on iOS
2- running the app on actual device through Xcode
3- Using yarn to install react-native-permissions

### Reproducible sample code

```js
1- Install react-native-permissions using rpm or yarn
2- Follow the documentation and add the code in your podfile
3- yarn install
4- cd iOS/pod install
```

**Comment by zoontek** [comment]
I don't get it, what's the issue?

**Comment by tasad-7** [comment]
> I don't get it, what's the issue?
I had to use this 
pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications/Permission-Notifications.podspec"

instead of 
pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"

**Comment by mikehardy** [comment]
So what you're saying is, you did not follow the example in the README and define the variable, leading to failure later when the variable was used? :thinking: 

>  permissions_path = '../node_modules/react-native-permissions/ios'

https://github.com/zoontek/react-native-permissions/blame/master/README.md#L41

I can certainly see how not following the documentation would lead to build problems!

I cannot see how it is a bug with the module though

**Comment by zoontek** [comment]
I agree on this one, there is currently no issues if you respect the README
