### ISSUE TITLE
App launches with pre-granted push notification permissions

### ISSUE THREAD

**Issue by Taimoormk** [zoontek/react-native-permissions#643]
### Bug summary

After integrating react-native-permissions, when the app is launched for the very first time, I checked in the device setting of that app and it showed that app has already been granted access to deliver notifications quietly. However, hence why when I browse the app, it never asks for push notification permissions with the native modal, and when I manually turn off the push notifications from the setting screen, app does show up the second flow of modal which takes user to the setting screen.

I really don't understand as to why app launches with pre-granted push notifications?

![Simulator Screen Shot - iPhone 12 - 2021-09-03 at 16 52 09](https://user-images.githubusercontent.com/27800340/132000979-e03dcff9-d980-4a46-8b3d-6986ae3dd47e.png)

### Library version

3.0.5

### Environment info

```shell
System:
    OS: macOS 11.5.2
    CPU: (8) arm64 Apple M1
    Memory: 117.72 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.6.1 - /opt/homebrew/bin/node
    Yarn: 1.22.10 - /opt/homebrew/bin/yarn
    npm: 7.20.3 - /opt/homebrew/bin/npm
    Watchman: 2021.06.07.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.2
      System Images: android-25 | Google APIs ARM 64 v8a, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64, android-31 | Google Play ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7486908
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.64.2 => 0.64.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

1. install the library and integrate iOS and Android flows as per docs
2. launch the app, then switch to settings screen and look for the app permissions, you will see on initial launch app already has permissions to delivery notifications quietly.
2. Turn off these notifications from settings screen and go back to the app
3. Now you will see the second modal, which is will show open settings and take user to the settings screen, upon being pressed.

### Reproducible sample code

```js
import { useNotificationStatus } from 'react-native-use-permissions';
import { Alert } from 'react-native';
import {
    requestNotifications,
    RESULTS,
    openSettings,
    PermissionStatus,
} from 'react-native-permissions';
import { trans } from 'trans';
import { actionLoad } from 'analytics';
import { useCallback } from 'react';

const useRequestNotificationPermission = () => {
    const addEvent = useUiEvent();

    const [notificationStatus] = useNotificationStatus();

    const trackNotificationStatus = useCallback(
        (status: PermissionStatus) => {
            addEvent(actionLoad('PushNotificationPermission'), {
                metadata: {
                    status: status === RESULTS.GRANTED,
                },
            });
        },
        [addEvent],
    );

    const requestNotificationPermission = useCallback(
        (callback = () => undefined) => {
            const handlePressSettings = () => {
                openSettings().finally(callback);
            };

            if (notificationStatus === RESULTS.BLOCKED) {
                Alert.alert(
                    trans(
                        'app-transparency-push-notification-allow-notifications',
                        {},
                        'student-mobile-app',
                    ),
                    trans('push-notification-explanation-text', {}, 'student-mobile-app'),
                    [
                        {
                            text: trans('settings-tab-settings', {}, 'public-settings'),
                            onPress: handlePressSettings,
                        },
                        {
                            text: trans('cancel', {}, 'teacher-registration'),
                            onPress: callback,
                            style: 'cancel',
                        },
                    ],
                );
            } else {
                requestNotifications(['alert', 'sound'])
                    .then(({ status }) => trackNotificationStatus(status))
                    .finally(() => callback());
            }
        },
        [notificationStatus, trackNotificationStatus],
    );

    return requestNotificationPermission;
};

export default useRequestNotificationPermission;
```

**Comment by zoontek** [comment]
Do you reset the permissions when you debug your app?
Check how to here: https://developer.apple.com/library/archive/qa/qa1906/_index.html

**Comment by Taimoormk** [comment]
@zoontek Yes, several times, my ways to reset it are following:

- delete the app off the simulator/real device - also mentioned in the link you shared
- erase the simulator to start with a fresh copy
- also tried the one you mentioned, but same results :/

**Comment by zoontek** [comment]
This is an iOS issue anyway. Does this happen on real devices?

**Comment by Taimoormk** [comment]
@zoontek Yes, strangely it happens on real iOS devices too. Also, it does happen on debug and release builds too.

**Comment by Taimoormk** [comment]
@zoontek Interesting observation, I ran the app on iPhone 8 simulator for the very first time, the app initialized with `off` status for push notifications permissions, then I ran the flow, it never asked for the native modal permission, instead it loaded the open settings modal, and I went to the settings screen and granted push notifications. After cleaning the device, I tried to run the app again on the same simulator now it initialises with pre-granted permissions 😭

**Comment by zoontek** [comment]
Sorry, this sometimes happen, but is not related to this library.
