### ISSUE TITLE
Permissions for Android 12

### ISSUE THREAD

**Issue by dinesh-fareye** [zoontek/react-native-permissions#645]
### Why it is needed?

I need to use Bluetooth into App (Android 12) below permissions are missing.

<uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />
<uses-permission android:name="android.permission.BLUETOOTH_SCAN" />
<uses-permission android:name="android.permission.BLUETOOTH_ADVERTISE" />

**Comment by zoontek** [comment]
Fill a proper feature request, with a minimum of informations.

**Comment by dinesh-fareye** [comment]
I want to connect Bluetooth in Android 12 device for this I need to Ask for permission to user **android.permission.BLUETOOTH_CONNECT**

**Comment by brunomartinezciompi** [comment]
You are talking about the new bluetooth permission of Android 12?

https://developer.android.com/guide/topics/connectivity/bluetooth/permissions

**Comment by mikehardy** [comment]
Sure! But then we're still in the realm of "sounds great, post a PR..." :-)

**Comment by brunomartinezciompi** [comment]
@mikehardy I agree with you, but I think we can reopen the issue right? 

If we keep this feature request open then perhaps other developers with the same issue can see it and work on a pull request if they have time to do it.

**Comment by mikehardy** [comment]
Maybe open a fresh one with clear title (feature request, android 12, permission name)
