### ISSUE TITLE
[iOS] Permissions.openSettings() -> change permission -> app crashes

### ISSUE THREAD

**Issue by skizzo** [zoontek/react-native-permissions#65]
Hi,

first of all, thanks for this component 👍 

I have a little problem with Permissions.openSettings() (using version 0.2.5) - as mentioned in the title, as soon as I change the permissions of, e.g., my camera, the app crashes.. No error message, nothing..

![screen shot 2017-01-17 at 18 30 23](https://cloud.githubusercontent.com/assets/2892572/22032062/35a2d176-dce3-11e6-8cda-a9234abea953.png)

- desciptions for _Camera_ and _Photos_ usage are added in `Info.plist`
- don't know if that has something to do with this or another comonent, but when running `rnpm link`, I get the error `ERR! ERRPLIST Could not locate Info.plist. Check if your project has 'INFOPLIST_FILE' set properly`

Any idea what could be the problem..?

**Comment by yonahforst** [comment]
This is normal. iOS restarts your app when your privacy settings change. Just google "ios crash permission change"
