### ISSUE TITLE
Not able to install RN-Permissions  to RNfW application

### ISSUE THREAD

**Issue by JerryMacedoCastro** [zoontek/react-native-permissions#650]
### Bug summary

When install react-native-permissions in a react-native-windows app crashes the app. 
![image](https://user-images.githubusercontent.com/39466788/135148349-514b6b08-3bff-4187-8c46-4dcb572c6f46.png)

### Library version

3.0.5

### Environment info

```shell
System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 5.05 GB / 15.88 GB
  Binaries:
    Node: 14.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.16299.0, 10.0.17763.0, 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.10.31402.337 (Visual Studio Enterprise 2019)
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.64.1 => 0.64.1
    react-native-windows: 0.64.14 => 0.64.14
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

1. Fallow the steps at https://microsoft.github.io/react-native-windows/docs/getting-started in order to create a RNfW app
2. Install react-native-permissions to your project 
3. run the bundle (yarn start)
4. Try to Launch the app in the Visual Studio 

### Reproducible sample code

```js
Here are the samples provided by react-native-windows that can be used to reproduce the problem https://github.com/microsoft/react-native-windows-samples/tree/main/samples
```

**Comment by JerryMacedoCastro** [comment]
I was able to make it work change $(MSBuildThisFileDirectory) for $(SolutionDir) in this file https://github.com/zoontek/react-native-permissions/blob/master/windows/RNPermissions/RNPermissions.vcxproj#L21

**Comment by zoontek** [comment]
@JerryMacedoCastro Could you open a PR to fix it?

**Comment by JerryMacedoCastro** [comment]
> @JerryMacedoCastro Could you open a PR to fix it?

Sure! I was trying but I couldn't install the dependencies in the example app. Is there any contribution guide I didn't see?

**Comment by mikehardy** [comment]
I don't have a react-native-windows environment right now (sorry), but I just checked ios and android on a macOS machine, and this worked:

```bash
git clone git@github.com:zoontek/react-native-permissions.git
cd react-native-permissions
yarn
cd example
yarn react-native run-android  # works
yarn react-native run-ios # works
```

So at least for ios/android no problem. Perhaps the example is not working for RNW ? Indeed it looks like there is a completely different example for RNW inside example/windows/Example ? I wasn't able to find a contributors guide either and in my experience maintaining react-native-device-info at least, examples go out of date kind of quickly, and the Windows ports especially don't see much attention as the main maintainers don't typically use them.

All to say, it probably just needs some serious attention

**Comment by JerryMacedoCastro** [comment]
I opened this [PR](https://github.com/zoontek/react-native-permissions/pull/652) with the change. It was tested in a RNW app. But it seems  something is wrong on C++ side of example app in the windows environment. Not sure cause I don't have knowledge if c++.  Also here is the [docs](https://microsoft.github.io/react-native-windows/docs/0.63/native-modules-setup#referencing-react-native-windows-in-your-project) where you can find why this change is necessary.

**Comment by zoontek** [comment]
This has been merged and will be released in the afternoon. Thanks a lot for your help!
