### ISSUE TITLE
ios - 'openSettings()' open general settings instead of app settings on the first time it is called

### ISSUE THREAD

**Issue by felipe-nunes-mlse** [zoontek/react-native-permissions#651]
### Bug summary

The first time that we call ```openSettings```it opens the general settings page instead of the current app settings. It takes some seconds the first time to navigate to the App settings.

On all the calls for ```openSettings```after this, the current app settings open correctly.

![Simulator Screen Recording - iPhone 12 - 2021-09-30 at 16 20 47](https://user-images.githubusercontent.com/90851458/135518083-332c41fd-279b-4030-9377-2c12c0833eea.gif)

You can found the sample code for the example above at this [link](https://github.com/fansilva1991/ReactNativePermissionsIssue)

### Library version

3.0.5

### Environment info

```shell
System:
    OS: macOS 11.4
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 432.93 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.8.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.21.0 - /usr/local/bin/npm
    Watchman: 2021.08.23.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 28, 29, 30, 31
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 31.0.0
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7486908
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.65.1 => 0.65.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

Follow the steps on the gif below:

![Simulator Screen Recording - iPhone 12 - 2021-09-30 at 16 20 47](https://user-images.githubusercontent.com/90851458/135518339-a9f20c57-988a-40db-aa06-553f2323daa5.gif)

You can found the code to reproduce the scenario at this [link](https://github.com/fansilva1991/ReactNativePermissionsIssue)

### Reproducible sample code

```js
import React, {useState} from 'react';
import {
  SafeAreaView,
  ScrollView,
  StatusBar,
  StyleSheet,
  Text,
  useColorScheme,
  View,
  TouchableOpacity,
} from 'react-native';

import {Colors} from 'react-native/Libraries/NewAppScreen';

import {
  request,
  PERMISSIONS,
  RESULTS,
  openSettings,
} from 'react-native-permissions';

const App = () => {
  const [permissionBlocked, setPermissionBlocked] = useState(false);

  const isDarkMode = useColorScheme() === 'dark';

  const backgroundStyle = {
    backgroundColor: isDarkMode ? Colors.darker : Colors.lighter,
  };

  const requestPermission = () => {
    request(PERMISSIONS.IOS.CAMERA).then(result => {
      if (permissionBlocked) {
        openSettings();
        return;
      }
      if (result === RESULTS.BLOCKED) {
        setPermissionBlocked(true);
      }
      if (result === RESULTS.GRANTED) {
        setPermissionBlocked(false);
      }
    });
  };

  return (
    <SafeAreaView style={backgroundStyle}>
      <StatusBar barStyle={isDarkMode ? 'light-content' : 'dark-content'} />
      <ScrollView
        contentInsetAdjustmentBehavior="automatic"
        style={backgroundStyle}
        contentContainerStyle={styles.scrollView}>
        <View style={styles.view}>
          <TouchableOpacity onPress={requestPermission} style={styles.button}>
            {permissionBlocked ? (
              <Text style={styles.text}>Open Settings</Text>
            ) : (
              <Text style={styles.text}>Request Permission</Text>
            )}
          </TouchableOpacity>
        </View>
      </ScrollView>
    </SafeAreaView>
  );
};

const styles = StyleSheet.create({
  scrollView: {
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    height: '100%',
  },
  view: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  button: {
    backgroundColor: 'blue',
    width: '100%',
    maxWidth: 150,
    height: '100%',
    maxHeight: 50,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 8,
  },
  text: {
    color: 'white',
  },
});

export default App;
```

**Comment by zoontek** [comment]
Did you tried on a real device or on a simulator?

**Comment by felipe-nunes-mlse** [comment]
Both. Real device and simulator. 

( The example above is recorded from a simulator screen )

**Comment by mikehardy** [comment]
This is a system thing as far as I can tell. Settings is an actual android app shipped by google and has nothing to do with your app running (which would imply the react-native-permissions module, inside your app). It seems like it just takes a while for the settings app to actually load up the settings for a specific app.

No idea what react-native-permissions can do about it, so even though I noticed this a long time ago I never thought to log it as an issue here - doesn't seem actionable

**Comment by mikehardy** [comment]
Sorry - realized you meant iOS, I did notice it there also, but came to the same conclusion - does not seem actionable

**Comment by zoontek** [comment]
I once noticed that there is sometimes a bug when you develop on iOS: the app setting menu does not exists the first time you install it. This explain why it can't be opened.

(This issue does not happen on production)

**Comment by zoontek** [comment]
Closed since we can't do much about it
