### ISSUE TITLE
Support Android 12 Bluetooth Permission

### ISSUE THREAD

**Issue by brunomartinezciompi** [zoontek/react-native-permissions#653]
### Why it is needed?

Android introduced a new bluetooth permission on Android 12. 

https://developer.android.com/guide/topics/connectivity/bluetooth/permissions

React Native added support for this in version 0.66 https://reactnative.dev/blog/2021/10/01/version-066

_"The BLUETOOTH_ADVERTISE, BLUETOOTH_CONNECT, and BLUETOOTH_SCAN permissions are runtime permissions. Therefore, you must explicitly request user approval in your app before you can look for Bluetooth devices, make a device discoverable to other devices, or communicate with already-paired Bluetooth devices."_

<img width="304" alt="Screen Shot 2021-10-06 at 15 33 20" src="https://user-images.githubusercontent.com/50216253/136262557-1a6d67ee-3bd8-4e46-a024-541907def9b8.png">

This issue was closed for lack of information: https://github.com/zoontek/react-native-permissions/issues/645

But I think there should be a feature request issue open in this library just in case anyone find this issue on the repository and wants to create a pull request.

### Possible implementation

-

### Code sample

```js
-
```

**Comment by mikehardy** [comment]
Here are the lists to the react-native commits, for reference:
https://github.com/facebook/react-native/commit/eeb8e5829e183f6b5cd5fd327cf6da03a7db0541
https://github.com/facebook/react-native/commit/2bcc6fac3844f0752bc7067517c92a643679575e

**Comment by zoontek** [comment]
Fixed by #655
