### ISSUE TITLE
[Android] Add MANAGE_EXTERNAL_STORAGE permission

### ISSUE THREAD

**Issue by amine-chaffari** [zoontek/react-native-permissions#659]
### Why it is needed?

This permission is needed for Android 11+ since WRITE_EXTERNAL_STORAGE and READ_EXTERNAL_STORAGE won't be accepted by google in any android app update starting from November

Android Documentation : https://developer.android.com/training/data-storage/manage-all-files

Relevant for the following app types:

- File managers
- Backup and restore apps
- Anti-virus apps
- Document management apps
- On-device file search
- Disk and file encryption
- Device-to-device data migration

**Comment by mikehardy** [comment]
Duplicate, not workable, should close: #587 + please search then post in open source repos
