### ISSUE TITLE
Rationale option is ignoring for 'request' method

### ISSUE THREAD

**Issue by pavel-stryber** [zoontek/react-native-permissions#663]
### Bug summary

I want to change default title and message of location permission alert but can't do this.
I specify second parameter for 'request' method it but it doesn't work.

### Library version

3.1.0

### Environment info

```shell
iPhoneX, iOS 21.1
Mi 9T, Android 10 QKQ1.190825.002
```

### Steps to reproduce

This happens on both Android/iOS physical devices:
iPhoneX, iOS 21.1
Mi 9T, Android 10 QKQ1.190825.002

### Reproducible sample code

```js
`import {
  PERMISSIONS, request, Rationale,
} from 'react-native-permissions';

request(
          PERMISSIONS.ANDROID.ACCESS_FINE_LOCATION,
          {
            title: i18n.t('Custom title'),
            message: i18n.t('Custom message'),
          } as Rationale,
        );
`
```

**Comment by zoontek** [comment]
`Rationale` is not about the permission dialog, it's about a warning when the user refused the request once.
More infos: https://developer.android.com/training/permissions/requesting#explain
