### ISSUE TITLE
 UnhandledPromiseRejection Cannot open application settings

### ISSUE THREAD

**Issue by harleenarora** [zoontek/react-native-permissions#666]
### Bug summary

Hi, I have got the non-fatal issue of openSettings, I got so many times, Can you provide me solutions.
Device Info
Model:iPhone 11
Orientation: Portrait
RAM free: Unknown
Disk free: Unknown
Operating System
Version:14.8.1
Orientation: Portrait
Jailbroken:No

### Library version

3.0.0

### Environment info

```shell
System:
    OS: macOS 11.3
    CPU: (4) x64 Intel(R) Core(TM)
 i5-4278U CPU @ 2.60GHz
    Memory: 1.72 GB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.4 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.10 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^17.0.2 => 17.0.2 
    react-native: ^0.65.1 => 0.65.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

Non-fatal Exception: UnhandledPromiseRejection
0  ???                            0x0 <unknown> + 45 (main.jsbundle:45:1121:45)
1  ???                            0x0 <unknown> + 1367 (main.jsbundle:1367:1659:1367)
2  ???                            0x0 p + 9 (main.jsbundle:9:588:9)
3  ???                            0x0 <unknown> + 9 (main.jsbundle:9:1893:9)
4  ???                            0x0 p + 9 (main.jsbundle:9:588:9)
5  ???                            0x0 o + 9 (main.jsbundle:9:1069:9)
6  ???                            0x0 <unknown> + 9 (main.jsbundle:9:1426:9)
7  ???                            0x0 f + 71 (main.jsbundle:71:207:71)
8  ???                            0x0 y + 71 (main.jsbundle:71:1588:71)
9  ???                            0x0 c + 71 (main.jsbundle:71:486:71)
10 ???                            0x0 u + 9 (main.jsbundle:9:1410:9)
11 ???                            0x0 <unknown> + 9 (main.jsbundle:9:1462:9)
12 ???                            0x0 <unknown> + 9 (main.jsbundle:9:3865:9)
13 ???                            0x0 <unknown> + 1613 (main.jsbundle:1613:4335:1613)
14 ???                            0x0 <unknown> + 76 (main.jsbundle:76:1261:76)
15 ???                            0x0 p + 76 (main.jsbundle:76:517:76)
16 ???                            0x0 callTimers + 76 (main.jsbundle:76:2614:76)
17 ???                            0x0 value + 53 (main.jsbundle:53:3493:53)
18 ???                            0x0 <unknown> + 53 (main.jsbundle:53:748:53)
19 ???                            0x0 value + 53 (main.jsbundle:53:2539:53)
20 ???                            0x0 value + 53 (main.jsbundle:53:720:53)
21 ???                            0x0 value ([native code]:0:0)

### Reproducible sample code

```js
setTimeout(() => openSettings(), 4000);
```

**Comment by zoontek** [comment]
It just cannot open the settings in a particular context, you have to handle the error and display something to the user.

```js
openSettings()
  .catch(() => displayError("Cannot open settings"))
```
