### ISSUE TITLE
Location permission return denied when select Approximate option on android 12

### ISSUE THREAD

**Issue by LinhNguyen1059** [zoontek/react-native-permissions#668]
### Bug summary

On android 12, when the popup location request showing, then I select the `Approximate -> When using the app (or Only this time)` and the response returned is `denied`.

I've add both `ACCESS_FINE_LOCATION` & `ACCESS_COARSE_LOCATION` to the `AndroidManifest`.

![Frame 3](https://user-images.githubusercontent.com/69496694/144384009-766679bf-0381-43eb-9f20-7f51f6d07eb5.png)
### Library version

3.1.0

### Environment info

```shell
System:
    OS: macOS 12.0.1
    CPU: (8) x64 Apple M1
    Memory: 25.07 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.0 - ~/.nvm/versions/node/v14.15.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.15.0/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.15.0/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7583922
    Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.10 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.64.2 => 0.64.2
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

1. Call `Permissions.request(PERMISSIONS.ANDROID.ACCESS_FINE_LOCATION)` on android 12 devices.
2. When the popup location showing, select `Approximate` then choose `When using the app` or `Only this time`
3. Get `denied` in the `result` log

### Reproducible sample code

```js
import { request, PERMISSIONS } from "react-native-permissions";

request(PERMISSIONS.ANDROID.ACCESS_FINE_LOCATION).then(result => {
  console.log("result: ", result); // return denied when select Approximate -> When using the app
})
```

**Comment by zoontek** [comment]
This seems normal. You request fine location, the new permission system allow user to only allow coarse location.
When you receive denied, use check for coarse location.

A similar flow exists on iOS: https://github.com/zoontek/react-native-permissions#about-ios-location_always-permission

**Comment by LinhNguyen1059** [comment]
So how can I check that when the user chooses Approximate so that when I get denied I will call the `ACCESS_COARSE_LOCATION `.
or just check in denied case, don't care about what user chooses?

**Comment by zoontek** [comment]
With the check function from this package + COARSE_LOCATION permission.

**Comment by LinhNguyen1059** [comment]
oh, i'l try that and feedback later.
Thank you so much :))

**Comment by zoontek** [comment]
Something like this:

```ts
import { check, request, PERMISSIONS, RESULTS } from "react-native-permissions";

request(PERMISSIONS.ANDROID.ACCESS_FINE_LOCATION)
  .then(async status =>
    status === RESULTS.GRANTED
      ? { status, precise: true }
      : { status: await check(PERMISSIONS.ANDROID.ACCESS_FINE_LOCATION), precise: false },
  )
  .then(({ status, precise }) => console.log("location status: ", status));
```
