### ISSUE TITLE
Xcode : Argument list too long problem on Example

### ISSUE THREAD

**Issue by Okipa** [zoontek/react-native-permissions#67]
I have this error on Xcode that cause a build error :
```
Argument list too long: recursive header expansion failed at /Users/arthurlorent/workspace/ecovelo-mobile/ios/../node_modules/react-native-permissions/Example/ios.
```

I have removed the the Example folder and the error is gone.
I am using react-native v0.37.

**Comment by yonahforst** [comment]
Thanks for reporting this. i just merged https://github.com/yonahforst/react-native-permissions/pull/54 that should fix this. Gonna close this, if it's still an issue, just reopen it
