### ISSUE TITLE
No permission handler detected when using Expo SDK 44

### ISSUE THREAD

**Issue by fobos531** [zoontek/react-native-permissions#670]
### Bug summary

Thanks for the great library!

I have a react native app created using react-native CLI and have been successfully using this library in the past months. I'm also using Expo in my app (bare workflow). Everything's been working fine up until Expo released SDK 44. In this version of the SDK, they enforce the `#import <React/*.h>` import style for the React header imports. See [this discussion]( https://github.com/expo/expo/issues/15622) for more information. There's a [proposed workaround](https://github.com/expo/expo/issues/15622#issuecomment-999609806) for libraries that haven't been updated yet for compatibility with Expo SDK 44. However, when I try to apply the said workaround, after launching my app in the console I get the error that the permission handler's haven't been set up, even though I have them properly set up as per the instructions. Could this have anything to do with the changes introduced in SDK 44? 

### Library version

3.2.0

### Environment info

```shell
info Fetching system and libraries information...
System:
    OS: macOS 12.1
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 1.39 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.2.0 - /usr/local/bin/node
    Yarn: 3.1.0 - ~/.yarn/bin/yarn
    npm: 8.1.4 - /usr/local/bin/npm
    Watchman: 2021.12.13.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7784292
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 15.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: ^0.64.3 => 0.64.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

1. Create a react native project 
2. Add Expo to the project and set up Expo modules (SDK 44)
3. Add a permission handler using this library
4. Apply the [proposed workaround](https://github.com/expo/expo/issues/15622#issuecomment-999609806).
5. The "No permission handler detected" error should pop up when running the debug build

### Reproducible sample code

```js
See above, steps to reproduce
```

**Comment by zoontek** [comment]
@fobos531 This library doesn't support Expo, use their `Permissions` module instead: https://docs.expo.dev/guides/permissions/

**Comment by Yandamuri** [comment]
@fobos531 Did you find any solution or opt in for Expo permissions?

**Comment by fobos531** [comment]
@Yandamuri It depends on which permission you need - most Expo packages nowadays include mechanisms to check/request permissions out of the box

**Comment by Yandamuri** [comment]
@fobos531 I am also using Expo and facing the same issue. I am using Camera, location, microphone, storage permissions. for these permissions which do you thing is suitable(RN Permissions or Expo)?

BTW, Are you still using the react-native-permissions?

**Comment by tomeq93** [comment]
Just a note that you can use this library with expo eas
`"eas-build-post-install": "npx react-native setup-ios-permissions && npx pod-install"`
does the trick :)

**Comment by Yandamuri** [comment]
@tomeq93 BTW, Did you mean managed workflow or bare work flow?

**Comment by tomeq93** [comment]
@Yandamuri managed

**Comment by ismith98** [comment]
Hey everyone,
In the updated version of react-native-permissions they have removed setup-ios-permissions. The process now involves executing a .sh script that contains the necessary commands to modify the files specified in the RNPermissions documentation. Here's how my eas-build-post-install command is configured in my package.json:

`"eas-build-post-install":"sh ./prep-RNPermissions.sh"`
 
I've placed a file named [prep-RNPermissions.sh](http://prep-rnpermissions.sh/) in the same directory as my package.json. Here are the commands contained within that script:
 
```
cd ios && perl -pi -e 's|(native_modules"\))|$1\n  require_relative '\''../node_modules/react-native-permissions/scripts/setup'\''|g' Podfile && perl -pi -e 's|(prepare_react_native_project!)|$1\n  setup_permissions([ '\''Bluetooth'\'',])|g' Podfile
cat Podfile
pod install 
cd *folder name similar to your app's name*
perl -i -pe 's|(<string>SplashScreen</string>)|$1\n\t\t<key>NSBluetoothAlwaysUsageDescription</key><string>YOUR TEXT</string>\n\t\t<key>NSBluetoothPeripheralUsageDescription</key><string>YOUR TEXT</string>|g' Info.plist
cat Info.plist
```

**Comment by zoontek** [comment]
@ismith98 There's an expo plugin since 4.1.0
