### ISSUE TITLE
react-native-permissions not compatible with react-native 0.66.2 (IOS)

### ISSUE THREAD

**Issue by keesjetil** [zoontek/react-native-permissions#671]
### Bug summary

Hi all,

When trying to adding camera permissions to my react native app, everything builds fine on Android and IOS. On android this functionality seems to work fine, however when asking permissions on IOS, i made some code that opens the settings:

Permissions.openSettings();

There is no checkbox for giving camera permissions. I tried to reset my privacy settings on the IOS but i still see no camera icon.

Is it correct that react-native-permissions is not yet ready for this react native version? What is the last react-native-version that has been succesfully tested with this package?

If more info is needed please do reply here :)

Happy Coding,

Kees Til

### Library version

3.2.0

### Environment info

```shell
I Just downgraded to another version, if this is really necessary i wil post it. For now downgrading to 0.63.3 and then:

System:
    OS: macOS 11.6
    CPU: (8) arm64 Apple M1
    Memory: 128.16 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.3.0 - /opt/homebrew/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.3.0 - /opt/homebrew/bin/npm
    Watchman: 2021.12.20.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 28, 32
      Build Tools: 27.0.3, 28.0.3, 29.0.2, 30.0.2, 32.0.0
      System Images: android-28 | Intel x86 Atom_64, android-32 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7935034
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

see bug summary

### Reproducible sample code

```js
async function requestDirectPermissionsPlugin(permissionType) {
  const status = await pluginPermissionsCheck(permissionType);

  if (status === true) {
    return status;
  }

  if (Platform.OS === 'ios' && status === false) {
    Permissions.openSettings();
    return null;
  }

  return pluginPermissionsRequest(permissionType);
}
```

**Comment by zoontek** [comment]
`react-native-permissions` is fully compatible with RN 0.66.x.

In order to have the permission switch visible in settings, you have to request it. More infos here https://stackoverflow.com/questions/32332313/ios-camera-permissions-doesnt-appear-under-settings-in-some-devices

```objc
async function requestDirectPermissionsPlugin(permissionType) {
  const status = await request(permissionType);

  if (status === RESULTS.GRANTED) {
    return true;
  } else {
    Permissions.openSettings();
  }
}
```

**Comment by keesjetil** [comment]
When removing the following code for the sake of purpose:

Permissions.openSettings()

I see that the call for a request: Permissions.request(permissionType) works. So thats good news!

However i want the switch to be present. Since the Permissions.openSettings exists within this package, maybe expanding the documentation on how to add these switches when using this function is a great idea?

I am not the greatest with native code (objective-C/SWIFT), If you have any idea on how to do this i would be very happy, but if you have no time i will try figuring it out by myself. Thanks for the fast reply!

**Comment by zoontek** [comment]
That's an iOS issue. The switch cannot be present in some cases (first app run, permission not requested, parental control etc).

We cannot do something about it on our side, sorry!
