### ISSUE TITLE
ACTIVITY_RECOGNITION permission doesn't show dialog in Realme device.

### ISSUE THREAD

**Issue by Bhavdip29** [zoontek/react-native-permissions#679]
### Bug summary

Hello,

I am using react-native 0.61.4 and trying to add the ACTIVITY_RECOGNITION permission. It's working in most of the devices but it is not showing permission dialogue in Realme devices. I was looking for solutions around the web but I couldn't find them.

Can you please suggest to me how can I achieve it?

### Library version

2.2.2

### Environment info

```shell
System:
    OS: macOS 11.6
    CPU: (12) x64 Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz
    Memory: 540.77 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.6.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.5.1 - /usr/local/bin/npm
    Watchman: 2022.02.21.00 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    Android SDK:
      API Levels: 23, 28, 29, 30, 31
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 31.0.0
      System Images: android-29 | Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64, android-30 | Intel x86 Atom_64, android-30 | Google APIs ARM 64 v8a, android-30 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom_64, android-30 | Google Play ARM 64 v8a, android-30 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom_64
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7784292
    Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.4 => 0.61.4 
  npmGlobalPackages:
    react-native-shadow: 1.2.2
```

### Steps to reproduce

1. Ask for the android permission incode like this
`request(PERMISSIONS.ANDROID.ACTIVITY_RECOGNITION).then(status => {
          console.log('Status of the Motion Activity', status);
          this.setState({
            motionActivityStatus: status,
          });})
      .catch(e=>{
       console.log("Error:",e);})`

This code is not working on the Realme device.

### Reproducible sample code

```js
request(PERMISSIONS.ANDROID.ACTIVITY_RECOGNITION).then(status => {
          console.log('Status of the Motion Activity', status);
          this.setState({
            motionActivityStatus: status,
          });})
      .catch(e=>{
       console.log("Error:",e);})
```

**Comment by zoontek** [comment]
@Bhavdip29 Before checking that, try the example app which use up-to-date dependencies (current `react-native` version is 0.67, current `react-native-permissions` version is 3.3.0!)

Here is the exemple app: https://github.com/zoontek/react-native-permissions/tree/master/example
