### ISSUE TITLE
[call for sponsors] - React Native new architecture support

### ISSUE THREAD

**Issue by zoontek** [zoontek/react-native-permissions#684]
Hi everyone 👋

@zoontek here, creator and maintainer of `react-native-{bootsplash / localize / permissions / bars / dev-menu}`.
I'm opening this issue to prevent multiple ones from being created about the new React Native architecture compatibility ([introduced in version `0.68`](https://reactnative.dev/blog/2022/03/30/version-068)).

I'm excited about these changes and the future of React Native, but it's quite hard for me to free up time to work on it.
To explain myself a little bit: I did a lot of open source these last years, mainly for free - and I enjoyed it, don't even doubt about that 😄. It's not only about writing code, but also about helping people, so they can craft great products ✨.

But time flies. On a personal note, I'm currently trying to buy my own flat and started a freelance activity in addition to my regular job to achieve this goal.
Open source is time-consuming (handling issues, reproducing, reviewing PRs, etc) and doesn't pay bills. Even worse: it currently costs me money (I bought several used phones for testing, a personal MacBook recently). I could use this time to work for paid freelancing instead.

On the other side, every day I see companies using these libraries in quite popular apps. That's why I'm calling them for sponsorship. It doesn't have to be a recurrent, monthly sponsorship, but if you want to push for the new arch landing on this repository, understand that it will be easier for me to find some time if I'm being paid for the task 🙂 (actually, it could be fast!)

👉 For that, I created one-time sponsorship tiers ([available here](https://github.com/sponsors/zoontek?frequency=one-time)). You don't have to respect the amounts (custom is possible - maybe you are an individual and can only give a little or maybe you want to give even more than the last tier).
If you are not used to giving money for open source software, you can think of it as a one-time payment license (even if it's clearly not - it will stay free and MIT).

P.S. I'm aware I could also wait for a PR written for free by a community member to land, but that's **not** what I want.
Even if it happens, I will still have to learn about the new arch, review it, and will maintain it / answer your questions after it's merged. So it will probably be easier if I work on it initially.

P.S. (2) That doesn't mean that it will never land if I don't get sponsorships, just that it will be less of a priority for me.

**Comment by BraveEvidence** [comment]
This can help https://www.youtube.com/watch?v=Bn-HIVb2ZIw

**Comment by fobos531** [comment]
@zoontek I'm assuming this can be closed now that #748  is merged?
