### ISSUE TITLE
Storage permission missing

### ISSUE THREAD

**Issue by Okipa** [zoontek/react-native-permissions#69]
First, thanks for your nice package that is working like a charm.

I just noticed that there is one important missing permission for Android.
Indeed, there is no way to ask permission for the Android `READ_EXTERNAL_STORAGE` and `WRITE_EXTERNAL_STORAGE`permissions that are required to use some other packages as https://github.com/bamlab/react-native-image-resizer or https://github.com/johanneslumpe/react-native-fs that are manipulating files and stuff in the device storage.

I had to use http://facebook.github.io/react-native/releases/0.37/docs/permissionsandroid.html in order to request the storage permission.
It would be great to add it to your package !

**Comment by yonahforst** [comment]
I've added an explicit permission type called `storage` in bdf121d. Note: `photo` also required external storage so if you request one, you'll get them both. For write access just include `android.permission.WRITE_EXTERNAL_STORAGE` in your manifest
