### ISSUE TITLE
Android 12 - Nearby Devices Permission.

### ISSUE THREAD

**Issue by Hamashassan** [zoontek/react-native-permissions#690]
### Bug summary

In Android 12, In my application I would like to enable Nearby Devices. In my manifest I already given BLUETOOTH_SCAN and BLUETOOTH_CONNECT permission as per the google documentation. I would like to show the permission popup to ask user to enable Nearby Devices.

### Library version

3.3.0

### Environment info

```shell
System:
    OS: macOS 11.6.5
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 2.28 GB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.14.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.3.1 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8193401
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: 18.0.1.1 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

1. …nothing
2. …

### Reproducible sample code

```js
....
```

**Comment by zoontek** [comment]
Use `requestMultiple`

```ts
requestMultiple([
  PERMISSIONS.ANDROID.BLUETOOTH_SCAN,
  PERMISSIONS.ANDROID.BLUETOOTH_CONNECT
]).then((statuses) => {
  // …
});
```

**Comment by amb-silvertree** [comment]
This should be reopened: the Android "Nearby Devices" permission is not the same as the combination of  PERMISSIONS.ANDROID.BLUETOOTH_SCAN and  PERMISSIONS.ANDROID.BLUETOOTH_CONNECT. I am currently seeing the following data from requestMultiple and my Nearby Devices permission on the app is denied: 

{"android.permission.ACCESS_FINE_LOCATION": "granted", "android.permission.BLUETOOTH_CONNECT": "granted", "android.permission.BLUETOOTH_SCAN": "granted"}

**Comment by bm181354** [comment]
@amb-silvertree were you able to fix this?

**Comment by yahacom** [comment]
Probably same issue on `react-native-permissions 3.3.1`
Nearby devices permission is always `granted` even if it's revoked in Settings.

**Comment by zoontek** [comment]
@yahacom Just update.
Why: https://github.com/zoontek/react-native-permissions/releases/tag/3.4.0

**Comment by yahacom** [comment]
thanks, I see.

also for anyone check your `compileSdkVersion` and `targetSdkVersion` to be 31 at least to work with nearby devices permission correctly. outdated lib version and `targetSdkVersion: 30` was reason of issue for me.
