### ISSUE TITLE
Support for healthkit

### ISSUE THREAD

**Issue by walterholohan** [zoontek/react-native-permissions#691]
### Why it is needed?

I am currently building an apple watch app which tracks a user while they are running. We use healthKit on the watch app to get the users heart rate, distance and speed while running. In order to do so the user must accept healthkit permissions for this data. This can be done on the apple watch app or on the mobile app. At the moment the only way to do this on React Native is to use https://github.com/agencyenterprise/react-native-health/blob/master/docs/permissions.md however this does not allow us to check if a user has accepted the permission, it will only request.

**Comment by zoontek** [comment]
Duplicate of https://github.com/zoontek/react-native-permissions/issues/229

**Comment by walterholohan** [comment]
@zoontek did you mean to reference https://github.com/zoontek/react-native-permissions/issues/691 as that is this current feature request

**Comment by zoontek** [comment]
@walterholohan Yes, my bad, wrong copy / paste.
