### ISSUE TITLE
(Android 12)There is no 'Deny', 'Don't Ask again' option anymore

### ISSUE THREAD

**Issue by DonRyu** [zoontek/react-native-permissions#692]
### Why it is needed?

I am using Android 12. There is no 'Deny', 'Don't Ask again' option anymore.
It has  only three things
-While using this app' (granted) 
-'only this time' (granted) 
-'don't allow' (blocked)

Android changed the process or this library has error? (Lower version android still has 'deny' and 'Don't Ask again' option

### Possible implementation

When user choose block, move them to setting page

### Code sample

```js
request(PERMISSIONS.ANDROID.ACCESS_FINE_LOCATION).then((res) => console.log('res###', res))

//Android manifest setting

<uses-permission android:name="android.permission.INTERNET"/>
<uses-permission android:name="android.permission.CAMERA"/>
<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
```

**Comment by zoontek** [comment]
Android system changed
