### ISSUE TITLE
No permission handler detected

### ISSUE THREAD

**Issue by JB-CHAUVIN** [zoontek/react-native-permissions#694]
### Bug summary

Hello,

I have the following error : "**No permission handler detected**". 
![error694](https://user-images.githubusercontent.com/8957878/175506921-f40150cb-b94e-4c36-a6a9-ef82a2d798e5.jpg)

I followed all steps to clean Derived data, XCODE project, installed Pods correctly, deleted the app... etc...
I really tried everything but it's not working after upgrading from RN 0.64 to 0.68.

Any ideas ?

### Library version

3.3.1

### Environment info

```shell
System:
    OS: macOS 12.2.1
    CPU: (10) x64 Apple M1 Pro
    Memory: 28.11 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.19.1 - /usr/local/bin/node
    Yarn: 1.22.18 - /opt/homebrew/bin/yarn
    npm: 6.14.16 - /usr/local/bin/npm
    Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8309675
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/bin/javac
  npmPackages:
    react: 17.0.2
    react-native: 0.68.1
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

N/A

### Reproducible sample code

```js
N/A
```

**Comment by zoontek** [comment]
@JB-CHAUVIN Hi! This kind of issues are frequent and are not really issues for the library, so I let you search for duplicates.

1. Check that you setup at least on handler in your Podfile and run pod install after
2. If you use `use_frameworks!`, be sure to read the README for the workaround
3. If it's a build cache error, run [react-native-clean-project](https://github.com/pmadruga/react-native-clean-project)

**Comment by JB-CHAUVIN** [comment]
Please don't close my issue,

I already tried the solutions and spent many days on this problem...

My podfile is installed correctly : 
```
    permissions_path = '../node_modules/react-native-permissions/ios'
    # pod 'Permission-AppTrackingTransparency', :path => "#{permissions_path}/AppTrackingTransparency"
    # pod 'Permission-BluetoothPeripheral', :path => "#{permissions_path}/BluetoothPeripheral"
    pod 'Permission-Calendars', :path => "#{permissions_path}/Calendars"
    pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
    pod 'Permission-Contacts', :path => "#{permissions_path}/Contacts"
    pod 'Permission-FaceID', :path => "#{permissions_path}/FaceID"
    pod 'Permission-LocationAccuracy', :path => "#{permissions_path}/LocationAccuracy"
    pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways"
    pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
    pod 'Permission-MediaLibrary', :path => "#{permissions_path}/MediaLibrary"
    pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone"
    # pod 'Permission-Motion', :path => "#{permissions_path}/Motion"
    pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"
    pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
    pod 'Permission-PhotoLibraryAddOnly', :path => "#{permissions_path}/PhotoLibraryAddOnly"
    # pod 'Permission-Reminders', :path => "#{permissions_path}/Reminders"
    # pod 'Permission-Siri', :path => "#{permissions_path}/Siri"
    # pod 'Permission-SpeechRecognition', :path => "#{permissions_path}/SpeechRecognition"
    # pod 'Permission-StoreKit', :path => "#{permissions_path}/StoreKit"
```

**Comment by zoontek** [comment]
@JB-CHAUVIN Can you reproduce this on a fresh project with only the library? If you can't, that's not a library issue, but an error while upgrading your project.
You can check https://react-native-community.github.io/upgrade-helper/?from=0.64.0&to=0.68.2 to be sure you didn't miss something during the update.

**Comment by kevinnguy** [comment]
I found the issue to be the path of the headers imported in `RNPermission` for iOS. I had to patch my import paths based on the permission dependency like:  `#import "Permission-Camera/RNPermissionHandlerCamera.h"`
