### ISSUE TITLE
Android permission biometric

### ISSUE THREAD

**Issue by rodrigodiasf1984** [zoontek/react-native-permissions#703]
### Why it is needed?

Hi guys, I hope you're doing well! Can you please help me with, how I can check if the user has the android and IOS biometric permission? 

After the user login, I need to verify if the permission has been granted or not! 

Thanks in advance!

### Code sample

```js
<uses-permission android:name="android.permission.USE_BIOMETRIC" />

check(PERMISSIONS.ANDROID_BIOMETRIC)
        .then(result => {
          console.log('result ACTIVITY_BIOMETRIC', result);
        })
        .catch(error => {
          console.log('error checkPermissions', error);
        });
```

**Comment by zoontek** [comment]
USE_BIOMETRIC is not a "dangerous level" permission (something to request). Just declare it in your AndroidManifest.

https://developer.android.com/reference/android/Manifest.permission#USE_BIOMETRIC

**Comment by zoontek** [comment]
@rodrigodiasf1984 Next time, search for duplicates first https://github.com/zoontek/react-native-permissions/issues/388 🙂

**Comment by rodrigodiasf1984** [comment]
> @rodrigodiasf1984 Next time, search for duplicates first #388 🙂

I will thanks!
