### ISSUE TITLE
"Only this time" and "While using the app" both options are returned "granted" on location permission request

### ISSUE THREAD

**Issue by hozdemir** [zoontek/react-native-permissions#705]
### Bug summary

When i choose "**only this time**" on location permission window on android 11 "**granted**" status returned from `**check**` and request methods. Shouldn't it return "**limited**" when "**only this time**" is selected?

### Library version

3.3.1

### Environment info

```shell
System:
    OS: macOS 12.5
    CPU: (8) arm64 Apple M1
    Memory: 87.05 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.6.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.13.2 - /opt/homebrew/bin/npm
    Watchman: 2022.07.04.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: Dolphin 2021.3.1 Canary 9 Dolphin 2021.3.1 Canary 9
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.1 => 0.68.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

1. install example app in example folder
2. press "check" button on location line and press "only this time" on native android location permission window
3. notification appeared on `check` method status as "granted"
4. remove application data and permissions with following commands `adb shell pm clear com.xxxx` and `adb shell pm revoke com.xxx android.permission.ACCESS_FINE_LOCATION` 
5. press check button on location line and press "while using the app" on native android location permission window
6. notification appeared on `check` method status as "granted"

### Reproducible sample code

```js
**
```

**Comment by zoontek** [comment]
Please update first (https://github.com/zoontek/react-native-permissions/releases/tag/3.4.0) to avoid issues with "Only this time" and "Ask next time"

Also, no. Permission is granted for this time, that's not what limited represent.
