### ISSUE TITLE
Find doc error in iOS permission flow

### ISSUE THREAD

**Issue by ChokShen** [zoontek/react-native-permissions#706]
### Why it is needed?

Should exchange YES and NO flow in my screen shot? 
<img width="873" alt="image" src="https://user-images.githubusercontent.com/26767040/184852815-f8de3206-c9fe-4d3e-8788-bd226e69c979.png">

**Comment by zoontek** [comment]
@ChokShen No? I don't see an issue here

**Comment by ChokShen** [comment]
> @ChokShen No? I don't see an issue here

@zoontek I mean if requestable is NO, flow should request permission, otherwise it returns RESULTS

**Comment by zoontek** [comment]
@ChokShen That's still don't make sense. If the request is not requestable, this means the feature access is: BLOCKED, GRANTED or LIMITED. No prompt alert will appear.

**Comment by ChokShen** [comment]
@zoontek I get confused because RESULTS.DENIED means the permission has not been requested / is denied but requestable you mentioned in doc.I believe I understand its meaning when I compare the flow with Android.

**Comment by zoontek** [comment]
DENIED is Android official wording and it's not clear indeed. Next major version will probably rename it UNDETERMINED

**Comment by ChokShen** [comment]
Sorry about that.I think I misunderstood&nbsp;
what&nbsp;requestable mean. I thought permission &nbsp;request has been sent at once when it is YES.But&nbsp;requestable seems not a formal English word😂.

发自我的iPhone


------------------ Original ------------------
From: Mathieu Acthernoene ***@***.***&gt;
Date: Tue,Aug 16,2022 7:31 PM
To: zoontek/react-native-permissions ***@***.***&gt;
Cc: ChokShen ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [zoontek/react-native-permissions] Find doc error in iOS permission flow (Issue #706)





 
DENIED is Android official wording and it's not clear indeed. Next major version will probably rename it UNDETERMINED
