### ISSUE TITLE
Request Promise not working on Android

### ISSUE THREAD

**Issue by Estroo** [zoontek/react-native-permissions#708]
### Bug summary

Hello, I tried to implement the permission request, it works well on iOS but on Android I got some issue and it doesn't go inside the then after requesting the promise. I have this issue with the simple request and the multiple request.

Here's the code : 
```js
    let cameraPerm =
      Platform.OS === 'ios'
        ? PERMISSIONS.IOS.CAMERA
        : PERMISSIONS.ANDROID.CAMERA;
    let locationPerm =
      Platform.OS === 'ios'
        ? PERMISSIONS.IOS.LOCATION_WHEN_IN_USE
        : PERMISSIONS.ANDROID.ACCESS_FINE_LOCATION;
    requestMultiple([cameraPerm, locationPerm]).then(status => {
      console.log('status camera : ', status[cameraPerm]);
      console.log('status location : ', status[locationPerm]);
    });
```
I have nothing inside the console

### Library version

3.6.1

### Environment info

```shell
System:
    OS: macOS 12.5
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 87.05 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.15.1 - ~/.nvm/versions/node/v14.15.1/bin/node
    Yarn: Not Found
    npm: 6.14.8 - ~/.nvm/versions/node/v14.15.1/bin/npm
    Watchman: 2022.03.21.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 27, 29, 32
      Build Tools: 29.0.2, 32.0.0
      System Images: android-27 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7935034
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_312 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.64.1 => 0.64.1
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

1. Implement the code
2. Run it on Android and see if any console after request

### Reproducible sample code

```js
let cameraPerm =
      Platform.OS === 'ios'
        ? PERMISSIONS.IOS.CAMERA
        : PERMISSIONS.ANDROID.CAMERA;
    let locationPerm =
      Platform.OS === 'ios'
        ? PERMISSIONS.IOS.LOCATION_WHEN_IN_USE
        : PERMISSIONS.ANDROID.ACCESS_FINE_LOCATION;
    requestMultiple([cameraPerm, locationPerm]).then(status => {
      console.log('status camera : ', status[cameraPerm]);
      console.log('status location : ', status[locationPerm]);
    });
```

**Comment by esutton** [comment]
This worked for me using **Android 12**, Pixel 3a.
```
    requestMultiple([
      PERMISSIONS.ANDROID.BLUETOOTH_CONNECT, 
      PERMISSIONS.ANDROID.BLUETOOTH_SCAN
    ]).then((statuses) => {
      console.log('PERMISSIONS.ANDROID.BLUETOOTH_CONNECT', statuses[PERMISSIONS.ANDROID.BLUETOOTH_CONNECT]);
      console.log('PERMISSIONS.ANDROID.BLUETOOTH_SCAN', statuses[PERMISSIONS.ANDROID.BLUETOOTH_SCAN]);
    });

```

package.json
```
    "react-native-permissions": "^3.6.1",
```

android/app/src/main/AndroidManifest.xml
```
	<!-- Request legacy Bluetooth permissions on older devices. -->
	<uses-permission android:name="android.permission.BLUETOOTH" 
					 android:maxSdkVersion="30" />
	<uses-permission android:name="android.permission.BLUETOOTH_ADMIN"
					 android:maxSdkVersion="30" /> />

	<!--From Android 12-->
	<uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />
    <!-- BLUETOOTH_SCAN if your app looks for Bluetooth devices.
             If your app doesn't use Bluetooth scan results to derive physical
             location information, you can strongly assert that your app
             doesn't derive physical location. -->	
    <uses-permission android:name="android.permission.BLUETOOTH_SCAN"
                     android:usesPermissionFlags="neverForLocation" />

    <!-- BLUETOOTH_ADVERTISE if your app makes the device discoverable to Bluetooth
      devices. -->
	<uses-permission android:name="android.permission.BLUETOOTH_ADVERTISE" />	
```

android/build.gradle
```
    ext {
        buildToolsVersion = "30.0.3"
        minSdkVersion = 21
        compileSdkVersion = 31
        targetSdkVersion = 31
    }    
```

Thank you for a great library!

**Comment by zoontek** [comment]
@Estroo1 Are you sure you are not missing something, and it goes though the catch? (The promise is rejected?)

**Comment by Estroo** [comment]
> @Estroo1 Are you sure you are not missing something, and it goes though the catch? (The promise is rejected?)

I wish I do but I can't find anything wrong. It doesn't go through the catch, the promise is still pending. If I click again on my button to ask permission I got the warning telling me that this promise already exists and still pending, like if something was missing inside the native component and was looping inside of it or something like that

**Comment by zoontek** [comment]
Just checked, it works without any issue. Could you provide more infos about how you request the permissions? Maybe a minimal example in a reproduction repository?

https://user-images.githubusercontent.com/1902323/187069073-077d8728-5f59-4d07-bdd7-1b6e7770e87b.mp4

**Comment by Estroo** [comment]
Just tested and I still have the issue, but with a fresh project it's working well. Look like I have to deal with the native android files, that's my only difference got some old that I should maybe update. I keep you in touch if I find something and let it open if you have any idea

**Comment by zoontek** [comment]
I'm closing this since it seems more related to your stack / there is no solid reproduction test. Feel free to ping me on this issue if you got what's wrong here.

**Comment by ghorbani-m** [comment]
I have the same issue!

**Comment by mikehardy** [comment]
> I have the same issue!

From a "getting help" perspective, this is content-free unfortunately
https://stackoverflow.com/help/how-to-ask
https://stackoverflow.com/help/minimal-reproducible-example
