### ISSUE TITLE
please publish latest version to npm 

### ISSUE THREAD

**Issue by alfonsodev** [zoontek/react-native-permissions#71]
The latests change to support react-native 0.40 seem to published on npm. 
The headers are 
```
#import "RCTConvert.h"
```

Thank you.

**Comment by yonahforst** [comment]
Will do! I'm just addressing the open issues and I'll push a new vesion

**Comment by yonahforst** [comment]
just published 0.2.6

**Comment by yonahforst** [comment]
please use 0.2.7. there was an android bug in 0.2.6
