### ISSUE TITLE
Expose shouldShowRequestPermissionRationale

### ISSUE THREAD

**Issue by Minishlink** [zoontek/react-native-permissions#710]
### Why it is needed?

Hi, would you be open as to expose shouldShowRequestPermissionRationale Android method?
This is needed when you want to have a custom rationale screen and not an Alert.

Currently one can access it from NativeModules but this is not very safe as this is an internal thing right now.

Thanks

### Possible implementation

Maybe naming it android_shouldShowRequestPermissionRationale or something like this to indicate this is an Android-only method.

**Comment by zoontek** [comment]
Latest version allows `() => Promise<boolean>` as `rationale` argument, allowing you to perform whatever you want and just return the user choice 🙂

Full changelog: https://github.com/zoontek/react-native-permissions/releases/tag/3.9.0
