### ISSUE TITLE
requestNotifications doesn't return blocked the first time is called on android 13

### ISSUE THREAD

**Issue by rborn** [zoontek/react-native-permissions#712]
### Bug summary

I have a weird situation when I call the `requestNotifications` and the first time I call it, if I click "don't allow" it will return `denied` instead of `blocked`.

The next time I call requestNotifications (in the same session), the OS popup shows again  and  this time on deny it will show `blocked`

This ( and the fact that android doesn't report blocked on checkNotification) makes the user flows we have impossible.

This happens on an Android Emulator ( don't have a real device) 

Any idea what could be wrong? 

### Library version

3.6.1

### Environment info

```shell
Node: 16.11.1 
    Yarn: 1.22.18
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 28, 29, 30, 31, 33
      Build Tools: 28.0.2, 28.0.3, 29.0.3, 30.0.2, 30.0.3, 31.0.0, 33.0.0
      System Images: android-29 | Google APIs Intel x86 Atom, android-29 | Google Play ARM 64 v8a, android-29 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom_64, android-33 | Google Play Intel x86 Atom_64
      Android NDK: 20.1.5948944

react-native: 0.67.4
```

### Steps to reproduce

~~I'm really sorry, this is a crazy monorepo and is super hard to create a repro but, the steps are like it follows~~
The flow is as it follows, but I have managed to reproduce is (see next step)

- install app
- onboard user
- ask for push permissions ( will return `denied` if we don't accept)
- move to other section of the app where we ask permissions again
- ask for push permissions ( will return `blocked` if we don't accept) 

The thing is that I want to understand when I can expect to see the OS popup or I need to call `openSettings`. Right now with the current issue the app will show the popup and then move to openSettings which is bad.

### Reproducible sample code

 - npx react-native init rnp --version 0.67.4
 - set in AndroidManifest.xml  `android:exported="true"` for the activity
 - set in android/build.gradle 
 ```
    buildToolsVersion = "33.0.0"
        minSdkVersion = 26
        compileSdkVersion = 33
        targetSdkVersion = 33
        supportLibVersion = "33.0.0"
        ndkVersion = "21.4.7075529"
        
```
- npx react-native run-android
- app.js 
```
import {requestNotifications} from 'react-native-permissions';

...

  const onAsk = async () => {
    const result = await requestNotifications();
    console.log(result);
  };
```

To get the behaviour you need to reinstall the app every time you want to try this

https://user-images.githubusercontent.com/406409/187996865-c72ca62f-5afd-4dd3-b59b-2a33eb29e78e.mov

**Comment by zoontek** [comment]
@rborn This is totally normal if it's still requestable on a second call.

Check the Android flow in the README https://github.com/zoontek/react-native-permissions#android-flow

Before they were a "Never ask again" checkbox, in recent Android versions permissions can be requested twice.

**Comment by rborn** [comment]
@zoontek oh, I didn't know you can ask twice, thank you and sorry for the mess 😅
