### ISSUE TITLE
iOS 15.3.1 ATT permission not showing up, status alway unvailable

### ISSUE THREAD

**Issue by camboYY** [zoontek/react-native-permissions#713]
### Bug summary

React.useEffect(() => {
    const listener = async () => {
      const ATT_CHECK = await check(PERMISSIONS.IOS.APP_TRACKING_TRANSPARENCY);

      console.log('helllloooooostatus', Platform.OS, appState, ATT_CHECK);

      if (Platform.OS === 'ios' && appState === 'active') {
        request(PERMISSIONS.IOS.APP_TRACKING_TRANSPARENCY)
          .then((result) => console.log(result, 'helllloooooo122'))
          .catch((error) => console.log(error, 'helllloooooo1000'));
      }
    };
    listener();
  }, [appState]);

### Library version

3.6.1

### Environment info

```shell
System:
    OS: macOS 12.5
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 35.86 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.17.4 - /usr/local/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 7.20.3 - /usr/local/bin/npm
    Watchman: 2021.08.02.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7583922
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.12 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

1. …
2. …

### Reproducible sample code

```js
React.useEffect(() => {
    const listener = async () => {
      const ATT_CHECK = await check(PERMISSIONS.IOS.APP_TRACKING_TRANSPARENCY);

      console.log('helllloooooostatus', Platform.OS, appState, ATT_CHECK);

      if (Platform.OS === 'ios' && appState === 'active') {
        request(PERMISSIONS.IOS.APP_TRACKING_TRANSPARENCY)
          .then((result) => console.log(result, 'helllloooooo122'))
          .catch((error) => console.log(error, 'helllloooooo1000'));
      }
    };
    listener();
  }, [appState]);
```

**Comment by choijiho0021** [comment]
same problem.
15.3 ios version error
15.5 ios version working

( lib version 3.3.1 )

**Comment by mikehardy** [comment]
@choijiho0021 how is working with 15.7 since that is current, and everyone on 15.x will update pretty shortly? Supporting the intermediate versions does not have much value if 15.7 works
