### ISSUE TITLE
Cannot build Android, asking for sdktool 33

### ISSUE THREAD

**Issue by deckyfx** [zoontek/react-native-permissions#719]
### Bug summary

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':react-native-permissions:compileDebugAidl'.
> Installed Build Tools revision 33.0.0 is corrupted. Remove and install again using the SDK Manager.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 27s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup. Run CLI with --verbose flag for more details.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

error Command failed with exit code 1.
```

### Library version

3.6.1

### Environment info

```shell
System:
    OS: macOS 12.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Memory: 36.39 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
    Watchman: 2022.09.12.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/decky/.rvm/gems/ruby-3.0.2/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33
      Build Tools: 26.0.2, 27.0.1, 27.0.3, 28.0.3, 29.0.2, 29.0.3, 30.0.0, 30.0.0, 30.0.2, 30.0.3, 31.0.0, 33.0.0
      System Images: android-25 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8512546
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 13.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^16.13.1 => 16.14.0 
    react-native: ^0.63.2 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

run react-native run-android

### Reproducible sample code

```js
Its error during build phase so no code to show
```

**Comment by deckyfx** [comment]
btw sdktool 33 is installed from SDKManager, i tried reinstall it many times

**Comment by zoontek** [comment]
> Installed Build Tools revision 33.0.0 is corrupted. Remove and install again using the SDK Manager.

This does not look like an issue with the library itself, more an install issue on your computer.

More infos here, maybe:
- https://stackoverflow.com/questions/68387270/android-studio-error-installed-build-tools-revision-31-0-0-is-corrupted
- https://issuetracker.google.com/issues/242767861

Also, please check that you installed the latest Android Studio version.

**Comment by cw-sanjeev** [comment]
Hi @zoontek , facing the face issue, tested on different systems (windows, linux, mac) and still getting the above issue as raised.

**Comment by mikehardy** [comment]
I just did this

bash
```
git clone git@github.com:zoontek/react-native-permissions
cd react-native-permissions
yarn
cd example
yarn
yarn react-native run-android
```

It worked for me.0

Please note that JDK13 (listed in your environment output) is not viable. react-native specifically uses JDK11 right now. 

Basically the links posted above are correct, **please heed them**

Specifically, your gradle is too old, most likely because your react-native is too old (0.63.x is way too old).

**upgrade your react-native and you will get a version of gradle that works**. 

The example in this repo uses gradle 7.3.3 for instance, it works fine.

**Comment by zoontek** [comment]
Same as @mikehardy here. I tried on two different computers without any issue.

I recommend using Temurin to install Java 11: https://adoptium.net/en-GB/installation
And same advice, try updating React Native (and Gradle) and Android Studio. Everything will work correctly then.

Sorry I can't help more here, but this is not related to `react-native-permissions` directly 😕

**Comment by luis-cicada** [comment]
This seems to do the trick @deckyfx 

## change below to your Android SDK path
cd ~/Library/Android/sdk/build-tools/33.0.0 \
  && mv d8 dx \
  && cd lib  \
  && mv d8.jar dx.jar

**Comment by mikehardy** [comment]
@luis-cicada that's a workaround, and it gets lots of praise on stackoverflow and issue trackers, but is just a workaround. It should not be necessary. There is something wrong in the local install of something, but renaming internal parts of the build-tools is not a great solution, I would dig deeper. Perhaps $ANDROID_HOME/cmdline-tools/latest/bin is not on the $PATH first, and an out of date gradle that cannot handle buildtools 33 yet
