### ISSUE TITLE
** BUILD FAILED **

### ISSUE THREAD

**Issue by katarina-simnova** [zoontek/react-native-permissions#72]
I get this error when trying to run on IOS:

** BUILD FAILED **

The following build commands failed:
        CompileC /Users/katarina/AndroidStudioProjects/reactnative-kitchensink/ios/build/
Build/Intermediates/ReactNativePermissions.build/Debug-iphonesimulator/ReactNativePermiss
ions.build/Objects-normal/x86_64/ReactNativePermissions.o ReactNativePermissions.m normal
 x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/kitchensink.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/
Debug-iphonesimulator/kitchensink.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

I tried to link library manually but I can't find "libReactNativePermissions.a" file.

**Comment by yonahforst** [comment]
you can find it by expanding `ReactNativePermissions.xcodeproj` -> `Projects`

I've never seen this error. possibly related to this? https://github.com/facebook/react-native/issues/7308

Which version of RN are you running?

**Comment by katarina-simnova** [comment]
I solved this problem just yesterday. I''m running version RN 0.40.
You upgraded library to RN 0.41. 
But after running:

> npm install --save react-native-permissions

 the old version of library is installed.
I mean old version using this importing syntax: 

> #import "RCTConvert.h"

 instead of this:

>  #import <React/RCTConvert.h>

Installing directly helped: 

> npm i -S https://github.com/yonahforst/react-native-permissions.git

**Comment by yonahforst** [comment]
ah yes. I havent pushed a new version to NPM yet. waiting to fix the open issues. I'll be pushing shortly

**Comment by yonahforst** [comment]
just published 0.2.6

**Comment by yonahforst** [comment]
please use 0.2.7. there was an android bug in 0.2.6
