### ISSUE TITLE
check(PERMISSIONS.ANDROID.ACCESS_FINE_LOCATION) is returning "already-enabled"

### ISSUE THREAD

**Issue by Himatheja** [zoontek/react-native-permissions#723]
### Why it is needed?

For Fewer mobile devices (OnePlus 6), if Permssion is already granted then the result of check(PERMISSIONS.ANDROID.ACCESS_FINE_LOCATION) is returning "already-enabled". This helps us to handle the location permission efficently and not affecting the flow.

**Comment by zoontek** [comment]
@Himatheja I didn't understand what you mean at all. Please respect the template and give more infos (Possible implementation, code sample)
