### ISSUE TITLE
Android 13 check(PERMISSIONS.ANDROID.POST_NOTIFICATIONS) returns denied and not blocked

### ISSUE THREAD

**Issue by nicolasdevienne** [zoontek/react-native-permissions#725]
### Bug summary

On Android 13, when a user choice "Don't allow" twice in the prompt for notifications, `request(PERMISSIONS.ANDROID.POST_NOTIFICATIONS)` returns "blocked" but `check(PERMISSIONS.ANDROID.POST_NOTIFICATIONS)` returns "denied". I think `check(PERMISSIONS.ANDROID.POST_NOTIFICATIONS)` must return "blocked" in this case.

### Library version

3.6.1

### Environment info

```shell
System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1 Pro
    Memory: 91.02 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.9.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.1 - /opt/homebrew/bin/npm
    Watchman: 2022.09.05.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9014738
    Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /opt/homebrew/opt/openjdk@11/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.4 => 0.66.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

1. `request(PERMISSIONS.ANDROID.POST_NOTIFICATIONS)` for the first time
2. user choice "Don't allow"
3. `request(PERMISSIONS.ANDROID.POST_NOTIFICATIONS)` for the second time
4. user choice "Don't allow"
5. it's impossible to request because status = blocked but `check(PERMISSIONS.ANDROID.POST_NOTIFICATIONS)` returns "denied" and not "blocked"

### Reproducible sample code

```js
await request(PERMISSIONS.ANDROID.POST_NOTIFICATIONS)
await request(PERMISSIONS.ANDROID.POST_NOTIFICATIONS)
const response = check(PERMISSIONS.ANDROID.POST_NOTIFICATIONS)
console.log(response)
```

**Comment by zoontek** [comment]
This is unfortunately not possible on Android. Check the flow: https://github.com/zoontek/react-native-permissions#android-flow
