### ISSUE TITLE
[Android] Add check if locations are enabled on the whole device

### ISSUE THREAD

**Issue by emjeku** [zoontek/react-native-permissions#727]
### Why it is needed?

Hey there, it's a nice lib, we are using it. 
We need additional information about the GPS Provider.
If the app has all location permissions, but you go to the system settings and turn off `Location` => `Use location` then the library will (correctly) say that the app has all the rights. However for knowing if we can use the location API it would be helpful to see, if locations are enabled on the whole device as well.

### Code sample
We came up with this
```js



 @ReactMethod
  public void checkIfGPSProviderEnabled(final Promise promise){
    final ReactApplicationContext reactContext = getReactApplicationContext();
    LocationManager locationManager =(LocationManager) reactContext.getSystemService(Context.LOCATION_SERVICE);
      gpsStatus = locationManager.isProviderEnabled(LocationManager.GPS_PROVIDER);
      promise.resolve(gpsStatus);
  }



```
but you might have a better idea on how to do this.

**Comment by mikehardy** [comment]
Hey there @emjeku - you want https://github.com/react-native-device-info/react-native-device-info#isLocationEnabled

This package is about permissions.
That package (react-native-device-info) is about device status etc.

**Comment by mikehardy** [comment]
Also may like to know details: https://github.com/react-native-device-info/react-native-device-info#getavailablelocationproviders

**Comment by miallo** [comment]
@mikehardy Thank you for your fast reply and pointing us in the right direction! :+1:
