### ISSUE TITLE
No permission popup for Android 13

### ISSUE THREAD

**Issue by jslok** [zoontek/react-native-permissions#728]
### Bug summary

When using a real device, I get no permission request popups when I use a Pixel 7 real device or an emulator on Android 13. My app is targeting sdk version 33.
It works as expected on Android 12 and/or if I revert to target sdk version 29.

### Library version

3.6.1

### Environment info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 AMD Ryzen 5 5600X 6-Core Processor
    Memory: 15.50 GB / 31.93 GB
  Binaries:
    Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0, 31.0.0, 32.1.0, 33.0.0, 33.0.0, 33.0.0, 33.0.0, 33.0.0
      System Images: android-24 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-31 | Google APIs Intel x86 Atom_64, android-33 | Google APIs Intel x86 Atom_64
      Android NDK: 22.1.7171670
    Windows SDK: Not Found
  IDEs:
    Android Studio: AI-212.5712.43.2112.8609683
    Visual Studio: 17.2.32630.192 (Visual Studio Community 2022), 15.9.28307.1831 (Visual Studio Community 2017)
  Languages:
    Java: 16.0.2
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^18.2.0 => 18.2.0
    react-native: 0.70.3 => 0.70.3
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

Try to request permission. See no popup.

### Reproducible sample code

```js
async function hasAndroidPermission() {
    const permission = PERMISSIONS.ANDROID.READ_EXTERNAL_STORAGE

    let hasPermission = await check(permission)
      .then((result) => {
        return ['limited', 'granted'].includes(result)
      })
      .catch((e) => {
        console.log(e)
      })
    if (hasPermission) return true

    let rationale = {
      title: 'Grant storage permisssion',
      message: 'App needs device storage permission to save images.',
      buttonNeutral: 'Ask Me Later',
      buttonNegative: 'Cancel',
      buttonPositive: 'OK!',
    }
    return request(permission, rationale)
      .then((result) => {
        return ['limited', 'granted'].includes(result)
      })
      .catch((e) => {
        console.log(e)
      })
  }
```

**Comment by zoontek** [comment]
@jslok And what is the result here?

**Comment by jslok** [comment]
@zoontek The permission request returns 'blocked' even with a fresh install and the first time requesting the permission.

**Comment by zoontek** [comment]
Found it, it's explained here: https://developer.android.com/about/versions/13/behavior-changes-13#granular-media-permissions

> If your app targets Android 13 or higher and needs to [access media files that other apps have created](https://developer.android.com/training/data-storage/shared/media#storage-permission), you must request one or more of the following granular media permissions instead of the [READ_EXTERNAL_STORAGE](https://developer.android.com/reference/android/Manifest.permission#READ_EXTERNAL_STORAGE) permission:
>
> Type of media | Permission to request
> -- | --
> Images and photos | READ_MEDIA_IMAGES
> Videos | READ_MEDIA_VIDEO
> Audio files | READ_MEDIA_AUDIO

**Comment by jslok** [comment]
Thanks @zoontek that did the trick.

**Comment by pierroo** [comment]
Quick question for the above @jslok @zoontek :

If i'm targeting SDK 33 in my build.gradle, does that mean I no longer even have to check permission READ_EXTERNAL_STORAGE?
Even for android version below 13?

So by asking for permission READ_MEDIA_IMAGES it will also ask for permission properly on an android 12 device?

**Comment by irodeanu** [comment]
> 

You can use something like this:


```
function writeStoragePermission() {
  if (Platform.OS === 'ios') {
    return undefined;
  }
  DeviceInfo.getApiLevel().then((level) => {
    if (level && Number(level) >= 33) {
      return PERMISSIONS.ANDROID.READ_MEDIA_IMAGES;
    } else {
      return PERMISSIONS.ANDROID.WRITE_EXTERNAL_STORAGE;
    }
  });
}
```

**Comment by pierroo** [comment]
Thank you for this suggestion @irodeanu 
I found an even more straight forward way without third party dependency, from Platform imported from react-native you can have the following on android:
`const { Release = 13 } = Platform.constants`
then: 
`const permission = parseInt(Release) >= 13 ? PERMISSIONS.ANDROID.READ_MEDIA_IMAGES : PERMISSIONS.ANDROID.READ_EXTERNAL_STORAGE`
