### ISSUE TITLE
how can i get a notification permission status?

### ISSUE THREAD

**Issue by pepe-dunamu** [zoontek/react-native-permissions#729]
### Bug summary

![스크린샷 2022-10-25 오후 8 43 11](https://user-images.githubusercontent.com/79429899/197764576-e995bf91-5bd5-4d18-9962-a8b9f2ad02ef.png)

there is nothing related to notifications
i want to do this Permissions.IOS.Notifications 

### Library version

3.1.0

### Environment info

```shell
sorry
```

### Steps to reproduce

1. …1
2. …2

### Reproducible sample code

```js
case 'NOTIFICATION':
          result = await check(PERMISSIONS.IOS.);
          break;
```

**Comment by zoontek** [comment]
> Environment info
> 
> sorry

Me too. RTFM.

**Comment by rishabhyadavv** [comment]
Hi @taehyun-kim-tenuto 

Did you get the solution for this?

Regards,
Rishabh

**Comment by mlazari** [comment]
@rishabhyadavv Use [checkNotifications](https://github.com/zoontek/react-native-permissions#checknotifications) / [requestNotifications](https://github.com/zoontek/react-native-permissions#requestnotifications)
