### ISSUE TITLE
Checking permission for iOS LOCATION_ALWAYS and LOCATION_WHEN_IN_USE return as "granted"

### ISSUE THREAD

**Issue by m2jobe** [zoontek/react-native-permissions#730]
### Bug summary

We are seeing a bug where when we request **request(Permissions.PERMISSIONS.IOS.LOCATION_ALWAYS)** and we see the popup below. Upon selecting **Allow while using app (LOCATION_WHEN_IN_USE)**, if we then check both the permissions LOCATION_ALWAYS and LOCATION_WHEN_IN_USE, they return as **granted**. The expected behaviour from this flow would be that LOCATION_ALWAYS is **denied** and only **LOCATION_WHEN_IN_USE** is marked as **granted**
<img width="275" alt="Screen Shot 2022-10-25 at 5 02 19 PM" src="https://user-images.githubusercontent.com/9561974/197881301-5f079506-77f7-4b49-9c0b-f456938a3fef.png">

In suspecting that this may be related to: https://github.com/zoontek/react-native-permissions/issues/490

I am investigating going through the "A normal permission escalation" as outlined here. 

<img width="931" alt="Screen Shot 2022-10-25 at 5 05 20 PM" src="https://user-images.githubusercontent.com/9561974/197881848-78e66642-55ea-4cd1-ad00-acfa11db34ff.png">

### Library version

3.3.1

### Environment info

```shell
System:
    OS: macOS 12.3
    CPU: (10) arm64 Apple M1 Pro
    Memory: 108.70 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.7.0 - ~/.nvm/versions/node/v18.7.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.7.0/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v18.7.0/bin/npm
    Watchman: 2022.07.04.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/muhammedjobe/.rvm/rubies/ruby-3.0.0/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8815526
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 15.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.1 => 0.68.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```
```


### Steps to reproduce

1. Request ios location always permissions
2. checkMultiple permissions for ios location always and location when in use (both should appear as granted)


### Reproducible sample code

```js
request(Permissions.PERMISSIONS.IOS.LOCATION_ALWAYS).then(
    permissionResult => {
      if (permissionResult !== Permissions.RESULTS.GRANTED) {
        console.log("failed on both back and fore");
      } else {
        checkMultiple([
          PERMISSIONS.IOS.LOCATION_ALWAYS,
          PERMISSIONS.IOS.LOCATION_WHEN_IN_USE,
        ]).then(statuses => {
          console.log(
            "LOCATION_ALWAYS",
            statuses[PERMISSIONS.IOS.LOCATION_ALWAYS],
          );
          console.log(
            "LOCATION_WHEN_IN_USE",
            statuses[PERMISSIONS.IOS.LOCATION_WHEN_IN_USE],
          );
        });
      }
    },
  );
```
```

**Comment by zoontek** [comment]
@m2jobe That's an expectation, but that's not how iOS location permission works 😄

Check "Request Always Authorization Directly" in here: https://developer.apple.com/documentation/corelocation/cllocationmanager/1620551-requestalwaysauthorization

**Comment by zoontek** [comment]
This is normal, just how the iOS location permission works. See https://developer.apple.com/documentation/corelocation/cllocationmanager/1620551-requestalwaysauthorization (search for "Request Always Authorization Directly" in the page)

> If your app’s current state is [CLAuthorizationStatus.notDetermined](https://developer.apple.com/documentation/corelocation/clauthorizationstatus/notdetermined) and you call requestAlwaysAuthorization(), Core Location uses two prompts before it fully enables Always authorization.
The first prompt displays immediately with the string from NSLocationWhenInUseUsageDescription. The user prompt displays the following options, which determine the authorization your app receives:
>
> Allow While Using App | Core Location grants your app a Provisional Always authorization. The delegate receives CLAuthorizationStatus.authorizedAlways.

And later, it will prompt a second time saying this app uses background location and the user will be able to change his mind.

**Comment by zoontek** [comment]
More infos here: https://github.com/zoontek/react-native-permissions/issues/521#issuecomment-699522129, here: https://github.com/zoontek/react-native-permissions/issues/379#issuecomment-559840130 or in the README: https://github.com/zoontek/react-native-permissions/blob/master/README.md#about-ios-location_always-permission

**Comment by m2jobe** [comment]
Thank you @zoontek
