### ISSUE TITLE
"Ask next time" option or "Only this time" option for Android does not behave properly

### ISSUE THREAD

**Issue by airomo45** [zoontek/react-native-permissions#733]
### Bug summary

"Ask next time" setting or "Only this time" for Android Permissions returns "granted" which means it automatically sets it to allow instead of requesting for permission every time. 

### Library version

3.6.1

### Environment info

```shell
System:
    OS: macOS 13.0
    CPU: (10) arm64 Apple M1 Pro
    Memory: 67.28 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 19.0.1 - ~/homebrew/bin/node
    Yarn: 1.22.19 - ~/homebrew/bin/yarn
    npm: 8.19.2 - ~/homebrew/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /Users/romois/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: 0.69.1 => 0.69.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

1. …
2. …

### Reproducible sample code

```js
**
```

**Comment by zoontek** [comment]
This is the correct behaviour.
Next time when checking it, it will be denied, you will have to request it again.

**Comment by airomo45** [comment]
@zoontek when I close the app and go back I don't get re prompted for the permission request and it is already is set as "granted"

> This is the correct behaviour. Next time when checking it, it will be denied, you will have to request it again.

**Comment by zoontek** [comment]
@airomo45 Fill this:

### Steps to reproduce

1. …
2. …


### Reproducible sample code

```js
**
```

**Comment by scerdal** [comment]
> @zoontek when I close the app and go back I don't get re prompted for the permission request and it is already is set as "granted"
> 
> > This is the correct behaviour. Next time when checking it, it will be denied, you will have to request it again.

I had the same issue. I guess that when you close the app and reopen it shortly after, the app might still remember the previous settings. So I tried force stopping the app and that way it actually asks for the permission as expected
