### ISSUE TITLE
Requesting for a permission never resolves

### ISSUE THREAD

**Issue by Yandamuri** [zoontek/react-native-permissions#735]
### Bug summary

Requesting for a permission never resolves. Let's say I am requesting for **Camera** like following,

```
import { check, PERMISSIONS, request, requestMultiple } from 'react-native-permissions';
 let permissionStatus = await request(PERMISSIONS.ANDROID.CAMERA);
 console.log('permissionStatus requesting result', permissionStatus);
```
The above request never resolves. But If i refresh the app and check in device settings, App's `Camera` access is granted. Same thing is happening with all the permissions like RECORD_AUDIO, WRITE_EXTERNAL_STORAGE, ACCESS_FINE_LOCATION.

### Library version

 "react-native-permissions": "^3.6.1",

### Environment info

```shell
System:
    OS: macOS 12.5
    CPU: (8) x64 Apple M1
    Memory: 23.42 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.0.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.4 => 0.64.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

```
```


### Steps to reproduce

I am not sure if it can be reproduced in all devices, But to reproduce it you can simply run the code I mentioned in `Bug Summary` section. Then you can notice that request never resolves.

In addition to that I would like to provide few details like,

**sdk version:**

```
minSdkVersion               = 21
compileSdkVersion           = 31
targetSdkVersion            = 31
buildToolsVersion           = "31"
```

**gradle dependency:**

```
classpath 'com.android.tools.build:gradle:4.2.1'
```

**gradle Plugin:**
```
distributionUrl=https\://services.gradle.org/distributions/gradle-6.9-all.zip
```

**AndroidManifest.xml:**

```
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" /> 
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.RECORD_AUDIO" />
```


### Reproducible sample code

```js
Code mentioned in the `Bug Summary` section can be used for reproducing the bug.


I tried to debug the issue. So I looked into `methods.android.js`(`/node_modules/react-native-permissions/dist/commonjs/methods.android.js`). Here `NativeModules.RNPermissions.requestPermission()` is being called eventually. I couldn't trace where `NativeModules` exists. This is where I got stuck.

If you think the bug is in my project only, Can you please let me know how can I proceed for further to debug the issue?


Thank You.
```

**Comment by zoontek** [comment]
@Yandamuri Don't use top level await, it's not supported in React Native

**Comment by Yandamuri** [comment]
> @Yandamuri Don't use top level await, it's not supported in React Native

I am not sure what do you mean by **top level await**, But I changed my code like this,

old code:
```
let permissionStatus = await request(PERMISSIONS.ANDROID.CAMERA);
```

New code: 

```
request(PERMISSIONS.ANDROID.CAMERA).then((result) => {
        console.log("permission result", result);
}).catch(e => console.log('permission catch error', e));
```

But still request never resolves.

BTW,  I am  `reac-native-permissions` in my some other project, But there is no issue.(In that project I am using `await` as well).

**Comment by zoontek** [comment]
@Yandamuri Please ask on StackOverflow for this kind of help.
This is not reproducible, most likely an error in your codebase. I can't afford to help everyone just because they use this library 😕

**Comment by IlyaKovtonyck** [comment]
@Yandamuri Hey,did you solve it?I have the same.

**Comment by Yandamuri** [comment]
@IlyaKovtonyck Have you eve tried permission handling through native android ever(By using bridging)?

**Comment by qusaieilouti99** [comment]
@zoontek I can reproduce the issue
It is when you call request() multiple times at the same time 
my case:

I have a function that calls 3 requests individually but waits for each one to finish before requesting the next. the 3 requests are resolved.
when calling another function that requests another permission at the same time that the first function running, one of them never resolves.

I can workaround this by calling requestMultiple or permissions but each request in my case is related to initializing a service in my app so doesn't make sense to combine them.
