### ISSUE TITLE
ANDROID 13 SDK 33 on first launch I don't get a popup for notification permission

### ISSUE THREAD

**Issue by tchahin5** [zoontek/react-native-permissions#742]
### Bug summary

I built an app in react native, after the user logs in I check the notification permissions, and as a result I get 'denied'. I try to request permission for notifications but no popup appears, instead it returns the blocked status, on a simulator and on a real device on first launch, and this only happens on Android, on iOS everything works fine!

### Library version

3.6.1

### Environment info

```shell
System:
    OS: macOS 12.6.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 326.78 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.2.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.3 - /usr/local/bin/npm
    Watchman: 2022.11.28.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: 0.70.6 => 0.70.6
```

### Steps to reproduce

1. Check for notification permission status -> returns 'denied'
2. Request notification permission -> returns 'blocked' on first launch

### Reproducible sample code

```js
export const checkNotificationPermissions = (setNotificationPermission: (val: boolean) => void) => {
  checkNotifications().then(({ status, settings }) => {
    console.log("not", status);
    if (status === "granted") setNotificationPermission(true);
    else requestNotificationPermissions(setNotificationPermission);
  });
};

const requestNotificationPermissions = (setNotificationPermission: (val: boolean) => void) => {
    requestNotifications([]).then(({ status, settings }) => {
      console.log("not2", status); //returns blocked
      if (status === "granted") setNotificationPermission(true);
      else setNotificationPermission(false);
    });
};
```

**Comment by zoontek** [comment]
Please make sure that [you are correctly targeting API 33](https://github.com/zoontek/react-native-permissions/releases/tag/3.5.0).
Also, provide a reproduction repository.

**Comment by chenop** [comment]
@tchahin5 have you figure this out?
I cant see the notifications popup

**Comment by zoontek** [comment]
I just gave it a try (Pixel 4a, API 33). Doing exactly what you did:

> 1. Check for notification permission status -> returns 'denied'
> 2. Request notification permission -> returns 'blocked' on first launch

And it worked perfectly. Be sure to try the example app on the repository to check if it's really an issue, or maybe something wrong with your setup.

**Comment by chenop** [comment]
Please check you've upgraded to API 33.
Here is how you do it:

in android/app/build.gradle:
```
android {
    buildToolsVersion rootProject.ext.buildToolsVersion
    compileSdkVersion rootProject.ext.compileSdkVersion

    defaultConfig {
        targetSdkVersion = rootProject.ext.targetSdkVersion
        ...
   }
   ...
}
```

in android/build.gradle:
```
buildscript {
    ext {
        buildToolsVersion = "33.0.0"
        compileSdkVersion = 33
        targetSdkVersion = 33
        ...
    }
    ...
}
```

**Comment by zoontek** [comment]
@chenop https://github.com/zoontek/react-native-permissions/blob/master/example/android/build.gradle#L5
