### ISSUE TITLE
openLimitedPhotoLibraryPicker result promise should get resolved when the picker is closed only

### ISSUE THREAD

**Issue by mtnt** [zoontek/react-native-permissions#743]
### Why it is needed?

There is no way to determine when allowed photos list has changed.

### Code sample

```js
await openLimitedPhotoLibraryPicker();

Cameraroll.getPhotos(...)
```

**Comment by zoontek** [comment]
Duplicate of https://github.com/zoontek/react-native-permissions/issues/689
