### ISSUE TITLE
No Permission Handler Detected

### ISSUE THREAD

**Issue by AntonioLi1** [zoontek/react-native-permissions#744]
### Bug summary

I installed react native permissions with yarn, then followed all the steps in the documents (adding permissions in Podfile and info.plist) and pod install. I received the current error, then followed the provided steps by uninstalling the app, deleting DerivedData and rebuild. I also used the workaround for use_frameworks. But I am still receiving the same error. I have also tried yarn remove and yarn add again, but with no success

### Library version

3.6.1

### Environment info

```shell
System:
    OS: macOS 12.5.1
    CPU: (8) arm64 Apple M2
    Memory: 92.05 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.3.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.2.0 - /opt/homebrew/bin/npm
    Watchman: 2022.12.26.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/antonioli/.rvm/gems/ruby-2.7.5/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.70.6 => 0.70.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

1. Install RN permissions and follow document steps with pod install
2. Rebuild app
3. received error

### Reproducible sample code

```js
This is my podfile:
use_frameworks!

# Convert all permission pods into static libraries
pre_install do |installer|
  Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}

  installer.pod_targets.each do |pod|
    if pod.name.eql?('RNPermissions') || pod.name.start_with?('Permission-')
      def pod.build_type;
        # Uncomment the line corresponding to your CocoaPods version
        Pod::BuildType.static_library # >= 1.9
        # Pod::Target::BuildType.static_library # < 1.9
      end
    end
  end
end
...
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
  pod 'Permission-LocationAccuracy', :path => "#{permissions_path}/LocationAccuracy"
  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways"

And this is my info.plist
...
	<key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
	<string>Location Permission</string>
	<key>NSLocationAlwaysUsageDescription</key>
	<string>Location Permission</string>
	<key>NSLocationUsageDescription</key>
	<string>GPS data is required to...</string>
	<key>NSLocationWhenInUseUsageDescription</key>
	<string>Location Permission</string>

	<key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
  	<string>YOUR TEXT</string>
...
```

**Comment by AntonioLi1** [comment]
Why did this issue get closed as completed? I am yet to find a fix for this issue...

**Comment by zoontek** [comment]
Because it's a duplicate: https://github.com/zoontek/react-native-permissions/issues?q=is%3Aissue+No+Permission+Handler

**Comment by AntonioLi1** [comment]
> Because it's a duplicate: https://github.com/zoontek/react-native-permissions/issues?q=is%3Aissue+No+Permission+Handler

I have read through all the other issues and tried different fixes but none have been successful

**Comment by dunapanta** [comment]
Same issue here

**Comment by dunapanta** [comment]
For me the solution was downgrade react-native-permissions to this version 
`"react-native-permissions": "3.0.5"`

**Comment by Jlplarkus** [comment]
Still getting the same error after following all the possible solutions. I'm using react native 0.71.6 and react native permissions 3.8.0

**Comment by Jlplarkus** [comment]
Running the `npx react-native setup-ios-permissions ` and `pod install ` worked for me. If not try deleting the **[DeliveredData](https://stackoverflow.com/questions/13761934/xcode-derived-data-location)** folder from your Xcode Project and then rebuild the app. That was the solution for me.

**Comment by MobileMon** [comment]
deleting derived data worked for me

**Comment by KHadham** [comment]
> Running the `npx react-native setup-ios-permissions ` and `pod install ` worked for me. If not try deleting the **[DeliveredData](https://stackoverflow.com/questions/13761934/xcode-derived-data-location)** folder from your Xcode Project and then rebuild the app. That was the solution for me.

this is work for me

**Comment by cx5686557** [comment]
> npx react-native setup-ios-permissions

error: unknown command 'setup-ios-permissions'

**Comment by zoontek** [comment]
@cx5686557 You have to install the package first.

**Comment by migsandia-1984** [comment]
Try install the package with **Yarn**, but first uninstall the npm package. I don't know why, but to for me this solution works.

**Comment by opeyemijj** [comment]
this works like charm:

# At the top of your Podfile
def node_require(script)
  # Resolve script with node to allow for hoisting
  require Pod::Executable.execute_command('node', ['-p',
    "require.resolve(
      '#{script}',
      {paths: [process.argv[1]]},
    )", __dir__]).strip
end

# Use it to require both react-native's and this package's scripts:
node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')

# Inside your target block
target 'YourApp' do
  # Other configurations...

  # Specify the permissions you need
  setup_permissions([
    'LocationWhenInUse', # Add other permissions as needed
  ])

  # Other configurations...
end
