### ISSUE TITLE
How to tell if the user has been given the one-time prompt with requestNotifications()?

### ISSUE THREAD

**Issue by oscadev** [zoontek/react-native-permissions#745]
### Why it is needed?

If a status check shows "blocked", we know they have been given the prompt before, and that they chose no. However, I cant seem to find a way to know if they have been given the prompt if they clicked yes on it since it is indistinguishable from them never having been given the prompt and them choosing to turn on notifications manually.

It would be useful to be able to know if we can still prompt the user to allow notifications, or if the prompt has already been used up.

### Possible implementation

a status check can have a boolean for whether we can or cannot prompt them.

**Comment by zoontek** [comment]
You can't. That's a flaw in the Android permissions system. That's also why [react native `PermissionsAndroid.check()`](https://reactnative.dev/docs/permissionsandroid) returns a boolean and not a `PermissionStatus` like `request()`.

A proper flow can be found here: https://github.com/zoontek/react-native-permissions/issues/714#issuecomment-1238382187
