### ISSUE TITLE
 Error: While trying to resolve module `react-native-permissions`

### ISSUE THREAD

**Issue by xxxifan** [zoontek/react-native-permissions#749]
### Bug summary

Getting this error while running:

```
Error: While trying to resolve module `react-native-permissions` from file `src\clients\Controller.js`, the package `node_modules\react-native-permissions\package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`node_modules\react-native-permissions\dist\commonjs\index.js`. Indeed, none of these files exist:
```

we run with `yarn`, don't know why it's not generate `dist` folder, please help, thanks.

### Library version

3.6.1

### Environment info

```shell
System:
    OS: Windows 10 10.0.22623
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i5-12600KF
    Memory: 14.41 GB / 31.82 GB
  Binaries:
    Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.15 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.16.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Visual Studio: Not Found
  Languages:
    Java: 11.0.15.1
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.66.0 => 0.66.0
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

yarn android:start-dev

### Reproducible sample code

```js
no
```

**Comment by zoontek** [comment]
Please provide more context. `node_modules\react-native-permissions\dist\commonjs\index.js` is a basic, commonJS file that should be loaded.
It's probably an issue with your bundler config.

**Comment by jeffinhk** [comment]
Hey I had same issue but it worked out after I restarted my whole computer. Not sure what is the minimum action for this reboot, but simple rebuilding did not work on android. I don't think it's a peer dependency issue. Hope this helps!

**Comment by zoontek** [comment]
@xxxifan Do you confirm that @jeffinhk solution solves your issue?

**Comment by xxxifan** [comment]
no I restarted multiple times and still exists.
is there any manual build command to generate the `dist` folder?

**Comment by zoontek** [comment]
@xxxifan The dist directory? How do you install the lib? 😅

**Comment by xxxifan** [comment]
by `yarn` command, configured in package.json, it pulled from github directly

**Comment by zoontek** [comment]
@xxxifan `yarn add react-native-permissions` so? Than the `dist` directory exists in it.

**Comment by mikehardy** [comment]
Posting the actual dependency from your package.json would be the right way to ask this question (https://stackoverflow.com/help/how-to-ask)

It's possible if you are using a git reference vs a real package then you need to run the build locally as a postinstall (cd node_modules/etc/etc && yarn some-build-command) but we can't guess that without full info.

**Comment by xxxifan** [comment]
@zoontek it's working, thanks for your reply, I was thought the project script should works fine, it wasn't me who write the code though.
@mikehardy I have node_modules/react-native-permissions in my local files, it need "yarn add" to fix the thing.
