### ISSUE TITLE
Add multi-target iOS configuration

### ISSUE THREAD

**Issue by chist3r** [zoontek/react-native-permissions#753]
### Bug summary

Hello,
Recently working on a multi-target app that would need to include some permissions in all targets and a different permission in single target

As you can see in the below Podfile, I have included 3 permissions in both targets and camera permission only in MyTarget2

When building MyTarget2 it works fine. But when build MyTarget1 it fails with error `Undefined symbol: _OBJC_CLASS_$_RNPermissionHandlerCamera`

I believe this happens because cocoapods will collect libraries from all targets and them to header search paths for all targets. And while [library implementation](https://github.com/zoontek/react-native-permissions/blob/master/ios/RNPermissions.m#L10-L12) uses `__has_include` it will always resolve true in all targets because library header in the search path but the library itself is not included.

```
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, min_ios_version_supported
prepare_react_native_project!

def permissions_pod(name)
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod "Permission-#{name}", :path => "#{permissions_path}/#{name}"
end

def common_pods
  flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled
  
  linkage = ENV['USE_FRAMEWORKS']
  if linkage != nil
    Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
    use_frameworks! :linkage => linkage.to_sym
  end

  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    :flipper_configuration => flipper_config,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  permissions_pod 'Notifications'
  permissions_pod 'LocationAlways'
  permissions_pod 'LocationWhenInUse'
end

target 'MyTarget1' do
  common_pods
end

target 'MyTarget2' do
  common_pods
  permissions_pod 'Camera'
end

post_install do |installer|
  react_native_post_install(
    installer,
    # Set `mac_catalyst_enabled` to `true` in order to apply patches
    # necessary for Mac Catalyst builds
    :mac_catalyst_enabled => false
  )
  __apply_Xcode_12_5_M1_post_install_workaround(installer)
end

```

### Library version

3.7.2

### Environment info

```shell
System:
    OS: macOS 13.2.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 99.43 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
    Yarn: Not Found
    npm: 6.14.11 - ~/.nvm/versions/node/v14.16.0/bin/npm
    Watchman: 2022.08.29.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/atef/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 28, 29, 30, 31, 33
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0, 31.0.0
      System Images: android-27 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7351085
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/local/opt/openjdk@11/bin/javac
  npmPackages:
    @react-native-community/cli: 9.3.2 => 9.3.2
    react: 18.2.0 => 18.2.0
    react-native: 0.70.6 => 0.70.6
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

1. Create a 2 targets app
2. Include any permission in both targets
3. Include different permission in a single target

### Reproducible sample code

```js
https://github.com/chist3r/RNPermissionsMultiTarget
```

**Comment by zoontek** [comment]
@chist3r First, please switch to the new linking system: https://github.com/zoontek/react-native-permissions/releases/tag/3.7.0

Then, for now I suggest to activate all used permissions (`Notifications`, `LocationAlways`, `LocationWhenInUse` and `Camera`) and warn the app store reviewer that you use a library (I recommend tweaking the purpose messages depending on the target)

You can also duplicate the whole `ios` directory. Which I highly recommend because you will have the exact same issues with other libraries (with react-native autolink)

**Comment by chist3r** [comment]
Thanks @zoontek 
Just noticed the new implementation.. Looks cool..

Noticed you're using `cosmiconfig` to load the config key.
I think I can have permissions in `.reactNativePermissionsIOSrc` (git ignored) instead of `package.json` and automatically modify this file before calling the `setup-ios-permissions` command leaving `package.json` intact.

**Comment by zoontek** [comment]
Actually I removed it in `3.7.2` because it has [an import problem](https://github.com/zoontek/react-native-permissions/pull/752#issuecomment-1445528704).

But I could ship a new version that read `reactNativePermissionsIOS.json` at root if `reactNativePermissionsIOS` is not present in `package.json` if that works for you.

**Comment by chist3r** [comment]
That would be great, thanks @zoontek

**Comment by zoontek** [comment]
@chist3r It's available: https://github.com/zoontek/react-native-permissions/releases/tag/3.7.3
I'm closing this, since it does the trick 🙂

**Comment by hoodedice** [comment]
Hi, minor comment:
in this source file: `react-native.config.js`, we have:
```js
        let config = JSON.parse(pkg)[CONFIG_KEY];

        if (!config && existsSync(jsonPath)) {
          const text = await fs.readFile(jsonPath, 'utf-8');
          config = JSON.parse(text);
        }
```

This leads to the package.json syntax being the same as in the Readme:
```json
{
  "reactNativePermissionsIOS": [
  ]
}
```
but in the `reactNativePermissionsIOS.json` file it should just be an array. This is not very clear in the present Readme, and I got an error: `Invalid "reactNativePermissionsIOS" config detected. It must be a non-empty array.` when I used the json format as in the Readme
