### ISSUE TITLE
react-native-permissions: NativeModule.RNPermissions is null. 

### ISSUE THREAD

**Issue by sejeeth11** [zoontek/react-native-permissions#759]
### Bug summary

Error: react-native-permissions: NativeModule.RNPermissions is null. To fix this issue try these steps:
• If you are using CocoaPods on iOS, run `pod install` in the `ios` directory and then rebuild and re-run the app. You may also need to re-open Xcode to get the new pods.
* If you are getting this error while unit testing you need to mock the native module. Follow the guide in the README.
If none of these fix the issue, please open an issue on the Github repository

### Library version

3.8.0

### Environment info

```shell
"react": "18.2.0",
   "react-native": "0.71.4",

Also set up below one too 

jest.mock('react-native-permissions', () => require('react-native-permissions/mock'));

But still showing NativeModule.RNPermissions is null. in IOS when i run from xcode
```

### Steps to reproduce

1. …
2. …

### Reproducible sample code

```js
"reactNativePermissionsIOS": [
    "Camera",
    "Contacts",
    "LocationWhenInUse",
    "BluetoothPeripheral"
  ],
  "dependencies": {
    "react": "18.2.0",
    "react-native": "0.71.4",
    "react-native-paper": "^5.4.1",
    "react-native-permissions": "^3.8.0"
  },
```

**Comment by bakhiem** [comment]
Yes, It happens to me when I use version 3.8.0 too

**Comment by zoontek** [comment]
@sejeeth11 @bakhiem I just gave it another try with a fresh project, everything is working.

Please be sure that:
- You ran `npx react-native setup-ios-permissions`
- You ran `pod install`
- You cleaned your Xcode cache

EDIT: What operating system are you using? You don't mention it.

**Comment by stanjhae** [comment]
I experienced this issue when working with `react-native-qrcode-scanner`.

`react-native-permissions` is a dependency but uses the old version `2.0.2`

I had to follow the steps in setting up `react-native-permissions` and then delete `node_modules/react-native-qrcode-scanner/node_modules/react-native-permissions` afterwards.

Anyone experiencing this should check if they're using a library which has `react-native-permissions` as a dependency. It's probably using an old version. 

You'll need to delete the `react-native-permissions` dependency in the specific library's `node_modules`

https://github.com/moaazsidat/react-native-qrcode-scanner/issues/403#issuecomment-1476900938

@zoontek, please update the readME to inform other developers as this wasn't easy to figure out else they'll think it's an issue with `react-native-permissions`

**Comment by bhargav-trt** [comment]
I have face error in 3.8.0 version

**Comment by stanjhae** [comment]
> I have face error in 3.8.0 version

Are you using any other library that depends on `react-native-permissions`?

**Comment by bhargav-trt** [comment]
issue resolve using below solution thanks 
> I experienced this issue when working with `react-native-qrcode-scanner`.
> 
> `react-native-permissions` is a dependency but uses the old version `2.0.2`
> 
> I had to follow the steps in setting up `react-native-permissions` and then delete `node_modules/react-native-qrcode-scanner/node_modules/react-native-permissions` afterwards.
> 
> Anyone experiencing this should check if they're using a library which has `react-native-permissions` as a dependency. It's probably using an old version.
> 
> You'll need to delete the `react-native-permissions` dependency in the specific library's `node_modules`
> 
> [moaazsidat/react-native-qrcode-scanner#403 (comment)](https://github.com/moaazsidat/react-native-qrcode-scanner/issues/403#issuecomment-1476900938)
> 
> @zoontek, please update the readME to inform other developers as this wasn't easy to figure out so they'll think it's an issue with `react-native-permissions`

**Comment by zoontek** [comment]
@bhargav-trt The fix should be on `react-native-qrcode-scanner` side. React native dependencies are not supposed to be installed as libraries dependencies:

```json
"peerDependencies": {
  "react-native-permissions": ">=3.8.0"
},
"peerDependenciesMeta": {
  "react-native-permissions": {
    "optional": true
  }
}
```

**Comment by joshuayoes** [comment]
For those working with this library in a monorepo, a better strategy is to use

```js
// jest.config.js
module.exports = {
  // ... other config
  moduleNameMapper: {
    'react-native-permissions': '<rootDir>/node_modules/react-native-permissions/mock',
  },
};
```

This will ensure that you use the mock even if `react-native-permissions` is installed in other workspace node_modules

**Comment by saim11-cloud** [comment]
> I experienced this issue when working with `react-native-qrcode-scanner`.
> 
> `react-native-permissions` is a dependency but uses the old version `2.0.2`
> 
> I had to follow the steps in setting up `react-native-permissions` and then delete `node_modules/react-native-qrcode-scanner/node_modules/react-native-permissions` afterwards.
> 
> Anyone experiencing this should check if they're using a library which has `react-native-permissions` as a dependency. It's probably using an old version.
> 
> You'll need to delete the `react-native-permissions` dependency in the specific library's `node_modules`
> 
> [moaazsidat/react-native-qrcode-scanner#403 (comment)](https://github.com/moaazsidat/react-native-qrcode-scanner/issues/403#issuecomment-1476900938)
> 
> @zoontek, please update the readME to inform other developers as this wasn't easy to figure out else they'll think it's an issue with `react-native-permissions`

it worked thanks😊

**Comment by elgambet** [comment]
In my case I don't have other dependencies that use "react-native-permissions" still it keeps happening, [this comment ](https://github.com/zoontek/react-native-permissions/issues/757#issuecomment-1471393920) worked for me.

**Comment by srkanyalcinkaya** [comment]
> I experienced this issue when working with `react-native-qrcode-scanner`.
> 
> `react-native-permissions` is a dependency but uses the old version `2.0.2`
> 
> I had to follow the steps in setting up `react-native-permissions` and then delete `node_modules/react-native-qrcode-scanner/node_modules/react-native-permissions` afterwards.
> 
> Anyone experiencing this should check if they're using a library which has `react-native-permissions` as a dependency. It's probably using an old version.
> 
> You'll need to delete the `react-native-permissions` dependency in the specific library's `node_modules`
> 
> [moaazsidat/react-native-qrcode-scanner#403 (comment)](https://github.com/moaazsidat/react-native-qrcode-scanner/issues/403#issuecomment-1476900938)
> 
> @zoontek, please update the readME to inform other developers as this wasn't easy to figure out else they'll think it's an issue with `react-native-permissions`

it worked thanks :)

**Comment by empiteranga** [comment]
```
  "resolutions": {
    "react-native-permissions": "^4.0.1"
  },
  "overrides": {
    "react-native-qrcode-scanner": {
      "react-native-permissions": "^4.0.1"
    }
  },
```

The above code works for me with react-native-qrcode-scanner , Finally found the solution need to add resolutions if using yarn 
Thanks All

**Comment by ramzanbilal** [comment]
This is not working for latest version of react native 0.80.0. you just need to add at least 1 permission in setup permission function in `iOS -> podfile `

```
setup_permissions([ 'Camera', 
# or any permission you might need 
])
```
