### ISSUE TITLE
Latest commits in Master breaks  <= RN 0.39

### ISSUE THREAD

**Issue by larryranches** [zoontek/react-native-permissions#76]
The latest commits in master breaks in versions of React Native <= 0.39. Could this package versions be identified in specific Release versions so that we can safely assign the version numbers in our package.json and avoid breaks?

**Comment by yonahforst** [comment]
Hi @larryranches  - yes, that's a really good point. I'm going to implement the version support table from #41. What is failing for you in 0.39. ?

**Comment by larryranches** [comment]
@yonahforst It's just the "Header" update needed for >= RN 0.40.0 that breaks on <= 0.39

**Comment by yonahforst** [comment]
Oh, of course. Thanks for pointing it out

**Comment by yonahforst** [comment]
added version table in 32260fa
