### ISSUE TITLE
Duplicate interface definition for class 'RNPermissionHandlerNotifications'

### ISSUE THREAD

**Issue by kg-currenxie** [zoontek/react-native-permissions#760]
### Bug summary

Can't build iOS app when adding `"Notifications"` to `"reactNativePermissionsIOS": []`

![SCR-20230321-jeh](https://user-images.githubusercontent.com/48229166/226530769-adc36b4c-ba3e-4aaf-8896-e166dbd5928d.png)

### Library version

3.7.2

### Environment info

```shell
System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 87.70 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.19.1 - /var/folders/wl/rld35ngd74l38l3ljkg53hbm0000gn/T/yarn--1679378936767-0.4891053475748359/node
    Yarn: 1.22.17 - /var/folders/wl/rld35ngd74l38l3ljkg53hbm0000gn/T/yarn--1679378936767-0.4891053475748359/yarn
    npm: 6.14.16 - ~/.nvm/versions/node/v14.19.1/bin/npm
    Watchman: 2023.01.23.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/frexuz/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 28, 30, 31, 33
      Build Tools: 30.0.2, 30.0.3, 31.0.0
      System Images: android-29 | Google Play ARM 64 v8a, android-31 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7784292
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.10 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0
    react-native: 0.70.4 => 0.70.4
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

1. Install yarn package
2. Add
```
  "reactNativePermissionsIOS": [
    "AppTrackingTransparency",
    "FaceID",
    "Notifications"
  ],
```
3. pod install (added `use_frameworks!`!)
4. build app in xcode

### Reproducible sample code

I don't think this is related:
Maybe it collides with `@react-native-firebase/messaging`'s or `@notifee/react-native`'s permission handling.

(I have tried deleting DerivedData, build cache, uninstalling the app)

**Comment by zoontek** [comment]
@kg-currenxie Did you remove all permissions handlers from your Podfile? Maybe publish it too, it will help.

EDIT: I just saw on your screenshot that the error come from the `Permission-Notifications` pod, so I think you're using both methods at the same time. Follow this to fix your issue: https://github.com/zoontek/react-native-permissions/releases/tag/3.7.0

**Comment by kg-currenxie** [comment]
Thanks. You are correct, i still had the `Permission-Notifications` pod. I got confused about the steps/changes :) 
All good now <3
