### ISSUE TITLE
`check()` and `request()` return different results

### ISSUE THREAD

**Issue by jkaufman** [zoontek/react-native-permissions#764]
### Bug summary

In this scenario, `check()` and `request()` yield different results. Calling `check()` always returns `DENIED`, but every call to `request()` after the first immediately returns `BLOCKED` without presenting a dialog.

The project readme notes that `DENIED` means `"The permission has not been requested / is denied but requestable"`.  I had been relying on `DENIED` to indicate the need for a "Request" button, but this behavior suggests that I cannot use the result of `check()` to indicate requestability. Is this expected behavior and, if so, is there an alternative approach to evaluating requestability that accounts for "Never Ask Again" on Android 10 and below and repeated denials on Android 11 and above?

The reproduction steps below were run on Android 10, but repeated denials on Android 11 yield the same result.

Thank you!

### Library version

3.8.0

### Environment info

```shell
Expo, emulator running Android 10
```

### Steps to reproduce

1. Check permission
  _Value: `DENIED`_
2. Request permission. User selects "Don't ask me again" and taps "Deny".
  _Value: `BLOCKED`_
3. Check permission
  _Value: `DENIED`_
4. Request permission. No dialog displayed.
  _Value: `BLOCKED`_
5. Check permission
  _Value: `DENIED`_

### Reproducible sample code

```js
testAll()

const testAll = async () => {
    await testCheck()
    await testRequest()
    await testCheck()
    await testRequest()
    await testCheck()
}

const testCheck = async ()=> {
    return check(PERMISSIONS.ANDROID.ACCESS_FINE_LOCATION).then((res)=>{
        console.log("check " + res)
    })
}

const testRequest = async () => {
    return request(PERMISSIONS.ANDROID.ACCESS_FINE_LOCATION).then((res)=>{
        console.log("request: " + res)
    })
```

**Comment by jkaufman** [comment]
This is probably expected behavior given how permissions work on Android. My colleague points out that we can change our UX to avoid relying on `check()`. So feel free to either consider or close.

**Comment by zoontek** [comment]
This is expected, it cannot ne known on Android before requested.
That's also why PermissionsAndroid returns a boolean on check, but can return `NEVER_ASK_AGAIN` on request https://reactnative.dev/docs/permissionsandroid#check

More infos: https://developer.android.com/training/permissions/requesting#workflow_for_requesting_permissions

**Comment by cfradella** [comment]
@zoontek 
> it cannot ne known on Android before requested.

Then how can the app ever know if a permission is granted if we specifically don't want to request it to find out?

If you run a `check`, then `request`, then `check`, the `check`s are always incorrect. What is the point of a `check`?

**Comment by zoontek** [comment]
@cfradella You cannot know it the permission is `blocked` before requesting it, but you can know if the permission is `granted` with a `check`. Check the android flow schema in the README.
