### ISSUE TITLE
Update docs post install scripts

### ISSUE THREAD

**Issue by elmcapp** [zoontek/react-native-permissions#766]
### Bug summary

we need to update the post install script. It should be

"react-native setup-ios-permissions && cd ios && pod install && cd .."

I get error when using pod-install 

the directory don't exist

### Library version

latest

### Environment info

```shell
react native
```

### Steps to reproduce

na

### Reproducible sample code

```js
na
```

**Comment by zoontek** [comment]
The README already mention `pod install` (using the `pod-install` package, which can be run from root)
