### ISSUE TITLE
May I know why shared preferences usage was removed. 

### ISSUE THREAD

**Issue by shubhamdeol** [zoontek/react-native-permissions#769]
### Bug summary

in older version check method used to give `blocked` response if permission was blocked but now it says `denied`. 
When I request the permission then it says `blocked`. 

For my use case. 
- I do not want to show popup when user clicks `never ask again` but on second time when user clicks some action button I want to know if permission was `blocked` and show a popup to user saying `he can enable permission from setting`

### Library version

3.8.0

### Environment info

```shell
System:
    OS: macOS 13.3.1
    CPU: (8) arm64 Apple M1
    Memory: 85.27 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - /usr/local/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 9.6.4 - /opt/homebrew/bin/npm
    Watchman: 2023.05.01.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/shubham/.rvm/rubies/ruby-2.7.4/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.2 AI-222.4459.24.2221.9862592
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: 15.0.10 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.7 => 0.71.7
```

### Steps to reproduce

1. call ```const permissionsPrevStatus = await checkMultiple(permissionsToRequest);```

It returns blocked permissions as denied

### Reproducible sample code

```js
const permissionsPrevStatus = await checkMultiple(permissionsToRequest);
```

**Comment by shubhamdeol** [comment]
I am asking about
this https://github.com/zoontek/react-native-permissions/commit/4e08185f16551711f43bdbfb731cf760e5aa0f41 change

**Comment by zoontek** [comment]
The release directly mention the PR: https://github.com/zoontek/react-native-permissions/pull/696
