### ISSUE TITLE
Missing Notification Permissions in iOS Permission List

### ISSUE THREAD

**Issue by maoryadin** [zoontek/react-native-permissions#773]
### Bug summary

In our current application, the notification permissions are absent from the list of iOS permissions. This absence is causing difficulties in managing and implementing notification-related features in our iOS application.

The current list of iOS permissions is as follows:

`const IOS = Object.freeze({
  APP_TRACKING_TRANSPARENCY: 'ios.permission.APP_TRACKING_TRANSPARENCY',
  BLUETOOTH_PERIPHERAL: 'ios.permission.BLUETOOTH_PERIPHERAL',
  CALENDARS: 'ios.permission.CALENDARS',
  CAMERA: 'ios.permission.CAMERA',
  CONTACTS: 'ios.permission.CONTACTS',
  FACE_ID: 'ios.permission.FACE_ID',
  LOCATION_ALWAYS: 'ios.permission.LOCATION_ALWAYS',
  LOCATION_WHEN_IN_USE: 'ios.permission.LOCATION_WHEN_IN_USE',
  MEDIA_LIBRARY: 'ios.permission.MEDIA_LIBRARY',
  MICROPHONE: 'ios.permission.MICROPHONE',
  MOTION: 'ios.permission.MOTION',
  PHOTO_LIBRARY: 'ios.permission.PHOTO_LIBRARY',
  PHOTO_LIBRARY_ADD_ONLY: 'ios.permission.PHOTO_LIBRARY_ADD_ONLY',
  REMINDERS: 'ios.permission.REMINDERS',
  SIRI: 'ios.permission.SIRI',
  SPEECH_RECOGNITION: 'ios.permission.SPEECH_RECOGNITION',
  STOREKIT: 'ios.permission.STOREKIT',
} as const);
`

However, the notification permissions, such as NOTIFICATIONS or PUSH_NOTIFICATIONS, are not included in this list.

Expected behavior:

The notification permissions should be included in the list of iOS permissions to allow for control and management of notification services.

### Library version

3.8.0

### Environment info

```shell
info Fetching system and libraries information...
(node:16942) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
System:
    OS: macOS 13.3.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Memory: 56.01 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 14.17.1 - ~/.nvm/versions/node/v14.17.1/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.1/bin/npm
    Watchman: 2023.04.17.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /Users/maoryadin/.rvm/gems/ruby-3.0.0/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: 16.0.2 - /Library/Java/JavaVirtualMachines/jdk-16.0.2.jdk/Contents/Home/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.70.6 => 0.70.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

Steps to reproduce:

Review the list of available iOS permissions in the app.

Expected behavior:

The notification permissions should be included in the list of iOS permissions to allow for control and management of notification services.

### Reproducible sample code

```js
import { useEffect, useState } from 'react';
import { Platform } from 'react-native';
import { PERMISSIONS, request } from 'react-native-permissions';

// Define the available permissions as an object
export const Permission = {
  APP_TRACKING: 'APP_TRACKING',
  LOCATION: 'LOCATION',
};

// Map the permissions based on the platform (iOS or Android)
const platformPermissionMapping = {
  [Permission.APP_TRACKING]: {
    ios: PERMISSIONS.IOS.APP_TRACKING_TRANSPARENCY,
  },
  [Permission.LOCATION]: {
    android: PERMISSIONS.ANDROID.ACCESS_FINE_LOCATION,
    ios: PERMISSIONS.IOS.LOCATION_WHEN_IN_USE,
  },
  [Permission.NOTIFICATIONS]: {
    android: PERMISSIONS.ANDROID.POST_NOTIFICATIONS,
    //ios: PERMISSIONS.IOS.NOTIFICATIONS, ?
  },
};

// Helper function to get the correct permission for the current platform
const getPermissionForPlatform = (permission) => platformPermissionMapping[permission]?.[Platform.OS];

// Custom hook to handle permissions
export const usePermissions = (permission) => {
  // Create a state to hold the permission status
  const [permissionStatus, setPermissionStatus] = useState('denied');

  // When the permission prop changes, request the specified permission
  useEffect(() => {
    const requestPermission = async () => {
      try {
        const platformPermission = getPermissionForPlatform(permission);

        // If there is no defined permission for the current platform, log a warning and return
        if (!platformPermission) {
          console.warn(`Permission "${permission}" is not supported on ${Platform.OS} platform.`);
          return;
        }

        // Request the permission and update the state with the response
        const statusResponse = await request(platformPermission);
        setPermissionStatus(statusResponse);
      } catch (error) {
        console.error(error);
      }
    };

    // Invoke the requestPermission function
    requestPermission();
  }, [permission]);

  // Return the current permission status
  return { permissionStatus };
};
```

**Comment by zoontek** [comment]
Requesting notifications is done using [requestNotifications](https://github.com/zoontek/react-native-permissions#requestnotifications) as compared to the others permissions, it has settings.

**Comment by jose920405** [comment]
How can I use it in the `checkMultiple` function?
