### ISSUE TITLE
I'm using the request(PERMISSIONS.ANDROID.POST_NOTIFICATIONS) but it show unavailable 

### ISSUE THREAD

**Issue by NikhilMasurkar** [zoontek/react-native-permissions#775]
### Bug summary

I'm using the request(PERMISSIONS.ANDROID.POST_NOTIFICATIONS) but when i was console it result then it show me as unavailable why?

### Library version

3.8.0

### Environment info

```shell
react native version :0.71.7
```

### Steps to reproduce

1. …
2. …
added   <uses-permission android:name="android.permission.POST_NOTIFICATIONS" /> in AndroidManifest.xml file 
and after i using this 

```
 useEffect(() => {
    request(PERMISSIONS.ANDROID.POST_NOTIFICATIONS).then((result) => {
      console.log(result);
    });
  }, []);
```
  
  it show me the result is unavailable

### Reproducible sample code

```js
1. …
2. …
added   <uses-permission android:name="android.permission.POST_NOTIFICATIONS" /> in AndroidManifest.xml file 
and after i using this 


 useEffect(() => {
    request(PERMISSIONS.ANDROID.POST_NOTIFICATIONS).then((result) => {
      console.log(result);
    });
  }, []);
```
  
  it show me the result is unavailable
```

**Comment by twocs** [comment]
In my opinion, correct me if I'm wrong, but after looking at this issue:
POST_NOTIFICATIONS was added in Android 33. So for all earlier SDKs, the result of the call will be "UNAVAILABLE", which means that you cannot request this permission. This means an emulator running an earlier version will say "UNAVAILABLE". Nonetheless, you can receive notifications on the older device.
