### ISSUE TITLE
Disabling alert asking for "always" permission 

### ISSUE THREAD

**Issue by siemya** [zoontek/react-native-permissions#777]
### Why it is needed?

My app needs background location, but in some conditions and screens, it doesn't. 

In one of that cases, when I request location with LOCATION_WHEN_IN_USE, I see this location modal ;

<img width="243" alt="Screenshot 2023-05-29 at 17 52 35" src="https://github.com/zoontek/react-native-permissions/assets/1944945/2d9be5e7-0a58-473e-a154-91eccf13d7a5">

When I press "Allow While Using The App" now I get;

<img width="241" alt="Screenshot 2023-05-29 at 17 55 41" src="https://github.com/zoontek/react-native-permissions/assets/1944945/5b3a50b7-5fea-4fba-9321-4b39e3ae8786">
<br/>

Which actually I don't need it in this case at all since It is unnecessary for the user to give background location on this screen. But I know that it appears because the background location is enabled on my app.

I am not sure if it is possible but mainly I want to be able to disable the second modal programmatically if that is possible.

**Comment by zoontek** [comment]
Sorry that's not possible, that's how iOS is handling location permissions requests: https://developer.apple.com/documentation/corelocation/requesting_authorization_to_use_location_services
