### ISSUE TITLE
Unhandled JS Exception: Error: react-native-permissions: NativeModule.RNPermissions is null.

### ISSUE THREAD

**Issue by radekzz** [zoontek/react-native-permissions#779]
### Bug summary

It's been solved here [multiple times](https://github.com/zoontek/react-native-permissions/issues?q=is%3Aissue+RNPermissions+is+null), but solutions are not actually fixes, just workarounds.

I followed installation readme using `reactNativePermissionsIOS.json`
I have same issue and app is crashing because of that.
I don't have any dependencies and using new architecture, so i can't just donwgrade.

```
"react": "18.2.0",
"react-native": "0.71.7",
"react-native-permissions": "3.8.0",
```

Did anyone solved this without downgrading?

### Library version

3.8.0

### Environment info

```shell
"react": "18.2.0",
"react-native": "0.71.7",
"react-native-permissions": "3.8.0",
```

### Steps to reproduce

1. Run app
2. call checkNotifications();
3. App crashes or return an error `Notifications permission pod is missing`

### Reproducible sample code

```js
checkNotifications()
```

**Comment by zoontek** [comment]
Be sure you cleaned your project (don't forget the `ios/build` directory).

**Comment by radekzz** [comment]
I acually did that and it disappeared, but i still don't receive any popup with permissions request
