### ISSUE TITLE
Giving Android a way to open the notification settings directly

### ISSUE THREAD

**Issue by marqroldan** [zoontek/react-native-permissions#783]
### Why it is needed?

Hello,

I'm currently using `react-native-open-notification` (https://github.com/riwu/react-native-open-notification) to directly open the notification settings for Android (no such thing on iOS, could just fallback to `Linking.openURL('app-settings:')`), this is all what the package does and currently my goal is to reduce the number of packages that I use 😅

I am wondering if it's alright to mix such method here in this package, as all it really does is create an intent with the action `APP_NOTIFICATION_SETTINGS`, but also we have a similar method called `openSettings()`

Thank you!

### Possible implementation

This is copy pasted from the package
```java
    public void open() {
        ReactContext reactContext = getReactApplicationContext();
        String packageName = reactContext.getPackageName();
        Intent intent = new Intent();

        if (android.os.Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
            intent.setAction("android.settings.APP_NOTIFICATION_SETTINGS");
            intent.putExtra("android.provider.extra.APP_PACKAGE", packageName);
            intent.putExtra("app_package", packageName);
            intent.putExtra("app_uid", reactContext.getApplicationInfo().uid);
        } else {
            intent.setAction(Settings.ACTION_APPLICATION_DETAILS_SETTINGS);
            intent.addCategory(Intent.CATEGORY_DEFAULT);
            intent.setData(Uri.parse("package:" + packageName));
        }

        getReactApplicationContext().startActivityForResult(intent, REQUEST_CODE, null);
    }
 ```

### Code sample

```js
Could just be a simple call:





import {openNotificationSettings} from 'react-native-permissions';

openNotificationSettings()
```

-----------------------

Edit:
- If you're using Notifee, it turns out they have `openNotificationSettings()`

**Comment by zoontek** [comment]
This has nothing to do in this package.
You can copy / paste it in your code if you want.

**Comment by marqroldan** [comment]
Understandable, thank you!
