### ISSUE TITLE
Could not set unknown property 'namespace' for extension 'android' of type com.android.build.gradle.LibraryExtension

### ISSUE THREAD

**Issue by QMY-ZQ** [zoontek/react-native-permissions#785]
### Bug summary

![image](https://github.com/zoontek/react-native-permissions/assets/57746139/69831cbf-d6a4-4537-82e4-f2373e2a42c9)
When running react-native run-android, the following problem occurs, and then I upgrade to the latest permissions package, it will be the same

 buildToolsVersion = "29.0.3"
        minSdkVersion = 21
        compileSdkVersion = 33
        targetSdkVersion = 29
        ndkVersion = "20.1.5948944"
        kotlinVersion = '1.6.10'
        This is the environment, gradle seems to be 4.2.2

### Library version

3.6.1

### Environment info

```shell
System:
    OS: macOS 13.4
    CPU: (8) x64 Apple M1
    Memory: 20.92 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 14.14.0 - ~/.nvm/versions/node/v14.14.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v14.14.0/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.14.0/bin/npm
    Watchman: 2023.03.13.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.18 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.4 => 0.64.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

1.run react-native run-android

### Reproducible sample code

```js
buildToolsVersion = "29.0.3"
        minSdkVersion = 21
        compileSdkVersion = 33
        targetSdkVersion = 29
        ndkVersion = "20.1.5948944"
        kotlinVersion = '1.6.10'
        This is the environment, gradle seems to be 4.2.2
```

**Comment by zoontek** [comment]
@Jack-QMY You use a really old version of react-native, could you update to be sure the issue does not come from there?

**Comment by zoontek** [comment]
It appears you are using a really old version of react native / gradle. Support is not guaranteed for these versions anymore.

Several options:
- Pin `react-native-permissions` to `"3.8.0"` (without a `^`)
- Use [patch-package](https://github.com/ds300/patch-package) to remove this line (`android/build.gradle`, line 62)

**Comment by mikehardy** [comment]
It appears that react-native through 0.66 has gradle 6, and it does not understand the namespace thing.
So a conditonal namespace thing is apparently the most compatible.
Working through this in netinfo (and then following packages)

Concrete implementation possibility: https://github.com/react-native-netinfo/react-native-netinfo/pull/676/files

```groovy
def agpVersion = com.android.Version.ANDROID_GRADLE_PLUGIN_VERSION
// Check AGP version for backward compatibility reasons
if (agpVersion.tokenize('.')[0].toInteger() >= 7) {
   namespace = "com.reactnativecommunity.netinfo"
}
```

**Comment by zoontek** [comment]
I communicated about this: https://twitter.com/zoontek/status/1672920540795813890
