### ISSUE TITLE
request Bluetooth permission open it and print undetermined

### ISSUE THREAD

**Issue by peixin** [zoontek/react-native-permissions#79]
Version

> react-native : 0.41.1
   lottie-react-native: 1.0.6
   lottie-ios: 1.0.2
   Xcode: 8.2.1

Code

    checkPermission = () => {
        Permissions.requestPermission('bluetooth')
            .then(response => console.log('bluetooth', response))
    };

Run app on device iOS 10. 
It will popup alert, and I click Setting, to open Bluetooth. then check again.

Console

    bluetooth undetermined

Is it Right?

and why not support check bluetooth on android?  If not support, We will find other library to check it. @yonahforst  Do you have plan to do it?

**Comment by yonahforst** [comment]
ATM Bluetooth on Android is not considered a "dangerous" permission and does not require user permission (https://developer.android.com/guide/topics/permissions/requesting.html#normal-dangerous)

About bluetooth unsupported, do you experience this even when the debugger is not connected?

Changing permissions from the settings menu should cause the app to crash (this is normal). When it reloads, the bluetooth status should be correct.

**Comment by peixin** [comment]
@yonahforst thanks reply. When I turn off debugger, show the bluetooth status by `<Text>`, the result is same as console.

Now the situation is. when I turn off bluetooth, Permissions.requestPermission('bluetooth') show `undetermined` and prompt dialog every time. then turn on bluetooth. no prompt. but always show `undetermined`.

My temporary solution:

    checkPermission = (permission) => {
        Permissions.getPermissionStatus(permission)
            .then(response => {
                if (response === 'undetermined') {
                    Permissions.requestPermission(permission)
                        .then((response) => {
                            // bluetooth always get undetermined even though turn on it after request permission
                            // so when the code goes here, it is considered successful.
                            if (permission === 'bluetooth') {
                                callback('successful');
                            } else {
                                callback(response);
                            }
                        });
                }
            })
    }

**Comment by yonahforst** [comment]
@beiming  - i can't seem to replicate this - please confirm if you still have this issue on version 1.0.0

**Comment by jwtea** [comment]
Hey i'm having a similar issue, when requesting the bluetooth permission i just get 'undetermined'. When i do the same with notifications permission everything works as it should.

react-native: 0.44.3
xcode: 8.3.3
```

    Permissions.request('bluetooth',['alert', 'badge']).then( response => {
      console.log(response)
      this.setState({bluetoothEnabled: response})
    })

```
 I have tried manual linking and react-native linking, there are no errors or warnings displayed.

**Comment by yonahforst** [comment]
@jwtea - does this happen on the simulator or on a real device?

**Comment by jwtea** [comment]
@yonahforst Thanks for the reply, yeah on device. This is on a Galaxy S6 running android 7.0.

**Comment by yonahforst** [comment]
This lib only calls [RN's own PermissionsAndroid](https://facebook.github.io/react-native/docs/permissionsandroid.html) under the hood. I would suggest checking for this issue there...

**Comment by wdifruscio** [comment]
Any update on this issue? On older android devices I am always getting undetermined for location permission (no popup on these devices). I might use something like @beiming has done for now. Will check PermissionsAndroid as well

**Comment by baygeldin** [comment]
I experience the same issue on `1.1.1` on a real device (iOS 11).

**UPD**: I got around it by using [react-native-bluetooth-status](https://github.com/solinor/react-native-bluetooth-status) to check for bluetooth status manually. Since I only use `bluetooth` permission on iOS, I decided to go back to plain PermissionsAndroid though.

**Comment by garrottkai** [comment]
This is still a problem on 1.1.1 with iOS 11.4 and RN 0.55.4

**Comment by Vladimirovici** [comment]
RN-permissions: 1.1.1
ios real device: 12.0
RN: 0.57.4

RN newb here, trying to `request('bluetooth')`, but the dialog doesn't appear and instead returns `undetermined` everytime. I'm assuming I'm doing something wrong so any help is appreciated.

**Comment by philipaarseth** [comment]
+1 @Vladimirovici 

I'm also seeing undetermined even if I console.log the response inside .request

```
_requestPermission = () => {
    Permissions.request('bluetooth').then(response => {
      // Returns once the user has chosen to 'allow' or to 'not allow' access
      console.log("permissions for bluetooth is now: " + response)
```

**Comment by ajaykumarbl** [comment]
Hey i'm having a similar issue, when trying to request('bluetooth') permission i just get 'undetermined'. And the dialog doesn't appear.

RN-permissions: 1.2.0
IOS real device: 12.3
RN: 0.59.8

**Comment by zoontek** [comment]
I am closing this since this issue does not exists anymore with the [2.0.0 release](https://github.com/react-native-community/react-native-permissions/releases/tag/2.0.0).
