### ISSUE TITLE
Error: Notifications permission pod is missing

### ISSUE THREAD

**Issue by matthieu-alc** [zoontek/react-native-permissions#790]
### Bug summary

Hello, I know there is a closed issue related : https://github.com/zoontek/react-native-permissions/issues/418

But I followed every instructions on this issue and didn't manage to fix the problem.

getting this error when `checkNotifications` is called.

React-native : v0.69.7
react-native-permissions: v3.8.4
 package.json contains :  
``` 
"reactNativePermissionsIOS": [
    "LocationWhenInUse",
    "LocationAccuracy",
    "Notifications",
    "Camera"
  ]
```

### Library version

3.8.4

### Environment info

```shell
System:
    OS: macOS 12.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 192.54 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.19.1 - ~/.nvm/versions/node/v14.19.1/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 6.14.16 - ~/.nvm/versions/node/v14.19.1/bin/npm
    Watchman: 2023.07.17.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.2 AI-222.4459.24.2221.10121639
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.5 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

- run `npx react-native-clean-project --remove-iOS-build --remove-iOS-pods`
- run `pod install`
- Call `checkNotifications`, `requestNotifications`, or whatever from `react-native-permissions`
- Getting `Error: Notifications permission pod is missing`

### Reproducible sample code

```js
checkNotifications()
		.then(({status, settings}) => {
			if (status === 'granted') {
				setNotifSystemEnabled(true)
				if (activateGeneralNotifications){
					setActivateGeneralNotifications(false)
					const updatedNotification = {
						...notifications,
						generalNotification: true
					}
					setNotifications(updatedNotification)
					const updateNotificationRequest = buildNotificationUpdateRequest(updatedNotification);
					updateService.mutate(updateNotificationRequest);
				}
			}
			else {
				setNotifSystemEnabled(false)
				if (notifications.generalNotification){
					const updatedNotification = {
						...notifications,
						generalNotification: false
					}
					setNotifications(updatedNotification)
					const updateNotificationRequest = buildNotificationUpdateRequest(updatedNotification);
					updateService.mutate(updateNotificationRequest);
					
				}
			}
		  })
```

**Comment by zoontek** [comment]
@matthieu-alc did you ran `npx react-native setup-ios-permissions` before `pod install`? Don't forget to cleanup Xcode cache (check how to delete `DerivedData`), just in case.

**Comment by matthieu-alc** [comment]
@zoontek after investigation, I was using a previous version of `react-native-permissions` which resulted in command not found `setup-ios-permissions`.
After upgrading the library, I ran the command `npx react-native setup-ios-permissions` after what I ran `pod install` and it seems to cause the following error when I launch `react-native run ios` : 

`2023-07-25 10:38:01.087 xcodebuild[29448:146987] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
2023-07-25 10:38:01.087 xcodebuild[29448:146987] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore`

which I can fix with the following commands : 
```
rm -rf ~/Library/Caches/CocoaPods 
rm -rf ios/Pods
rm -rf ~/Library/Developer/Xcode/DerivedData/*
rm iOS/Podfile.lock
```

At this point running ```pod install && react-native run ios``` works well, but running ```npx react-native setup-ios-permissions``` before gives me the same problem

Maybe it's related to my Xcode version being outdated (13.4.1). What do you think ?

**Comment by zoontek** [comment]
@matthieu-alc The `watchOS` error has nothing to do with this library. See [this similar issue](https://github.com/facebook/react-native/issues/34063), it seems to occurs when you have an outdated toolchain.

Yeah, I suggest to update to latest Xcode version + toolchain.

**Comment by matthieu-alc** [comment]
Updated to 14.3.1 and still have errors. Now it looks like I have conflicting duplicates symbols related to some permissions.

I'm not used to iOS environment, can you tell me if something is wrong (or in conflict with your library) in my Podfile ?

```bash
target 'MyApp' do

  config = use_native_modules!
  config = use_frameworks! :linkage => :static

  $RNFirebaseAsStaticFramework = true

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false,
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
  #   use_flipper!()

   # React Native Maps dependencies
   rn_maps_path = '../node_modules/react-native-maps'
   pod 'react-native-google-maps', :path => rn_maps_path

    $static_library = [
      'React',
      'Google-Maps-iOS-Utils',
      'GoogleMaps',
      'react-native-permissions',
      'react-native-google-maps',
      'react-native-maps',
      'Permission-Camera',
      'Permission-LocationWhenInUse',
      'RNPermissions'
    ]


  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
```

**Comment by zoontek** [comment]
@matthieu-alc Replace pods usage (especially if you are installing them as static libraries, why?) with [the new `npx react-native setup-ios-permissions` command](https://github.com/zoontek/react-native-permissions#ios), [clean your project](https://www.npmjs.com/package/react-native-clean-project), rebuild.

Everything should work after that.

**Comment by matthieu-alc** [comment]
- Removed the 3 last lines from Podfile : 
```bash
permissions_path = '../node_modules/react-native-permissions/ios'
pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
```

- ran ```npx react-native-clean-project --remove-iOS-build --remove-iOS-pods```
- removed everything I could : ``` npx react-native-clean-project --remove-iOS-build --remove-iOS-pods && rm -rf ~/Library/Caches/CocoaPods && rm -rf ios/Pods && rm -rf ~/Library/Developer/Xcode/DerivedData/* && rm iOS/Podfile.lock```
- ran ```npx react-native setup-ios-permissions```
- finally ran ```pod install```

And it's working.

Issue was related to library version + Xcode/toolchain version + conflicts from my Podfile

**Comment by satheeshwaran** [comment]
`npx react-native setup-ios-permissions` + Clean build on Xcode did it for me

**Comment by josedomingos919** [comment]
> @zoontek after investigation, I was using a previous version of `react-native-permissions` which resulted in command not found `setup-ios-permissions`. After upgrading the library, I ran the command `npx react-native setup-ios-permissions` after what I ran `pod install` and it seems to cause the following error when I launch `react-native run ios` :
> 
> `2023-07-25 10:38:01.087 xcodebuild[29448:146987] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore 2023-07-25 10:38:01.087 xcodebuild[29448:146987] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore`
> 
> which I can fix with the following commands :
> 
> ```
> rm -rf ~/Library/Caches/CocoaPods 
> rm -rf ios/Pods
> rm -rf ~/Library/Developer/Xcode/DerivedData/*
> rm iOS/Podfile.lock
> ```
> 
> At this point running `pod install && react-native run ios` works well, but running `npx react-native setup-ios-permissions` before gives me the same problem
> 
> Maybe it's related to my Xcode version being outdated (13.4.1). What do you think ?

This solution is working for me, thanks!

**Comment by kesha-antonov** [comment]
Did anyone solve this for macos catalyst?
