### ISSUE TITLE
CI/CD Release Camera Returns Unavailable

### ISSUE THREAD

**Issue by Wahsner** [zoontek/react-native-permissions#791]
### Bug summary

After a release from our CI/CD to TestFlight, the camera permission check _always_ returns 'unavailable'.

After NPM install is ran, the post install is triggered to run the react-native setup-ios-permissions && pod-install as per the documentation.

- Running on a simulator it works
- If I build locally from Xcode to my device it works
- If I open the Xcode project from the pipeline build agent and perform an archive and release to TestFlight manually, it works.

The CI/CD stage is 

```
      xcodebuild \
        -sdk iphoneos \
        -configuration Release \
        -workspace App.xcworkspace \
        -scheme 'App' \
        archive \
        -archivePath '$(Build.SourcesDirectory)/output/App.xcarchive' \
        -parallelizeTargets \
        -jobs 8 \
        CODE_SIGN_STYLE=Manual \
        CODE_SIGN_IDENTITY='$(APPLE_CERTIFICATE_SIGNING_IDENTITY)' \
        PROVISIONING_PROFILE='$(APPLE_PROV_PROFILE_UUID)' \
        && \
        xcodebuild \
        -exportArchive \
        -archivePath '$(Build.SourcesDirectory)/output/App.xcarchive' \
        -exportPath '$(Build.SourcesDirectory)/output' \
        -exportOptionsPlist exportOptions.plist
```

Im at a loss as to how to resolve this. Any suggestions? 

### Library version

3.8.4

### Environment info

```shell
System:
  OS: macOS 13.3.1
  CPU: (8) x64 Apple M1
  Memory: 529.65 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 16.20.1
    path: ~/.nvm/versions/node/v16.20.1/bin/node
  Yarn: Not Found
  npm:
    version: 8.19.4
    path: ~/.nvm/versions/node/v16.20.1/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.12.1
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2021.1 AI-211.7628.21.2111.8193401
  Xcode:
    version: 14.3/14E222b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.2
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Steps to reproduce

1. Run CI/CD pipeline
2. Release to TestFlight
3. Download build from TestFlight on device
4. Launch app
5. Click Camera button

**Expected**
- For permission request to return 'denied' to allow the 'Request' to be triggered

**Actual**
- Returns 'Unavailable' regardless

### Reproducible sample code

```js
Not sure how this can be provided as its CI/CD yml
```

**Comment by zoontek** [comment]
@0xRenshaw Maybe some kind of build cache (based on the Podfile.lock?). I'm not sure this is something directly related to the library.

**Comment by Wahsner** [comment]
> @0xRenshaw Maybe some kind of build cache (based on the Podfile.lock?). I'm not sure this is something directly related to the library.

Thank you for your feedback. 

Upon further investigation it appears to had been related to having [ccache enabled](https://reactnative.dev/docs/build-speed#xcode-specific-setup). 

After running the command `ccache --clear` on the build agent machine, followed by a new build and release I can confirm the permission request is now working as expected. 

Therefore, you are correct, the issue wasn't related to this package directly but rather ccache

Marking as closed
