### ISSUE TITLE
SCHEDULE_EXACT_ALARM Permission need in Android 14

### ISSUE THREAD

**Issue by ThushalIntervest** [zoontek/react-native-permissions#795]
### Why it is needed?

In my project, I am utilizing the SCHEDULE_EXACT_ALARM feature. With the transition to Android 14 and onwards, there is a change in permission handling. In previous Android versions, this permission was granted by default (ALLOWED). However, starting from Android 14, there is a shift, and the default behaviour for this permission has changed to being denied by default. Therefore, in order to continue using the SCHEDULE_EXACT_ALARM feature effectively in Android 14 and beyond, it is now necessary to explicitly request and obtain the appropriate permission from the user.

**Comment by truongduy997** [comment]
I also need this permission, please support me !!!  🥹 🥹 🥹
<img width="822" alt="Screenshot 2023-09-07 at 23 17 47" src="https://github.com/zoontek/react-native-permissions/assets/43513612/13423b0f-a172-461d-8dc9-e5835e05eefa">

**Comment by ThushalIntervest** [comment]
You can use [Notifee](https://notifee.app/react-native/docs/triggers) Libary to request for this permission.

  `await notifee.openAlarmPermissionSettings();`

Otherwise, I didn't find any solution for this issue

**Comment by nateshmbhat** [comment]
AlarmNotificationSetting.ENABLED still comes true even if we haven't explicitly requested schedule_exact_alarm in android 14 (so the permission is not enabled but still gives enabled as true)

![image](https://github.com/zoontek/react-native-permissions/assets/23279926/fbaa73cb-f097-4090-b58d-d0823ab43bb7)

**Comment by ThushalIntervest** [comment]
For me this works fine in android 14. This can be happen in Android 13.

**Comment by gustavomts** [comment]
Apparently, this is only a problem if your target SDK is >= 33

**Comment by anomsejogati** [comment]
Hi guys, Is there any solution for this issue without using notifee library?

**Comment by zoontek** [comment]
There's an open PR: https://github.com/zoontek/react-native-permissions/pull/878
But I don't have the time to review it for the moment 😕

**Comment by zoontek** [comment]
It's available in [5.1.0](https://github.com/zoontek/react-native-permissions/releases/tag/5.1.0).
