### ISSUE TITLE
react native android files and media permissions not showing in settings

### ISSUE THREAD

**Issue by ManikNagpal00** [zoontek/react-native-permissions#796]
### Bug summary

Model name - A52s Samsung
Android Version - 13
![1692358152304](https://github.com/zoontek/react-native-permissions/assets/99965187/336d638a-182b-4fda-b49a-9badb17b7c9e)

Model name - redmi  power 10
Android Version - 13

My Android Manifest File :=>
![Screenshot 2023-08-18 at 17 00 44](https://github.com/zoontek/react-native-permissions/assets/99965187/1e76530f-66c2-4f4f-9faf-86ae86deb875)

### Library version

^3.8.3

### Environment info

```shell
NAN
```

### Steps to reproduce

1. Attached my android manifest
2. And showing my settings options 
3. But not having android permissions for files and media

### Reproducible sample code

```js
NAN
```

**Comment by zoontek** [comment]
Use the Android 13+ permissions required for that: https://developer.android.com/about/versions/13/behavior-changes-13#granular-media-permissions
