### ISSUE TITLE
Error: react-native-permissions: NativeModule.RNPermissions is null

### ISSUE THREAD

**Issue by Skvitthani** [zoontek/react-native-permissions#798]
### Bug summary

 "react": "18.2.0",
    "react-native": "0.72.4",

### Library version

3.8.4

### Environment info

```shell
"react": "18.2.0",
"react-native": "0.72.4",
```

### Steps to reproduce

1. …
2. …
import {StyleSheet, View, Text, TouchableOpacity} from 'react-native';
import React, {useEffect} from 'react';
import QRCodeScanner from 'react-native-qrcode-scanner';
// import {RNCamera} from 'react-native-camera';
import BarcodeMask from 'react-native-barcode-mask';
import {isTablet} from 'react-native-device-info';
import Header from './Header';
import {useNavigation} from '@react-navigation/native';

const QRScannerCustome = () => {
  const navigation = useNavigation();
  return (
    <View style={styles.container}>
      <View
        style={{
          //   flex: 1,
          height: isTablet() ? 70 : 50,
        }}>
        <Header
          onPress={() => {
            navigation.goBack();
          }}
        />
      </View>
      <View style={{flex: 1}}>
        {/* <QRCodeScanner
          onRead={event => {
            console.log('react :: ', event);
          }}
          // flashMode={RNCamera.Constants.FlashMode.torch}
          topContent={
            <Text style={styles.centerText}>
              Go to{' '}
              <Text style={styles.textBold}>wikipedia.org/wiki/QR_code</Text> on
              your computer and scan the QR code.
            </Text>
          }
          bottomContent={
            <TouchableOpacity style={styles.buttonTouchable}>
              <Text style={styles.buttonText}>OK. Got it!</Text>
            </TouchableOpacity>
          }
        /> */}
        <QRCodeScanner
          cameraStyle={styles.cameraContainer}
          topViewStyle={styles.zeroContainer}
          reactivateTimeout={4000}
          bottomViewStyle={styles.zeroContainer}
          containerStyle={styles.zeroContainer}
          markerStyle={styles.markerStyle}
          reactivate={true}
        />
        <BarcodeMask
          animatedLineColor="red"
          edgeColor="#62B1F6"
          width={isTablet() ? 450 : 250}
          height={isTablet() ? 450 : 250}
          backgroundColor="rgba(0,0,0,0.5)"
        />
      </View>
    </View>
  );
};

export default QRScannerCustome;

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  cameraContainer: {
    height: '100%',
    width: '100%',
    // alignItems: 'center',
  },
  zeroContainer: {
    height: '100%',
    width: '100%',
  },
  markerStyle: {
    borderWidth: 2,
    borderColor: 'white',
  },
});

### Reproducible sample code

```js
{
  "name": "App",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-native-async-storage/async-storage": "^1.19.1",
    "@react-native-community/netinfo": "^9.4.1",
    "@react-navigation/material-top-tabs": "^6.6.3",
    "@react-navigation/native": "^6.1.7",
    "@react-navigation/native-stack": "^6.9.13",
    "@reduxjs/toolkit": "^1.9.5",
    "add": "^2.0.6",
    "axios": "^1.4.0",
    "deprecated-react-native-prop-types": "^4.2.1",
    "js-base64": "^3.7.5",
    "moment": "^2.29.4",
    "react": "18.2.0",
    "react-native": "0.72.4",
    "react-native-barcode-mask": "^1.2.4",
    "react-native-camera": "^4.2.1",
    "react-native-device-info": "^10.8.0",
    "react-native-element-dropdown": "^2.9.0",
    "react-native-keyboard-aware-scroll-view": "^0.9.5",
    "react-native-pager-view": "^6.2.0",
    "react-native-permissions": "^3.8.4",
    "react-native-qrcode-scanner": "^1.5.5",
    "react-native-responsive-fontsize": "^0.5.1",
    "react-native-safe-area-context": "^4.7.1",
    "react-native-screens": "^3.24.0",
    "react-native-splash-screen": "^3.3.0",
    "react-native-sqlite-storage": "^6.0.1",
    "react-native-tab-view": "^3.5.2",
    "react-native-toast-message": "^2.1.6",
    "react-redux": "^8.1.2",
    "redux": "^4.2.1",
    "yarn": "^1.22.19"
  },
  "reactNativePermissionsIOS": [
    "AppTrackingTransparency",
    "BluetoothPeripheral",
    "Calendars",
    "Camera",
    "Contacts",
    "FaceID",
    "LocationAccuracy",
    "LocationAlways",
    "LocationWhenInUse",
    "MediaLibrary",
    "Microphone",
    "Motion",
    "Notifications",
    "PhotoLibrary",
    "PhotoLibraryAddOnly",
    "Reminders",
    "Siri",
    "SpeechRecognition",
    "StoreKit"
  ],
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.6.3",
    "eslint": "^7.32.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "0.72.4",
    "react-test-renderer": "18.1.0"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

**Comment by zoontek** [comment]
Duplicate of https://github.com/zoontek/react-native-permissions/issues?q=is%3Aissue+NativeModule.RNPermissions+is+null
