### ISSUE TITLE
Geolocation permission with "Allow once" is set as denied in ios

### ISSUE THREAD

**Issue by IgorBaio** [zoontek/react-native-permissions#802]
### Bug summary

In the case the app with Geolocation, when set the permission "Allow once", in the iOS device, the permission is set as "Denied" and block to access the location  

### Library version

^3.8.4

### Environment info

```shell
System:
    OS: macOS 13.3.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 90.55 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.5.1 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - ~/Documents/Ipiranga/appmotoristamobile/node_modules/.bin/yarn
    npm: 9.8.0 - /opt/homebrew/bin/npm
    Watchman: 2023.08.14.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9619390
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.8.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.7 => 0.71.7 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

1. Use checkPermission to get the actually permission
2. Use requestFullPermission to show the native modal requesting the permission

### Reproducible sample code

```js
export const REQUEST_PERMISSIONS_TYPE = {
    geolocation: PLATFORM_GEOLOCATION_PERMISSIONS,
    camera: PLATFORM_CAMERA_PERMISSIONS,
}

export const getCheckPermissionGeolocation = async () =>
    Promise.resolve(PermissionApp.checkPermission('geolocation'))

export const getCheckFullPermissionGeolocation = async () =>
    Promise.resolve(PermissionApp.checkLocationAccuracyIos())

export const getRequestFullPermissionGeolocation = async () =>
    Promise.resolve(PermissionApp.requestFullPermission())


export const getRequestPermissionGeolocation = async () => {
    const platform = Platform.OS as 'ios' | 'android'
    return Promise.resolve(
        PermissionApp.requestPermission(REQUEST_PERMISSIONS_TYPE.geolocation[platform])
    )
}

const onViewDetailsInvoicesState = async (item: InvoiceProps) => {
        const isGranted = await getCheckPermissionGeolocation()
        console.log('isGranted', isGranted)
        if (isGranted === RESULTS.GRANTED) {
            if (Platform.OS === 'android') selectInvoice(item)
            else if (Platform.OS === 'ios') {
                const isFullPermission = await getCheckFullPermissionGeolocation()
                if (isFullPermission === 'full') selectInvoice(item)
                else await getRequestFullPermissionGeolocation()
            }
        } else {
            setVisibleModalvisibleModalAgreeGeolocation(true)
        }
    }
```

**Comment by zoontek** [comment]
Your reproduction code contains some abstractions that make it impossible to fully understand the issue here.

My guess: You are requesting `PERMISSIONS.IOS.LOCATION_ALWAYS`, select "Allow once", it results in `DENIED` (which is normal, as `ALWAYS` isn't granted).

I recommend an additional `check` to `PERMISSIONS.IOS.LOCATION_WHEN_IN_USE` when it's denied, to fully determine the user choice.

All of this is explained in the documentation already: https://github.com/zoontek/react-native-permissions#about-ios-location_always-permission

This isn't a bug, just the way iOS location permission work: https://developer.apple.com/documentation/corelocation/requesting_authorization_to_use_location_services

**Comment by IgorBaio** [comment]
> I tried this, but I wil make new tests like your instructions

**Comment by IgorBaio** [comment]
> Your reproduction code contains some abstractions that make it impossible to fully understand the issue here.
> 
> My guess: You are requesting `PERMISSIONS.IOS.LOCATION_ALWAYS`, select "Allow once", it results in `DENIED` (which is normal, as `ALWAYS` isn't granted).
> 
> I recommend an additional `check` to `PERMISSIONS.IOS.LOCATION_WHEN_IN_USE` when it's denied, to fully determine the user choice.
> 
> All of this is explained in the documentation already: https://github.com/zoontek/react-native-permissions#about-ios-location_always-permission
> 
> This isn't a bug, just the way iOS location permission work: https://developer.apple.com/documentation/corelocation/requesting_authorization_to_use_location_services

Is normal the native modal does not show in iOS simulator?
