### ISSUE TITLE
Calendar permission fail on iOS 17 (will be released on Sept 18th)

### ISSUE THREAD

**Issue by andrejguran** [zoontek/react-native-permissions#804]
### Bug summary

In new iOS 17 (to be relased on 18th of Sept)
this permission request: https://github.com/zoontek/react-native-permissions/blob/33472788eac2526276477afd077b50f3a0855371/ios/Calendars/RNPermissionHandlerCalendars.m#L31
is deprecated and throw error: 
`Error: -requestAccessToEntityType:completion: has been deprecated-calling this method is no longer allowed. Instead, use -requestFullAccessToEventsWithCompletion:, -requestWriteOnlyAccessToEventsWithCompletion:, or -requestFullAccessToRemindersWithCompletion:.`

Deprication notice: https://developer.apple.com/documentation/eventkit/ekeventstore/1507547-requestaccesstoentitytype

### Library version

3.9.0

### Environment info

```shell
ios 17
```

### Steps to reproduce

request calendar permissions on iOS 17

### Reproducible sample code

```js
`await request(PERMISSIONS.IOS.CALENDARS);`
```

**Comment by zoontek** [comment]
@andrejguran Does this actually really throw or is it more a deprecation warning?

Those two new methods just landed in iOS 17 beta, that would be weird for Apple to prevent old API usage and publish the replacements in the same version.

Usually, they let developers the time to migrate by supporting both for at least one major version.

**Comment by andrejguran** [comment]
@zoontek it's an error. Also they are deprecating [EKAuthorizationStatus:authorized](https://developer.apple.com/documentation/eventkit/ekauthorizationstatus#4169153)
so the library will return incorrect status
https://github.com/zoontek/react-native-permissions/blob/33472788eac2526276477afd077b50f3a0855371/ios/Calendars/RNPermissionHandlerCalendars.m#L24

It's possible that they will support both version, but I can't imagine how they'd support old `authorized` and new `fullAccess` and `writeOnly` statuses at the same time. I am leaning towards the possibility that on 18th when iOS 17 is [released](https://en.wikipedia.org/wiki/IOS_17#cite_note-6) it will stop working.

**Comment by zoontek** [comment]
Fixed in first v4 alpha: https://github.com/zoontek/react-native-permissions/pull/808
