### ISSUE TITLE
Android location services behaves differently from the flowchart

### ISSUE THREAD

**Issue by stefoid** [zoontek/react-native-permissions#814]
### Bug summary

The happy flow of CHECK for DENIED  then   REQUEST  to GRANTED works fine.  (user says yes when prompted)  -> the next time permissions is CHECKED it returns GRANTED

Also the happy flow of CHECK for DENIED then REQUEST to BLOCKED works fine.  (user says no when prompted) -> the next time permissions is checked it returns BLOCKED

1) However, if permissions was GRANTED and the user goes to SETTINGS outside of the app and turns location services off explicitly, the next time you CHECK you will receive DENIED, not BLOCKED.   If the user has explicitly turned off permissions, CHECK should return BLOCKED so we dont have to bother the user with another reqeust

2) If, when prompted, the user sets location settings to THIS TIME ONLY, the next time permissions are CHECKED it returns GRANTED rather than DENIED.  This is the opposite problem - the user has expicitly said 'ask me again next time'  but CHECK returns GRANTED

### Library version

3.10.0

### Environment info

```shell
Android only.
```

### Steps to reproduce

1. …
2. …

### Reproducible sample code

```js
I have no code
```

**Comment by captncanary** [comment]
I'm seeing a similar problem on at least android 9 & 10 - need to check later OS. For me, if the user clicks deny and don't ask again, then 'check' is showing the permission status as denied. Only 'request' returns blocked. Check ought to be returning blocked in this scenario right?

**Comment by zoontek** [comment]
@stefoid @captncanary https://github.com/zoontek/react-native-permissions#check

<img width="894" alt="Screenshot 2023-10-16 at 14 26 32" src="https://github.com/zoontek/react-native-permissions/assets/1902323/d0ccaf9b-5024-48f7-916a-d383afc9f871">

<img width="852" alt="Screenshot 2023-10-16 at 14 52 53" src="https://github.com/zoontek/react-native-permissions/assets/1902323/28104871-3f3f-423d-9a0d-a747cf0fa394">

**Comment by zoontek** [comment]
For the second part:

> If, when prompted, the user sets location settings to THIS TIME ONLY, the next time permissions are CHECKED it returns GRANTED rather than DENIED. This is the opposite problem - the user has expicitly said 'ask me again next time' but CHECK returns GRANTED

The permission is granted **for this app session**. Which means it will be revoked (switch back to denied) if the app is killed. Until then, `check` returns `GRANTED` because the permission is `GRANTED`, and the feature is usable.

**Comment by captncanary** [comment]
Often in apps we want to check the permission in order to determine whether or not to present the user with a permissions flow. Is there any suggestion on how to handle that on android if requesting the permission is the only option?
May I ask the reason why check cannot return the permission status in android?

**Comment by zoontek** [comment]
@captncanary Unfortunately, no.

See https://developer.android.com/training/permissions/requesting

**Comment by stefoid** [comment]
I guess I dont understand - what is the process to implement 'ask every time' option if the user choose that?

**Comment by zoontek** [comment]
@stefoid you don't have to implement something specific.

When the user chooses "Ask next time", the permission is granted until the app is closed. On next app session (the app is killed and relaunched), the permission will be denied and requestable again.
