### ISSUE TITLE
cannot request photo library on IOS

### ISSUE THREAD

**Issue by alainib** [zoontek/react-native-permissions#815]
### Bug summary

hello

i'm trying to read photo from phone's library on IOS&Android
on ios i always get "unavailable" with PERMISSIONS.IOS.PHOTO_LIBRARY

in `info.plist` i put 

```
<key>NSPhotoLibraryUsageDescription</key>
<string>YOUR TEXT</string>
<key>NSPhotoLibraryAddUsageDescription</key>
<string>YOUR TEXT</string>
```

 Any fix please ?
 
  

<img width="320" alt="Capture d’écran 2023-10-13 à 17 51 03" src="https://github.com/zoontek/react-native-permissions/assets/7910081/6452eced-0ac9-4ca6-8384-9ae31cf48fb3">

### Library version

3.8.4

### Environment info

```shell
"react-native": "0.71.12",
```

### Steps to reproduce

1. …
2. …

### Reproducible sample code

```js
const permissions = {
  camera: Platform.select({
    android: PERMISSIONS.ANDROID.CAMERA,
    ios: PERMISSIONS.IOS.CAMERA,
  }),
  library: Platform.select({
    android:
      parseInt(Platform.Version.toString(), 10) >= 33
        ? PERMISSIONS.ANDROID.READ_MEDIA_IMAGES
        : PERMISSIONS.ANDROID.READ_EXTERNAL_STORAGE,
    ios: PERMISSIONS.IOS.PHOTO_LIBRARY,
  }),
};

const status = await request(permissions.library);

// log status: "unavailable"
```

**Comment by alainib** [comment]
and if i ignore request result status and open `launchCamera()` from `react-native-image-picker` i get this 
 
<img width="305" alt="Capture d’écran 2023-10-13 à 18 24 49" src="https://github.com/zoontek/react-native-permissions/assets/7910081/b50d3a0e-8d25-4b0d-91cd-c2224f62efab">

how to open it first or when i want ? thannnks

**Comment by fabiendem** [comment]
Do you put actual values for the keys in the `info.plist`?
It should be:
```
  <key>NSPhotoLibraryUsageDescription</key>
  <string>YOUR TEXT</string>
  <key>NSPhotoLibraryAddUsageDescription</key>
<string>YOUR TEXT</string>
```

**Comment by alainib** [comment]
> Do you put actual values for the keys in the `info.plist`? It should be:
> 
> ```
>   <key>NSPhotoLibraryUsageDescription</key>
>   <string>YOUR TEXT</string>
>   <key>NSPhotoLibraryAddUsageDescription</key>
> <string>YOUR TEXT</string>
> ```

hello . yes i put string value , i just didn't past them before but i edited my question .
thanks for help

**Comment by zoontek** [comment]
@alainib Not reproductible on my side.

https://github.com/zoontek/react-native-permissions/assets/1902323/a3049501-524a-4523-9434-df3e67503271

Please:

1. [Try the example app](https://github.com/zoontek/react-native-permissions/tree/3.10.0/example) (clone the repo, `yarn install` at root + `yarn install` in `/example`)
2. Provide a proper reproduction (a clonable repository)

**Comment by Berk-Kaya** [comment]
I am also having the same issue. It keeps returning unavailable.

**Comment by Milutin-P** [comment]
I am also having this issue. I've tried all latest version since the major change.

- 3.9.0
- 3.9.1
- 3.9.2
- 3.9.3
- 3.10.0

In `ios/Podfile` I have:
`setup_permissions(['AppTrackingTransparency','Camera','MediaLibrary'])`

Inside `App.tsx` I have
```typescript

  React.useEffect(() => {
    requestAppTrackingTransparency();
    requestMediaPermissions();
  }, []);
  ```
  
  And inside a separate file I have
  
  ```typescript
 
export const requestAppTrackingTransparency = async () => {
  if (Platform.OS === 'ios') {
    const trackingStatus = await check(
      PERMISSIONS.IOS.APP_TRACKING_TRANSPARENCY,
    );
    switch (trackingStatus) {
    .....
    
    }
   }
  };

export const requestMediaPermissions = async () => {
  try {
    const photoPermissionStatus = await request(PERMISSIONS.IOS.PHOTO_LIBRARY);
    const documentPermissionStatus = await request(
      PERMISSIONS.IOS.MEDIA_LIBRARY,
    );
      console.log('Permission for photo library: ',photoPermissionStatus);
      console.log('Permission for media library: ',documentPermissionStatus);
    ....
     }
};
  ```


`AppTrackingTransparency` shows on app start, and the whole flow for it works.
But, `'Camera'` and `'MediaLibrary'` do not.

Console shows
```
Permission for photo library:  unavailable
 Permission for media library:  unavailable
 ```

I am testing on iOS 17.0 and latest XCode 15.0
Also, I've only tested this on the Simulator, not on the actual device.

**Comment by zoontek** [comment]
@Milutin-P Try the example app.

Also, just to be sure: you don't forget to run pod install after adding some permissions?

**Comment by Milutin-P** [comment]
> Also, just to be sure: you don't forget to run pod install after adding some permissions?

Of course.

In `ios` folder:
1. `pod deintegrate`
2. `rm -rf Podfile.lock`
3. `rm -rf Pods`
4. `pod install`

Just to be sure.

**Comment by zoontek** [comment]
@Milutin-P Can you publish your complete Podfile?

**Comment by Milutin-P** [comment]
@zoontek 

Demo App from simulator: https://i.imgur.com/b4VIux8.png (I intended to upload direct image here, but it was too big in the preview)

`Podfile` 

```ruby
# Resolve react_native_pods.rb with node to allow for hoisting
# require Pod::Executable.execute_command('node', ['-p',
#   'require.resolve(
#     "react-native/scripts/react_native_pods.rb",
#     {paths: [process.argv[1]]},
#   )', __dir__]).strip
# react-native-permissions change
def node_require(script)
  require Pod::Executable.execute_command('node', ['-p',
    "require.resolve(
      '#{script}',
        {paths: [process.argv[1]]},
      )", __dir__]).strip
end

node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')

setup_permissions(['AppTrackingTransparency','Camera','LocationAccuracy','LocationAlways','MediaLibrary'])

# RNFBAnalytics: You may set variable `$RNFirebaseAnalyticsWithoutAdIdSupport=true` in Podfile to use analytics without ad ids.
# RNFBAnalytics: Using Firebase/AnalyticsWithoutAdIdSupport pod in place of default Firebase/Analytics
$RNFirebaseAnalyticsWithoutAdIdSupport=true

platform :ios, '13.0' # This version is set because of the Google Maps and Stripe SDK
prepare_react_native_project!

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

abstract_target 'appCommonPods' do
  # Firebase from https://rnfirebase.io/
  use_frameworks! :linkage => :static
  $RNFirebaseAsStaticFramework = true

  # React Native Maps dependencies
  # The following line is only needed if building on an Apple silicon Mac without rosetta.
  pod 'Google-Maps-iOS-Utils', :git => 'https://github.com/Simon-TechForm/google-maps-ios-utils.git', :branch => 'feat/support-apple-silicon'

  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path

  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    # Upcoming versions of React Native may rely on get_default_flags(), but
    # we make it explicit here to aid in the React Native upgrade process.
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    # Firebase comment required to avoid error!
    # :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
  
  target 'appDev' do
  end
  
  target 'appStg' do
  end
  
  target 'app' do
  end
  
  target 'appTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # Added for react native image picker library
    installer.pods_project.build_configurations.each do |config|
      config.build_settings["CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES"] = true
    end
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end



```

**Comment by alainib** [comment]
> @zoontek
 good luck man 
 
 the only working solution for me was to trigger camera or camera roll when it's unavailable, then permissions work

**Comment by zoontek** [comment]
@alainib @Milutin-P If it works in others ways, there's one explanation: for some reason, `setup_permissions` might not perform correctly on your computers (resulting in missing `.h` + `.m` permission handlers files and `unavailable` status)

Could you confirm this hypothesis by opening Xcode and check the installed Pods:

<img width="272" alt="Screenshot 2023-10-18 at 11 20 34" src="https://github.com/zoontek/react-native-permissions/assets/1902323/7e13819e-9619-4a63-a6fb-8e5abf9020f7">

<br/>Open the wanted permissions directories, for each one you should have a `.h` and a `.m` files

<img width="290" alt="Screenshot 2023-10-18 at 11 20 53" src="https://github.com/zoontek/react-native-permissions/assets/1902323/d406bbac-aacf-4770-a8cd-b40bb9723b15">

<br/>If it's not the case, don't hesitate to screenshot here what you see.

EDIT: if there's missing permissions (compared to what you passed to `setup_permissions`), please copy / paste your `node_modules/react-native-permissions/RNPermissions.podspec` file content here (after performing a `pod install`, as `setup_permissions` edit his file)

**Comment by alainib** [comment]
yeees, it work  now 
the pod file was setuped wrong 

in `Pod.file` i had 

``` 
target 'GiftCool' do
  $static_framework = []
  rn_maps_path = '../node_modules/react-native-maps'

  use_expo_modules!

   # Hit build times and times and which library ever failing add here
  $static_framework += [
   ....
    'RNPermissions',
  ]
  ```

but no 
```
def node_require(script)
  require Pod::Executable.execute_command('node', ['-p',
    "require.resolve(
      '#{script}',
        {paths: [process.argv[1]]},
      )", __dir__]).strip
end
 
node_require('react-native-permissions/scripts/setup.rb')

setup_permissions(['Camera','PhotoLibrary','Notifications','Contacts','LocationAccuracy','LocationWhenInUse','LocationAlways'])
```


i run `cd ios ; pod deintegrate ; rm -rf Podfile.lock ; rm -rf Pods ; pod install ;`


in fact before i was using expo media library i didn't had to do this, i removed it and install camera-roll now.

**Comment by Milutin-P** [comment]
@zoontek So, I did

1. `rm -rf yarn.lock`
2. `cd ios`
3. `rm -rf ./Pods`
4. `rm -rf Podfile.lock`

then `yarn install` with my package.json containing `"react-native-permissions": "^3.10.0",`

My `node_modules/react-native-permissions/RNPermissions.podspec` is

```ruby
require "json"

package = JSON.parse(File.read(File.join(__dir__, "package.json")))

Pod::Spec.new do |s|
  s.name         = "RNPermissions"

  s.version      = package["version"]
  s.license      = package["license"]
  s.summary      = package["description"]
  s.author       = package["author"]
  s.homepage     = package["homepage"]

  s.requires_arc = true

  s.source       = { :git => package["repository"]["url"], :tag => s.version }
  s.source_files = "ios/*.{h,m,mm}", "ios/LocationAlways/*.{h,m,mm}", "ios/Camera/*.{h,m,mm}", "ios/AppTrackingTransparency/*.{h,m,mm}", "ios/LocationAccuracy/*.{h,m,mm}", "ios/MediaLibrary/*.{h,m,mm}"

  if ENV['RCT_NEW_ARCH_ENABLED'] == "1" then
    install_modules_dependencies(s)
    s.platforms  = { :ios => "12.4", :tvos => "12.4" }
  else
    s.dependency   "React-Core"
    s.platforms  = { :ios => "10.0", :tvos => "11.0" }
  end
end
```

And in `Pods/Development Pods/RNPermissions` I have both `MediaLibrary` and `Camera` with matching .h and .m files.

![image](https://github.com/zoontek/react-native-permissions/assets/7932073/d8065581-faf4-4724-be44-59b57eea3d8c)

**Comment by zoontek** [comment]
Just realized: you don't use a real device. This permission is not available in simulators: https://github.com/zoontek/react-native-permissions/blob/2d496bbc5e6bdba04f64a1281a3cd81d1e43f82c/ios/MediaLibrary/RNPermissionHandlerMediaLibrary.m#L35

My bad, I forgot that 🤦🏻‍♂️ (it works on real devices, tho)

Similar issue: https://stackoverflow.com/a/56221080

Try these permissions on a real device. As there's no setup issues here, they will work. iOS provides simulators, not emulators (like android), and sometimes this behaves differently than real devices.

**Comment by alainib** [comment]
> Just realized: you don't use a real device. This permission is not available in simulators:
> 
> https://github.com/zoontek/react-native-permissions/blob/2d496bbc5e6bdba04f64a1281a3cd81d1e43f82c/ios/MediaLibrary/RNPermissionHandlerMediaLibrary.m#L35
> 
> My bad, I forgot that 🤦🏻‍♂️ (it works on real devices, tho)
> 
> Similar issue: https://stackoverflow.com/a/56221080
> 
> Try these permissions on a real device. As there's no setup issues here, they will work. iOS provides simulators, not emulators (like android), and sometimes this behaves differently than real devices.

damn it's good to know, maybe it will nice to have this info in readme ?

i cannot use camera in sumualtor too (but have permissions asked lo )

**Comment by zoontek** [comment]
@alainib yeah, adding a general warning in the iOS part of the README. I will add that.

**Comment by Milutin-P** [comment]
@zoontek Thank you for your efforts.


<img width="483" alt="image" src="https://github.com/zoontek/react-native-permissions/assets/7932073/b0be9534-94e2-4450-89fe-897fe17ceaf5">
