### ISSUE TITLE
Android 13 Write External Permission Not Works.

### ISSUE THREAD

**Issue by SuryaS243** [zoontek/react-native-permissions#817]
### Bug summary

In react native 0.71.2 application with react native permission 3.8.0 i have try to get the write external permission request, but it works up to android 12 as expected in android 13 always return the never ask again i want to download the pdf file from my app so any suggestion to fix this problem is appreciable.

### Library version

3.8.0

### Environment info

```shell
react-native - 0.71.2
react-native-permission -3.8.0
```

### Steps to reproduce

in android 13 try to get external write permission using write external permission in the react native 0.71.2 using react-native-permissions 3.8.0

### Reproducible sample code

```js
Andoridmanifest:
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" android:maxSdkVersion="32" tools:replace="android:maxSdkVersion"/>
 
download component:
const permission = await request(PERMISSIONS.ANDROID.WRITE_EXTERNAL_STORAGE, {
                  title: "Storage Permission Required",
                  message: "This app needs access to your storage to download report",
                  buttonNeutral: 'Ask Me Later',
                  buttonNegative: 'Cancel',
                  buttonPositive: 'OK',
                });
```

**Comment by zoontek** [comment]
First result on Google: https://stackoverflow.com/questions/73620790/android-13-how-to-request-write-external-storage
