### ISSUE TITLE
openSettings exit event

### ISSUE THREAD

**Issue by korhaliv** [zoontek/react-native-permissions#82]
Is there a way to get notified when the user returns back from the Settings screen via back-to-app button in the top left corner of Settings screen ? I'm trying to handle location permission changes. For all other settings except location iOS automatically reloads the app upon exit (if something was changed)

**Comment by scerelli** [comment]
ehy @dot3bumpmap i was looking for something like this too but i suppose there is nothing implemented yet. Anyway you can try to do a workaround listening to the [`AppState`](https://facebook.github.io/react-native/docs/appstate.html#app-states).

I did something like this:
```
else if (denied.length) {
   const listenAppStateChange = appStatus => {
       if (appStatus === 'active') {
          AppState.removeEventListener('change', listenAppStateChange)
          checkPermissionsStatus(permissions).then(resolve)
       }
   }
}

AppState.addEventListener('change', listenAppStateChange)
```

**Comment by yonahforst** [comment]
@dot3bumpmap - i just pushed version 0.3.0 to master (f54d00). `openSettings` now returns a promise which resolves when the user has returned to the app. (iOS only for now)
