### ISSUE TITLE
Still available "PERMISSIONS.ANDROID.READ_EXTERNAL_STORAGE" on android 13

### ISSUE THREAD

**Issue by onionkim** [zoontek/react-native-permissions#822]
### Bug summary

I upgraded my app the sdk version 31 to 33 for Android 13. (compilesdkversion & targetsdkversion)

and still using of react-native-permissions version 2.x.x; ( not upgrade over 3.6.x yet )

but still available permission "READ_EXTERNAL_STORAGE" without error or crash.

why this working?

background ( this may not be necessary information )
i'm using patch-package for low RN version.
to use new android permissions.
because of low RN version, i'm using new permissions (READ_MEDIA_IMAGES & POST_NOTIFICATION) via PermissionsAndroid in react-native with patch-package for quick fix.

### Library version

2.0.10

### Environment info

```shell
react-native : 0.61.5
react-native-permissions : 2.0.10
```

### Steps to reproduce

happening on android 13 to use new permissions(READ_MEDIA_IMAGES & POST_NOTIFICATION)

### Reproducible sample code

```js
if(Platform.Version >= 33) {
  //this code still working.
  result = await request(PERMISSIONS.ANDROID.CAMERA ||PERMISSIONS.ANDROID.READ_EXTERNAL_STORAGE);
}
```

**Comment by zoontek** [comment]
2.x is not maintained anymore, update to latest version.
