### ISSUE TITLE
For Android 14, you need to query permission READ_MEDIA_VISUAL_USER_SELECTED

### ISSUE THREAD

**Issue by sunny635533** [zoontek/react-native-permissions#827]
### Why it is needed?

For Android 14, the permission READ_MEDIA_VISUAL_USER_SELECTED is added. Development needs to query the permission to know whether the next access to images or videos is successful.

**Comment by samcodefish** [comment]
This is available in the [WIP next version](https://github.com/zoontek/react-native-permissions/pull/808)

**Comment by zoontek** [comment]
@samcodefish Unfortunately, kinda: https://github.com/zoontek/react-native-permissions/issues/689#issuecomment-1789366602

It is still needed to make `openLimitedPhotoLibraryPicker` work on Android.

**Comment by zoontek** [comment]
Closed as [v4.0.0 is out](https://github.com/zoontek/react-native-permissions/releases/tag/4.0.0). `openPhotoPicker` for android is a different topic, another feature request should be filled.

**Comment by efstathiosntonas** [comment]
@zoontek sorry for digging this, are there any plans on `openPhotoPicker` for Android when this permission is set by the user?

**Comment by zoontek** [comment]
@efstathiosntonas If a company funds this, yes!
