### ISSUE TITLE
Apple privacy manifest file 

### ISSUE THREAD

**Issue by AntonyARHS** [zoontek/react-native-permissions#830]
### Why it is needed?

Hi,

I would like to ask a question regarding the new permission file from Apple: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api

As we don't know what APIs are used internally in your library, could you confirm whether or not you will be managing the new permission file required by Apple? Is the point already open / track somewhere maybe ? 

Thank you very much,

**Comment by zoontek** [comment]
> As we don't know what APIs are used internally in your library

What do you mean? The code is fully open source, and in the `ios` directory

**Comment by AntonyARHS** [comment]
Yes of course, it was more to say you know better than me all the API used in the lib :D I would like to avoid analysing all the dependency source code one by one to make sure there will be no problem. So it was just in case you were aware of the topic and already had an answer :) 

PS : Sorry, I didn't think to adapt my message on the issue. It was a copy and paste of a request made to another non-open source SDK.

**Comment by zoontek** [comment]
Only `NSUserDefaults` is used by the `FaceID` permission.

**Comment by yamade** [comment]
Hello @zoontek Do you have a plan to add privacy manifest file for `NSUserDefaults` usage soon? 

Ref: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api#4278401

**Comment by zoontek** [comment]
@yamade It's the app author job (it should be the `CA92.1`)

**Comment by fabiendem** [comment]
Hey @zoontek, sorry, but are you sure about "It's the app author job"?

Reading: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api

See the highlighted section:
<img width="954" alt="Screenshot 2024-02-22 at 12 42 55" src="https://github.com/zoontek/react-native-permissions/assets/1186282/3f703f8e-7df4-4e98-a2a0-6ca2f4db588f">

> If you use the API in your third-party SDK’s code, then you need to report the API in your third-party SDK’s privacy manifest file. **Your third-party SDK can’t rely on the privacy manifest files for apps that link the third-party SDK**, or those of other third-party SDKs the app links, to report your third-party SDK’s use of required reasons API.

My understanding is that Apple is annoyingly asking all the SDK maintainers to declare their own manifest.
(I am not using the FaceID permission, not pushing here).

Do you think there is a way to dynamically add the declaration based on the `setup_permissions` parameters?

**Comment by zoontek** [comment]
@fabiendem Ugh, Apple being Apple. I think it's better to migrate away from `NSUserDefaults` and write a blank file / check this file existence then having to deal with this. Meanwhile, I think it should be doable on user side for the few people using the FaceID permission (?)

**Comment by fabiendem** [comment]
> Meanwhile, I think it should be doable on user side for the few people using the FaceID permission (?)

That's the approach we're taking for now, because there is no way all our deps will have the manifest in time.
We hope Apple will be okay with the manifest at the App level covering for the deps (even if their doc says the opposite). 🤞

**Comment by johnhatvani** [comment]
@zoontek is this currently something in WIP (migrating away from `NSUserDefaults`)  or are you open to a contribution to add the declaration in the interim?

**Comment by zoontek** [comment]
@johnhatvani I'm open to a pull request!

**Comment by johnhatvani** [comment]
@zoontek I couldn't find a contributing guide, can you provide some steps on building the framework itself? or are you happy for me to open the PR for you to validate it builds properly
