### ISSUE TITLE
Not work  Permission-Location 

### ISSUE THREAD

**Issue by fraporitmos** [zoontek/react-native-permissions#833]
### Bug summary

A problem with 4.0.1 version 
I get the next message error when the enviroment is success:
[!] No podspec found for `Permission-LocationAccuracy` in `../node_modules/react-native-permissions/ios/LocationAccuracy` 

### Library version

4.0.1

### Environment info

```shell
The solution is update version to 3.10.1 : 
"react-native-permissions": "^3.10.1"
```

### Steps to reproduce

1. …
2. …

### Reproducible sample code

```js
"react-native-permissions": "^4.0.1",
```

**Comment by zoontek** [comment]
Read the migration guide in the v4.0.0 release

**Comment by FreTimmerman** [comment]
the migration is described here: https://github.com/zoontek/react-native-permissions/releases/tag/3.9.0

however it fails to mention that you also need to remove the existing pod definitions. for example:

```diff
- permissions_path = '../node_modules/react-native-permissions/ios'
- pod 'Permission-LocationAccuracy', :path => "#{permissions_path}/LocationAccuracy"
```
