### ISSUE TITLE
'RNPermissionsModule' could not be found

### ISSUE THREAD

**Issue by craigdrayton** [zoontek/react-native-permissions#842]
### Before submitting a new issue

- [X] I tested using the latest release of the library, as maybe the bug has been already fixed.
- [X] I checked for possible duplicate issues, with possible answers.

### Bug summary

Received this error upon trying to load the app on my physical Android device:

Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNPermissionsModule' could not be found. Verify that a module by this name is registered in the native binary.Bridgeless mode: false. TurboModule interop: false. Modules loaded: {"NativeModules":["PlatformConstants","LogBox","SourceCode","Timing","AppState","BlobModule","WebSocketModule","DevSettings","DevToolsSettingsManager","Networking","Appearance","DevLoadingView","HeadlessJsTaskSupport","DeviceInfo","UIManager","DeviceEventManager"],"TurboModules":[],"NotFound":["NativePerformanceCxx","NativePerformanceObserverCxx","RedBox","BugReporting","RNPermissionsModule"]}, js engine: hermes

### Library version

^4.1.0

### Environment info

```shell
System:
  OS: Windows 10 10.0.19045
  CPU: (8) x64 Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
  Memory: 4.59 GB / 11.89 GB
Binaries:
  Node:
    version: 20.10.0
    path: C:\Program Files\nodejs\node.EXE     
  Yarn:
    version: 1.22.19
    path: ~\AppData\Roaming\npm\yarn.CMD       
  npm:
    version: 9.5.1
    path: C:\Program Files\nodejs\npm.CMD      
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK: Not Found
IDEs:
  Android Studio: Not Found
  Visual Studio:
    - 17.8.34511.84 (Visual Studio Community 2022)
    - 16.6.30204.135 (Visual Studio Community 2019)
Languages:
  Java: Not Found
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found     
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.2
    wanted: 0.73.2
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Steps to reproduce

- Created a fresh expo project (~50.0.4)
- Ran `npx expo install react-native-permissions`
- Added the iosPermissions configuration to the react-native-plugin in app.json
- Started Expo

### Reproducible sample code

```js
No code changes from a fresh expo project, except as described in the steps to reproduce
```

**Comment by zoontek** [comment]
Install it normally, not with expo install.

**Comment by whois42** [comment]
Experiencing the same issue when running tests, but I'm not using expo. We use RN 0.70.8 in the project. Package was linked manually as well.

**Comment by SamJBerry** [comment]
> Experiencing the same issue when running tests, but I'm not using expo. We use RN 0.70.8 in the project. Package was linked manually as well.

Same issue here on RN 0.70.5, react-native-permissions@4.1.2 (also tested @4.0.0).

```

    Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNPermissionsModule' could not be found. Verify that a module by this name is registered in the native binary.

    > 29 | import {
         | ^
      30 |   request as requestPermission,
      31 |   check as checkPermission,
      32 |   PERMISSIONS,

      at invariant (node_modules/invariant/invariant.js:40:15)
      at Object.getEnforcing (node_modules/react-native/Libraries/TurboModule/TurboModuleRegistry.js:41:12)
      at Object.getEnforcing (node_modules/react-native-permissions/src/NativePermissionsModule.ts:27:36)
      at Object.<anonymous> (node_modules/react-native-permissions/src/methods.ios.ts:2:1)
      at Object.<anonymous> (node_modules/react-native-permissions/src/index.ts:1:1)
      ```

**Comment by SamJBerry** [comment]
@whois42 if you've still got this, you probably need to mock out RN permissions with jest : https://github.com/zoontek/react-native-permissions/issues/759#issuecomment-1496641261

**Comment by AdamBCo** [comment]
@zoontek I'm running into this issue right now. I've installed react-native-permissions using `npm` and `yarn`. iOS is fine, but Android always reports the issue listed above. @craigdrayton how were you able to resolve this? @SamJBerry I'm not using jest but I'd be interested in your opinion on resolving the issue as well. Thank you

**Comment by JohnBilousov** [comment]
Still facing the same error... Any solution?

**Comment by ShanavasPS** [comment]
@JohnBilousov Can you provide a minimum reproducible app.
