### ISSUE TITLE
Unregister for remote notifications method

### ISSUE THREAD

**Issue by nazmeln** [zoontek/react-native-permissions#843]
### Why it is needed?

We have an app where we need to disable remote notifications for the next release. However, it was previously enabled. I know that out there is another library that already has this solution in place but I don't want to add one more lib for this simple [method](https://developer.apple.com/documentation/uikit/uiapplication/1623093-unregisterforremotenotifications?language=objc).

**Note**: only iOS

### Possible implementation

If you're good with introducing this new method, I am happy to make a PR with it(disableRemoteNotifcations).

**Comment by zoontek** [comment]
This is not a feature related to permissions.

**Comment by nazmeln** [comment]
@zoontek 
Okay, can we still add it?

**Comment by zoontek** [comment]
No. This is a permissions library.
