### ISSUE TITLE
iOS microphone permission pop up not appearing on simulator

### ISSUE THREAD

**Issue by sacim41** [zoontek/react-native-permissions#845]
### Before submitting a new issue

- [ ] I tested using the latest release of the library, as maybe the bug has been already fixed.
- [x] I checked for possible duplicate issues, with possible answers.

### Bug summary

In my app, users are required to check in and detect background noise. Prior to check-in, I need to check for microphone permission. The native iOS microphone permission pop-up does not open after requesting permission. I have checked previous bug conversations (https://github.com/zoontek/react-native-permissions/issues/571) and found the following  apple AVaudioSession documentation link related to 'requestRecordPermission,' which is now deprecated. I am not sure if this deprecation is the cause of the issue. Is there any configuration that needs to be added to AppDelegate.m or the Podfile?"

https://developer.apple.com/documentation/avfaudio/avaudiosession/1616601-requestrecordpermission?language=objc

### Library version

4.1.1

### Environment info

```shell
System:
  OS: macOS 14.3.1
  CPU: (8) arm64 Apple M2
  Memory: 83.66 MB / 8.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 21.2.0
    path: /opt/homebrew/bin/node
  Yarn: Not Found
  npm:
    version: 10.4.0
    path: ~/node_modules/.bin/npm
  Watchman:
    version: 2023.11.20.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.14.3
    path: /Users/name/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - visionOS 1.0
      - watchOS 10.2
IDEs:
  Xcode:
    version: 15.2/15C500b
    path: /usr/bin/xcodebuild
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.4
    wanted: 0.73.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
```

### Steps to reproduce

1. Init new RN project
2. run npm install --save react-native-permissions
3. Add pods for this Library
4. Add NSMicrophoneUsageDescription to Info.plist
5. Add code to request microphone
6. Run in simulator with iOS 17.2

### Reproducible sample code

```js
#import "RNPermissionHandlerMicrophone.h"

@import AVFoundation;

@implementation RNPermissionHandlerMicrophone

+ (NSArray<NSString *> * _Nonnull)usageDescriptionKeys {
  return @[@"NSMicrophoneUsageDescription"];
}

+ (NSString * _Nonnull)handlerUniqueId {
  return @"ios.permission.MICROPHONE";
}

- (void)checkWithResolver:(void (^ _Nonnull)(RNPermissionStatus))resolve
                 rejecter:(void (__unused ^ _Nonnull)(NSError * _Nonnull))reject {
  switch ([[AVAudioSession sharedInstance] recordPermission]) {
    case AVAudioSessionRecordPermissionUndetermined:
      return resolve(RNPermissionStatusNotDetermined);
    case AVAudioSessionRecordPermissionDenied:
      return resolve(RNPermissionStatusDenied);
    case AVAudioSessionRecordPermissionGranted:
      return resolve(RNPermissionStatusAuthorized);
  }
}

- (void)requestWithResolver:(void (^ _Nonnull)(RNPermissionStatus))resolve
                   rejecter:(void (^ _Nonnull)(NSError * _Nonnull))reject {
  [[AVAudioSession sharedInstance] requestRecordPermission:^(__unused BOOL granted) {
    [self checkWithResolver:resolve rejecter:reject];
  }];
}

@end
```

**Comment by sacim41** [comment]
<img width="444" alt="Screenshot 2024-02-17 at 2 03 52 PM" src="https://github.com/zoontek/react-native-permissions/assets/107274903/ea9a4a8a-ac86-4015-af13-c19a2e19ed92">


I'm facing an issue with permission pop-ups in my React Native application. Despite correctly configuring the info.plist file, 
  const permissions = [
    PERMISSIONS.IOS.MICROPHONE,
    PERMISSIONS.IOS.PHOTO_LIBRARY,
    PERMISSIONS.IOS.CAMERA,
    PERMISSIONS.IOS.PHOTO_LIBRARY_ADD_ONLY,
    PERMISSIONS.IOS.PHOTO_LIBRARY,
    PERMISSIONS.IOS.MEDIA_LIBRARY,
  ];
  
The permission pop-ups are not showing up on the iOS simulator(17.2). I need help figuring out why this is happening.

**Comment by zoontek** [comment]
No, this is an old issue, Apple never made it works on simulators. See duplicates:

- https://github.com/zoontek/react-native-permissions/issues/455
- https://github.com/zoontek/react-native-permissions/issues/58

**Comment by zoontek** [comment]
@sacim41 [New version](https://github.com/zoontek/react-native-permissions/releases/tag/4.1.2) uses `AVAudioApplication` on iOS >= 17, making the request possible on the simulator for those versions. Request stays impossible on iOS < 17.

**Comment by sacim41** [comment]
Thank you so much, @zoontek! Additionally, I would like to confirm the behavior of other permissions in the simulator. I'm using the following permission requests:
const permissions = [
  PERMISSIONS.IOS.MICROPHONE,
  PERMISSIONS.IOS.MOTION,
  PERMISSIONS.IOS.PHOTO_LIBRARY,
  PERMISSIONS.IOS.CAMERA,
  PERMISSIONS.IOS.PHOTO_LIBRARY_ADD_ONLY,
  PERMISSIONS.IOS.PHOTO_LIBRARY,
  PERMISSIONS.IOS.MEDIA_LIBRARY,
]
I've added the necessary configurations, but the permission request pop-up is still not appearing in the simulator. Is there anything specific I might be missing or should check to troubleshoot this issue? Your guidance is appreciated.

**Comment by zoontek** [comment]
@sacim41 Yes, following the documentation. Just throwing at me an array of permissions don't tell me what you are doing with it at all. You can also play with [the example app](https://github.com/zoontek/react-native-permissions/tree/master/example).

**Comment by sacim41** [comment]
Thank you @zoontek
