### ISSUE TITLE
[Android 13-14] App crash at requestNotifications(['alert', 'sound'])

### ISSUE THREAD

**Issue by neemanwa** [zoontek/react-native-permissions#856]
### Before submitting a new issue

- [X] I tested using the latest release of the library, as maybe the bug has been already fixed.
- [X] I checked for possible duplicate issues, with possible answers.

### Bug summary

	Fatal Exception: java.lang.RuntimeException
Unable to resume activity {com.dollartree.consumer/com.dollartree.consumer.MainActivity}: java.lang.reflect.InvocationTargetException

Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void com.facebook.react.bridge.Callback.invoke(java.lang.Object[])' on a null object reference
	at com.facebook.react.modules.permissions.PermissionsModule.onRequestPermissionsResult(PermissionsModule.java:207)
	

<img width="537" alt="Screenshot 2024-03-13 at 12 04 29 PM" src="https://github.com/zoontek/react-native-permissions/assets/103624938/d85ab11f-e766-4d01-a804-74277c69178a">

### Library version

4.1.4, 3.10.1, 3.9.1

### Environment info

```shell
Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
System:
    OS: macOS 13.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 28.41 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.13.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.3 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /Users/neemanwa/.rvm/gems/ruby-2.7.5/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8193401
    Xcode: 15.0/15A240d - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.6 => 0.71.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

1. Open the App
2. Select don't allow for location permission
3. Move to Notification permission
4. Click Don't allow for notification permission
5. App crashed

### Reproducible sample code

```js
import {requestNotifications} from 'react-native-permissions';

try {
         const { status, settings } = await requestNotifications(['alert', 'sound']); //Crashing abruptly 
         //Not coming here
} catch (error) {
         console.error('Error:', error);
         // Handle the error appropriately
      }
```

**Comment by zoontek** [comment]
@neemanwa Tried it with the latest version, no crash.

https://github.com/zoontek/react-native-permissions/assets/1902323/f3bc7c08-94e3-4f25-9e09-d0c040e62ea8

As this has been covered in [4.1.0](https://github.com/zoontek/react-native-permissions/releases/tag/4.1.0) and you mention older versions, I guess this is the issue here (you have to update)

If this is still occurring on latest version of react-native + of the library, publish a message here with a reproduction that will trigger the crash 100% of the time.

**Comment by rizbud** [comment]
I have the same issue here using 4.1.5. on Android 13, it crashes after denying the permission.
Do you find any solution?

Edit: Solved by using `request` from `PermissionsAndroid`
```typescript
if (Platform.OS === "android") {
	const granted = await PermissionsAndroid.request(
		PermissionsAndroid.PERMISSIONS.POST_NOTIFICATIONS,
	);
	return granted === "granted";
} else {
	const { status } = await requestNotifications(["alert", "sound"]);
	return status === "granted";
}
```

**Comment by zoontek** [comment]
@rizbud That's exactly [what `requestNotifications` already does](https://github.com/zoontek/react-native-permissions/blob/4.1.5/src/methods.android.ts#L69) (Android tiramisu = 13) + your solution does not handle Android < 13, where `POST_NOTIFICATIONS` does not exist.
