### ISSUE TITLE
 ios.permission.FACE_ID denied

### ISSUE THREAD

**Issue by oleg-moseyko** [zoontek/react-native-permissions#867]
### Before submitting a new issue

- [X] I tested using the latest version of the library, as the bug might be already fixed.
- [X] I tested using a [supported version](https://github.com/reactwg/react-native-releases/blob/main/docs/support.md) of react native.
- [X] I checked for possible duplicate issues, with possible answers.

### Bug summary

Checking FaceID permission (PERMISSIONS.IOS.FACE_ID) always return **denied**.

### Library version

4.1.5

### Environment info

```shell
o$ react-native info
info Fetching system and libraries information...
System:
    OS: macOS 13.5.2
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 64.82 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 18.20.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 10.5.0 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.15.2 - /Users/olegmoseyko/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    Android SDK:
      API Levels: 23, 27, 28, 29, 30
      Build Tools: 27.0.3, 28.0.3, 29.0.2, 29.0.3, 30.0.1, 30.0.2, 30.0.3, 31.0.0
      System Images: android-28 | China version of Wear OS Intel x86 Atom, android-29 | Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom_64
      Android NDK: 22.0.7026061
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6858069
    Xcode: 15.0/15A240d - /usr/bin/xcodebuild
  Languages:
    Java: 15.0.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.1 => 0.64.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

Create a react-native project
install react-native-permissions 4.1.5
cd ios && pod install
Create a simple button, and inPress: check(PERMISSIONS.IOS.FACE_ID)
'check' will return RESULTS. denied 
Describe what you expected to happen:

'check' should return RESULTS. GRANTED

### Reproducible sample code

```js
Podfile

require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/react-native-permissions/scripts/setup'

platform :ios, '14.0'
target 'Mobile' do

  config = use_native_modules!
  use_react_native!(
     :path => config[:reactNativePath],
     # to enable hermes on iOS, change `false` to `true` and then install pods
     :hermes_enabled => false
  )
  use_frameworks! :linkage => :static

  ### Permission
  # ⬇️ uncomment wanted permissions
  setup_permissions([
    # 'AppTrackingTransparency',
    # 'Bluetooth',
    # 'Calendars',
    # 'CalendarsWriteOnly',
    # 'Camera',
    # 'Contacts',
     'FaceID',
    # 'LocationAccuracy',
    # 'LocationAlways',
    # 'LocationWhenInUse',
     'MediaLibrary',
    # 'Microphone',
    # 'Motion',
    # 'Notifications',
     'PhotoLibrary',
     'PhotoLibraryAddOnly',
    # 'Reminders',
    # 'Siri',
    # 'SpeechRecognition',
    # 'StoreKit',
  ])
.....

````

        async handleFaceIdPermission(force) {
            const TAG = 'UserScreenLockSettingModel.handlePhotosPermission';
            try {
                console.log(TAG, 'check permission:', PERMISSIONS.IOS.FACE_ID);

                let res = await check(PERMISSIONS.IOS.FACE_ID);               

                console.log(TAG, 'isFaceIdGranted.before:', res);

                if ([RESULTS.DENIED, RESULTS.BLOCKED].includes(res)) {
                    console.log(
                        TAG,
                        'isFaceIdGranted:',
                        res,
                        'self.getFaceIdPermission():',
                        self.getFaceIdPermission(),
                    );

                    if (self.getFaceIdPermission() == null || force) {
                        res = await request(PERMISSIONS.IOS.FACE_ID);

                        console.log(TAG, 'isFaceIdGranted.after: ', res);
                    }
                }

                self.setFaceIdPermission(res);
            } catch (error) {
                console.log(TAG, 'error:', error);
            }
        },
    }));

**Comment by zoontek** [comment]
@oleg-moseyko Please correctly format your code.

You say that you call check, it returns denied: this is normal. Did you called request first?

**Comment by zoontek** [comment]
No issue according to the flow:

<img width="610" alt="Screenshot 2024-04-18 at 10 50 07" src="https://github.com/zoontek/react-native-permissions/assets/1902323/30d12db3-1553-4d7b-b537-5406d95f55fe">

**Comment by oleg-moseyko** [comment]
@zoontek wow)) thanks for quick response. Better support than many paid services 
works well. thanks
`````
async handleFaceIdPermission() {
            const TAG = 'UserScreenLockSettingModel.handlePhotosPermission';
            try {
                console.log(TAG, 'check permission:', PERMISSIONS.IOS.FACE_ID);

                let res = await check(PERMISSIONS.IOS.FACE_ID);
                console.log(TAG, 'isFaceIdGranted.before:', res);

                if ([RESULTS.DENIED, RESULTS.BLOCKED].includes(res)) {
                    res = await request(PERMISSIONS.IOS.FACE_ID);
                    console.log(TAG, 'isFaceIdGranted.after: ', res);
                }

                self.setFaceIdPermission(res);
            } catch (error) {
                console.log(TAG, 'error:', error);
            }
        },

**Comment by amitkumarcoding** [comment]
let res = await check(PERMISSIONS.IOS.FACE_ID);

this giving me granted always even before permission modal comes
