### ISSUE TITLE
await request(PERMISSIONS.IOS.PHOTO_LIBRARY); is always unavailable

### ISSUE THREAD

**Issue by ajen010** [zoontek/react-native-permissions#873]
### Before submitting a new issue

- [X] I tested using the latest version of the library, as the bug might be already fixed.
- [X] I tested using a [supported version](https://github.com/reactwg/react-native-releases/blob/main/docs/support.md) of react native.
- [X] I checked for possible duplicate issues, with possible answers.

### Bug summary

`const` granted = await request(PERMISSIONS.IOS.PHOTO_LIBRARY);
The code never allows granted = 'granted' the only value granted gets is 'unavailable'

### Library version

4.1.5

### Environment info

```shell
info Fetching system and libraries information...
System:
  OS: macOS 14.4.1
  CPU: (10) arm64 Apple M2 Pro
  Memory: 54.69 MB / 16.00 GB
  Shell:
    version: 3.2.57
    path: /bin/bash
Binaries:
  Node:
    version: 18.20.1
    path: ~/.nvm/versions/node/v18.20.1/bin/node
  Yarn: Not Found
  npm:
    version: 10.5.0
    path: ~/.nvm/versions/node/v18.20.1/bin/npm
  Watchman:
    version: 2024.04.01.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.14.3
    path: /Users/andrewjennings/.rvm/gems/ruby-3.1.4/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - visionOS 1.0
      - watchOS 10.2
  Android SDK: Not Found
IDEs:
  Android Studio: 2023.2 AI-232.10300.40.2321.11567975
  Xcode:
    version: 15.2/15C500b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 20.0.2.1
    path: /usr/bin/javac
  Ruby:
    version: 3.1.4
    path: /Users/ajen010/.rvm/rubies/ruby-3.1.4/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.6
    wanted: 0.73.6
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Steps to reproduce

npm install --save react-native-permissions

import RNPermissions, { openSettings, PERMISSIONS, request } from 'react-native-permissions';
const checkImagePermission = async () => {
       const granted = await request(PERMISSIONS.IOS.PHOTO_LIBRARY);
       console.log("granted ",granted);
}

### Reproducible sample code

```js
checkImagePermission()
```

**Comment by ajen010** [comment]
I am happy to pay to have this bug fixed.

**Comment by zoontek** [comment]
@ajen010 Could you give me access to a repository?

**Comment by ajen010** [comment]
I'll have to upload the files to a repo, I'm doing everything on my local. Give me a second.

**Comment by tanishaCodebrew** [comment]
i also need this solution

**Comment by ajen010** [comment]
Ok I invited you to the private repo @zoontek zoontek

**Comment by ajen010** [comment]
The RNPermissions is used in the ImagePicker.js component.

**Comment by zoontek** [comment]
@ajen010 I don't have the issue:

https://github.com/zoontek/react-native-permissions/assets/1902323/11a115f4-41b1-4f85-889b-b370d79cc7f6

Are you sure you didn't forget step 3 of iOS setup?

> 3. Then execute pod install in your ios directory (📌  Note that it must be re-executed each time you update this config).

**Comment by ajen010** [comment]
The issue is the simulators don't respond when you do a request. When the code runs on a real mobile device everything works perfectly.

**Comment by zoontek** [comment]
@ajen010 My screen recording is on a simulator.

**Comment by kodenark** [comment]
if you were using an older version of react-native-permissions, you might have reactNativePermissionsIOS in your package.json, can you try removing it, doing pod install again?

**Comment by zoontek** [comment]
@ajen010 Did you tried again? With the example app / after cleaning your project?

**Comment by ajen010** [comment]
It works on the devices every time, just not on the simulator. I've moved
on and am working on other projects now. Thanks for your help.

**Comment by zoontek** [comment]
@ajen010 Weird, as I (and others) never had an issue with simulators, I even posted a video of it working for your app.

OK, I'm closing this.

**Comment by ObidosDev** [comment]
So I had the same issue right now with `RN 0.73.6` & `"react-native-permissions": "^4.1.5"`

**FIX**:
- Remove `ios/Pods` folder;
- Remove `node_modules` folder;
- `yarn install`;
- `pod install` in `ios` folder;
- And now it is OK.
