### ISSUE TITLE
Permission issue in vivo X70

### ISSUE THREAD

**Issue by TallNutAlt** [zoontek/react-native-permissions#879]
### Before submitting a new issue

- [X] I tested using the latest version of the library, as the bug might be already fixed.
- [X] I tested using a [supported version](https://github.com/reactwg/react-native-releases/blob/main/docs/support.md) of react native.
- [X] I checked for possible duplicate issues, with possible answers.

### Bug summary

` const permissions = [
          PERMISSIONS.ANDROID.WRITE_EXTERNAL_STORAGE,
          PERMISSIONS.ANDROID.READ_EXTERNAL_STORAGE,
        ];

        const statuses = await Promise.all(
          permissions.map(permission => check(permission)),
        );`
   I used check to check that these two permissions always returned ['denied ',' denied ']. After I made the request, there was no permission pop-up and I directly returned blocked. After commenting on the permission code, I downloaded an APK that can be used

### Library version

    "react-native-permissions": "^4.1.5",

### Environment info

```shell
System:
  OS: Windows 11 10.0.22631
  CPU: (16) x64 12th Gen Intel(R) Core(TM) i7-1260P
  Memory: 2.14 GB / 15.73 GB
Binaries:
  Node:
    version: 20.11.1
    path: D:\SDK\node.EXE
  Yarn:
    version: 1.22.22
    path: ~\AppData\Roaming\npm\yarn.CMD
  npm:
    version: 10.2.4
    path: D:\SDK\npm.CMD
  Watchman:
    version: 20231008.002904.0
    path: C:\ProgramData\chocolatey\lib\watchman\tools\watchman-v2023.10.09.00-windows\bin\watchman.EXE
SDKs:
  Android SDK: Not Found
  Windows SDK: Not Found
IDEs:
  Android Studio: Not Found
  Visual Studio: Not Found
Languages:
  Java: 17.0.8
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.4
    wanted: 0.72.4
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Steps to reproduce

Apply for permission directly in this setting

### Reproducible sample code

```js
` const permissions = [
          PERMISSIONS.ANDROID.WRITE_EXTERNAL_STORAGE,
          PERMISSIONS.ANDROID.READ_EXTERNAL_STORAGE,
        ];

        const statuses = await Promise.all(
          permissions.map(permission => check(permission)),
        );

        const unavailablePermissions = statuses.filter(status => status === RESULTS.UNAVAILABLE);
        console.log(statuses,unavailablePermissions);`
```

**Comment by zoontek** [comment]
@TallNutAlt 

<img width="890" alt="Screenshot 2024-06-06 at 09 48 02" src="https://github.com/zoontek/react-native-permissions/assets/1902323/aed81a54-6701-4d21-adad-e1ee3fc3b734">

---

**Existing duplicates:**

- https://github.com/zoontek/react-native-permissions/issues/870#issuecomment-2068001753
- https://github.com/zoontek/react-native-permissions/issues/828#issuecomment-1842456998
