### ISSUE TITLE
react native permission always return unavailable on ios camera

### ISSUE THREAD

**Issue by Zonara-Haroon** [zoontek/react-native-permissions#888]
### Before submitting a new issue

- [X] I tested using the latest version of the library, as the bug might be already fixed.
- [X] I tested using a [supported version](https://github.com/reactwg/react-native-releases/blob/main/docs/support.md) of react native.
- [X] I checked for possible duplicate issues, with possible answers.

### Bug summary

My permission is granted from phone app setting. But library always return unavailable. NSCameraUsageDescription is used in my info.plist.

### Library version

4.1.5

### Environment info

```shell
..
```

### Steps to reproduce

1. install package
2. update info.plist
3. import package

### Reproducible sample code

```js
const response = await check(PERMISSIONS.IOS.CAMERA)
        if (response == PermissionsAndroid.RESULTS.GRANTED) {
          return true
        }else{
          const result = await request(PERMISSIONS.IOS.CAMERA);          
          if (result === RESULTS.GRANTED) {
            return true;
          } else {
            Toast.show({
              type: 'error',
              text2: 'Permission not allowed to access camera'
            });
            return false;
          }
        }
```

**Comment by prashant-ksolves-consultant** [comment]
@zoontek Can you please point out "Duplicate" to which issue. Can you please share link of "Duplicate" issue.

**Comment by DwaveVito** [comment]
https://github.com/zoontek/react-native-permissions/issues/836

"Duplicate"  this issue
