### ISSUE TITLE
Update to newer CLLocationManager instance methods

### ISSUE THREAD

**Issue by joonmanji** [zoontek/react-native-permissions#891]
### Why it is needed?

static CLLocationManager authorization was deprecated 
```
'authorizationStatus' is deprecated: first deprecated in iOS 14.0
```

**Comment by zoontek** [comment]
I'm closing this as it's not really a *feature* request, just keep the PR opened.

**Comment by joonmanji** [comment]
yeah.. also realized the PR probably needs an update since minimum supported iOS version on your library might not be 14+
