### ISSUE TITLE
In iOS 18, a new feature has been added to the Contacts app, introducing a restricted permission called CNAuthorizationStatusLimited. If this permission is granted, attempting to access contacts will result in no returned records.

### ISSUE THREAD

**Issue by chen834921478** [zoontek/react-native-permissions#894]
### Before submitting a new issue

- [X] I tested using the latest version of the library, as the bug might be already fixed.
- [X] I tested using a [supported version](https://github.com/reactwg/react-native-releases/blob/main/docs/support.md) of react native.
- [X] I checked for possible duplicate issues, with possible answers.

### Bug summary

RNPermissionHandlerContacts.mm 
- (void)checkWithResolver:(void (^ _Nonnull)(RNPermissionStatus))resolve
                 rejecter:(void (__unused ^ _Nonnull)(NSError * _Nonnull))reject {
  switch ([CNContactStore authorizationStatusForEntityType:CNEntityTypeContacts]) {
    case CNAuthorizationStatusNotDetermined:
      return resolve(RNPermissionStatusNotDetermined);
    case CNAuthorizationStatusRestricted:
      return resolve(RNPermissionStatusRestricted);
    case CNAuthorizationStatusDenied:
      return resolve(RNPermissionStatusDenied);
    case CNAuthorizationStatusAuthorized:
      return resolve(RNPermissionStatusAuthorized);
      case CNAuthorizationStatusLimited:
          return resolve(RNPermissionStatusLimited);
  }
}
 iOS

### Library version

4.1.5

### Environment info

```shell
xxx
```

### Steps to reproduce

1. …
2. …

### Reproducible sample code

```js
check( PERMISSIONS.IOS.CONTACTS);
```

**Comment by zoontek** [comment]
https://github.com/zoontek/react-native-permissions/pull/890
