### ISSUE TITLE
Support for iOS 18 Limited Access?

### ISSUE THREAD

**Issue by Lee-sungheon** [zoontek/react-native-permissions#895]
### Why it is needed?

Hi @zoontek! Thanks for this awesome and very useful library :)

I was wondering if you were planning to add support for the iOS 18 changes with the limited contact access?

https://developer.apple.com/videos/play/wwdc2024/10121/
Here's a reference to the relevant feature.

Thank you!

**Comment by zoontek** [comment]
@Lee-sungheon Yes

Duplicate https://github.com/zoontek/react-native-permissions/issues/894

Beta https://github.com/zoontek/react-native-permissions/pull/890
