### ISSUE TITLE
iOS - Unable to fetch Device location

### ISSUE THREAD

**Issue by sanjay-cheemeni** [zoontek/react-native-permissions#900]
### Before submitting a new issue

- [X] I tested using the latest version of the library, as the bug might be already fixed.
- [X] I tested using a [supported version](https://github.com/reactwg/react-native-releases/blob/main/docs/support.md) of react native.
- [X] I checked for possible duplicate issues, with possible answers.

### Bug summary

On the initial load of the application, I am able to successfully fetch the device's location using the package on the first map screen.
 However, after navigating to another page within the app and then returning to the current page where the location is fetched, the device location is no longer retrieved.

On initial at the first map screen, Im receiving a popup from which i can grant location access:

I have clicked on 'allow once' option.
after that, while directing to the second map screen at times, Im not able to access the location and  receiving a different popup as below and not able to retrieve device location while clicking on 'keep only while using' option:

### Library version

4.1.5

### Environment info

```shell
System:
  OS: macOS 14.5
  CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
  Memory: 179.62 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.11.0
    path: ~/.nvm/versions/node/v20.11.0/bin/node
  Yarn:
    version: 1.22.21
    path: /usr/local/bin/yarn
  npm:
    version: 10.2.4
    path: ~/.nvm/versions/node/v20.11.0/bin/npm
  Watchman:
    version: 2024.05.06.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /Users/mac/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - visionOS 1.0
      - watchOS 10.2
  Android SDK:
    API Levels:
      - "28"
      - "29"
      - "30"
      - "31"
      - "33"
      - "34"
    Build Tools:
      - 29.0.3
      - 30.0.2
      - 30.0.3
      - 33.0.0
      - 33.0.1
      - 34.0.0
    System Images:
      - android-34 | Google APIs Intel x86_64 Atom
    Android NDK: Not Found
IDEs:
  Android Studio: 2023.1 AI-231.9392.1.2311.11330709
  Xcode:
    version: 15.2/15C500b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.10
    path: /usr/bin/javac
  Ruby:
    version: 2.7.6
    path: /Users/mac/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.2
    wanted: 0.73.2
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Steps to reproduce

The current location fetch works fine when the map screen is initially loaded. However, when I navigate to another screen and return to the map screen, it no longer fetches the user's current location. The location fetching logic is placed inside a `useFocusEffect`.

### Reproducible sample code

```js
useFocusEffect(
    React.useCallback(() => {
      const watchId = Geolocation.watchPosition(
        position => {
          setRealTimeLocation({
            latitude: position.coords.latitude,
            longitude: position.coords.longitude,
            latitudeDelta: 0.0922,
            longitudeDelta: 0.0421,
          });

          setPositionLoading(false);
        },
        error => {
          Geolocation.clearWatch(watchId);
        },
        {
          accuracy: {android: 'high', ios: 'bestForNavigation'},
          distanceFilter: 1,
          maximumAge: 10000,
        },
      );

      return () => {
        setRealTimeLocation(null);
      };
    }, [setRealTimeLocation]),
  );
```

**Comment by zoontek** [comment]
There's no issue regarding the permission here. Please update to v5 for [proper location always escalation support](https://github.com/zoontek/react-native-permissions?tab=readme-ov-file#about-ios-location_always-permission).
