### ISSUE TITLE
tvOS target includes unsupported permissions

### ISSUE THREAD

**Issue by RuudBurger** [zoontek/react-native-permissions#906]
### Before submitting a new issue

- [X] I tested using the latest version of the library, as the bug might be already fixed.
- [X] I tested using a [supported version](https://github.com/reactwg/react-native-releases/blob/main/docs/support.md) of react native.
- [X] I checked for possible duplicate issues, with possible answers.

### Bug summary

We have a single podfile for both iOS and tvOS. If we include permissions for notification on iOS, the `RNPermissionHandlerNotifications.h` is also included in the tvOS podspec.

Resulting in the following build error:
![Screenshot 2024-11-20 at 11 48 05](https://github.com/user-attachments/assets/de27fd98-3854-44bf-95bb-565068d18880)

### Library version

4.1.5

### Environment info

```shell
RN 0.75
```

### Steps to reproduce

See podfile example below.
Can probably also replicate if you call 
```ruby
setup_permissions([
  'Notifications',
])
```
in a tvos target

### Reproducible sample code

```js
target 'App' do
  platform :ios, "15.5"

  setup_permissions([
    'Notifications',
  ])
  ...
end

target 'App-tvOS' do
  platform :tvos, "15.5"

  # this doesn't do anything, the above `Notifications` are still loaded
  setup_permissions([])
   ...
end
```

**Comment by zoontek** [comment]
> ```
> # this doesn't do anything, the above `Notifications` are still loaded
> setup_permissions([])
> ```

That's unfortunately expected given what it does under the hood (it updates the react-native-permissions podspec file).
I think the easiest way to fix this is just to wrap the unavailable APIs with `#if TARGET_OS_IOS`

**Comment by zoontek** [comment]
Done in [5.2.0](https://github.com/zoontek/react-native-permissions/releases/tag/5.2.0) 🚀
If you enjoyed the reactive support, think about sponsoring.
