### ISSUE TITLE
ANDROID.POST_NOTIFICATIONS no longer available

### ISSUE THREAD

**Issue by jaco-louw** [zoontek/react-native-permissions#910]
### Before submitting a new issue

- [X] I tested using the latest version of the library, as the bug might be already fixed.
- [X] I tested using a [supported version](https://github.com/reactwg/react-native-releases/blob/main/docs/support.md) of react native.
- [X] I checked for possible duplicate issues, with possible answers.

### Bug summary

![image](https://github.com/user-attachments/assets/243d2fb2-f2cd-4e45-b76d-2792fc8a6880)
According to that changeset in release version 5.0.0 the android permission constant `POST_NOTIFICATIONS` was removed, but according to the readme, this should still be supported. I'm not sure if this is a bug or if there is some other way to check android push notification permissions

### Library version

5.2.1

### Environment info

```shell
System:
  OS: Windows 11 10.0.22631
  CPU: (20) x64 12th Gen Intel(R) Core(TM) i9-12900H
  Memory: 2.00 GB / 31.71 GB
Binaries:
  Node:
    version: 20.13.1
    path: ~\AppData\Local\nvs\node\20.13.1\x64\node.EXE
  Yarn: Not Found
  npm:
    version: 10.5.2
    path: ~\AppData\Local\nvs\node\20.13.1\x64\npm.CMD
  Watchman:
    version: 20241124.093321.0
    path: C:\ProgramData\chocolatey\bin\watchman.EXE
SDKs:
  Android SDK: Not Found
  Windows SDK: Not Found
IDEs:
  Android Studio: Not Found
  Visual Studio:
    - 17.12.35506.116 (Visual Studio Community 2022)
Languages:
  Java: 21.0.5
  Ruby:
    version: 2.7.7
    path: C:\Ruby27-x64\bin\ruby.EXE
npmPackages:
  "@react-native-community/cli":
    installed: 16.0.0
    wanted: 16.0.0
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.76.3
    wanted: 0.76.3
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Steps to reproduce

This issue is happening on Android. To reproduce is simple. Either do a `check` or `request` for the constant `PERMISSIONS.ANDROID.POST_NOTIFICATIONS`. The constant no longer exists and according to the changeset history was removed in version 5.0.0

### Reproducible sample code

```js
async function requestAndroidNotificationPermission() {
    return await request(PERMISSIONS.ANDROID.POST_NOTIFICATIONS);
}
```

**Comment by zoontek** [comment]
[See the comments here](https://github.com/zoontek/react-native-permissions/pull/890#issuecomment-2440539816)

**Comment by jaco-louw** [comment]
> [See the comments here](https://github.com/zoontek/react-native-permissions/pull/890#issuecomment-2440539816)

Sorry, I didn't check closed issues 🤦
