### ISSUE TITLE
[iOS] No permission prompt when requesting LOCATION_ALWAYS after WHEN_IN_USE

### ISSUE THREAD

**Issue by Oyzuu** [zoontek/react-native-permissions#913]
### Before submitting a new issue

- [X] I tested using the latest version of the library, as the bug might be already fixed.
- [X] I tested using a [supported version](https://github.com/reactwg/react-native-releases/blob/main/docs/support.md) of react native.
- [X] I checked for possible duplicate issues, with possible answers.

### Bug summary

On iOS, when attempting to request the `LOCATION_ALWAYS` permission after the `WHEN_IN_USE` permission (whether immediately or after a delay), the request result is "blocked." As a result, I am not prompted a second time to accept the `LOCATION_ALWAYS` permission.

I tried making the request immediately using either requestMultiple or by chaining both requests. I also attempted to call the `LOCATION_ALWAYS` request later in the app lifecycle, from a different screen. However, nothing works; I always end up with the same "blocked" status.

This issue was tested on a simulator (iPhone 15 — iOS 17.2) and on a physical iPhone SE 2 (iOS 17.4.1).

---

Note that I'm on an Nx project with multiple sub-apps, and therefore can't easily update to the latest version of the library. (but from what I've seen in the release notes, this issue — if a library issue — was not addressed)

### Library version

4.1.4

### Environment info

```shell
System:
  OS: macOS 14.5
  CPU: (10) arm64 Apple M1 Pro
  Memory: 293.05 MB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 21.6.2
    path: /opt/homebrew/bin/node
  Yarn:
    version: 1.22.21
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.2.4
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2024.01.22.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - visionOS 1.0
      - watchOS 10.2
  Android SDK: Not Found
IDEs:
  Android Studio: 2023.2 AI-232.10227.8.2321.11479570
  Xcode:
    version: 15.2/15C500b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.10
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli":
    installed: 11.3.6
    wanted: 11.3.6
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.4
    wanted: 0.72.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Steps to reproduce

Tested with : 
**Chained promises :**

```typescript
let result = await check(PERMISSIONS.IOS.LOCATION_WHEN_IN_USE);

if (result !== RESULTS.GRANTED) {
  request(PERMISSIONS.IOS.LOCATION_WHEN_IN_USE).then((value) => {
    if (Platform.OS === "ios") {
      request(PERMISSIONS.IOS.LOCATION_ALWAYS)
    }
  });
}
```

**Multiple requests :**

```typescript
requestMultiple([PERMISSIONS.IOS.LOCATION_WHEN_IN_USE, PERMISSIONS.IOS.LOCATION_ALWAYS])
```

### Reproducible sample code

```js
let result = await check(PERMISSIONS.IOS.LOCATION_WHEN_IN_USE);

if (result !== RESULTS.GRANTED) {
  request(PERMISSIONS.IOS.LOCATION_WHEN_IN_USE).then((value) => {
    if (Platform.OS === "ios") {
      request(PERMISSIONS.IOS.LOCATION_ALWAYS)
    }
  });
}
```

**Comment by zoontek** [comment]
> [x] I tested using the latest version of the library, as the bug might be already fixed.

@Oyzuu You [didn't](https://github.com/zoontek/react-native-permissions/releases/tag/5.0.0).

**Comment by Oyzuu** [comment]
Dammit, missed this in the 5.0.0 release note — sorry for the bother:

`Enabled location permission escalation on iOS (closes https://github.com/zoontek/react-native-permissions/pull/716) – This feature was sponsored by [Driversnote.com](https://www.driversnote.com/). Thank you! 🙌`

I'll try to patch it, as I can't upgrade to the latest version at the moment.
