### ISSUE TITLE
Location Permission request returning 'DENIED' for Android when user taps on 'Dont Allow'

### ISSUE THREAD

**Issue by madgreasemonkey** [zoontek/react-native-permissions#914]
### Before submitting a new issue

- [X] I tested using the latest version of the library, as the bug might be already fixed.
- [X] I tested using a [supported version](https://github.com/reactwg/react-native-releases/blob/main/docs/support.md) of react native.
- [X] I checked for possible duplicate issues, with possible answers.

### Bug summary

Problem:
I'm encountering inconsistent behavior in location permission handling between Android and iOS platforms. On Android, when a user taps "Don't Allow" on the permission request, the app receives a "DENIED" status. However, on iOS, the same action results in a "BLOCKED" status.

Desired Behavior:
I would like the app to accurately reflect the user's intent on both platforms, receiving a "BLOCKED" status on Android when the user explicitly denies the permission.

### Library version

5.2.1

### Environment info

```shell
System:
  OS: macOS 14.6.1
  CPU: (8) arm64 Apple M1
  Memory: 105.30 MB / 8.00 GB
  Shell:
    version: 3.2.57
    path: /bin/bash
Binaries:
  Node:
    version: 18.18.0
    path: ~/.nvm/versions/node/v18.18.0/bin/node
  Yarn:
    version: 1.22.22
    path: /opt/homebrew/bin/yarn
  npm:
    version: 9.8.1
    path: ~/.nvm/versions/node/v18.18.0/bin/npm
  Watchman:
    version: 2024.11.18.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.16.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.1
      - iOS 18.1
      - macOS 15.1
      - tvOS 18.1
      - visionOS 2.1
      - watchOS 11.1
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.1 AI-241.18034.62.2411.12169540
  Xcode:
    version: 16.1/16B40
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.13
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.74.2
    wanted: 0.74.2
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Steps to reproduce

1. Run the app with requestMultiple for location permissions
2. Check the log for response of the request.

### Reproducible sample code

```js
const response = await requestMultiple([
      PERMISSIONS.ANDROID.ACCESS_FINE_LOCATION,
      PERMISSIONS.ANDROID.ACCESS_COARSE_LOCATION,
    ]);

console.log('Location request response : ', response);
```

**Comment by zoontek** [comment]
@madgreasemonkey I encourage you to read the documentation, understand the flows, etc.
