### ISSUE TITLE
 Push notifcation  permission removed in the latest release.

### ISSUE THREAD

**Issue by dogra-deepak-tftus** [zoontek/react-native-permissions#917]
### Before submitting a new issue

- [X] I tested using the latest version of the library, as the bug might be already fixed.
- [X] I tested using a [supported version](https://github.com/reactwg/react-native-releases/blob/main/docs/support.md) of react native.
- [X] I checked for possible duplicate issues, with possible answers.

### Bug summary

The push notification permission is not available in the permissions.android.js file which was available earlier.

### Library version

5.2.1

### Environment info

```shell
System:
  OS: macOS 15.1.1
  CPU: (8) arm64 Apple M1
  Memory: 99.08 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.17.0
    path: ~/.nvm/versions/node/v20.17.0/bin/node
  Yarn:
    version: 1.22.22
    path: /usr/local/bin/yarn
  npm:
    version: 10.8.2
    path: ~/.nvm/versions/node/v20.17.0/bin/npm
  Watchman:
    version: 2024.11.04.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.16.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.2
      - iOS 18.2
      - macOS 15.2
      - tvOS 18.2
      - visionOS 2.2
      - watchOS 11.2
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.2 AI-242.23339.11.2421.12700392
  Xcode:
    version: 16.2/16C5032a
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.13
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli":
    installed: 15.0.1
    wanted: 15.0.1
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.76.3
    wanted: 0.76.3
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Steps to reproduce

1.install the libarary
2.try to access push notification permission from the library

### Reproducible sample code

```js
please check in permissions.android.js file.
```

**Comment by rahulsingh966233** [comment]
Here’s a polished version of your message for a GitHub issue:

Issue with POST_NOTIFICATION Permission in Latest React-Native-Permissions Version
In the latest version of the react-native-permissions library, the POST_NOTIFICATION permission has been removed. As a workaround, you can manually handle this permission or use the following code to check and request push notification permissions in your React Native project:

Code to Check Notification Permissions:

```
const requestNotificationPermission = async () => {
  console.log('Checking notification permissions...');
  RNPermissions.checkNotifications()
    .then(response => {
      console.log('checkNotifications()', response);
    })
    .catch(error => {
      console.error('Error while checking notifications:', error);
    });
};
```

Code to Request Notification Permissions:

```
const options = ['alert', 'sound', 'badge']; // Customize as needed
RNPermissions.requestNotifications(options)
  .then(response => {
    Logger.log(
      `requestNotifications([${options.map(option => `"${option}"`).join(', ')}])`,
      response,
    );
  })
  .catch(error => {
    console.error('Error while requesting notifications:', error);
  });
```


This approach can be used as an alternative for handling notification permissions until the library is updated or provides additional documentation.

Would it be possible for the library maintainers to clarify if there’s a recommended approach for handling the POST_NOTIFICATION permission in the latest versions, or if this functionality will be reintroduced?

**Comment by zoontek** [comment]
> This approach can be used as an alternative for handling notification permissions until the library is updated or provides additional documentation.

This is not an alternative, but always has been the preferred way.
