### ISSUE TITLE
Detect whether user tapped 'Never ask me again' (Android)

### ISSUE THREAD

**Issue by viktorsec** [zoontek/react-native-permissions#97]
Hey, on Android, it would be beneficial to be able to distinguish whether user disabled further requests.

For example imagine the user clicking a button to upload photo.

| state of the system | `getPermissionStatus()` | desired app behaviour |
| --- | --- | --- |
| User already declined to give the permission | `denied` | Ask for the permission again |
| User already declined to give the permission and tapped `Never ask me again` | `denied` | Display custom Alert |

Is it possible to find this out?

**Comment by yonahforst** [comment]
Hi @viktorsec - I've just pushed version 1.0.0 to master. If the user tapped 'Never ask me again', `check()` will now return `restricted`
